### ISSUE TITLE
[Feature] Implementatie van de ledenadministratie in Dives 2.0

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#10]
Tot op heden moet de ledenadministratie gebeuren via https://ledenadministratie.nelos.be/ ; kan dit geïmplementeerd worden in Dives 2.0 aub; zoals denk ik voordien ook al de bedoeling was in Dives 1.0?

**Comment by ndsmyter** [comment]
Dit is gepland, maar nog niet voor DIVES 2.0. Maar zal wel kort nadien stap voor stap volgen

**Comment by DIVEScoordinator** [comment]
@ndsmyter    zou deze afsluiten want dat pad is verlaten.
