### ISSUE TITLE
gegevens duikduur en duikdiepte korter bijeen plaatsen

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#100]
Momenteel staan (bij aan gelogde duik) de "duur" en "diepte" helemaal links en rechts op het scherm. Het lijkt mij handiger en overzichtelijker als deze twee korter bijeen staan.
<img width="1167" alt="Schermafbeelding 2022-10-07 om 13 13 24" src="https://user-images.githubusercontent.com/112781010/194541256-583563cd-5939-4130-9eae-6e3d3fd01a6b.png">

**Comment by ndsmyter** [comment]
Soms komen daar ook nog andere waarden te staan (temperatuur, zicht etc) en dan valt dat minder op. Maar het is wel correct dat het met enkel die waarden niet zo heel erg mooi oogt.

**Comment by user4294** [comment]
Bij gebruik van het volledig scherm oogt dit inderdaad wat verwarrend. Vermoed dat dit puur met uitlijning wel kan worden opgelost?

**Comment by user4294** [comment]
Eentje die hier op aansluit: op Android is de uitlijning van 'Temperatuur' niet consistent met de uitlijning van Duur, Diepte en Zicht. 

![Screenshot_20221105-200659_Brave](https://user-images.githubusercontent.com/56023403/200163022-d160e00a-5abe-4a28-8905-d2a4e8aa5c19.jpg)

**Comment by ndsmyter** [comment]
Gelogd bij Endare onder https://endare.atlassian.net/browse/NELOS-307 . Is nog niet opgelost, omdat ik het daar op lage prioriteit heb gezet

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
