### ISSUE TITLE
Startscherm - mogelijke verbeteringen

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#101]
Het logo op het startscherm om op in te loggen is, althans op mijn pc, zo groot dat het het hele scherm vult en het login kader niet zichtbaar is... tenzij ik naar beneden scroll.
Da's niet alleen vervelend, maar kan ook verwarrend zijn voor nieuwe gebruikers die denken dat het systeem nog aan't opstarten is en nog niet weten dat ze moeten scrollen.
Voor de gebruiksvriendelijkheid lijkt het mij beter dat het volledig inlogkader ineens mee zichtbaar is.
Bovendien ook de privacy-voorwaarden, of tenminste een knop om die te raadplegen/aanvaarden.
Een knop voor nieuwe registratie (eerste gebruik) zo ook welkom zijn.

**Stappen om te reproduceren**
1. Ga naar 'https://test.nelos.be/'
2. Zie fout

**Verwachte resultaat**
Een opstartscherm met gelijkaardige mogelijkheden als DIVES 1.0
![image](https://user-images.githubusercontent.com/115356929/194710811-da3d3fd7-84ff-46e4-8b5d-b8c66b43b03a.png)

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.
![image](https://user-images.githubusercontent.com/115356929/194710668-da18852a-5b5e-40ae-ac89-a72c2545d172.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows]
 - Browser: [Firefox]
 - Versie: [105.0.2]

**Comment by ndsmyter** [comment]
Dat zijn goede opmerkingen! Op mijn scherm nog nooit last gehad dat ik moest scrollen, maar ik test natuurlijk altijd met groot scherm.

Ben je zo nog dingen tegengekomen die op jouw scherm wat scrollen vereisen terwijl dat eigenlijk niet echt zou moeten?

**Comment by KamielKempeneers** [comment]
Vermits je ernaar vraagt: 
Persoonlijk vind ik dat de algemene layout van zowat alle pagina's van DIVES 2.0 onvoldoende "nuttig" gebruik maakt van de beschikbare ruimte op een scherm: er wordt in de nieuwe layout overal te veel schermruimte "verkwist" aan witte tussenruimte, waardoor er inderdaad onnodig veel gescrolld moet worden... althans da's mijn mening...
![image](https://user-images.githubusercontent.com/115356929/195211243-2ebda120-fe22-4864-9f1f-c64281bd3f9f.png)

**Comment by user4294** [comment]
Ik ben persoonlijk wel een voorstander van de extra witruimte - iets rustiger voor de ogen dan Dives 1.0. Hier en daar zouden er evt. nog wat zaken opvallender mogen gemaakt worden, zoals bijv. een groter blok voor de datum van de duik (à la Dives 1.0).

**Comment by ndsmyter** [comment]
Ik denk dat we deze kunnen afsluiten. De meeste mensen lijken wel te appreciëren dat het niet allemaal op elkaar plakt.
Dat geeft ook meer "rust" dan dat alles op elkaar plakt.
