### ISSUE TITLE
Opleiding aanmaken laadt eeuwig

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#102]
Wanneer ik (voor sommige leden) een opleiding wil aanmaken laadt de pagina eeuwig.

**Stappen om te reproduceren**
1. Ga naar 'beheer club (Salvanos)'
2. Achter een naam van een lid Klik op '...' en dan op 'start opleiding'
3. Zie fout

**Verwachte resultaat**
Hier zouden alle mogelijke opleidingen voor het gekozen lid moeten verschijnen om de gewenste opleiding te starten.
**Screenshots**
![image](https://user-images.githubusercontent.com/115356929/194711844-1159105d-1a33-4cbe-8de9-e2cc5380d869.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows]
 - Browser: [Firefox]
 - Versie: [105.0.2 (32-bit)]

**Comment by ndsmyter** [comment]
Gekend probleem. Maar is normaal gezien opgelost en zou in de migratie van maandagochtend aanstaande meekomen.

Ik ga deze dus al afsluiten omdat die zo goed als afgewerkt is, het staat klaar om te deployen.
