### ISSUE TITLE
Verschil in tellers met Dives 1.0 

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#103]
De tellers voor aantal duiken en duikuren geven een verschillend resultaat, voor de specifieke tellers kan dat misschien aan de initialisatie en/of de manier van taggen liggen, maar voor het totaal?? Zeker omdat het er 2 meer zijn lijkt het me raar, of werden sommige verwijderde duiken opnieuw meegeteld??
Ter info: mijn totaal aantal duiken klopt in de huidige DIVES met de realiteit, de specifieke tellers kloppen "min of meer", maar wat die tellers betreft zijn de verschillen met DIVES 2.0 enorm. 

Allicht was dit ook een al gekend probleem, maar ik zag het niet in de lijst.

**Screenshots**:
**Huidige DIVES**:
![image](https://user-images.githubusercontent.com/115356929/194902788-64d8ea9b-3a26-4ee7-8eea-4b5a796171bb.png)
**Test DIVES**:
![image](https://user-images.githubusercontent.com/115356929/194903330-716f6f69-370a-4fb9-8067-24720b69df42.png)

**Comment by ndsmyter** [comment]
Dat zijn nuttige punten dat je hier aanhaalt.

De reden dat er meer duiken zijn, is vermoedelijk omdat er in jouw carrière van DIVES 1.0 ook Overige activiteiten zijn. Die zijn recent gemigreerd als Duik (want Overige bestaat niet in DIVES 2), maar je zou dan wel gemarkeerd moeten zijn als Niet-Duiker en zou niet mogen meetellen.
Dus ofwel telt die duik hier toch per ongeluk mee, ofwel is er iets verkeerd gegaan bij het migreren. Ik zoek het uit!

De tellers zelf kloppen nog niet altijd omdat de initialisaties nog niet altijd meegeteld worden. Dit staat nog op mijn takenlijst om op te kuisen, maar is er nog niet van gekomen.

**Comment by user4294** [comment]
Ter aanvulling: ik heb op Dives 1.0 één duik teveel, in Dives 2.0 waren er het er initieel twee teveel. Sindsdien nog vijf duiken gedaan, waarbij mijn teller in 1.0 nu op 323 en in 2.0 326 staat, dus een verschil van drie. De laatste duiken staan niet dubbel in 2.0, dus kan de oorzaak niet meteen achterhalen.

**Comment by ndsmyter** [comment]
Misschien goed dat we deze check nog eens doen binnenkort nadat mijn aanpassing gepubliceerd is?

Ik heb de code al aangepast, maar iets anders houdt me nog even tegen om het al op test te zetten. Van zodra ik nog eens tijd heb om hier aan te werken, kan ik het hopelijk oplossen.

**Comment by user4294** [comment]
Lijkt erop dat mijn tellers nu gelijklopen tussen 1.0 en 2.0!

**Comment by ndsmyter** [comment]
Volgens @user4294 opgelost, dus sluit ik af. Indien nog iemand fouten merkt, kunnen we nieuwe bug maken of deze heropenen.

**Comment by KamielKempeneers** [comment]
Oorspronkelijk had ik in DIVES 2.0 2 duiken meer, nu nog steeds 1 duik meer dan in DIVES 1.0, dus iets opgelost maar misschien nog niet alles???

**Comment by KamielKempeneers** [comment]
In een poging te zoeken naar die éne duik verschil ben ik op andere eigenaardige resultaten gestoten:
DIVES 1.0: de jaartotalen kloppen, maar de "maandstatistieken" in de scrollbalk bovenaan tellen ALLES, ook niet-duikactiviteiten en zelfs deleted items.
DIVES 2.0: de jaartotalen kloppen, bij de totalen berekend per maandperiode loopt iets fout waardoor niet alle duiken geteld lijken te worden.
Resultaat: ik heb niet gevonden vanwaar die ene duik verschil komt, de jaartotalen van alle ingebrachte duiken sinds begin 2019 kloppen, de initialisatiegegevens zie ik niet, maar die zouden eigenlijk geen verschil met DIVES 1.0 mogen geven????
![Tellers DIVES 1 0](https://user-images.githubusercontent.com/115356929/207053023-a246eaa0-b0ce-4cdf-84dc-6fe715ebaadf.jpg)
![Tellers DIVES 2 0](https://user-images.githubusercontent.com/115356929/207053651-00498dac-56e4-45b6-b621-20a47881e4ef.jpg)

**Comment by ndsmyter** [comment]
Probleem met de ene waarde verschil zou nu opgelost moeten zijn.

**Comment by KamielKempeneers** [comment]
Niet echt overtuigd dat het opgelost is... 
Nu geeft mijn logboek in DIVES 2.0 ineens 50 duiken te weinig aan...
Het verschil zit nu volledig in het aantal van vóór 2019

**Comment by ndsmyter** [comment]
Hey @KamielKempeneers ,
Dat is omdat het wel opgelost is in de code, maar nog niet op test.nelos.be staat.
Je zal dus nog paar dagen geduld moeten hebben om goed te kunnen testen

**Comment by KamielKempeneers** [comment]
Ok, sorry dan... te rap gereageerd...

**Comment by KamielKempeneers** [comment]
Prettige Kerstdagen Nicolas... 
en af en toe ook eens je computer afzetten (heb daar ook moeite mee)...
