### ISSUE TITLE
[BUG] Mijn profiel versus Statistieken

### ISSUE THREAD

**Issue by user4294** [Nelos-VZW/dives-2#105]
**Beschrijf de bug**
Geen bug, maar momenteel is het wat verwarrend dat er zowel statistieken staan onder "Mijn profiel" (totalen) als onder "Statistieken" (aanpasbare periode). "Mijn profiel" is bij de recentste update lichtjes herschikt, maar je hebt nog altijd de combinatie van Persoonsgegevens en duiktotalen. 

![stats](https://user-images.githubusercontent.com/56023403/195357539-3ae9ebd9-45fc-49fb-85d1-502ef6a47893.png)

Mogelijk kan dit iets logischer worden opgebouwd? Bijv.
Mijn profiel (enkel persoonsgegevens + foto aanpassen) 
Opleidingen (lopende opleidingen en evt. datum behaalde brevetten?)
Overzicht (totalen)
Statistieken (aangepaste statistieken)

**Comment by ndsmyter** [comment]
Dat moeten we misschien inderdaad wat uitlijnen. Want ik was er nog niet over gestruikeld, maar je geeft wel een correcte opmerking.
Ik vermoed dat we de tabel "Type duiken" ook gewoon beter tonen op de "Statistieken" tab; want dat zijn inderdaad ook gewoon statistieken.

Ik denk dat het misschien ook beter is om "Mijn profiel" te hernoemen naar "Mijn gegevens". En ik zou het ook naar de laatste tab brengen, want je hebt dat niet ELKE keer nodig als eerste tab. Logischer om eerst de Opleidingen of Statistieken tab te tonen.

**Comment by ndsmyter** [comment]
Dit zou nu beter moeten zijn

**Comment by user4294** [comment]
Opdeling is inderdaad logischer :)
