### ISSUE TITLE
[BUG] Weergave Opleiding

### ISSUE THREAD

**Issue by user4294** [Nelos-VZW/dives-2#106]
**Beschrijf de bug**
Vakjes voor lopende opleiding zijn nog wat te klein.

**Stappen om te reproduceren**
1. Ga naar 'Profiel'
2. Klik op 'Opleidingen'

**Verwachte resultaat**
De tekst voor de opleidingen past niet altijd binnen de voorziene vakjes. In de vakjes wordt dezelfde tekst herhaald (als titel in wit en als verduidelijking in grijs). De vakjes zouden wat groter mogen, de tekst mogelijk wat herwerkt. 
(bijv. de afkorting OW voor open water lijkt me niet bij elke beginnende duiker gekend, AI voor Assistent Instr. dan weer wel).

**Screenshots**
![opl](https://user-images.githubusercontent.com/56023403/195359577-7cc28e89-b99b-4482-a950-6d183798f75e.png)

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: Samsung A52S
 - Besturingssysteem: Android 12
 - Browser: Brave

**Comment by user4294** [comment]
Kleine aanvullende opmerking: ik vind het niet evident de icoontjes van de proeven te interpreteren. Afgelegde proeven een zwart stempeltje (?), niet-afgelegde een blauw bolletje met '...'.  Hoe moet je dit juist lezen? Voor mij zou het bijv. logischer te zijn met een zwarte open checkbox te werken, een in-progress gekleurd bolletje en een groen vinkje, zoals in DIVES 1.0.

![Screenshot_20221204_161913_Brave](https://user-images.githubusercontent.com/56023403/205502744-6df31673-b8a1-401f-b205-b868be8db034.jpg)

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-397

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
