### ISSUE TITLE
[BUG] Export logboek Excel

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#107]
**Beschrijf de bug**
Exporteren naar excel van het logboek werkt niet

**Stappen om te reproduceren**
1. Ga naar logboek
2. Klik op exporteren excel

**Verwachte resultaat**
Excel die wordt aangemaakt en gedownload/geopend

**Screenshots**
![image](https://user-images.githubusercontent.com/8513610/196348710-7a445c26-3e54-4907-a71c-20dccdfd7aa6.png)

**Comment by ndsmyter** [comment]
Zou opgelost moeten zijn.
