### ISSUE TITLE
Ledenadministratie, doorklikken naar brevetkaart

### ISSUE THREAD

**Issue by Ann-Mieke** [Nelos-VZW/dives-2#108]
Als je in de ledenadministratie wil doorklikken op brevetkaart spring je terug naar je logboek
![image](https://user-images.githubusercontent.com/116261776/196896825-20ab7519-7803-4b0a-88e4-cce00b626ab1.png)

**Comment by ndsmyter** [comment]
Ik denk -- maar niet 100% zeker -- dat dit vermoedelijk reeds opgelost is.

**Comment by ndsmyter** [comment]
Dit lijkt nu opgelost te zijn
