### ISSUE TITLE
Weergave: beheer club - deel van de info niet zichtbaar

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#110]
Wanneer de kolom "bookmarks" actief is, dan is een gedeelte van de info van het scherm niet zichtbaar, met name een deel van de kolom brevetten en heel de kolom opleidingen, terwijl men zou verwachten dat de kolombreedte zich aanpast.
Vooral dat de kolom opleiding totaal niet zichtbaar is in deze weergave is hinderlijk, het is daardoor onmogelijk opleidingen te controleren, een OPLV aan te passen, enz.

Bijkomend probleem van de weergave: ongelooflijk veel "blanco" schermruimte, daardoor passen er amper 4 leden op het hele scherm, terwijl dit verondersteld wordt een lijst-weergave te zijn; erg vervelend, het beheer wordt een oefening in scrollen.
Het aantal lijnen van de kolom "bookmarks" geeft een beeld van nuttig schermgebruik, met min of meer vergelijkbare grootte van de letters.

**Stappen om te reproduceren**
1. kolom 'bookmarks' actief
2. Ga naar 'beheer club'
3. Zie fout

**Verwachte resultaat**
schermweergave analoog aan weergave zonder kolom "bookmarks"
![image](https://user-images.githubusercontent.com/115356929/198854966-6ab40ba4-b8e9-491f-bcb3-298022fa2506.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/115356929/198855006-f310803c-d4b6-4d91-bd62-d76d843e655b.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows
 - Browser: Firefox
 - Versie: 106.0.2

**Smartphone (indien mogelijk aanvullen):**
 N.V.T.
**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Ik zet deze even on-hold. Endare moet deze pagina nog een beetje verwerken, dus we kunnen beter nadien kijken welke opmerkingen er nog over blijven.

In elk geval kan ik wel steleln dat de kolommen zich niet zullen aanpassen als uw scherm kleiner wordt. Er zal altijd een beetje witruimte links en rechts overblijven, om het niet te druk te maken. In de plaats daarvan zal je moeten scrollen links/rechts om de informatie uit de andere kolommen te zien.

Maar Endare gaat enkele van de overbodige kolommen weghalen, waardoor het misschien al iets aangenamer is om te lezen.
Daarnaast zal de kolom van de opleidingen ook wat aangepast worden, en zullen de lange namen van de opleidingen afgekort worden de codes van de opleidingen (bv "3*D" ipv "3* Duiker"). Hierdoor zal er minder nood zijn aan nieuwe regels, en zullen er normaal gezien meer leden op 1 scherm kunnen.

**Comment by KamielKempeneers** [comment]
1. Door de horizontale scrollbar kan nu de volledige breedte wel zichtbaar gemaakt worden, maar daarbij schuift de tekst van boven de tabel zelf doorheen de linker kolom.
2. De kolom "brevetten" zou m.i. veel smaller mogen zijn (kolombreedtes kan ik niet zelf aanpassen).
![image](https://user-images.githubusercontent.com/115356929/210117699-64d0f2c4-8bde-4bcf-96d4-d2e8cabb1317.png)

**Comment by DIVEScoordinator** [comment]
@ndsmyter   deze lijkt mij achterhaald, ondertussen veel veranderd. Nog relevant?

**Comment by ndsmyter** [comment]
Zou inderdaad niet meer mogen voorkomen. Ik heb dat overlaatst nog eens getest, en toen had ik dat probleem niet meer.

**Comment by KamielKempeneers** [comment]
Klopt, actueel geen probleem: basisbrevet, andere brevetten en opleidingen zijn nu in één kolom.
Op de laatste Teams-meeting met ledenadministrators werd aangekondigd dat het misschien terug drie aparte kolommen zouden worden, dan misschien opnieuw een aandachtspunt?

**Comment by ndsmyter** [comment]
In de volgende versie (vermoedelijk dit weekend in PROD), zal het alvast in 2 kolommen zijn. Brevetten vs opleidingen, ofwel behaald vs nog niet behaald.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/648669/233607105-0e57d888-182e-42d4-b7af-844fb188240e.png">

**Comment by KamielKempeneers** [comment]
Op de testsite ziet dit er ook bij mij alleszins goed uit... weer mooie verbetering!
Detail: misschien kan de kolom inschrijvingstype iets smaller (vb. titel "activiteit" is minder breed dan "inschrijvingstype")
