### ISSUE TITLE
[BUG] Teller aantal duiken heeft 1 duik verschil met Dives 1.0?

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#115]
**Beschrijf de bug**
We hebben onlangs 2 theorie activiteiten toegevoegd in Dives 1.0 voor een CPR les  voor kandidaat 1*D en kandidaat vrijduikers. Als ik in Dives 2.0 naar die kandidaten ga kijken (die allemaal nog nooit gedoken hebben) dan hebben die allemaal 1 duik op hun naam staan. (zie screenshot 1)
Ook in mijn statistieken is er een verschil van 1 duik (alhoewel ik deelnemer ben bij de 2 theorie activiteiten), maar als ik me niet vergis komt dat door de synchronisatie van een 'overige duik' in dives 1.0, klopt dat? (zie screenshot 2)
Alhoewel dat het aantal duik uren ook verschilt (+33) terwijl die extra duik activiteit voor 'overige' 0 minuten is. (zie screenshot 3)

**Stappen om te reproduceren**
Ik ging naar de laatst gelogde theorie activiteit, klik op één van de K1*D deelnemers en zag dat die 1 duik had gedaan.

**Verwachte resultaat**
- theorie mag niet als duik tellen (ook niet na synchronisatie met dives 1.0
- overige zou niet mogen synchroniseren als duik, maar daar had 'Nicolas' een aantal voorstellen klaar dacht ik.

**Screenshots**
K1*duikers met 1 extra duik
![image](https://user-images.githubusercontent.com/121305742/209364489-de326575-d73f-45a3-88af-a6a0e7ee7244.png)
Mezelf met 1 extra duik
![image](https://user-images.githubusercontent.com/121305742/209364657-87e59810-e1bb-43f4-9be2-7c5ba3630054.png)
Verschil in uren
![image](https://user-images.githubusercontent.com/121305742/209365248-34fa171b-2cd4-49d9-bbbe-d2a08f6d97c8.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Probleem met de teller is opgelost.

**Comment by KWillemse** [comment]
Dat zou kunnen maar ik kan dat nu niet nakijken want alle activiteiten van januari zijn nog niet geimporteerd.

**Comment by ndsmyter** [comment]
Importeren gebeurt maar 1 keer per week meer, en dat is op maandag. Normaal zou je dus vanaf maandag alle activiteiten moeten zien. Tot en met maandagmorgen.

**Comment by KWillemse** [comment]
ik heb een duik op 7,14 en 15 januari en ik zie ze niet in DIVES 2.0

**Comment by KWillemse** [comment]
Ik heb het vandaag nog eens even nagekeken maar ik blijf mijn duiken van januari 2023 niet zien. Als ik dan trouwens filter op alle duiken vanaf jan 2023, dan zie ik enkel de duiken van Januari 2020 en 2019. 
![image](https://user-images.githubusercontent.com/121305742/214058486-7ce2ccd9-d3d4-4c65-8d6c-328aa7c3d35c.png)

Filteren vanaf december 2022 werkt wel.
Moet ik hier een ander issue voor loggen?

**Comment by ndsmyter** [comment]
Ik zal de taak even terug open zetten, zodanig dat we het eens kunnen bekijken.

**Comment by ndsmyter** [comment]
Dit lag aan een migratie-issue, dat normaal reeds opgelost is.

**Comment by KWillemse** [comment]
Ik heb nog 2 nieuwe issues gelinkt. Eén daarvan is een klein onderdeel van de 'counters', een tweede had ik in de history van deze case al gemeld.

Het hoofdprobleem is wel degelijk opgelost.
