### ISSUE TITLE
[BUG] diepte statistieken zijn verschillend tussen Dives 1.0 en 2.0

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#116]
**Beschrijf de bug**
aantal duiken dieper dan 30 lijken nogal te verschillen terwijl de andere statistieken kloppen.

**Stappen om te reproduceren**
Ga naar de statistieken op Dives 1.0 en vergelijk met de statistieken op Dives 2.0

**Verwachte resultaat**
Dat ze gelijk zijn.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209365568-6c9ac646-d50f-4551-bf9a-c84c957438a7.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Correct opgemerkt. Blijkbaar zat de fout in de berekening van de statistieken in DIVES 1.0. Daar had ik eerst >=30 EN <40 staan. Maar moest dit dan weghalen omdat ze vanuit duikonderricht enkel max >30 wilden zien staan. Ik heb blijkbaar nooit de conditie <40 weggehaald. In DIVES 2.0 had ik die conditie niet toegevoegd.

Ik heb nu het script aangepast, en morgenvroeg zullen de statistieken van DIVES 1.0 correct worden berekend.

**Comment by KWillemse** [comment]
geverifieerd en goegekeurd
