### ISSUE TITLE
[BUG] het aantal leden in onze club (DIVES 2.0) komt niet overeen met de ledendatabase van NELOS en met DIVES 1.0

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#117]
**Beschrijf de bug**
Als we de ledendatabase van NELOS exporteren hebben wij 189 lijnen, als we DIVES 1.0 exporteren zijn er 170 lijnen en in DIVES 2.0 heeft er 178.
- ofwel zijn er bepaalde lidgeld types die niet meer worden overnomen in DIVES, zoja dewelke
- ofwel zit er een bugje in

**Stappen om te reproduceren**
Ga naar de ledendatabase van NELOS en Exporteer deze naar excel.
Ga naar DIVES 1.0, uw club en dan Exporteer Excel
Ga naar beheer in DIVES 2.0 en kijk naar het 'totaal'.

**Verwachte resultaat**
Ik verwacht dezelfde hoeveelheid aan leden in alle databases

**Screenshots**
Nelos DB:
![image](https://user-images.githubusercontent.com/121305742/209380937-b8b90cbe-3771-4a10-9572-509a435c82f4.png)
DIVES 1.0:
![image](https://user-images.githubusercontent.com/121305742/209381876-7949507f-d4f4-4d56-8899-faca9dc4316b.png)
DIVES 2.0:
![image](https://user-images.githubusercontent.com/121305742/209382059-de45b6f1-fc91-40c5-9dba-59e911782fc1.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Momenteel werden enkel de leden uit DIVES gemigreerd. Dat betekent dat het enkel mensen zijn die al eens eerder ingelogd zijn geweest in DIVES. Dat verklaart het verschil tussen DIVES 1.0 en 2.0. Ik heb nu enkele aanpassingen gedaan zodanig dat de ontbrekende personen ook mee gemigreerd zouden moeten worden.

**Comment by KWillemse** [comment]
de switch voor 'Actieve leden' is super, dus ik zette hem op 'Alle leden' en ik zie de lijst volledig, SUPER. Maar ik heb nu geen teller meer onderaan.
Als ik de lijnen in excel paste kom ik op 265 leden, NELOS ledenDB is maar 194

Nu lijkt het wel of je echt alle leden, ook leden van de vorige jaren mee importeert.

**Comment by ndsmyter** [comment]
@KWillemse 
Volgens mij is deze ondertussen al opgelost?

**Comment by KWillemse** [comment]
Nog niet helemaal denk ik: De leden in DIVES 1.0 zijn er 181 en de leden in DIVES 2.0 zijn er 172. 
Er zijn dus 9 leden tekort. In eerste geval dacht ik aan vrijzwemmers, niet-actieve leden, maar er zitten ook een vrijduiker en 2 sportduikers tussen. Daarenboven zijn er zijn ook vrijzwemmers die wel in de lijst staan van DIVES 2.0.

Dit zijn de leden die niet in DIVES 2.0 staan:
![image](https://user-images.githubusercontent.com/121305742/226491839-c2a24520-aa63-4325-b738-43ff6e077386.png)
