### ISSUE TITLE
[BUG] er wordt momenteel geen rekening gehouden met de juiste rol om bepaalde poeven af te tekenen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#118]
**Beschrijf de bug**
Een gesyncroniseerde Theorie activiteit vanuit DIVES 1.0 bevat alleen maar 'deelnemers'. Als je daar dan proeven aan toevoegt, dan staat er wel een 'evaluator' bij, dit lijkt de persoon te zijn die de activiteit heeft gelogd of de OPLV, maar ik kan als 'deelnemer' toch de proeven als afgewerkt markeren. (zie screenshot 1)
Is de rol functie enkel maar 'supplementair' of moet die ook effectief bepaalde zaken gaan verbieden/toelaten bovenop onze brevetten?

**Stappen om te reproduceren**
Ga naar een gesyncroniseerde Theorie activiteit vanuit DIVES 1.0, voeg proeven toe en selecteer ze als afwerkt.

**Verwachte resultaat**
Als er geen 'evaluator' bij theorie activiteiten is aangeduid, moet er bij evaluator eigenlijk staan 'Voeg eerst een evaluator buddy toe' (zie screenshot 2)

**Screenshots**
Evaluator staat ingevuld maar er is geen rol toegekend. Is dit de creator van de activiteit of the OPLV?
![image](https://user-images.githubusercontent.com/121305742/209385251-a5c74091-1843-4551-85d8-e6617b1409ea.png)

Bij deze proef is er nog geen evaluator (omdat dit normaal DO-NELOS is, of omdat ik die proef niet mag aftekenen?)
![image](https://user-images.githubusercontent.com/121305742/209384940-c2ef88d2-8d4b-43a0-84df-354a76551cfd.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Hey @KWillemse ,
Eigenlijk valt dat onder jouw voorsteld "supplementair". Het is geen vereiste dat de persoon zich aangeeft als "evalutator". Sterker nog, soms kan je dat zelf niet. Als je denkt aan de proef "Vinzwemmen B1-C1-D1-E1", dan hoef je als instructeur niet meegedoken te hebben. Om dit op te vangen kan je je als instructeur op "Niet-duiker" zetten. Dit heeft namelijk het speciale effect dat je als instructeur wel lid bent van de activiteit, maar dat je duik niet meetelt als duik voor jou. Dus alle duiken waar je als "Niet-duiker" staat, zullen niet meetellen voor je persoonlijke eindtotalen.

Dit is dus redelijk normaal gedrag.

**Comment by KWillemse** [comment]
Ik begrijp het design en voor mij is deze wel in orde.
