### ISSUE TITLE
[Feature] Info bestuursleden zoals in Dives 1.0

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#12]
In Dives 1.0 had je als ledenbeheerder een zicht op de functies die NELOS gegeven heeft aan de bestuursleden (voorzitter, postontvanger, boetiekverantwoordelijke, ect). Dit is niet zichtbaar in Dives 2.0; kan dus ook niet meer gecontroleerd worden of dit correct is. 

**Beschrijf de oplossing die je zou willen**
- Het zichtbaar maken van deze functies, zoals in Dives 1.0
- de mogelijkheid om deze functies aan te passen als ledenbeheerder; nu moeten we hiervoor het secretariaat altijd contacteren

![image](https://user-images.githubusercontent.com/112517511/187549800-d656559d-ab64-4a8c-950a-10ce9d141139.png)

Verder vind ik de lay-out van Dives 1.0 voor dit onderdeel wel aangenamer dan in Dives 2.0

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-396

**Comment by ndsmyter** [comment]
Zal voor volgende versie zijn

**Comment by DIVEScoordinator** [comment]
@ndsmyter deze zeker in de volgende sprint meenemen

**Comment by ndsmyter** [comment]
Kan je in huidige versie zien
