### ISSUE TITLE
[BUG] men kan proeven toevoegen waarvoor men niet bevoegd is

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#120]
**Beschrijf de bug**
Ik ben zelf 1*I en bij een 'theorie activiteit' kan ik een proef toevoegen voor '2*I'. Ik kan ze op dit moment niet aftekenen, dus voorlopig niet erg, maar ik veronderstel dat het toevoegen van proeven al moet kijken naar je brevet. Nogal stom om eerst toe te laten om proeven toe te voegen om daarna pas te zien dat jij ze eigenlijk niet mag aftekenen.

**Stappen om te reproduceren**
Maak een theorie activiteit met twee 1*I, je kan dan de proef 'Theorie examen' voor 2*I toevoegen.

**Verwachte resultaat**
Bij de lijst van toe te voegen proeven zou ik alleen de proeven die ik mag af tekenen verwachten. Ik begrijp dat men zou willen toelaten dat een OPLV ook proeven mag toevoegen die niet tot zijn bevoegdheid horen om dan daarna door instructeurs te laten aftekenen die wel bevoegd zijn. Maar dat ik een proef kan toevoegen voor 2*I dat lijkt me echt niet correct.

**Screenshots**
Ik kan dit kiezen:
![image](https://user-images.githubusercontent.com/121305742/209389434-a7d2ca86-fb00-4ced-aa86-9e84d5126245.png)

Maar ik kan deze niet aftekenen (misschien kan ik het wel als er een evaluator zou opgegeven zijn).
![image](https://user-images.githubusercontent.com/121305742/209389956-05b4e31b-be72-4298-9cb9-4465dcdaa630.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Hey @KWillemse ,
Wat je hier beschrijft is geen bug, maar wel een feature.
Iedereen, dus ook kandidaten, gaan nu proeven kunnen ingeven in DIVES 2.0. Het voordeel hiervan is dat we ook de instructeurs nu gaan kunnen triggeren als ze nog een proef moeten aftekenen.
Vanzelfsprekend ga je die natuurlijk wel niet kunnen aftekenen als je daarvoor niet bevoegt bent.

Dus dit is geen bug :-)

**Comment by KWillemse** [comment]
Ik begrijp het feature dat je als kandidaat je instructeur zou willen triggeren om een proef af te tekenen en dan moet je dus in staat zijn om een proef toe te voegen waarvoor je zelf niet bevoegd bent (en die je dus ook niet zelf kan aftekenen) maar is het niet raar dat ik een proef kan kiezen waarbij niemand van je buddy (of buddies) bevoegd is om die af te tekenen? Stel dat je dat per ongeluk doet, kan die proef dan uiteindelijk in een andere activiteit nog toegevoegd en goedgekeurd worden?

**Comment by ndsmyter** [comment]
Je kan een proef meerdere keren linken, maar kan maar 1 keer afgetekend worden. Dit om bijvoorbeeld toe te laten dat 2 mensen toch samen proeven aan het aanmaken zijn.

Eenmaal een proef afgetekend werd, wordt die van alle andere activiteiten verwijderd. Ik de backend code wordt ook afgecheckt dat een proef niet dubbel afgetekend kan worden.

**Comment by KWillemse** [comment]
Dat zijn goede checks om fouten te voorkomen. Desalnietemin blijf ik het raar vinden om een proef toe te voegen aan een activiteit als niemand van de buddies bevoegd is om die af te tekenen. 
Heeft enkel nut om DO-NELOS en VR-NELOS te triggeren lijkt me ;-)

**Comment by ndsmyter** [comment]
Dat is hoe we het overeengekomen tijdens de functionele analyse fase 🙂
