### ISSUE TITLE
[BUG] een nieuwe foto uploaden werkt niet

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#121]
**Beschrijf de bug**
Ik heb een gewone foto genomen (.jpg) maar ook een echte 'avatar.png' en als je klikt op 'opslaan' dan gebeurd er niets

**Stappen om te reproduceren**
1. Ga naar je profiel, Persoonlijke gegevens, en klik de 'Choose File' knop.
2. Kies een foto
3. kies 'opslaan'

**Verwachte resultaat**
Je moet een foto kunnen uploaden en er moet info staan over het formaat of je moet feedback krijgen als het formaat niet goed is.

**Screenshots**
foto opladen:
![image](https://user-images.githubusercontent.com/121305742/209391019-4cf8ffd3-5df1-4b8d-917a-f891d4a64944.png)
niet gelukt:
![image](https://user-images.githubusercontent.com/121305742/209391074-9c0c448e-0266-4fef-b44f-9daf5f61ed95.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Dit zou normaal gezien nu terug moeten werken.

**Comment by KWillemse** [comment]
geverifieerd en goegekeurd
