### ISSUE TITLE
[BUG] het aanpassen van de 'Initialisatie' geeft extra lijnen.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#122]
**Beschrijf de bug**
Als je op het pen icoontje drukt van een item in de Initialisatie en je past de waarde aan, dan komt er een extra item met dezelfde naam te staan.

**Stappen om te reproduceren**
1. Ga naar je profiel, initialisatie
2. klik op het pen icoon naast 'Aantal duiken'
3. pas de waarde aan en klik op OK

**Verwachte resultaat**
Ik verwacht dat je deze waarden gewoon kan aanpassen en dat automatisch de teller van je duiken (en type duiken) word aangepast

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209391558-7c5f9b0a-acad-4c6d-921e-d8b3effbb664.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Probleem werd aangepakt in de code waardoor dit niet meer zou mogen voorkomen.

**Comment by KWillemse** [comment]
geverifieerd en goedgekeurd
