### ISSUE TITLE
[BUG] De bewerkingsgeschiedenis moet alleen de aanpassingen weergeven

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#123]
**Beschrijf de bug**
Ik had enkel de rol van mezelf in een theorie activiteit aangepast en de bewerkingsgeschiedenis geeft aanpassingen van datum, tijd, duurtijd, diepte, temperatuur en zichtbaarheid. (in zwembad wezenberg  :-).

**Stappen om te reproduceren**
1. Ga naar een theorie activeit
2. verander je rol naar bv 'Evaluator'
3. kijk naar de bewerkingsgeschiedenis

**Verwachte resultaat**
Enkel maar de effectieve bewerkingen meegeven. Stel dat je dezelfde waarde zou typen dan mag dit van mij part een bewerking zijn.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209391984-2e717b4d-ca59-441a-80c9-86ee8d6b2462.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Is volgens mij opgelost nu

**Comment by KWillemse** [comment]
'Evaluator' kan je niet meer kiezen, als je 'Niet-duiker' kiest dan krijg je nog wel 2 logs, eerst 'verwijderd als duiker' en dan aangepast naar 'Niet-duiker', maar gelukkig zijn er geen logging meer van datum, tijd, uur, etc.

Ik zie wel dat je de rol 'leeg' kan maken, is dat normaal?

**Comment by ndsmyter** [comment]
Dubbele logging is niet ideaal, maar ook niet zo erg denk ik.

Het leegmaken van de rol heb ik nu uitgezet en zal binnenkort ook actief worden op dives.nelos.be bij volgende deploy (nu nog niet)

**Comment by KWillemse** [comment]
OK
