### ISSUE TITLE
[BUG] de 'Back' (browser) vanuit een activiteit moet in je logboek die activiteit in view brengen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#124]
**Beschrijf de bug**
Als ik naar een 'oude' activiteit scroll, deze open doe en dan de 'back' toets van de browser gebruik, dan zie ik terug mijn logboek maar mijn laatste duiken in 'view'. Heel lastig als je wat info over verschillende oude duiken wil ophalen.

**Stappen om te reproduceren**
1. Ga naar je logboek
2. scroll verder naar beneden en klik op een duik
3. click op de back knop van je browser

**Verwachte resultaat**
Je moet de duik die je aan het bekijken was terug in view brengen als je terug naar je logboek gaat.

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by KWillemse** [comment]
Zelfs als je een filter hebt toegepast van bv. de maand juni zal de 'Back' in de browser de filter verwijderen en ga de view gewoon terug naar je laatste duiken.

**Comment by ndsmyter** [comment]
Dat zal vermoedelijk nog niet voor de eerste versie van DIVES 2.0 worden.

**Comment by DIVEScoordinator** [comment]
Niet voor 2024 - op de lijst voor 2025

**Comment by ndsmyter** [comment]
Opgelost voor in de volgende versie
