### ISSUE TITLE
[BUG] Indien een foto niet gekend is zou deze het nieuw NELOS logo moeten zijn

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#125]
**Beschrijf de bug**
Als er in DIVES 1.0 geen foto werd toegekend, of voor nieuwe DIVES 2.0 leden kan je best het 'nieuwe NELOS logo' gebruiken.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209392663-07b3a319-45c5-4e82-82ec-d58d76824565.png)

**Comment by ndsmyter** [comment]
Done

**Comment by KWillemse** [comment]
Ik zie geen icoontje meer, ik zie nu het woordje 'Buddy met de naam', dit is echt niet goed:
![image](https://user-images.githubusercontent.com/121305742/213882574-e74b8436-ef94-420d-aea2-72f3c4bef097.png)

**Comment by ndsmyter** [comment]
@Cereal2nd Kan jij deze eens bekijken?

**Comment by Cereal2nd** [comment]
hmm op dev werkt dit wel, op test niet, ergens moet er dus iets verschillend zijn ...


dev
![afbeelding](https://user-images.githubusercontent.com/3715825/213932042-f02038c4-5c1c-44fa-8d5d-69e5ceacf24d.png)
test
![afbeelding](https://user-images.githubusercontent.com/3715825/213932064-d13c8fa1-044e-4632-8c61-68ccfb0de95c.png)

**Comment by Cereal2nd** [comment]
de cache verwijderd op test en daarmee is het opgelost

**Comment by ndsmyter** [comment]
Lang leve cache clear 😀

**Comment by KWillemse** [comment]
Idd lang leve de cache clear.

Waar staat die button om te clearen ;-)
