### ISSUE TITLE
[BUG] De scroll functie zou niet mogen werken op het kaartje van een activiteit

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#126]
**Beschrijf de bug**
Ik ben een gebruiker van het scroll wieltje van mijn computer muis en als ik in een activiteit aan het scrollen ben en het kaartje komt 'in view' dan begint dat kaartje in te zoomen, terwijl ik eigenlijk naar beneden wil gaan om naar bv. de bewerkingsgeschiedenis te gaan kijken.
Dit was trouwens ook een probleem in DIVES 1.0.
Ik weet dat er voorlopig alleen maar de bewerkingsgeschiedenis onder staat maar ik vermoed dat er ooit misschien nog meer info onder komt.

**Stappen om te reproduceren**
1. Ga naar een activiteit en begin te scrollen
2. boven op het kaartje scroll je verder 

**Verwachte resultaat**
Liefst geen scroll functionaliteit op het kaartje.

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Opgelost. Je moet nu klikken op kaartje om te activeren. Buiten kaart klikken zal terug deactiveren.
