### ISSUE TITLE
[BUG] De gekende samenvatting van je profiel in DIVES 1.0 zou misschien ook in DIVES 2.0 zichtbaar kunnen zijn in de hoofdbalk

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#129]
**Beschrijf de bug**
Het is wel handig om naast je naam ook al je brevetten en je status als instructeur te zien in de samenvatting van je profiel (DIVES 1.0), deze zou geplaatste kunnen worden in de hoofdbalk (zie screenshot) waardoor je in één oogopslag je samenvatting ziet en dan voor meer info op de tabs 'Brevetten',... Ik vind trouwens die status als instructeur momenteel nergens terug.

**Verwachte resultaat**
In één oogopslag je samenvatting zien zoals in DIVES 1.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209408114-53c6e36b-386c-4bae-9d07-cc3c08684217.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Deze request werd ondertussen geïmplementeerd en uitgerold

**Comment by KWillemse** [comment]
is niet echt opgelost. Deze info staat wel op de 'Mijn Profiel' pagina maar ik had deze graag samengevat gezien naast de 'Header' zoals ik in de screenshot had aangeduid, waardoor je altijd de samenvatting ziet zoals in DIVES 1.0 en dat de tabs dienen om meer 'details' te kunnen opzoeken. 
Ik vermoed dat er nog meer info in die tabs gaat komen en dan gaat die 'samenvatting' weer verloren.

**Comment by KWillemse** [comment]
Voor de 'status instructeur' ga ik akkoord, deze zal de header te druk maken. Voor de brevetten zou ik toch graag een opsomming zien in de header. BTW, nu zie ik alleen mij 'sportduikbrevet'. Bij een vrijduiker staat daar niets ook al heeft die vrijduiker een brevet.

**Comment by ndsmyter** [comment]
Vrijduikers zullen nog even geduld moeten hebben. We hebben een populatie van 200 (?) vrijduikers versus > 8000 (?) sportduikers. Dus ik vrees dat we altijd eerst naar de sportduikers zullen kijken als het aankomt op dergelijke features. En dat bedoel ik niet onrespectvol, dat is gewoon prioriteiten dat we wat moeten plaatsen.

**Comment by KWillemse** [comment]
Ik begrijp dat de prioriteit voor de vriijduikers niet opweegt tegen de prioriteit voor de sportduikers, maar daarom wil ik deze case nog niet laten sluiten omdat ik hoop dat de prioriteit voor de vrijduikers wel ooit eens aan bod zal komen. Of heb je liever dat ik deze request als een nieuwe log, enkel voor de brevetten?

**Comment by ndsmyter** [comment]
Het punt  van vrijduikers staat nog op mijn persoonlijke planning, dus gaat zeker ooit aan bod komen. Je mag hier gerust ook een taak voor aanmaken in Github. Dat is misschien eenvoudiger dat je dan via die weg een update krijgt als het gebeurd is.

Deze specifieke taak (#129), wil ik dus liever gesloten houden, aangezien die dus wel verwerkt is :-)

**Comment by KWillemse** [comment]
OK, ik zal en taak aanmaken. Ik zal daar dan ook mijn opmerkingen op de mail 'Implementatie van de inschrijving van vrijduiken' aan toevoegen, OK?

**Comment by ndsmyter** [comment]
OK 👍
