### ISSUE TITLE
[BUG] Proef selecteren - GND2 voor GND1?

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#13]
**Beschrijf de bug**
Bij het aanmaken van een duik, als ik een proef wil selecteren kan ik GND2 aanvinken terwijl ik nog geen GND1 gedaan heb. Dit lijkt mij niet correct. GND3 is wel niet beschikbaar tot GND2 uitgevoerd is

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar Maak duik activiteit
2. Klik op proeven toevoegen

**Verwachte resultaat**
GND2 mag volgens mij enkel uitgevoerd worden als GND1 afgewerkt is

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187551426-003b6902-a5a7-424d-ac9c-05f69d8e6ed2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Versie 105.0.5195.54 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
Volgens de infomap zijn enkel de volgorde van de proeven GND2 en GND3 van belang, die mogen niet omgewisseld worden. Dit lijkt me dus geen bug te zijn.
