### ISSUE TITLE
[BUG] Bij de rapportering klopt het aantal kandidaten niet en crashed the client wanneer ik alle kandidaten van de club wil kiezen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#130]
**Beschrijf de bug**
In DIVES 1.0 ben ik OPLV van 19 kandidaten, in DIVES 2.0 van maar 17. Misschien is dat het maximum dat er op het scherm kunnen.
Als ik dan 'Alle kindaten van uw club' wil kiezen dan crashed de client. 

**Stappen om te reproduceren**
1. Ga naar Rapportering
2. Klik op 'all kandidaten van uw club'

**Verwachte resultaat**
Ik veronderstel dat het aantal kandidaten tussen DIVES 1.0 en 2.0 niet veranderd zou mogen zijn en dat ik ook alle kandidaten van mijn club zou kunnen zien.

**Screenshots**
Verschil in aantal
![image](https://user-images.githubusercontent.com/121305742/209408440-91180330-6efb-479c-aa53-bf22b08c39c4.png)

Crash
![image](https://user-images.githubusercontent.com/121305742/209408380-4d7114b6-a41c-4203-bf55-f6e28a090ba1.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Verplaatst naar DIVES 2.1
