### ISSUE TITLE
[BUG] Het zou beter zijn dat bij de rapportering de opleidingen op de horizontale as en de kandidaten op de verticale as zouden staan.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#131]
**Beschrijf de bug**
Ik ben zelf al OPLV van 17/19 BND opleidingen en die passen er maar net op. Als ik dan alle kandidaten van mijn club zou opvragen dan zijn dat er 75. Dat wordt een heel lange 'scroll balk' onderaan.

**Stappen om te reproduceren**
1. Ga naar 'Rapportering'

**Verwachte resultaat**
Ik vermoed dat er in de meeste clubs 'meer kandidaten' zijn dan 'opleidingen', dus lijkt het mij beter dat de kandidaten op de verticale as staan en opleidingen op de horizontale as

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/209408886-936c3624-1d3e-4efa-b34e-386421a04fb2.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Ik ga deze nog even on hold zetten. Ik moet eens wat beter onderzoek doen hiervoor dan.
Want voor de mensen die ik had geprobeerd, leek het beter om het in de huidige richting te doen, omdat er meestal meer opleidingen en proeven waren dan kandidaten. Natuurlijk met de "alle leden" die ik nadien toegevoegd heb, is dat een andere zaak.

Ik bekijk deze nog even, maar ga deze nu even niet als prioritair beschouwen.
