### ISSUE TITLE
[BUG] De titel balk zou moeten aangeven dat je in DIVES zit en een keuze moeten geven om naar de andere NELOS onderdelen te gaan

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#132]
**Beschrijf de bug**
1.  het huidige logo van NELOS in de hoek is te klein om te zien dat je in DIVES zit. 
2. Op de huidige 'nelos.be' kan je gemakkelijk van de homepage met 1 klik naar Boetiek, Clubzoeker, Documenten, DIVES, Agenda
En vanuit Clubzoeker, Documenten en Agenda kan je ook met 1 klik naar alle andere gaan.
Maar vanuit Boetiek en DIVES kan je nu niet met 1 klik naar die andere gaan. Boetiek is iets externs, er opent een 2de tab dus dat lijkt me logisch, maar DIVES lijkt me iets interns dus dat zou toch moeten lukken. In DIVES 1.0 moet dat met 2 klikken.

**Verwachte resultaat**
1. Misschien moet het logo wat groter maken of met een witte achtegrond (alleen voor het logo) gelijkaardig aan de boetiek. Dat is wel leesbaarder.  Of misschien gewoon het 'gekende woordje' duidelijk en groot in het midden.
2. Graag ook de gekende balk bovenaan zodat je met 1 klik naar Boetiek, Clubzoeker, Documenten, DIVES, Agenda

**Screenshots**
Huidige titel balk:
![image](https://user-images.githubusercontent.com/121305742/209409722-2e108614-fb44-43e2-9ff8-15e55582655e.png)

Voorstel:
![image](https://user-images.githubusercontent.com/121305742/209409979-f2b71031-1994-4076-b531-8df43657d930.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
De meeste mensen weten uiteindelijk wel dat als ze dit scherm zien, dat ze dan in DIVES zitten. Dus daar zie ik niet onmiddellijk een noodzaak voor.
De links naar de andere pagina's vind ik wel een goed idee. Deze zullen wel niet op de plaats komen uit de screenshot, omdat we dan 2 menubalken gaan hebben (links en bovenaan). De links zullen opgenomen worden in de menubalk aan de linkerkant.

**Comment by KWillemse** [comment]
De meeste mensen weten uiteindelijk wel dat als ze dit scherm zien, dat ze dan in DIVES zitten. Dus daar zie ik niet onmiddellijk een noodzaak voor.
==> maar dat is nu duidelijker met het woord DIVES in de linkse hoek, dus OK
De links naar de andere pagina's vind ik wel een goed idee. Deze zullen wel niet op de plaats komen uit de screenshot, omdat we dan 2 menubalken gaan hebben (links en bovenaan). De links zullen opgenomen worden in de menubalk aan de linkerkant.
==> ze staan er maar ik zou ook nog graag terug naar NELOS home kunnen springen (documenten, agenda,...)
![image](https://user-images.githubusercontent.com/121305742/215357005-cd6cb61f-3e1c-419c-8906-e56e5b5fc790.png)
