### ISSUE TITLE
[BUG] 'Proef Volbracht' en de 'RESET' knop voor proeven brengt verwarring

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#133]
**Beschrijf de bug**
1. De woorden 'Proef Volbracht' brengen verwarring om dat het dan lijkt dat ze ook 'goed werd afgewerkt'.
2. het icoontje van 'RESET' lijkt op een 'verbodsteken', dus brengt verwarring met 'een proef is afgekeurd of in opleiding'.

**Stappen om te reproduceren**
1. Ga naar 'een theorie activiteit'.
2. voeg een proef toe

**Verwachte resultaat**
1. om verwarring te vermijden beter de woorden 'Proef uitgevoerd' of 'Proef meegedaan' of 'Proef gedaan' zouden zijn.
2. misschien is het duidelijker met een uitgegrijsd 'revert pijltje' dat zwart wordt wanneer je een keuze hebt gemaakt.
3. Ook de kolom volgorde zou beter kunnen denk ik. Geslaagd/In Opleiding/Reset.

**Screenshots**
'Proef uitgevoerd' en duidelijk 'Reset' knop
![image](https://user-images.githubusercontent.com/121305742/209410259-ec1b87b1-a4da-485c-a0ff-c2b39cbd1077.png)

Betere volgorde:
![image](https://user-images.githubusercontent.com/121305742/209410595-d0122ed9-6112-4fc9-b26f-44a68925e4a8.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Volgens mij zou dat nu allemaal wat duidelijker moeten zijn?

**Comment by KWillemse** [comment]
Ik vind de 'RESET' nog altijd onduidelijk. Vooral omdat wij, oude garde, al jaren spreken van 'In Opleiding' met een duidelijk icoontje:
![afbeelding](https://user-images.githubusercontent.com/121305742/231883997-92e859d9-2e52-480a-b77a-bf771ce8f3d9.png)
