### ISSUE TITLE
[BUG] De kandidaten lijst zou alfabetisch gerangschikt moeten worden op achternaam

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#136]
**Beschrijf de bug**
In de NELOS Leden DB, in DIVES 1.0 en in het Club Beheer in DIVES 2.0 zijn de leden alfabetisch  gerangschikt op achternaam. In de Kandidaten zijn ze gerangschikt op voornaam

**Stappen om te reproduceren**
1. Ga naar 'kandidaten' menu

**Verwachte resultaat**
De kandidaten lijst zou alfabetisch gerangschikt moeten worden op achternaam

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by DIVEScoordinator** [comment]
Ik ben het daar niet mee eens; ik weet dat veel applicaties op achternaam sorteren maar je kent meestal wel de voornaam van een clublid/kandidaat maar niet altijd de achternaam en dan is het een zoektocht om de persoon te vinden.  Dit is een keuze en je kan daar twee kampen hebben: de voornaam en de achternaam sorteerders.

**Comment by ndsmyter** [comment]
We gaan het op dit moment houden zoals het nu is. De voornaam binnen clubs is in elk geval beter gekend dan de familienamen; waardoor hier de voorkeur gaat naar de voornaam.

Besproken met @DIVEScoordinator
