### ISSUE TITLE
[BUG] kandidaten met verschillende sporten bij één club, vermeld clubnaam maar één keer.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#137]
**Beschrijf de bug**
Zowel in Profiel als in kandidaten hebben leden met meerder sporten binnen één club, de club naam 2 keer vermeld staan.

**Verwachte resultaat**
Dezelfde clubnamen moeten verwijderd worden

**Screenshots**
Profiel
![image](https://user-images.githubusercontent.com/121305742/209411710-ec69769a-ba65-4fbd-b516-0a9ccc8ba3be.png)

Kandidaten:
![image](https://user-images.githubusercontent.com/121305742/209411660-7b40f367-227b-47e5-a64c-5194ecfdf219.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Dit werd ondertussen al opgelost paar dagen geleden. Stond misschien nog niet op de TEST website. Maar nu zou dat er normaal gezien wel al moeten op staan denk ik.

**Comment by KWillemse** [comment]
geverifieerd en goed bevonden
