### ISSUE TITLE
[Feature] Bewaren van het aantal resultaten per pagina

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#138]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Ik zou graag een mogelijkheid hebben om het aantal items in de lijst views te kunnen vast zetten of te laten bewaren.
De default 'resultaten per pagina' in de Kanidaten lijst en het club beheer is 10. Wij hebben 75 kandidaten en 180 leden. Een default van 10 is altijd te weinig.

**Beschrijf de oplossing die je zou willen**
Ofwel in het Profiel een extra tab 'instellingen' waar je dan kan kiezen default per lijst, 5,10,25,100,150,200, alles
Ofwel gewoon bewaren in cookies of zo, telkens als ik inlog de juiste default nemen. Gelijkaardig aan de zoom factor (als je bijvoorbeeld een website inzoomt, browser sluit en deze website terug opent dan is de 'zoom factor' bewaard.

Voordeel van de extra tab is dat je deze ook kunt uitbreiden naar andere toekomstige persoonlijk 'instellingen'.

**Comment by ndsmyter** [comment]
Ik zet deze even op de plannig van DIVES 2.1 ipv 2.0, want denk dat deze misschien niet hoogst prioritair is.

**Comment by KWillemse** [comment]
Club beheer is niet meer gelimiteerd, top.
