### ISSUE TITLE
Verschillende uurzones in logboek / detail

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#139]
Een duik die in DIVES 1.0 ingebracht werd op een bepaald uur, wordt in het overzicht van DIVES 2.0 weergegeven als 2 uur later, en in het detailscherm van DIVES 2.0 als 1 uur later.
Ik vond anderzijds ook geen instelling om zelf uurzones in te stellen en te linken aan specifieke duiken (vb voor duiken in buitenland).
**Printscreens**:
**DIVES 1.0** uur = x
![image](https://user-images.githubusercontent.com/115356929/210116850-007080a4-8c3e-40d1-aa8b-b598ed1c6be5.png)
**DIVES 2.0 overzicht** uur = x+2
![image](https://user-images.githubusercontent.com/115356929/210116927-33044cb2-3556-4cc4-950c-2c2dfea7bfd6.png)
**DIVES 2.0 detail** uur = x+1
![image](https://user-images.githubusercontent.com/115356929/210117061-3d50be00-c7af-4ddd-8252-de13e8784c5f.png)

**Comment by ndsmyter** [comment]
Dit probleem zou ondertussen aangepakt moeten zijn. Dit vereist wel een migratie van de databank, dus het zal vermoedelijk pas morgen zichtbaar zijn.
