### ISSUE TITLE
[BUG] Aanmaken duikactiviteit lukt niet

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#14]
**Beschrijf de bug**
Bij het aanmaken van een nieuwe duik-activiteit; na het invullen van alle gegevens (duikduur had ik 180min genomen; ik kreeg wel de opmerking dat dit uitzonderlijk lang was); en na het klikken op de knop 'activiteit opslaan'; bleef het cirkeltje draaien; de activiteit werd niet aangemaakt. 

edit: bij een 2de poging, met een realistischere duikduur kreeg ik hetzelfde resultaat. De duik werd niet aangemaakt

**Stappen om te reporduceren**

De stappen om de bug te reproduceren:
1. Ga naar maak duikactiviteit
2. vul alle gegevens in zoals op de printscreen en klik op 'activiteit opslaan'
3. Scroll naar '...'
4. Zie fout

**Screenshots**

![image](https://user-images.githubusercontent.com/112517511/187552514-2caf2cbc-1f35-417c-8a0c-0e049ed59bb9.png)

![image](https://user-images.githubusercontent.com/112517511/187552566-d9baaf3d-a130-48b5-a832-cfe489f9cf21.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Version Versie 105.0.5195.54 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
@pieter-mouton ,
Kan jij deze bug eens bekijken? Ik had hier gisterenavond ook last van. Als ik nadien naar mijn logboek ging, zag ik daar wel dat de activiteit correct werd aangemaakt.

++ @KimEndare

**Comment by DelangheM** [comment]
Molentje blijft draaien totdat je of refresh van de pagina klikt of opnieuw op "Logboek". Dan zie je de nieuwe activiteit wel.

**Comment by ndsmyter** [comment]
Dit probleem zou nu opgelost moeten zijn.

**Comment by AndreVanhecke** [comment]
idem als #57 maar mijn duik wordt zelfs niet aangemaakt en verschijnt dus niet in het logboek
