### ISSUE TITLE
[verbeterpunt - toon geen predecessors bij automatisch af te tekenen onderdelen

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#143]
**Beschrijf de bug**
bij automatisch af te tekenen onderdelen komt nu het onderdeel als pre-decessor.  Laat dit voorlopig weg. Op termijn kan dit eventueel wel vervangen door het tonen van hoeveel duiken/uren nog nodig zijn (toekomstig item)

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-398

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
