### ISSUE TITLE
[BUG] Proeven bij leden van de club krijgen niet juiste teken

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#146]
**Beschrijf de bug**
Bij kandidaten binnen de club staan 
![image](https://user-images.githubusercontent.com/112652115/213542970-35c93bc1-b089-4f53-89a9-a64b3bed6b42.png)
alle proeven met drie puntjes wat betekent nog af te tekenen door evaluator. Echter zijn die proeven nog allemaal af te leggen.  
![image](https://user-images.githubusercontent.com/112652115/213543037-9c3ab4f1-2617-42b3-8ce4-c56b7d1a94d6.png)

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
Je kan hier een korte en bondige beschrijving geven van wat er had moeten gebeuren.

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-397

**Comment by KimEndare** [comment]
@ndsmyter dit lijkt me een erg klein scherm. Maar gezien het 5G is, lijkt het me wel een recent toestel. Kan het zijn dat er ingezoomed werd?

**Comment by ndsmyter** [comment]
Scherm en opmerking komt van Lutgart.

@DIVEScoordinator  Kan jij verduidelijken?

**Comment by DIVEScoordinator** [comment]
Allen dit probleem is niet iPhone gebonden. Ook op laptop komen niet de juiste symbolen voor de proeven bij kandidaten van de eigen club.  Drie puntjes ipv een vraagteken.
Ik heb iPhone 13 met een normaal scherm. Geen extra groot maar wel vrij standaard maat. Ik heb niet ingezoomd.



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Thursday, January 26, 2023 12:04:43 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Proeven bij leden van de club krijgen niet juiste teken (Issue #146)


Scherm en opmerking komt van Lutgart.

@DIVEScoordinator<https://github.com/DIVEScoordinator> Kan jij verduidelijken?

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
