### ISSUE TITLE
Synchroniseren van nlq gebruikers naar DIVES

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#148]
Momenteel worden de gebruikers enkel aangemaakt in nlq databank. Dat betekent dat deze master-data ook naar DIVES gesynchroniseerd moet worden. Dat kan efficiënt gebeuren door het veld nlq.personen.pe_wz_time te bekijken en enkel de gewijzigde te synchroniseren.

Deze sync moet elke X minuten uitgevoerd worden en kijken naar de laatst gewijzigde gebruikers. Het tijdstip van de laatste sync kan dan opgeslagen worden in de system_parameter tabel bijgehouden worden.

Deze synchronisatie moet enkel lopen op de productie-databank.

**Comment by Cereal2nd** [comment]
system_parameters code 'nlq:sync' will be used for the last sync time
