### ISSUE TITLE
[BUG] Brevet overzicht komt niet overeen met detail brevet

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#15]
**Probleem**
Als je in het overzicht kijkt van een duik staat er naast Dierickx Niko brevet 1*D, maar in het detail staat er 3*D
Het gaat hier over een geimporteerde duik

**Verwachte resultaat**
Detail en overzicht zouden dezelfde data moeten weergeven

**Screenshots**
![image](https://user-images.githubusercontent.com/8513610/187660000-aa4803ca-7ab1-4d70-a61f-dca7bdab23b1.png)
![image](https://user-images.githubusercontent.com/8513610/187660052-8634fe88-5115-4dd9-95aa-907d911ab8f6.png)

**Comment by ndsmyter** [comment]
Dit is inderdaad een bug, maar heb ik gisterenavond al opgelost. Je ziet het nog niet, aangezien die fix nog uitgerold moet worden op de testserver.
Ik ga deze bug dus al afsluiten, maar het is wel effectief een probleem geweest.
