### ISSUE TITLE
Synchronisatie tussen Auth0 en DIVES efficiënter

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#150]
Momenteel worden alle gebruikers tussen Auth0 en DIVES telkens allemaal vergeleken. Dat is natuurlijk niet zo heel efficiënt.

We zouden liefst een systeem hebben dat enkel de gewijzigde gebruikers gaat synchroniseren.

Er zou  ook wel een manier moeten zijn om de gebruikers die zichzelf geblokkeerd hebben te gaan deblokkeren. Dit deblokkeringssysteem kan beter maar 1 keer per dag lopen, om ook te garanderen dat het niet geblokkeerd was omwille van misbruik.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   is dit nog een probleem?

**Comment by ndsmyter** [comment]
Dat is nog steeds iets dat moet gebeuren 🙂 Maar dat is iets in de achtergrond. Momenteel verloopt het daar nog niet zoals het zou moeten. Het werkt wel, maar niet zo proper, dus ooit moeten we dat proper doen. Is gewoon niet zo prioritair op dit moment.

**Comment by DIVEScoordinator** [comment]
Naar 2.2 verplaatsen, alles van 2024 of later ga ik doorschuiven

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Tuesday, July 18, 2023 9:20:29 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Synchronisatie tussen Auth0 en DIVES efficiënter (Issue #150)


Dat is nog steeds iets dat moet gebeuren 🙂 Maar dat is iets in de achtergrond. Momenteel verloopt het daar nog niet zoals het zou moeten. Het werkt wel, maar niet zo proper, dus ooit moeten we dat proper doen. Is gewoon niet zo prioritair op dit moment.

**Comment by ndsmyter** [comment]
Ik zou deze hier nog even laten staan. Want eigenlijk is dat iets dat we ook niet te lang mee moeten wachten. Hoe meer gebruikers, hoe minder problemen die minder goede efficiëntie gaat beginnen geven :-)

**Comment by DIVEScoordinator** [comment]
Ik heb daar een ticket voor aangemaakt in sprint 2024-02 (juni) maar misschien moet je er meer technische informatie bijsteken.
https://endare.atlassian.net/browse/NELOS-674

**Comment by KimEndare** [comment]
In Jira staat dat ticket als rejected?
Wil dat zeggen dat dit ticket ook gesloten kan worden? @ndsmyter @DIVEScoordinator

**Comment by KimEndare** [comment]
ok, dan haal ik mezelf hier weg :-)

**Comment by DIVEScoordinator** [comment]
geen verdere actie meer - soms 2 min wachten ipv 1 min
