### ISSUE TITLE
[BUG] Zoeken in logboek werkt niet correct

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#151]
**Beschrijf de bug**
Als we zoeken in ons logboek dan werkt de intitele zoekfunctie enkel op de getoonde duiken (de aangeklikte jaar/maand).
als we dan scrollen worden de volgende activiteiten zichtbaar die matchen aan de zoekfunctie.

Indien we (bvb in mijn profiel) nu zoeken of "buddy eefje willemsen" hier heb ik in 2022 2 keer mee gedoken.
Maar de zoekfunctie toont nu geen resultaten en de "infite scroll" werkt ook niet,  we moeten manueel 2022 aanklikken om die gezochte duiken te vinden.

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
- De zoekfunctie moet initieel in het volledige logboek zoeken en niet enkel in een gedeelte.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/3715825/213877259-105e6a8f-0620-4ea8-989a-528368abc903.png)
![afbeelding](https://user-images.githubusercontent.com/3715825/213877266-480c2e53-b1e6-4fae-9c59-dc3f067c1037.png)

**Comment by Cereal2nd** [comment]
lijkt op op dev, sluit dit dus af

**Comment by jenno-verdonck** [comment]
Deze lijkt op dev nog niet correct te werken. Wanneer ik zelf in mijn duiken naar een buddy zoek en op zijn naam klik, krijg ik eerst de melding dat ik geen rechten heb om het profiel te bekijken. Hierna krijg ik gewoon al mijn duiken te zien en is de filtering verdwenen.

**Comment by ndsmyter** [comment]
@jenno-verdonck ,
Ik denk dat je dan mogelijks met oudere cache zit? Want wat jij zegt kan ik niet reproduceren.

**Comment by jenno-verdonck** [comment]
Had cache uitgezet in chrome en ook eens in edge getest.

**Comment by ndsmyter** [comment]
@jenno-verdonck ,
Lijkt mij dan een iets ander probleem te zijn dan hier beschreven wordt in elk geval.

Maak je een nieuwe bug aan? Liefst met wat screenshots, stappenplan of zelf een filmpje (bv met screentogif). Dan kunnen we eens verder bekijken.
