### ISSUE TITLE
[BUG] Import van een vrijstelling triggerd geen herevaluatie van de pre-condities

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#153]
**Beschrijf de bug**
Bij deimport van een vrijstelling worden de pre-condities van proeven niet ge herevalueerd (zie screenshot)

**Verwachte resultaat**
"klaar voor eindexamen" => vrijstelling
"theorie + zwembad examen zouden mogelijk moeten woren

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/3715825/214235169-29a6acc5-994c-498c-a041-87c8e6ba9c8c.png)

**Comment by ndsmyter** [comment]
Vrijstellingen worden nog niet bekeken in de proeven, dat moet ik inderdaad nog eens doen.

**Comment by ndsmyter** [comment]
Vergeet mijn vorige commentaar, want wordt blijkbaar wel gecontroleerd bij het ophalen van die proeven. Ik had nog niet goed gekeken naar uw screenshot.

De voorwaarden staan groen, dus dat wil zeggen dat ze voldaan zijn. Dus met andere woorden, dat is eigenlijk een correcte screenshot zoals ik het daar zie. De 2 examens staan effectief open, en zijn mogelijk om uit te voeren.

Het enige dat verkeerd is in de screenshot, is het icoontje van die 2 examens. Dat zou nu eigenlijk een "?" moeten zijn. Dat staat reeds gemeld bij Endare, dat ze daar eens naar zouden moeten kijken. Want momenteel klopt dat icoontje niet met de legende helemaal onderaan de pagina.
