### ISSUE TITLE
[BUG] Op I-phone niet mogelijk om activiteit aan te maken of te wijzigen

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#155]
**Beschrijf de bug**
Bij het inbrengen van activiteit kunnen alle gegevens ingevoerd worden maar bij het commando om op te slaan blijft het systeem hangen.  Na meerdere minuten terug gegaan met pijl maar niets in het logboek te zien.

Dit gebeurt met i-phone 13 op 5G

**Comment by ndsmyter** [comment]
Ik had hier al een bug voor doorgegeven aan Endare: https://endare.atlassian.net/browse/NELOS-399
