### ISSUE TITLE
[BUG] iPhone swith tussen logboek en opzoek werkt niet optimaal 

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#156]
**Beschrijf de bug**
Bij iPhone switched tussen logboek naar zoekfunctie en terug blijft dit hangen

**Stappen om te reproduceren**
1. Ga naar 'startpagina' 
2. Klik op 'zoekfunctie knop' 
3. Klik op 'tegels' of 'lijn'
4. je krijgt logboek niet te zien zonder nog eens op 'zoekfunctie knop' te drukken

**Verwachte resultaat**
Als je wisselt tussen zoekfunctie en logboek in tegels of lijnen moet dit dadelijk zichtbaar komen zonder nogmaals op zoekfunctie knop te moeten drukken

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-406

**Comment by KimEndare** [comment]
@DIVEScoordinator bedoel je met "Zoekfunctie knop" deze knop?
![image](https://user-images.githubusercontent.com/94067251/216276954-bdae30bd-aad7-4313-a0ba-0cc65d044469.png)

Probleem is dat eens je het zoekpaneel opent, dat die sectie open blijft en je dus niet ziet dat de weergave gewijzigd is, gezien de resultaten onder het zoekpaneel staan

Ik zie dan 2 oplossingen;

OF we klappen het zoekpaneel terug dicht wanneer gebruiker tussen tegels / lijst weergave wisselt
OF we zetten de weergave opties onder het zoekpaneel zodat je meteen het effect ziet
![image](https://user-images.githubusercontent.com/94067251/216278728-63b1ada5-aeb8-41eb-9a0e-2ed6524264b0.png)


Wat is jullie voorkeur?

**Comment by DIVEScoordinator** [comment]
Ja reset werkt niet op iPhone en laptop. Op iPhone werkt het switchen niet goed van het ene naar het andere,

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KimEndare ***@***.***>
Verzonden: Thursday, February 2, 2023 10:02:15 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] iPhone swith tussen logboek en opzoek werkt niet optimaal (Issue #156)


@DIVEScoordinator<https://github.com/DIVEScoordinator> bedoel je met "Zoekfunctie knop" deze knop?
[image]<https://user-images.githubusercontent.com/94067251/216276954-bdae30bd-aad7-4313-a0ba-0cc65d044469.png>

Probleem is dat eens je het zoekpaneel opent, dat die sectie open blijft en je dus niet ziet dat de weergave gewijzigd is, gezien de resultaten onder het zoekpaneel staan

Ik zie dan 2 oplossingen;

OF we klappen het zoekpaneel terug dicht wanneer gebruiker tussen tegels / lijst weergave wisselt
OF we zetten de weergave opties onder het zoekpaneel zodat je meteen het effect ziet
[image]<https://user-images.githubusercontent.com/94067251/216278728-63b1ada5-aeb8-41eb-9a0e-2ed6524264b0.png>

Wat is jullie voorkeur?
