### ISSUE TITLE
[BUG] Resetten van zoekfunctie input niet mogelijk?

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#157]
**Beschrijf de bug**
Bij het selecteren van waarden in zoekfunctie is het niet makkelijk om deze terug te verwijderen

**Stappen om te reproduceren**
1. Ga naar 'zoekfunctie.'
2. Klik op 'locatie' en geef put van Ekeren in
3. Duiken put van Ekeren komen in logboek
4. Om daarna alle duiken terug in bekomen met manueel het veld in locatie leeggemaakt worden, er staat geen reset of verwijder keuzes knop of ik zie deze niet staan

**Verwachte resultaat**
Er moet op een eenvoudige manier kunnen gereset worden.
**Screenshots**
![image](https://user-images.githubusercontent.com/112652115/215340905-587e0604-1d6b-48cd-bf71-c3133ab8938d.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in https://endare.atlassian.net/browse/NELOS-407

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
