### ISSUE TITLE
[BUG] Buddy zoekresultaten

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#16]
**Beschrijf de bug**
Zoekresultaten van buddy's geven soms overwacht resultaat

**Stappen om te reporduceren**
1. Nieuwe duik aanmaken
2. Zoeken naar buddy
3. Ingeven "Nelos"

**Verwachte resultaat**
Ik verwacht resultaten die een exacte match hebben terug te krijgen in de mogelijkheden; alsook hoger in de lijst terug te vinden.
Om de juiste gegevens terug te krijgen moet je nu zoeken op Technical

**Screenshots**
![image](https://user-images.githubusercontent.com/8513610/187663076-af15c1ea-a5cc-475c-baf8-89ad2d377ff4.png)
![image](https://user-images.githubusercontent.com/8513610/187663253-2445b7ec-6936-46c9-ada5-64bcb5956820.png)

**Comment by ndsmyter** [comment]
Gekend probleem, dat gerelateerd is aan #5

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
