### ISSUE TITLE
[BUG] Link naar andere website opent in hetzelfde tabblad

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#160]
**Beschrijf de bug**
Geen echte bug maar zou beter zijn om de link naar andere websites in een nieuw tabblad te openen zodat je vlot van het ene naar het andere kan switchen.  

ook best een link naar website toevoegen naast brightspace, boetiek en documenten (als dat niet meer op de website staat)

**Comment by ndsmyter** [comment]
Brightspace/elearning en boetiek staan reeds op de website.

Documenten wil ik niet linken naar de oude website, want ik wil daar geen reclame meer voor maken. Maar zoals gezegd, wil ik graag Documentencentrum binnentrekken in DIVES 2.0 al.

**Comment by DIVEScoordinator** [comment]
Nicolas,
Ik denk dat je de opmerking niet helemaal begrepen had.
Het gaat erover dat als je nu klikt op elearning gaat dit in hetzelfde tabblad open als DIVES 2 (en je kan niet meer terug?).

Was en suggestie van Ivo Hubert om dat in een ander tabblad te laten opengaan.

Website ok als je daar niet meer naar wilt linken (maar je gaat die vraag wel krijgen).

Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur | Voorzitter Sectie EDIT
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: zaterdag 18 februari 2023 16:29
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Link naar andere website opent in hetzelfde tabblad (Issue #160)


Brightspace/elearning en boetiek staan reeds op de website.

Documenten wil ik niet linken naar de oude website, want ik wil daar geen reclame meer voor maken. Maar zoals gezegd, wil ik graag Documentencentrum binnentrekken in DIVES 2.0 al.
