### ISSUE TITLE
[BUG] Brevetkaart niet meer zichtbaar

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#161]
**Beschrijf de bug**
De brevetkaart van Peter Moorthamer was op 19 februari niet meer zichtbaar in DIVES 2. Hij is zeker voor de opleiding ingeschreven en ik heb een week geleden nog volop met hem en andere van zijn generatie getest (Arne Moorthamer, Brent en Wim Tirry).  Mike Verspaandonck; een vroegere kandidaat en Nico VanLeene, nog eerder gestart, staan er wel nog in. 

Idem verhaal voor de 3*D ....

**Comment by ndsmyter** [comment]
Dit probleem is ondertussen opgelost in de laatste code.
Bij het ophalen van de brevetten werden er een paar IDs door elkaar gehaald waardoor het leek dat er geen brevetten aan deze persoon hingen, dat is ondertussen opgelost.
