### ISSUE TITLE
[BUG] Aantal personen ingeschreven voor een opleiding in DIVES 1 is lager in DIVES 2

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#162]
**Beschrijf de bug**
In DIVES 1 zijn 30 personen ingeschreven voor de opleiding 2*I, in DIVES 2 slechts 25, lijkt erop dat zij die in januari inschreven niet overkomen.

**Comment by ndsmyter** [comment]
Deze bug had te maken met #161 en is dus ook opgelost.

Als ik filter op de opleiding "2* Instructeur" als DO NELOS en dan onderaan naar de teller kijk zie ik terug 30 staan.
<img width="198" alt="image" src="https://user-images.githubusercontent.com/648669/221349985-1706352e-bd4a-4b40-9dfb-0e0e9afd6ecf.png">
