### ISSUE TITLE
[BUG] Sidemount en scooter opleidingen niet zichtbaar in DIVES 2

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#163]
**Beschrijf de bug**
Er zijn geen brevetkaarten zichtbaar van kandidaten voor deze opleidingen.

Er is iets mis in het synchroniseren van recentere inschrijvingen.

**Comment by ndsmyter** [comment]
Na wat onderzoek blijkt dit geen probleem met DIVES te zijn. Volgens de voorwaarden die er nu aan die brevetten hangt, kunnen proeven enkel afgetekend worden door een Sidemount Instructeur en/of Sidemount Instructeur Trainer. Dat heeft als gevolg dat die brevetkaarten niet zichtbaar zijn voor DO NELOS op dit moment. Want die gebruiker heeft niet de juist brevetten.

Ik heb nu aan Ivo gevraagd via mail om de juiste brevetten toe te voegen aan deze gebruiker, zodanig dat die dan nadien wel correct de brevetkaarten zou kunnen zien.

Ik kan in tussentijd wel tijdelijk het brevet van sidemount instructeur toekennen aan DO NELOS (of een andere gebruiker indien nodig). Maar dat zal dan natuurlijk wel elke maandag overschreven worden.
