### ISSUE TITLE
[BUG] Bij de 'Initialisatie' zou de afstand tussen de getallen en het 'edit' icoontje wat korter mogen zijn. 

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#164]
**Beschrijf de bug**
JBij de 'Initialisatie' zou de afstand tussen de getallen en het 'edit' icoontje wat korter mogen zijn.  Deze is namelijk zo groot dat het soms verwarrend is dat je het edit icoontje van de eerste kolom wil gebruiken om de tweede kolom aan te passen. Dit omdat het edit icoontje van de tweede kolom soms buiten beeld valt.

**Stappen om te reproduceren**
1. Ga naar je 'Profiel' en dan 'Initialisatie'.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/220459941-a7d420e9-c0bb-4100-a8fc-8ff46f0c692b.png)

**Desktop (indien mogelijk aanvullen):**
    Besturingssysteem: Windows 10
    Browser: Chrome
    Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Nadeel is dat het nu dus wel niet meer zo mooi aligneert

<img width="900" alt="image" src="https://user-images.githubusercontent.com/648669/221351617-7ba1c0c8-966a-4c4c-872d-8cf7cd63fe10.png">
