### ISSUE TITLE
[BUG] Buddy toevoegen die zwemmend lid is

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#166]
Je kan een buddy toevoegen die een brevet heeft van vroeger maar nu niet als duikend lid meer is ingeschreven maar als zwemmend lid (voorbeeld Marleen Viane)

**Comment by ndsmyter** [comment]
Deze is nog niet zo heel eenvoudig af te checken, dus ik ga die nog even parkeren. Dat zijn uiteindelijk ook niet zo heel veel personen waarover het gaat.

**Comment by DIVEScoordinator** [comment]
@ndsmyter verplaatsen naar 2.2?

**Comment by DIVEScoordinator** [comment]
Ik denk dat dit probleem zichzelf opgelost heeft want ik kan deze dame die nog steeds lid is al recreatief zwembadgebruik (betaald begin 2024) maar die geen medische keuringen heeft momenteel niet meer terugvinden als ik zoek in in de databank
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/be961f65-2f6e-4ce2-b35c-3e3c80a887af)
Ik zou deze dan ook afsluiten.

**Comment by DIVEScoordinator** [comment]
meestal gaan de zwemmende leden geen medische keuring indienen om te duiken en dan kan je ze ook niet selecteren. Indien wel is het zo een kleine groep dat het teveel werk is om dit te implementeren. We sluiten deze dan ook af.
