### ISSUE TITLE
CCR toevoegen in Initialisatie

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#167]
Kan in het scherm van de Initialisatie ook CCR toegevoegd worden.
Je hebt een aantal duiken en duikuren nodig om naar een volgend brevet te kunnen gaan of om opleidingsduiken te mogen afnemen als je met een Rebreather duikt.

**Comment by ndsmyter** [comment]
Dat is wel de bedoeling, naast ook vrijduiken en andere. Maar dit staat wel nog niet bovenaan mijn takenlijst :-) Deze initialisaties zie ik iets dat we later ook nog kunnen toevoegen, en daarom dus minder prioritair. Maar als deze hier gelogd staat, kunnen we het alleszins niet vergeten.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   eentje om de komende weken/maanden voor alle technische voorwaarden te realiseren.  Als ik iets kan doen om dit te faciliteren, laat maar weten.

**Comment by ndsmyter** [comment]
Kan je in de huidige versie doen.

**Comment by DelangheM** [comment]
Merk wel dat er opeens 7 duiken minder in mijn logboek staan en als ik het mijn gas invul onder Technische duiken – CCR er niets te zien is bij de Rebreatherduik.
Dien ik hiervoor iets anders aan te duiden?

 

Mario

 

 

Van: Nicolas De Smyter ***@***.***> 
Verzonden: zondag 30 juli 2023 21:05
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: DelangheM ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] CCR toevoegen in Initialisatie (Issue #167)

 

Kan je in de huidige versie doen.
