### ISSUE TITLE
Graag ook de 'afkorting' gebruiken in het zoekveld van brevetten en opleidingen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#168]
**Beschrijf de bug**
Als je op een 'brevet' of opleiding wil zoeken in de 'Clubbeheer' of 'Kandidaten', dan zou het invullen van de 'afkorting' ook het juiste brevet moeten filteren

**Stappen om te reproduceren**
1. Ga naar 'Clubbeheer' of 'Kandidaten'
2. In 'Zoek op brevet' of 'Zoek op opleiding'
3. type 'BND'
4. de filter is leeg

**Verwachte resultaat**
je verwacht bij 'BND' dat 'Basis Nitrox Duiker' zichtbaar is

**Desktop (indien mogelijk aanvullen):**
Besturingssysteem: Windows 10
Browser: Chrome
Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by KimEndare** [comment]
https://endare.atlassian.net/browse/NELOS-675

**Comment by DIVEScoordinator** [comment]
Is uitgevoerd en reeds beschikbaar in DEV. Komt in de loop van november in productie
