### ISSUE TITLE
Ik zou graag bij de 'Clubbeheer' de sport activiteit bij het Lidtype zien

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#169]
**Beschrijf de bug**
Wij zijn een club met 3 sporten: sportduiken, vrijduiken, owh en we hebben 'Recreatieve zwembadgebruikers' en 'niet actieve leden'. Voorlopig nog geen vinzwemmers

**Stappen om te reproduceren**
1. Ga naar 'clubbeheer'
2. je ziet enkel L1 of L2 maar verder geen info over het leden type

**Verwachte resultaat**
Ik zou graag de sport(en) willen zien en indien mogelijk ook info over de 'niet sporten'  RZ en NL

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/222556717-838ef92a-ca21-4a8f-bcd8-e88160d792a7.png)

**Desktop (indien mogelijk aanvullen):**
Besturingssysteem: Windows 10
Browser: Chrome
Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Dit is normaal gezien al tijdje zichtbaar, dus ik sluit deze af.

**Comment by KWillemse** [comment]
Je kan de activiteit van de 'Hoofdsport' zien, niet van alle bijsporten. Je kan ze pas zien als je het profiel bekijkt. Dat is spijtig.
