### ISSUE TITLE
[BUG] Aanpassen van een duik - toevoegen buddy of aanpassen uur....

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#17]
Niet mogelijk om een buddy toe te voegen in een bestaande duik of om het uur van de duik aan te passen

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar 'LOGBOEK'
2. Klik op 'Bestaande duik'
3. Klik op ' Aanpassen'
4. Zie fout : details van de duik zijn dan verdwenen ( Uur, locatie, Duikduur, Diepte)
5. Na aanpassen van bv het uur of het toevoegen van een deelnemer kan je niet op aanpassen klikken. 
6. Als je de Locatie opnieuw wil ingeven komt er ook geen pulldown menu waarin je de duikplaatsen kan kiezen.
7. Als je de verplichte velden invult kan je wel op Aanpassen klikken maar worden niet opgenomen/aangepast.

**Verwachte resultaat**
De reeds ingevulde gegevens dienen zichtbaar te blijven.

Mogelijkheid 
Je kan hier een korte en bondige beschrijving geven van wat er had moeten gebeuren.

**Screenshots**
![image](https://user-images.githubusercontent.com/112561123/187695433-4d53f005-43cf-44c2-957c-80037c1883ed.png)
![image](https://user-images.githubusercontent.com/112561123/187695724-23332c1d-3211-4d8d-a905-61fc3546fbef.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows11
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22] Versie 104.0.1293.70 (Officiële build) (64-bits)

**Additional context**

**Comment by ndsmyter** [comment]
Dit probleem lijkt nu niet meer te reproduceren in de laatste versie, dus vermoedelijk opgelost :-)
