### ISSUE TITLE
Het zou fijn zijn moesten we bepaalde proeven die voor meerdere brevetten gelden automatisch als 1 item kunnen verwerken.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#170]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Huidige situatie bij het sportduiken (zie infomap 2023)
4* Duiker vrijstellingen
-	Houders van de kwalificatie diep duiken (KDD) zijn vrijgesteld van de openwaterproeven D2, D4 en D5 en de duikleiding DL1 en DL2.
-	Houders van het brevet AI zijn vrijgesteld van de openwaterproef D1 en het theorie-examen.
AI vrijstellingen
-	Houders van het brevet 4*D zijn vrijgesteld van de openwaterproef E1 en het theorie-examen.
-	Voor eventuele andere vrijstellingen: zie website van Sport Vlaanderen.

We nemen als voorbeeld '900m vinzwemmen' voor 4* en AI. 
1. Als deze opleidingen na elkaar worden afgewerkt, dan zou er in principe een 'automatisch vrijstelling' moeten worden uitgevoerd als deze proef reeds werd uitgevoerd.
2. Als beide opleidingen tergelijkertijd lopen dan zouden we de 'proeven' in alle omstandigheden kunnen vasthangen aan elkaar in de GUI, achterliggend blijven het natuurelijk 2 onderdelen.
![image](https://user-images.githubusercontent.com/121305742/222561626-6f9cc88f-16b6-4f31-9c81-c22a0ded107a.png)

Nu moet je ze beide aanvinken als je de proef wil toevoegen aan een duik. 
![image](https://user-images.githubusercontent.com/121305742/222561673-6f815333-5daa-446a-a344-d278db8159a2.png)
je moet ze beide op geslaagd zetten en je moet voor beide commentaar geven als dat nodig is. 
![image](https://user-images.githubusercontent.com/121305742/222561929-b6b25122-7533-4d11-a169-ebd33adbe465.png)
Als men dit vergeet, zadelt men de personen die 'vrijstellingen' kunnen geven met onnodige extra werk op.
![image](https://user-images.githubusercontent.com/121305742/222562186-8f1807fb-d12b-42d7-96b1-4e3dcc1bc1c4.png)

**Beschrijf de oplossing die je zou willen**
Je zou de proeven kunnen samenvoegen (gelijkaardig aan het inschrijven gezamelijk inschrijven van 1* + BND. Dat is ook 1 inschrijving => 2 brevetkaarten.:
![image](https://user-images.githubusercontent.com/121305742/222565782-f920f3e2-5bdb-489f-83bd-8c79b0e8e763.png)
En bij het aftekenen zou je de proeven ook kunnen samenvoegen:
![image](https://user-images.githubusercontent.com/121305742/222562586-bab5fcea-81b8-4b4c-a745-c92cac18b4a4.png)
In de brevettenkaarten (en dus ook achterliggend in de database) kan je ze blijvend appart houden:
![image](https://user-images.githubusercontent.com/121305742/222562967-462a3def-4365-440d-b5e0-c47cee5b692c.png)

**Comment by ndsmyter** [comment]
Deze brevetten zullen nu wel automatisch afgetekend worden als je er 1 van de 2 aftekent. Dus op die manier zijn die achter de schermen wel al aan elkaar gelinkt.

Ik vermoed dat dit ook voldoende is voor nu?

**Comment by ndsmyter** [comment]
De meeste opleidingen worden al automatisch afgevinkt, maar blijkbaar ontbreekt de "theorie" voor AI en 4*D nog in de lijst. Dit is iets dat ik zelf nog moet toevoegen.

**Comment by DIVEScoordinator** [comment]
Dit werkt nu ook voor de theorielessen als je 4*D bent of de lessen al afgetekend hebt en inschrijft voor AI (getest in test omgeving met echte kandidaat).  Het blijft niet mogelijk om items die nog niet kunnen afgetekend worden vrij te stellen.  Dus als een kandidaat KDD is maar zijn voorwaarden zijn nog niet in orde (initialisatie nog niet ingebracht) dan worden de proeven niet vrijgesteld.  Vanaf dat de kandidaat dit in orde brengt, komt die wel in orde (ook met echte kandidaat uitgetest.  Theorie examen kan pas afgetekend van zodra 'klaar voor eindexamen' wordt ingebracht.
