### ISSUE TITLE
Ik zou graag een onderverdeling zien per 'type' bij het starten van een opleiding

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#171]
**Beschrijf de bug**
De lijst met alle mogelijke opleidingen is soms al heel lang en zal in de toekomst alleen nog maar langer worden. Nu staan die brevetten nogal onoverzichtelijk door elkaar en het bepalen van een juiste volgorde zou al een goede verbetering zijn maar desondanks denk ik dat het overzicht wel beter zou zijn moesten er ook nog een paar onderverdelingen tussen staan per type.

**Stappen om te reproduceren**
1. Ga naar 'club beheer'
2. Start een opleiding van een actieve 'multi-sporter' bv. sporduiken en vrijduiken
![image](https://user-images.githubusercontent.com/121305742/222567345-6510c75d-a85b-4178-b71d-80bde3f3d4ee.png)

**Verwachte resultaat**
Ik zou een onderverdeling, (door middel van een lijntje willen zien per type, bv.
- Sportduiken
- Vrijduiken
- Technisch duiken
- Jeugd duiken
- specialities

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/222568963-bb54f457-b654-466e-891b-40a68b5c5533.png)

**Desktop (indien mogelijk aanvullen):**
 Besturingssysteem: Windows 10
Browser: Chrome
Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by DIVEScoordinator** [comment]
JIRA ticket 810 aangemaakt
