### ISSUE TITLE
Graag de 'extra informatie' van 'Status evaluator' toevoegen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#172]
**Beschrijf de bug**
In DIVES 1.0 kan je 'extra informatie' laten zien en dan opent een document met deze info: https://leden.nelos.be/assets/documents/EDIT_status_instructeur.pdf

**Stappen om te reproduceren**
1. Ga naar 'Mijn Profiel'
er is geen mogelijkheid om 'Meer informatie' op te vragen

**Verwachte resultaat**
Juiste hetzelfde zoals in DIVES 1.0. 

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/222768383-54552e3d-8cc0-40af-82a9-6900bb721710.png)

**Comment by ndsmyter** [comment]
Gebeurd in productie ondertussen.
