### ISSUE TITLE
Afgeleverde brevetten via DIVES komen dubbel in de ledenadmin

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#173]
Naast de behaalde brevetten wordt in DIVES ook nog eens getoond dat een brevet certificatie is doorgegaan of dat een brevet geannuleerd werd.  Ik dacht dat dit met mijn algemene admin rol te maken had maar die is weggehaald en ik heb nog steeds die view.

![image](https://user-images.githubusercontent.com/112652115/226170209-ae5a2db5-4bd3-423f-a63f-fc10f902c02d.png)

**Comment by ndsmyter** [comment]
Reeds doorgegeven aan Endare https://endare.atlassian.net/browse/NELOS-444

**Comment by DIVEScoordinator** [comment]
@ndsmyter    gesloten want dit komt na dit WE ok en was eentje van mij
