### ISSUE TITLE
Heldere zeeduiken en zoetwater worden niet correct berekend

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#174]
**Beschrijf de bug**
Het aantal heldere zee duiken is gelijk aan diegene van de initialisatie en dus alle gelogde duiken in helder water worden niet meegenomen: zie hieronder vergelijking tussen statistieken en initialisatie.

![image](https://user-images.githubusercontent.com/112652115/226170713-3531f1f9-f9c1-4779-9d18-0970f7e7cf11.png)
![image](https://user-images.githubusercontent.com/112652115/226170735-123c234b-b8fe-4e36-9459-a2be8b125863.png)

**Comment by ndsmyter** [comment]
De berekening zou nu wel correct moeten gebeuren. Blijkbaar ergens een mismatch in de tagging.

**Comment by netdata-be** [comment]
@ndsmyter in mijn geval is dit nog niet opgelost:

<img width="356" alt="Scherm­afbeelding 2023-04-11 om 13 02 36" src="https://user-images.githubusercontent.com/494802/231141236-7c8b3587-3bc1-44bc-afa7-1fec069feeed.png">

Ik vind 208 duiken in heldere zee erg veel...

**Comment by ndsmyter** [comment]
@netdata-be ,
Als je gelijk hebt, dan heb je gelijk 😄 

Blijkbaar was de Oosterschelde ook getagd als een heldere zee, meestal niet bepaald helder nochtans 😛 

Beter nu ?
