### ISSUE TITLE
[BUG] 5 duiken bij 1*D vinkt niet af

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#175]
**Beschrijf de bug**
Ik breng extra duiken in met een kandidaat 1ster duiker tot deze er vijf heeft.  De automatische voorwaarde vinkt niet af, ook niet na refresh te doen.  Op welke basis gaat dit gebeuren?  Dit is in het algemeen belangrijk omdat in DIVES 1 je effectief nog eens een activiteit moest doen vooraleer het systeem terug rekende en ik dacht dat dit binnen DIVES 2 ging opgelost zijn.

![image](https://user-images.githubusercontent.com/112652115/226171514-00d2b36e-3e9d-433a-86c0-4ab385b15d1f.png)

**Comment by ndsmyter** [comment]
Lag aan de ontbrekende voorwaarde hiervoor. Werd opgelost in de databank

**Comment by DIVEScoordinator** [comment]
Dat probleem werd terug gemeld. Moet dit nog in productie gezet?

**Comment by DIVEScoordinator** [comment]
@ndsmyter  kan je eens kijken waarom dit terug gemeld wordt. Mail Piet 25 april kandidaat 52447
