### ISSUE TITLE
[BUG] de 'Getijdeduiken' bij 'Type duiken' is niet correct vergeleken met DIVES 1.0

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#177]
**Beschrijf de bug**
Bij het testen van issue #115 zijn alle 'Type' duiken, met utizondering van een paar oude/nieuwe types , correct gemigreerd behalve 'Getijdeduiken'.
Bij Dives 1.0 heb ik er 416:
![image](https://user-images.githubusercontent.com/121305742/226488866-46438563-44dc-4f3f-8919-4be2160f8d54.png)
Bij Dives 2.0 heb ik er 431
![image](https://user-images.githubusercontent.com/121305742/226488926-0f08ea4e-cbc2-4477-a716-1b6b5dcb1fb3.png)

**Comment by ndsmyter** [comment]
Dit probleem zou nu beter moeten zijn. Het is wel mogelijk dat er ergens toch een lichte mismatch is geweest, aangezien sommige duiklocaties een andere tagging hebben gekregen. Normaal gezien enkel in de juiste richting.

**Comment by KWillemse** [comment]
Dit kan ik natuurlijk niet meer nakijken (want ik kan niet meer aan DIVES 1.0). Ik begrijp de licht mismatch en dat het in de juiste richting zou moeten gaan.

Wel is het raar dat bij het maken van de screenshots ik 431 getijde duiken had en nu bij de release heb ik in totaal 2 duiken meer als toen maar geeft de teller 436 getijde duiken aan. Deze 2 duiken waren beide 50 min ongeveer en er is 4 uur bij gekomen.
