### ISSUE TITLE
[BUG] Zoeken werkt niet correct

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#178]
**Beschrijf de bug**
De 'zoek filter' in het logboek voor de maanden in 2023 werken niet. Deze bug had ik al beschreven in #115 .

**Stappen om te reproduceren**
1. Ga naar je logboek, alle activiteiten zijn correct zichtbaar in volgorde van datum
2. Klik op 'Jan' voor het jaar 2023, ik zie de activeiten van 'jan 2023' en dan jan 2020 en dan 'jan 2019'

**Verwachte resultaat**
Als je leest "zoeken vanaf maand of jaar", dan verwacht je toch alle activiteiten vanaf de geselecteerde jaar/maand.
Als ik dus klik op 'Jan' voor het jaar 2023, ik verwacht ik de activeiten van 'jan 2023' en dan dec 2021 en dan 'nov 2020', etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/226489611-ece915d1-35f0-4042-a408-a778f797374b.png)

**Comment by ndsmyter** [comment]
https://endare.atlassian.net/browse/NELOS-488
