### ISSUE TITLE
Kan duik niet opslaan als ik Technisch duiken - CCR aanklik in persoonlijke gegevens met He=0

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#179]
Als ik Technisch duiken - CCR kies in de persoonlijke gegevens en daar de waardes voor 02 - He en flesinhoud invul kan ik de duik niet opslaan.
![image](https://user-images.githubusercontent.com/112561123/227721287-c21f3d99-46be-4afc-ac67-652db5187c97.png)

De toets staat grijs en krijg de melding van foutieve flessen:
![image](https://user-images.githubusercontent.com/112561123/227721251-1b2f5aba-3e4c-4e9e-b58f-32d3d10df657.png)

Als ik een waarde hoger dan "0" ingeef voor He is het wel mogelijk.
Voor CCR-D-A dient het mogelijk te zijn om He op 0 te zetten

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare: https://endare.atlassian.net/browse/NELOS-489
