### ISSUE TITLE
Technisch duiken - OC met He = 0

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#180]
Kan duik niet opslaan zolang de waarde van He niet verschillend is van 0

![image](https://user-images.githubusercontent.com/112561123/227721859-faf2bd43-2ed3-4b68-bc90-e0a3b17e988d.png)

Zie fout
![image](https://user-images.githubusercontent.com/112561123/227721898-b26f42c6-750f-4ec2-9615-83d0cb441d78.png)

**Verwachte resultaat**
Moet mogelijk zijn om ook zonder He te duiken

**Comment by ndsmyter** [comment]
Ik sluit deze af, aangezien dit een duplicaat lijkt van https://github.com/Nelos-VZW/dives-2/issues/179
