### ISSUE TITLE
[BUG] layout boven zoekbalk niet ok

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#182]
**Beschrijf de bug**
![afbeelding](https://user-images.githubusercontent.com/3715825/227779191-272c23c5-e171-43cd-bb8c-4d6b3131aba8.png)
![afbeelding](https://user-images.githubusercontent.com/3715825/227779421-d61091ba-7c03-432c-9b8e-a1a5f818c6c9.png)

Uitlijning export is niet ok

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Win 10
 - Browser: Firefox
 - Versie: 112.0b5

**Comment by ndsmyter** [comment]
Bij mij is dat gelijk zo erg niet. Maar ik test wel op Chrome, zal dat later nog eens bekijken op Firefox.

Maar niet prioritair dus :-)

**Comment by ndsmyter** [comment]
Zou volgens mij moeten opgelost zijn.
