### ISSUE TITLE
[BUG] Tijd bij nieuwe duik AM/PM

### ISSUE THREAD

**Issue by ShinjiB** [Nelos-VZW/dives-2#183]
**Beschrijf de bug**
Tijd bij nieuwe duik ingeven staat in AM/PM
Geen idee of dit nog de bedoeling is om dit in AM/PM te laten staan. In de lijst van de duiken staat deze in 24H

**Comment by ndsmyter** [comment]
Hey @ShinjiB ,
Waar zie jij ergens die AM/PM staan? Want bij mij is dat gewoon 24u bij het aanmaken van een nieuwe duik (zie screenshot).
![image](https://user-images.githubusercontent.com/648669/230792754-f5cfd551-cff7-43b9-8c1d-8348869acf62.png)


Kan het misschien zijn dat uw browser ingesteld op een Amerikaanse locale ?

**Comment by ShinjiB** [comment]
Ja, sorry. was idd browser afhankelijk bij mij 


Van: "Nicolas De Smyter" ***@***.***> 
Aan: "Nelos-VZW/dives-2" ***@***.***> 
Cc: "shinji" ***@***.***>, "Mention" ***@***.***> 
Verzonden: Zondag 9 april 2023 21:30:28 
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Tijd bij nieuwe duik AM/PM (Issue #183) 





Hey [ https://github.com/ShinjiB | @ShinjiB ] , 
Waar zie jij ergens die AM/PM staan? Want bij mij is dat gewoon 24u bij het aanmaken van een nieuwe duik (zie screenshot). 
[ https://user-images.githubusercontent.com/648669/230792754-f5cfd551-cff7-43b9-8c1d-8348869acf62.png ] 

Kan het misschien zijn dat uw browser ingesteld op een Amerikaanse locale ?
