### ISSUE TITLE
[BUG] technische duik CCR / OC

### ISSUE THREAD

**Issue by ShinjiB** [Nelos-VZW/dives-2#184]
**Beschrijf de bug**
Bij het invoeren van een nieuwe duik, als je persoonlijke gegevens wil aanpassen naar "technische duik CCR" of OC. Dan verwacht het systeem om een percentage He in te geven. Terwijl je dit kan doen met lucht als diluent. of is een technische duik alleen met trimix?
Zelfde met de in te geven bailoutfles. Dit kan ook nx zijn

**Comment by ndsmyter** [comment]
Hey @ShinjiB ,
Dat is inderdaad een gekend probleem waar we nog naar moeten kijken. Staat op onze radar om zo snel mogelijk op te lossen.

**Comment by ndsmyter** [comment]
Duplicaat van #179

**Comment by ndsmyter** [comment]
Afgesloten omwille van duplicaat
