### ISSUE TITLE
Brevet behaald

### ISSUE THREAD

**Issue by KatherineTetaert** [Nelos-VZW/dives-2#185]
**Beschrijf de bug**
Ik was ingeschreven in de opleiding Advanced Freedive maar heb die nu onterecht behaald. Ik had slechts 1 proef of zo gedaan

**Comment by ndsmyter** [comment]
Hallo @KatherineTetaert ,
Dat was inderdaad een probleem dat we gisteren 76 mensen (waaronder jouw inschrijving) ten onrechte het brevet gegeven hadden. Dit had te maken met migratieproblemen die opdoken bij de vrijduikbrevetten. We hebben de nodige stappen gedaan om de opleidingen normaal gezien terug open te zetten. Maar je had het brevet inderdaad nog, waardoor je de opleiding ook niet zag staan.

Ik heb nu de nodige zaken aangepast waardoor jouw opleiding terug open zou moeten staan. Normaal gezien ben je geen voortgang verloren.

Bedankt om dit probleem te melden !

**Comment by KatherineTetaert** [comment]
Beste,
Bedankt om dit zo snel in orde te maken!

Mvg,
Katherine

Op zo 9 apr. 2023 21:20 schreef Nicolas De Smyter ***@***.***
