### ISSUE TITLE
Duiken zone 30

### ISSUE THREAD

**Issue by KatherineTetaert** [Nelos-VZW/dives-2#186]
**Beschrijf de bug**
Ik heb voldoende duiken in de zone 25-30, is ook correct weergegeven in Dives. Maar bij de voorwaarde voor mijn proef te doen C5 voor 3 * duiker staat dat ik nog niet voldoende duiken heb in die zone en kan de proef dus niet gedaan worden

**Comment by ndsmyter** [comment]
Hallo @KatherineTetaert ,
Dat is natuurlijk niet praktisch. Ik zal dit binnenkort eens bekijken.

**Comment by DIVEScoordinator** [comment]
@KatherineTetaert   Katrien ik heb in de testomgeving een duik met u aangemaakt en ik kan uw proef wel selecteren. Kan je even bekijken of dit probleem nu verdwenen is?  Mogelijks nog een nawee van de migratie gisteren
![image](https://user-images.githubusercontent.com/112652115/230876401-674f2640-7c5c-46cf-9d04-37dec6699750.png)

**Comment by KatherineTetaert** [comment]
Beste,

Het is in orde! Maar ik denk dat het al correct was maar dat ik door de
nieuwe layout het verkeerd geïnterpreteerd had misschien. Dus sorry
hiervoor. Alvast chapeau voor jullie werk!

Groetjes Katherine

Op ma 10 apr. 2023 11:38 schreef DIVEScoordinator ***@***.***
