### ISSUE TITLE
[BUG] Lagere brevet wordt getoond in logboek

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#187]
**Beschrijf de bug**
Wanneer een activiteit is gelogd ben ik plots een lagere brevet.

**Stappen om te reproduceren**
1. Ga naar logboek
2. Zie fout

**Verwachte resultaat**
Correcte brevet weergeven

**Screenshots**
![Screenshot_2023-04-09-23-43-27-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/93061973/230797845-b91200c5-1795-499d-8ee8-ccb1c31cb698.jpg)

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Ik heb een aantal aanpassingen gedaan waardoor normaal gezien nu wel het juiste brevet getoond zou moeten worden.
