### ISSUE TITLE
[BUG] overzicht type duiken op profiel staat niet correct

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#188]
**Beschrijf de bug**
Op het profiel kan je het aantal duiken per type raadplegen, hier zijn een aantal niet meer overgezet of staan niet juist.
Bij zeeduik en heldere zeeduik is bijvoorbeeld leeg en was in de vorige DIVES correct 

**Stappen om te reproduceren**
1. Ga naar profiel
2. Klik op mijn profiel
3. Zie fout

**Verwachte resultaat**
Correcte gegevens

**Screenshots**
![Screenshot_2023-04-09-23-52-18-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/93061973/230798186-63ba1177-33cc-407f-9fcf-d250ed32198d.jpg)

**Comment by ndsmyter** [comment]
Normaal gezien zou dit nu beter moeten zijn. Sommige duiklocaties (en zelfs ganse zones van duiklocaties) waren niet correct voorzien van tagging. Na het goedzetten van deze tagging en het herberekenen van alle statistieken zou dit een pak beter moeten zijn.
