### ISSUE TITLE
Lagere graad

### ISSUE THREAD

**Issue by WBogaert1** [Nelos-VZW/dives-2#189]
Ik ben 2* maar bij aanmaak van duik staat er 1*

**Comment by ndsmyter** [comment]
Er ging iets verkeerd bij het visualiseren van de brevetten op sommige pagina's. Dit was niet overal een probleem, maar in het logboek was het bijvoorbeeld wel verkeerd. Ik heb nu een paar aanpassingen gedaan aan de visualisatie waardoor het nu beter zou moeten zijn.

Duplicaat van #187
