### ISSUE TITLE
Aantal duiken per onderdeel

### ISSUE THREAD

**Issue by WBogaert1** [Nelos-VZW/dives-2#190]
De duiken per onderdeel zijn niet overgenomen naar Nelos 2.0

**Comment by ndsmyter** [comment]
Hallo @WBogaert1 ,
Kan je iets meer informatie geven? Want nu is het niet zo duidelijk wat je juist wil zeggen of het probleem is.

**Comment by WBogaert1** [comment]
Goede morgen Nicolas


Heb dit nog even nagekeken maar hier is er niets verkeerd aan.
Top om de andere puntje aan te passen.



Alvast bedankt!


Met Vriendelijke Groeten



Wim Bogaert

Bestuurslid Orka  vzw

2* Duiker Orka  vzw



***@***.***

+32 498 15 70 38



Orka vzw

www.orka-lokeren.be

Ondernemingsnummer: BE0432338106

SPORTLAAN 4 A – 9160 LOKEREN

Rek nr BE 82 9793 6609 4068


[Outlook-2gel0qbx.png]<http://www.orka-lokeren.be/>

Op 10 apr. 2023 om 10:01 heeft Nicolas De Smyter ***@***.***> het volgende geschreven:

﻿

Hallo @WBogaert1<https://github.com/WBogaert1> ,
Kan je iets meer informatie geven? Want nu is het niet zo duidelijk wat je juist wil zeggen of het probleem is.
