### ISSUE TITLE
Brevet

### ISSUE THREAD

**Issue by Kspruyt** [Nelos-VZW/dives-2#191]
**Beschrijf de bug**
Bij het logboek stel ik vast dat het brevet waarover ik beschik niet overeenkomt met mijn werkelijk brevet.
Mijn duiken staan geregistreerd als 1*D, terwijl ik een 2*D ben. 
Mijn brevet staat wel OK bij mijn profiel - brevet

**Verwachte resultaat**
Juiste inschaling vanaf het moment dat ik mijn 2*D brevet  gehaald heb.

**Comment by ndsmyter** [comment]
Er ging iets verkeerd bij het visualiseren van de brevetten op sommige pagina's. Dit was niet overal een probleem, maar in het logboek was het bijvoorbeeld wel verkeerd. Ik heb nu een paar aanpassingen gedaan aan de visualisatie waardoor het nu beter zou moeten zijn.

Duplicaat van #187

**Comment by Kspruyt** [comment]
Beste,

Dit staat nu wel correct, echter ben ik nu vanaf de start van mijn
opleidingen 2*D.
De duiken als 1*D staan niet meer visueel.

Kristof

Op ma 10 apr. 2023 08:31 schreef Nicolas De Smyter ***@***.***

**Comment by ndsmyter** [comment]
Hallo @Kspruyt ,
Het is me niet duidelijk welke duiken je juist bedoelt. Kan je iets meer informatie geven wat er juist verkeerd gaat? Wat verwacht je te zien, en wat zie je nu?

**Comment by Kspruyt** [comment]
Beste,

Bij de allereerste duiken die geregistreerd staan in het logboek, ben ik
reeds 2*D. Dit klopt niet.
Ik ben doorheen de jaren (precieze datum ontgaat me), ben ik 2*D geworden.

Kristof

Op ma 10 apr. 2023 10:06 schreef Nicolas De Smyter ***@***.***

**Comment by ndsmyter** [comment]
Hallo @Kspruyt ,
In feite is dat geen functionaliteit die we nu al hebben. We tonen (net zoals in DIVES 1 eigenlijk) het huidige brevet van de persoon.
Maar ik begrijp wel dat dit een nuttige toevoeging zou zijn, dus ik heb daar een aparte taak voor gemaakt: #193
