### ISSUE TITLE
[BUG] Mail wachtwoord reset not working

### ISSUE THREAD

**Issue by Looney-J** [Nelos-VZW/dives-2#192]
**Beschrijf de bug**
Mijn vrouw haar account is geblokkeerd en probeert deze te resetten, helaas komt de mail niet aan op het wachtwoord te resetten

**Stappen om te reproduceren**
1. Ga naar 'login'
2. Klik op 'wachtwoord resetten'
3. E-mail ingegeven
4. Klik op verzenden

**Verwachte resultaat**
Mail met link om wachtwoord te resetten

**Comment by ndsmyter** [comment]
@Looney-J
Kan je eventueel eens de naam van uw vrouw doorsturen? Als je dat liever hier niet publiek doet, kan je altijd mailtje sturen naar nicolas.desmyter@nelos.be . Dan kunnen we dat eens bekijken waarom haar account niet goed werkt.

**Comment by Looney-J** [comment]
Done via mail

**Comment by ndsmyter** [comment]
Probleem behandeld via mail
