### ISSUE TITLE
[BUG] technische gasmengsels ingeven niet mogelijk met 0% helium: geeft foutmelding

### ISSUE THREAD

**Issue by Kristofluycx** [Nelos-VZW/dives-2#194]
**Beschrijf de bug**
Wanneer je bij 'Persoonlijke Gegevens' een technische duik wilt loggen (bijv. CCR), dan kan je bij de gasmengels niet de waarde '0' ingeven voor % Helium: er moet minstens '1' staan, maar in de praktijk zijn er ook CCR en andere technisch duiken brevetten waarbij je geen Helium mag gebruiken en dit dus effectief '0' moet zijn.

**Stappen om te reproduceren**
1. Nieuwe duik aanmaken
2. Klik op 'Persoonlijke Gegevens'
3. Klik op 'Modus' > 'Technisch Duiken - CCR'
4. Vul percentage zuurstof is (21%) en percentage Helium (0%) en volume fles (2 liter)
5. Onderaan kan je niet op 'activiteit opslaan' klikken, maar staar er '1 foutieve fles(sen). Vul bij Persoonlijke Gegevens je samenstelling aan of verwijder fles(sen).

**Verwachte resultaat**
Het zou mogelijk moeten zijn om mengsels met 0% Helium in te vullen.

**Screenshots**

<img width="1175" alt="Screenshot 2023-04-10 at 10 25 12" src="https://user-images.githubusercontent.com/130356326/230875304-e3ca7723-80bc-4664-90d1-7cb8251dc7c5.png">

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: MacOS BigSur
 - Browser: Chrome
 - Versie: 111.0.5563.146

**Comment by ndsmyter** [comment]
Dit is een gekend probleem, dat momenteel al gemeld staat op #179
