### ISSUE TITLE
[BUG] Duplicate dives bij "back" toets wanneer je een duik selecteerd op een andere "page"

### ISSUE THREAD

**Issue by Maximvdw** [Nelos-VZW/dives-2#195]
**Beschrijf de bug**
Je kan hier een korte en bondige beschrijving geven van de bug.

**Stappen om te reproduceren**
1. Selecteer een duik in een maand die voldoende ver ligt (in mijn test sept 2022)
2. Druk op back
3. Alle duiken staan nu 2 keer weergegeven

Het probleem treed niet op wanneer je op de link "Terug naar logboek" klikt maar enkel wanneer je op "back" drukt in je browser.
Het probleem treed ook niet op wanneer je op de "back" toetst drukt na het selecteren van een duik die recent plaatsvond

**Verwachte resultaat**
Geen duplicates

**Screenshots**
![](https://i.mvdw-software.com/mspaint_IhEp4rWuN4.png)

**Extra informatie**
Wanneer ik "back" druk op een recente duik zal volgende request gebeuren: `https://dives.nelos.be/api/activity?page=0&size=15` (geen probleem)
Wanneer ik "back" druk op een minder recente duik zal volgende request gebeuren: `https://dives.nelos.be/api/activity?page=0&size=15&includeDeleted=false`
Nu zijn er wel duplicates

**Comment by ndsmyter** [comment]
Deze taak werd doorgegeven adhv https://endare.atlassian.net/browse/NELOS-515 (afgeschermde link voor dev team)

**Comment by Cereal2nd** [comment]
NELOS-508

**Comment by jenno-verdonck** [comment]
deze gebeurt ook wanneer je een filter toepast en deze hierna verwijderd

**Comment by jenno-verdonck** [comment]
@Cereal2nd Ik heb deze bug nog eens getest op dev.dives.nelos.be om zeker te zijn dat ik de aanpassingen heb. De bug gebeurt nog steeds als je een filter toepast en deze hierna verwijderd via de knop. Maak ik hiervoor een andere issue aan best?
