### ISSUE TITLE
Oudere duiken met decompressiegas zijn niet mee gemigreerd

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#198]
**Beschrijf de bug**
Oudere duiken met decompressiegas zijn niet mee gemigreerd. Als ik naar de statistieken kijk dan mis ik enkele niet-luchtduiken. Typisch waren dit alle duiken die ik gedaan heb met een decompressiegas.

**Stappen om te reproduceren**
1. Ga naar 'profiel'
2. Klik op 'mijn profiel'
3. Scroll naar 'Type duiken'
4. Zie fout

**Verwachte resultaat**
Na migratie werden mijn duiken met decompressiegas niet meegenomen. Ik heb deze duiken ondertussen zelf aangepast voor mezelf. Geen idee of het nog een mogelijkheid is om deze data statistisch terug op te halen en te implementeren of er anderzijds een nota moet komen dat anderen dit na moeten kijken en eventueel aanpassen.

**Screenshots**
![image](https://user-images.githubusercontent.com/130435688/231077212-a6b06d11-9e5b-4caa-bcda-77cb837ad295.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows, IOS, Android]
 - Browser: [chrome]
 - Versie: 

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Decompressiemengsels werden zoals reeds aangekondigd als _best-effort_ opgenomen in DIVES 2.0. In DIVES 1.0 zat deze gasmengsels informatie ongestructureerd (=vrij tekst), waardoor het migreren naar een gestructuurde manier zoals in DIVES 2.0 niet altijd eenvoudig is.
Als je een duidelijke notatie gebruikte voor de gasmengsels zou dit wel mee gemigreerd moeten zijn.

Veel meer kunnen we hier niet echt nog aan doen
