### ISSUE TITLE
Medische keuring (zichtbaarheid leden in clubbeheer)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#199]
**Beschrijf de bug**
Wanneer een lid niet in orde is met zijn/haar medische keuring dan is dit lid niet zichtbaar in het clubbeheer op DIVES. Vroeger was dit enkel in de lijst van buddies dat we ze niet meer konden selecteren.

**Stappen om te reproduceren**
1. Ga naar 'Beheer'
2. Klik op 'jouw club'
3. Scroll naar 'leden'
4. Zie fout

**Verwachte resultaat**
Graag deze leden wel zichtbaar in het overzicht van de club in DIVES.

**Screenshots**
Onmogelijk een screenshot te voorzien daar dit allemaal persoonsgegevens bevat

**Comment by DIVEScoordinator** [comment]
te sluiten na WE 22/23 april update
