### ISSUE TITLE
[BUG] Tijdstip activiteit klopt niet

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#20]
**Beschrijf de bug**
Als je een activiteit aanmaakt met standaard tijdstip vb 31/08 11:59PM wordt deze uiteindelijk gelogd als activiteit op 01/09 01:59

**Verwachte resultaat**
zelfde tijdstip als ingegeven

**Screenshots**

![2022-08-31 18_31_14-Activiteit](https://user-images.githubusercontent.com/112573476/187731305-2ca60426-a990-4e1c-b6ee-ac6a69da0ece.png)

![2022-08-31 18_31_30-Activiteiten](https://user-images.githubusercontent.com/112573476/187731253-6fbee83e-58b8-4647-bb6d-942e8648e602.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version  104.0.5112.102

**Comment by ndsmyter** [comment]
Lijkt hetzelfde probleem als #18

**Comment by ndsmyter** [comment]
Dit probleem zou opgelost moeten zijn
