### ISSUE TITLE
Vervaldata van brevetten zijn enkel zichtbaar als opleidingsverantwoordelijke

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#200]
**Beschrijf de bug**
Vervaldata van brevetten zijn enkel zichtbaar als opleidingsverantwoordelijke. De ledenadministrator zou hier ook zicht op moeten hebben om de leden op te kunnen volgen.

**Stappen om te reproduceren**
1. Ga naar 'Beheer'
2. Klik op 'Jouw club'
3. Scroll naar 'lid en selecteer "open detailkaart"'
4. Als ledenadmin zie je de vervaldata niet

**Verwachte resultaat**
Vervaldata brevetten zouden zichtbaar moeten zijn als ledenadministrator. 

**Screenshots**
Als opleidingsverantwoordelijke zie ik volgend beeld:
![image](https://user-images.githubusercontent.com/130435688/231080513-d33c3466-4a2a-452d-a66e-ffb590b44c80.png)

Als ledenadministrator / niet-opleidingsverantwoordelijke zie ik volgend beeld:
![image](https://user-images.githubusercontent.com/130435688/231080879-6d4dce14-8bc4-4811-9c3b-b3ed8b8754d6.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows]
 - Browser: [chrome]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [Oneplus 2T 5G]
 - Besturingssysteem: [Android 13]
 - Browser [Chrome]
 - Versie []

**Extra informatie**

**Comment by DIVEScoordinator** [comment]
Dit is ook het geval voor de kandidaat zelf (gecheckt met mijn eigen brevetkaart) en ook voor de instructeur binnen de club. Die gingen ook het verval van de brevetkaart kunnen zien.
![image](https://user-images.githubusercontent.com/112652115/231113682-9539e44b-b3a7-49b3-9a02-71c6800cfbed.png)

**Comment by DIVEScoordinator** [comment]
@ndsmyter eentje om ook mee te nemen in de volgende sprint van juni?

**Comment by ndsmyter** [comment]
Dit werd in de huidige versie aangepakt en normaal gezien opgelost. Nu kan je dit als kandidaat ook zien.
