### ISSUE TITLE
Gecertificeerde brevetten onzichtbaar maken in clubbeheer

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#201]
**Beschrijf de bug**
Gecertificeerde brevetten onzichtbaar maken in clubbeheer

**Stappen om te reproduceren**
1. Ga naar 'Beheer'
2. Klik op 'Jouw club'
3. Scroll naar 'Leden'
4. Achter enkele leden zie je de reeds behaalde brevetten in het grijs staan.

**Verwachte resultaat**
Reeds behaalde brevetten zouden onzichtbaar moeten zijn. Geannuleerde brevetten mogen zichtbaar blijven staan om later makkelijk te zien dat deze opleiding al eens geopend werd

**Screenshots**
![image](https://user-images.githubusercontent.com/130435688/231081709-3db36ca8-fa58-4e37-91a1-af6d8ae7d2e7.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows 10]
 - Browser: [chrome]
 - Versie: []

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [Oneplus 2T 5G]
 - Besturingssysteem: [Android 13]
 - Browser [Chrome]
 - Versie []

**Extra informatie**

**Comment by KWillemse** [comment]
Duplicate? #173

**Comment by ndsmyter** [comment]
Correct,
Dit is inderdaad een duplicaat van #173 . Ik sluit deze af, zodanig dat we zoveel mogelijk unieke bugs overhouden, en het overzichtelijk houden.
