### ISSUE TITLE
Afgelegde proef stemt niet overeen met de brevetkaart

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#202]
**Beschrijf de bug**
Afgelegde proef stemt niet overeen met de brevetkaart

**Stappen om te reproduceren**
1. Ga naar 'Logboek'
2. Klik op 'De gewenste duik met afgelegde proef'
3. Vergelijk deze data dan op je brevetkaart via je profiel
4. Zie fout

**Verwachte resultaat**
Afgelegde proef zou als getekend moeten komen in de brevetkaart ongeacht de status.

**Screenshots**
Zie mail omwille van persoonsgegevens

**Comment by ndsmyter** [comment]
Va mail beantwoord dat dit ondertussen OK is
