### ISSUE TITLE
Aanpassen duiklocatie

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#203]
**Beschrijf de bug**
Bij het aanpassen van een duiklocatie (naar een nieuwe, onbekende locatie) krijg ik een foutmelding

**Stappen om te reproduceren**
1. Ga naar 'Logboek'
2. Klik op 'De gewenste duik'
3. Klik op 'aanpassen'
4. Scroll naar 'duiklocatie'
5. Klik op 'het kaartje'
6. Selecteer nieuwe locatie
7. Geef flesvolume in (zonder dit kan je niet opslaan)
8. Klik op 'aanpassen'
9. Zie fout

**Verwachte resultaat**
Aanpassen duiklocaties mogelijk maken naar een nieuwe locatie die nog onbekend is in DIVES.

**Screenshots**
![image](https://user-images.githubusercontent.com/130435688/231087131-943831e2-f92c-4a15-8e5f-21266419e14e.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [Windows 10]
 - Browser: [Chrome]

**Comment by jenno-verdonck** [comment]
Hieraan gerelateerd. Ik wou een vrij oude duik uit dives 1.0 aanpassen omdat ik zag dat de persoonlijke locatie van deze duik niet juist stond op de kaart. Na opslaan is mijn locatie niet aangepast en krijg ik onderstaande error.
![image](https://user-images.githubusercontent.com/42772246/233987657-7adfa24f-de24-419b-95ee-bcc1c8d65bae.png)

**Comment by DIVEScoordinator** [comment]
Het inbrengen van onbekende duikplaats is mogelijk maar je moet het in de juiste stappen doen.
- eerst nieuwe naam intypen
- dan op het kaartje de locatie aangeven.

Er komt in de volgende hippo hier en artikel over en in 2024 werken we aan het verbeteren van alles rond duikplaatsen.
