### ISSUE TITLE
[BUG] Filter in leden administratie moet enkel werken op behaalde of in opleiding brevetten, niet op geanuleerde (grijze)

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#204]
**Beschrijf de bug**
bij een opzoeking van Brevet 1*D , dat ook de 2*D in de lijst voorkomen 

![afbeelding](https://user-images.githubusercontent.com/3715825/231109939-368bc44b-a698-40e9-be8c-9fbb82d45d57.png)

=> de filetr zou enkel moeten werken op de niet grijze brevetten

**Comment by KWillemse** [comment]
Duplicate? #173

**Comment by ndsmyter** [comment]
Dit is niet echt een duplicaat, aangezien het hier gaat over de filter. Niet perse de brevetten die getoond worden zoals in #173

**Comment by KWillemse** [comment]
Klopt maar de zoek functie werkt nu echt niet door #173 terwijl moest die gefixed zijn, dan zijn er misschien een paar geannuleerde opleidingen die mee in het resultaat zitten en dan is dat niet zo erg.

**Comment by ndsmyter** [comment]
@KWillemse ,
Je zal vermoedelijk gelijk hebben. Maar laat deze bug nog even apart bestaan zodanig dat we voor zekerheid nog eens controleren als #173 afgesloten is.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   kan gesloten van zodra aanpassingen op productie zijn geplaatst

**Comment by ndsmyter** [comment]
Dan kan ik het nu al sluiten. Want of het op productie staat of niet, bepaal ik adhv de status.
