### ISSUE TITLE
[BUG] Technisch Duiken OC/CCR - Geen mogelijkheid tot invoeren 0% He.

### ISSUE THREAD

**Issue by dietervi** [Nelos-VZW/dives-2#205]
**Beschrijf de bug**
Bij de persoonlijke gegevens, indien je kiest voor Technisch duiken, is het niet mogelijk om een mengsel te selecteren zonder helium.
Dit zowel bij OC als CCR. 

**Stappen om te reproduceren**
1. Ga binnenin een duik naar 'Persoonlijke gegevens'
2. Klik op 'Technisch Duike - OC' of 'Technisch Duiken CCR'
3. Stel de lucht- en/of nitroxwaarden in. Laat helium Leeg of zet de waarde (naar waarheid) op 0%). Vul ook het aantal liters in.
4. De knop "aanpassen" blijft grijs, en maakt melding dat één of meerdere flessen foutief werden ingegeven

**Verwachte resultaat**
een invoering van 0% Helium mag geen probleem zijn

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Comment by Cereal2nd** [comment]
dit is een duplicate of #179
