### ISSUE TITLE
[BUG] Tabblad secretariaat geeft niet dezelfde informatie als leden admin en Db DIVES

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#206]
**Beschrijf de bug**
Bij de duikclub amphora zitten fouten in de secretariaat lijst, mogelijks is dit ook bij andere clubs een issue vandaar dat ik het toch hierin opneem.

Toch nog enkele kinderziekten in de ledenadministratie.
- onze club heet Amphora - niet Amfora.
- de tweede naam in de lijst is Peter Coutteel - niet Pieter
- op lijn elf staat ‘jongen’ Deno - moet zijn Guy Deno

in ledenadmin staat het goed (info Ivo Hubert)
Db Dives alvast ook voor peter (info Maikel)

**Comment by ndsmyter** [comment]
Screenshots verwijderd uit originele bericht omwille van persoonlijke gegevens

**Comment by ndsmyter** [comment]
Dit probleem zou opgelost zijn omdat er blijkbaar een vertaalplugin actief was bij de gebruiker op die pagina op dat moment. Die zorgde voor bepaalde vertalingen en dus veranderingen in naamgeving.
