### ISSUE TITLE
[Feature] Verwarring rond OD en DD - Voorstel om duik # toe te voegen

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#207]
**OD1, OD2 en OD3 leiden soms to verwarring**

Sommige instructeurs raken in de war bij de bijna overlappende benaming DD1 en OD1

**Beschrijf de oplossing die je zou willen**

Hernoem de volgende proeven ( net zoals dit in DIVES 1 het geval was)
- DD1 - Duik 1
- DD2 - Duik 2 
- OD1 - Duik 3
- OD2 - Duik 4
- OD3 - Duik 5

Dat maakt het heel duidelijk wie wat moet afvinken, vooral wanneer deze proeven niet in correcte volgorde worden afgetekend maat dat het alvast duidelijker.

Dives 1 omschrijvingen zijn niet volledig overgenomen. Kan dat nog aangepast? Anders moet er manueel gecheckt want dit is  geen alleenstaand geval.

**Comment by DIVEScoordinator** [comment]
Is nu ok
