### ISSUE TITLE
[Feature] In de statistieken een onderscheid maken tussen jeugdduiken en volwassen duiken

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#208]
Als je veel met jeugd duikt geven de statistieken dit niet goed weer.
Alles wordt immers bij elkaar opgeteld

**Beschrijf de oplossing die je zou willen**

Het zou handig zijn om een onderscheid te kunnen maken tussen jeugdduiken en volwassen duiken.

**Beschrijf alternatieven die je overwogen hebt**

Eventueel kan er ook een aparte teller worden toegevoegd ipv bij de statistieken die aangeeft hoeveel jeugdduiken je gedaan hebt.
Jeugdduiken zou ik dan tellen zodra er een Bronzen / Zilveren / Gouden dolfijn mee als buddy is toegevoegd.

**Comment by DIVEScoordinator** [comment]
in DIVES 1 was er bij de jaarlijkse statistieken een verdeling van met welke brevetten je gedoken hebt. We stellen voor om dat te introduceren in de statistiek pagina zodat je ook een idee hebt van de duiken met jeugdduikers. Is dit een goed alternatief?

**Comment by ndsmyter** [comment]
Mijn voorstel zou zijn om alle leden te verwijzen naar een pagina in Grafana: https://grafana.nelos.be/d/fe6iityx8lj40d/persoonlijke-statistieken
