### ISSUE TITLE
[Feature] Je kan niet zien hoe ver een kandidaat staat met zijn '25 duiken in de zone (30)'

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#209]
Als instructeur / opleidingsverantwoordelijke kan je niet zien hoe ver een kandidaat staat in zijn aantal duiken voor 25 duiken in de zone (30)

**Gewenste oplossing**

Een progress bar of een teller die op/aftelt zodat je dit kan opvolgen.
Immers er is een verschil tussen iemand die slechts nog maar 1 duik gedaan heeft in zone 30 versus iemand die er reeds 20 gedaan heeft.

**Comment by ndsmyter** [comment]
Deze functionaliteit werd nu ingebouwd, maar staat nog niet op de productie website. Deze zal binnenkort wel beschikbaar worden.

Ik sluit deze taak wel al af als afgewerkt.

**Comment by ndsmyter** [comment]
Staat nu op productie
![image](https://github.com/Nelos-VZW/dives-2/assets/648669/5e619774-b598-48e4-9035-ea8a222318bf)
