### ISSUE TITLE
[BUG] duiklocatie zeelandbrug komt niet altijd tevoorschijn

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#21]
**Beschrijf de bug**
als je zoekt op 'zeeland' komt de locatie niet tevoorschijn
als je zoekt op 'zeelandbr' wel
als je zoekt op 'zeelan' lukt het ook

**Verwachte resultaat**
locatie moet altijd gevonden worden

.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 104.0.5112.102

**Comment by ndsmyter** [comment]
Dezelfde zoekfunctie wordt gebruikt bij de kandidaten, dus dit is een gelijkaardig probleem als in #4

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
