### ISSUE TITLE
[BUG] Hoofdletters in namen zijn niet altijd juist

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#211]
**Beschrijf de bug**

Wanneer een naam wordt weergegeven kloppen de hoofdletters in de naam niet altijd.

In mijn geval zie ik `Wouter D'haeseleer` staan ipv `Wouter D'Haeseleer`

<img width="225" alt="Scherm­afbeelding 2023-04-11 om 12 58 40" src="https://user-images.githubusercontent.com/494802/231140920-37626da3-514b-42cd-9fa6-2ce4da4f7bdd.png">

**Comment by Cereal2nd** [comment]
De namen worden overgenomen uit de ledenadministratie, hierin zitten achternamen volledig met hoofdletters.
Dit is iets wat we op dit moment dus nooit juist krijgen omdat we de data niet hebben.
Op de meeste plaatsen wordt de achternaam volledig in hoofdletters getoond, van waar komt deze screenshot?

**Comment by netdata-be** [comment]
Ik ging er inderdaad vanuit, dan is overal hoofdletters een correcte handeling.
Waar het hier fout loopt is het bij het aanmaken van een duik, in de buddy lijst:
<img width="1155" alt="Scherm­afbeelding 2023-04-11 om 17 47 01" src="https://user-images.githubusercontent.com/494802/231217855-28cc827d-a028-42ff-b2f2-ce718705a1e9.png">

**Comment by ndsmyter** [comment]
Ik heb dit probleem opgelost. Het staat nog niet op dives.nelos.be, maar zal binnenkort wel beschikbaar worden. (De status zal ook veranderen van dit ticket als dat gebeurd is)
