### ISSUE TITLE
[BUG] Proeven uit het verleden kunnen niet meer aangepast worden

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#213]
**Beschrijf de bug**
Er wil iemand aanpassingen doen aan proeven ingebracht in maart 2023 maar hij krijgt de melding dat hij niet kan aftekenen.
![image](https://user-images.githubusercontent.com/112652115/231189173-10735acb-a029-47a1-81c7-59d41456fb2a.png)

Als ik zelf een activiteit theorie aanmaak kan ik de stageles 1 selecteren en aftekenen.

**Comment by ndsmyter** [comment]
Ik ga deze afsluiten en #247 overhouden als echte bug. De 2 taken gaan over quasi hetzelfde. In de beschrijving van #247 wordt sowieso ook naar deze verwezen.
