### ISSUE TITLE
de linken naar andere websites: 'Blended learning' en 'NELOS homepage' 

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#214]
**Beschrijf de bug**
De linken naar NELOS-kalender en Documentencentrum blijven in dezelfde tab (logisch want het is nu geincludeerd)
De link naar de Boetiek opent een nieuwe tab: goed want dat is een andere website.
De link naar 'Blended learning' gaat niet naar een nieuwe tab: niet goed want dat is een andere website en de back in de browser gaat niet terug naar DIVES (je moet meerdere keren 'back' klikken).
Ik zou ook graag een link hebben naar de 'Nelos Home page'.

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/231295823-2df8293f-1cda-4228-8726-ad2051dcbc62.png)

**Comment by ndsmyter** [comment]
De knop voor blended learning heb ik aangepast. Dat zal beschikbaar worden bij de volgende deploy.

De knop voor "NELOS Home" die je vraagt, voeg ik liever niet toe.

**Comment by KWillemse** [comment]
Merci. 

Vraagje, waarom liever niet naar de NELOS Home page?
