### ISSUE TITLE
Ik kan niet meer nakijken of iemand correct is geregistreed of niet.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#215]
**Beschrijf de bug**
In DIVES 1.0 kon ik bij het club beheer nakijken of iemand zijn registratie op de NELOS website al had uitgevoerd of niet. Ook in de in de export naar excel stond een kolom 'confirmed' om aan te duiden of iemand zijn registratie al had uitgevoerd.

**Verwachte resultaat**
Liefst een indicatie in het club beheer (zie sreenshot). Alternatief met icoontjes, of een kolom die je  kan 'verbergen/tonen', of.....
Indien dit veel werk is, zou je deze info alvast kunnen toevoegen aan de 'Export Excel'.

**Screenshots**
<screenshots weggehaald door @ndsmyter omwille van persoonlijke gegevens>

**Comment by ndsmyter** [comment]
Dit stond nog op de planning om te doen, en staat daar nog steeds op. Dus we willen wel terug dergelijke informatie aanbieden. Alhoewel het nu mogelijks wel wat eenvoudiger zal worden, aangezien de gebruiker ofwel actief is of niet. We hebben geen tussenstatussen meer met bevestige e-mailadressen of niet.

Maar in elk geval nog steeds de bedoeling om dit zichtbaar te maken voor de ledenadministrator.

**Comment by KWillemse** [comment]
tussen statussen weglaten is idd eenvoudiger om te implementeren maar ik ben als ledenadmin steeds de first line support voor onze leden alvorens ze de powerusers aanspreken. Als ik reeds problemen kan oplossen door de tussen stappen na te kijken dan is dat minder werk voor de power users en een snellere service voor onze leden. Ik merk dat er nog ledenadmins zijn die iets meer info willen zien (#199) en als ik me niet vergis hadden we die zaken ook in de 'funct' specs van de secretarissen opgenomen ;-). Ik begrijp het wel dat er ook een verschil is tussen 120 secretarissen en 10000 duikers maar alle 'funct' specs van de secretarissen moeten er wel voor zorgen dat uw power users enkel belast worden met de belangrijke problemen.

**Comment by KWillemse** [comment]
Ik vind het spijtig dat de vragen van de 'secretarisssen' (zowel bij het opmaken van de functionele specs als bij het ingeven van requests) zomaar worden gesloten. Dat deze op een todo lijst komen voor de toekomst, OK, maar sluiten geeft toch een ander gevoel.
Deze vraag heeft niets te maken met de manier van inloggen in DIVES, dat werkt, dat is gemakkelijk en daar komen geen issues van binnen. Het gaat erover de de 'oude ledenadministratie' en initiele registratie bij NELOS niet altijd even vlot verloopt. Dat deze 'oude ledenadministratie' nog bestaat en pas in de toekomst zal worden aangepast, OK, ook begrijpbaar maar nu kunnen wij geen status meer zien die we in DIVES 1.0 wel zagen en ons de mogelijkheid gaf om een juist antwoord naar onze leden te sturen. 
Maar geen probleem, ik verwijs ze wel naar de power users.

**Comment by KWillemse** [comment]
Ik verwijs even naar mijn mail van 12 april 2023. Als ik me niet vergis zijn er  2 verschillende registraties op dit moment: NELOS website en DIVES.
En ik dacht dat de procedure dus als volgt was:
Ik schrijf een nieuw lid in in de NELOS ledenadministratie, dan kreeg die persoon een mail met 'Welkom bij NELOS.be' en een link naar de aanlog pagina van NELOS => registratie bij NELOS
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/0dc32370-161e-41d1-afaf-52c9d024beaf)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/a2d77ea6-3b81-45e4-99f4-f145484f4841)
En nadien moest die persoon zich nogmaals registreren bij DIVES

- Als er dus nog steeds 2 registraties zijn, dan kan ik nergens terugvinden of deze pesoon de 'Welkom bij NELOS.be' mail goed ontvangen had en zich had geregistreerd (dit kon je wel zien in DIVES 1.0)
- Als er nu nog maar 1 registratie bestaat en er geen 'Welkom' mail meer gestuurd word of de link in de 'Welkom' mail is aangepast naar de inlog pagina van DIVES dan mag je deze case sluiten.
Bijkomende vraag: Ik had toen ook volgend voorstel gedaan: @Nicolas of Maikel: uiteraard zou het wenselijk zijn dat er maar 1 registratie nodig is (NELOS webiste - DIVES - Blended learning) en dat dus de 'welkom mail' om te registreren mogelijks aangepast moet worden. Nog beter zou zijn dat ook de 'NELOS boetiek' dezelfde login zou kunnen gebruiken. ;-)

Ik spreek dus niet over de status in DIVES want zoals net hebt geschreven, er zijn maar heel weinig, zoniet geen issues met het aanloggen op DIVES. Dat is al een super goede verbetering ten opzichte van vroeger.
Ik wilde jou ook niet persoonlijk aanvallen hoor, ik weet perfect wat software/website ontwikkeling inhoud en dat je er maar met een paar personen aan moet werken. Er is alleen een enorm verschil tussen een case sluiten of een case uitstellen.

Ik zelf steek ook wel wat tijd in het loggen van issues, ik probeer ze zo goed mogelijk te documenteren met screenshots en dergelijke, maar als de cases in verband met de ledenadministratie (waar ik bij de functionele specs ook veel tijd heb ingestoken) gewoon gesloten worden, dan vrees ik dat mijn enthousiasme om mee te werken aan een verbetering snel zal wegvloeien. 
Ik begrijp maar al te goed, dat er een verschil is tussen 8000 duikers, 150 vrijduikers en 120 ledenadministrators maar je zal in je toekomstige planning toch ergens eens tijd moeten vrijmaken voor de minderheden.
