### ISSUE TITLE
[BUG] Nieuwe opleiding: voorwaarde Trimix Blender Instructor

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#219]
Om de opleiding Trimix Blender Instructor te kunnen starten moet je 2*I zijn

Op dit moment kan je die activeren als je 1*I bent:

<img width="773" alt="Scherm­afbeelding 2023-04-12 om 10 01 26" src="https://user-images.githubusercontent.com/494802/231393317-6a006c42-190d-4846-b225-e7c95eeed13c.png">

**Comment by ndsmyter** [comment]
Nog niet alle brevetten heb de juist voorwaarden gekregen. Dat is een gekend probleem, maar goed dat dit gelogd wordt zodanig dat we hier kunnen opvolgen. We hopen dat elke ledenadministrator zoals gewoonlijk ook nog even zijn eigen controles doet voor de moment (want ook in DIVES 1 was dat niet feilloos).
