### ISSUE TITLE
[BUG] wit scherm bij annuleren ingave persoonlijke tag

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#22]
**Beschrijf de bug**
wanneer je in een activiteit het scherm om een persoonlijke tag in te voegen opent en daarna deze actie annuleert krijg je een wit scherm

**Stappen om te reporduceren**
activiteit openen
scherm persoonlijke tags openen
annuleren klikken

**Verwachte resultaat**
de duikactiviteit waar je inzat zou terug moeten verschijnen

**Screenshots**

![2022-08-31 18_43_47-Activiteit](https://user-images.githubusercontent.com/112573476/187733559-c97b475e-feeb-4301-956c-3930da5e8d06.png)
![2022-08-31 18_44_04-Activiteit](https://user-images.githubusercontent.com/112573476/187733571-a2184aa0-0c57-4e77-aff6-01149257ecc1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 104.0.5112.102

**Comment by ndsmyter** [comment]
@pieter-mouton ,
Kan jij deze eens bekijken?
Lijkt me mogelijks een probleem met de recente tags, maar ik twijfel nu eigenlijk of dat al volledig getest was langs jullie kant. Mogelijks iets dat dus mee geslopen is bij de deploy naar Test.

++ @KimEndare

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
