### ISSUE TITLE
[Feature] Hoeveelste duik dit jaar

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#220]
Veel mensen houden in hun papieren logboek bij de hoeveelste duik van het jaar dit is.

**Beschrijf de oplossing die je zou willen**
Via een omweg kan je wel kijken hoeveel duiken je reeds hebt ( via profiel / statistieken)
Echter het zou niet slecht zijn om een teller te laten zien per lijn of per tegel

Enerzijds met de duiknummer in kwestie en anderzijds met de hoeveelste duik dit jaar.
Naar analogie zoals velen hun boekje invullen.

**Comment by ndsmyter** [comment]
Ik ben ook zo eiemand !

Je kan dat eigenlijk wel vrij eenvoudig te weten komen door naar "Statistieken" te gaan in je profiel. Want daar staat telkens standaard het huidige jaar geselecteerd. Dus het eerste getal op die pagina is normaal gezien het aantal duiken van het huidige jaar, de informatie die je wil.

Ik laat nog even open staan om hier later op terug te komen of we dat niet nog wat kunnen uitbreiden.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   Nicolas, via profiel kan je dit zien en nog veel meer statistieken, het wordt in mijn club vlot gebruikt.  Dit nog op een andere plaats tonen lijkt mij overkill.... en kan verwarring geven.  Ik zou deze afsluiten.

**Comment by ndsmyter** [comment]
Ja, in feite is het wel waar. Standaard staat de statistiek toch ingesteld op het huidige jaar, dus dan zie je het eigenlijk in een oogopslag als je de statistieken opent.
