### ISSUE TITLE
Proeven onder een opleiding vreemd gesorteerd

### ISSUE THREAD

**Issue by velghekevin** [Nelos-VZW/dives-2#222]
Bij het bekijken van de af te leggen proeven voor 3*D staan alle proeven in een logische volgorde. C1, C2, C3,... behalve CL2. Die staat helemaal onderaan...

Ingelogd als nelos id 50339 in het tabblad "opleidingen"

**Comment by ndsmyter** [comment]
De sortering maakte daar inderdaad een vreemde kronkel. Bij deze is dat rechtgezet.
