### ISSUE TITLE
niet meer mogelijk om het aantal duiken sedert huidig brevet te zien

### ISSUE THREAD

**Issue by velghekevin** [Nelos-VZW/dives-2#223]
Vroeger kon je zien in het overzicht hoeveel duiken je reeds had met je meest recente brevet.
Is handig voor de automatische voorwaarde "Minstens 40 duiken sinds het behalen van het brevet 2*D"
Dit kan misschien ook op de brevettenkaart zelf komen?

**Comment by ndsmyter** [comment]
Dit is vanaf nu wel terug mogelijk om te zien in je statistieken.
