### ISSUE TITLE
[Feature] Persoonlijke tags weergeven in tellers en statistieken

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#224]
Je kan aan een duik een persoonlijke tag toevoegen, bijvb `droogpak`
Echter kan je die tag niet zien in je tellers of in je statistieken

**Beschrijf de oplossing die je zou willen**

Het kan handig zijn om in 1 oogopslag te zien hoeveel duiken je hebt met een bepaalde tag.
In het voorbeeld is het leuk te weten hoeveel duiken je hebt met de tag `droogpak`

**Beschrijf alternatieven die je overwogen hebt**

Ook kan het handig zijn om te zoeken op tags, wat vandaag niet mogelijk is.

**Comment by ndsmyter** [comment]
Wat betreft zoeken van tags is dit een duplicaat van #90 , dus dat gedeelte zullen we daar verder behandelen.
We kunnen dit ticket dan houden voor de statistieken visualiseren zelf.
