### ISSUE TITLE
Opleiding van persoon niet meer zichtbaar

### ISSUE THREAD

**Issue by WalterVanN** [Nelos-VZW/dives-2#228]
De DSV van Sea King meldt dat clublid Joachim Vergauwen ingeschreven was voor een vrijduikopleiding en dat hij daar al 1 zwembadsessie voor aftekende in DIVES 1. Nu, in DIVES 2 ziet hij die opleiding niet meer.

De DSV (Eric De Graef) wil graag de opleiding kunnen zien om verdere sessies en proeven te kunnen aftekenen.

**Comment by ndsmyter** [comment]
Ik heb even de oude databank van DIVES 1 er bij genomen, en kon daar ook geen enkele opleiding vinden voor Joachim (NELOS ID 52711).
Ik ben dan naar de opleidingstabel van het NELOS-secretariaat gaan kijken, en ook daar kan ik geen enkele opleiding vinden voor deze persoon.

Ik weet dus niet waarom dat is, maar ik kan enkel zien dat die persoon geen enkele actieve opleiding heeft. En daardoor ook geen enkele proef in geen enkel systeem heeft zitten.

Dat het niet in DIVES 2 zou zien, dat zou een bug kunnen zijn; maar dat er in de andere 2 databanken ook geen enkele notie zou zijn, dat is niet echt mogelijk.

**Comment by WalterVanN** [comment]
Bedankt Nicolas, ik gaf de melding door zoals ze mij bezorgd werd, ik kon het zelf niet verifieren.



met vriendelijke groeten,

Walter Van Nieuwenhove
DIVES Power User
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: donderdag 13 april 2023 21:18
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Walter Van Nieuwenhove ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Opleiding van persoon niet meer zichtbaar (Issue #228)


Ik heb even de oude databank van DIVES 1 er bij genomen, en kon daar ook geen enkele opleiding vinden voor Joachim (NELOS ID 52711).
Ik ben dan naar de opleidingstabel van het NELOS-secretariaat<https://endare.atlassian.net/browse/NELOS-secretariaat> gaan kijken, en ook daar kan ik geen enkele opleiding vinden voor deze persoon.

Ik weet dus niet waarom dat is, maar ik kan enkel zien dat die persoon geen enkele actieve opleiding heeft. En daardoor ook geen enkele proef in geen enkel systeem heeft zitten.

Dat het niet in DIVES 2 zou zien, dat zou een bug kunnen zijn; maar dat er in de andere 2 databanken ook geen enkele notie zou zijn, dat is niet echt mogelijk.
