### ISSUE TITLE
[BUG] Niet-nelos lid verwijderen gaat niet voordat je de duik bewaard

### ISSUE THREAD

**Issue by Maximvdw** [Nelos-VZW/dives-2#229]
**Beschrijf de bug**
Het is niet mogelijk om een niet nelos lid te verwijderen bij het aanmaken van een duik. Dit geeft de foutmelding:
![](https://i.mvdw-software.com/chrome_4xvRPv2NN3.png)
Je moet eerst de duik bewaren en vervolgens aanpassen om de duiker te verwijderen

**Stappen om te reproduceren**
1. Maak een nieuwe duik aan
2. Voeg een Niet-nelos lid toe
3. Verwijder het niet-nelos lid zonder de duik eerst te bewaren
4. Je krijgt een foutmelding

**Comment by ndsmyter** [comment]
Dit was inderdaad een probleem. Dit probleem zal bij de volgende deploy (ergens tegen het weekend) opgelost zijn.
