### ISSUE TITLE
[BUG] theorieactiviteit wordt dubbel getoond op android

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#23]
**Beschrijf de bug**
een theorieactiviteit uit het verleden waar veel deelnemers waren wordt dubbel getoond

**Stappen om te reporduceren**
in historiek kijken

**Verwachte resultaat**
1 activiteit waar alle deelnemers instaan

**Screenshots**
activtiteit op android
![Screenshot_20220831-185111_Chrome](https://user-images.githubusercontent.com/112573476/187736147-3fc5d295-7cc8-4c0f-8c5f-26263882830d.jpg)

ik dacht dat het op de desktop eerst juist werd getoond
maar na het tesetn of de oorzaak bij het aantal deelnemers ligt zie ik op de desktop de activiteit ook 2 maal
Het bizarre is dat de opdeling na de test ook is veranderd
![image](https://user-images.githubusercontent.com/112573476/187736964-f1129898-a995-4bd3-8214-8a86ea94b951.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 104.0.5112.102 

**Smartphone (please complete the following information):**
 - Device: samsung galaxy a51
 - OS: android 12
 - Browser chrome
 - Version 104.0.5112.97

**Comment by ndsmyter** [comment]
Dit was een probleem dat ik tijdens de startvergadering ook zag. Ik heb het na de vergadering onmiddellijk opgelost.
Je ziet de oplossing nog niet, aangezien de oplossing pas beschikbaar zal worden als we de wijzigingen uitrollen op de test server. Dat zal mogelijks nog niet voor onmiddellijk zijn.

Ik ga deze bug wel al afsluiten, omdat hij op zich al opgelost is.
