### ISSUE TITLE
[BUG] Onmogelijk om een filter toe te passen op jaar en maand basis op mobile

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#232]
**Beschrijf de bug**

Het scherm om jaar en maand te selecteren gedraagt zich niet zoals je verwacht als je wil filteren op jaar en maand.

**Stappen om te reproduceren**
1. Ga naar logboek
2. Klik op filter icoon rechts boven
3. Kies nu voor een jaartal
4. Op het moment dat je het jaartal selecteert sluit het scherm reeds en kan je geen maand meer selecteren

**Verwachte resultaat**
Dat het venster niet sluit tenzij je op "Toon Resultaten" klikt

Op desktop niet van toepassing gezien de balk niet verdwijnt.

**Smartphone:**
 - Toestel: iPhone
 - Besturingssysteem: iOS 15
 - Browser: Safari

**Comment by DIVEScoordinator** [comment]
Aangepast en werkt op iPhone
