### ISSUE TITLE
[Feature] Bij klik op Nelos logo verwacht ik terug in het logboek te zitten

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#233]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? 

De meeste apps laten toe dat je klikt op het logo links boven en dat je vervolgens ergens logisch terug op uit komt.

**Beschrijf de oplossing die je zou willen**

In andere tickets las ik dat het niet perse gewenst is om naar de NELOS homepagina te linken.
Wat ikzelf een goede reden vind, immers op de homepagina vind je niet echt iets extra meer.

Echter ik zou verwachten als je op het logo klikt dat je naar de "home" van de app wordt gebracht, in dit geval het logboek dus.

**Comment by ndsmyter** [comment]
Aangepast
