### ISSUE TITLE
[BUG] Jeugdduiker heeft geen brevet in buddy lijst

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#234]
**Beschrijf de bug**
Als je een jeugdduiker toevoegt als buddy heeft deze geen brevet in de weergave:

**Verwachte resultaat**
Ik verwacht in dit geval dat het brevet `ZIL` zichtbaar was.

**Screenshots**

<img width="350" alt="Scherm­afbeelding 2023-04-13 om 11 48 29" src="https://user-images.githubusercontent.com/494802/231722544-5f19d859-6696-4ddb-90ff-41d581469e38.png">

Dit terwijl hij wel degelijk een zilveren dolfijn is:
<img width="750" alt="Scherm­afbeelding 2023-04-13 om 11 50 09" src="https://user-images.githubusercontent.com/494802/231722962-38336f46-818b-48d5-bc5e-40f48f78470b.png">

**Comment by ndsmyter** [comment]
Dat is een gekend probleem, dat ook voor vrijduikers geldig is. We kijken daar momenteel enkel maar naar de Luchtbrevetten van volwassenen. Maar we waren wel al bezig stappen te ondernemen om dit aan te passen.

**Comment by CarlAnto** [comment]
Voor wet wheels is dit ook het geval. Hier komen ook andere brevetten zichtbaar dan degene die ze momenteel hebben.

Bv. Iemand die een WW-A is en nu in Dives 2 een WW-B als actief brevet heeft staan.

Ik open hiervoor dan ook geen ander issue daar dit hier samen met freediving en jeugdduiken ook past.
