### ISSUE TITLE
[BUG] Verouderde gegevens en links op nelos.be over dives

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#235]
**Beschrijf de bug**
Wanneer je aanmeld op de leden pagina van Nelos ([https://leden.nelos.be/landing/main](https://leden.nelos.be/landing/main)) krijg je rechts boven een klop naar dives. Deze knop werkt echter niet.
Er zullen waarschijnlijk nog verouderde documentatie en links staan op de nelos website zoals de recente wijzigingen pagina. [https://leden.nelos.be/artikel/DIVES_INFO](https://leden.nelos.be/artikel/DIVES_INFO)

Ik wist niet of ik dit via hier moest melden of dat dit door iemand anders beheerd wordt.

**Comment by jenno-verdonck** [comment]
Ondertussen lijkt de knop rechts boven correct te werken.

**Comment by DIVEScoordinator** [comment]
Ik heb de DIVES pagina op website verwijderd.  Ticket mag gesloten.
