### ISSUE TITLE
[Feature] Berichten kunnen verwijderen of bijwerken

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#239]
Momenteel is het niet mogelijk om gemaakte berichten bij een activiteit te verwijderen of bij te werken. Hierdoor kan je als je een fout hebt gemaakt of het bericht per ongelijk publiek hebt gezet, deze niet aanpassen.

**Comment by DIVEScoordinator** [comment]
@ndsmyter  voorstel om deze mee te nemen in sprint van juni

**Comment by ndsmyter** [comment]
https://endare.atlassian.net/browse/NELOS-550
