### ISSUE TITLE
[BUG] verwijderen activiteit gaat niet

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#24]
**Beschrijf de bug**
het lukt niet om een aangemaakte activiteit te verwijderen

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar een activiteit
2. Klik op verwijderen
3. je krijgt vraag of je zeker bent en klikt op ok
4. er gebeurt niks

**Verwachte resultaat**
activiteit wordt verwijderd of melding waarom hij niet verwijderd kan worden

**Screenshots**
![image](https://user-images.githubusercontent.com/112573476/187737855-651d896a-7333-4f4e-9932-acbf450550a1.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 104.0.5112.102

**Comment by ndsmyter** [comment]
@pieter-mouton ,
Bekijk jij deze eens als het past?

++ @KimEndare
