### ISSUE TITLE
[BUG] Foutieve statistieken na verwijderen duik

### ISSUE THREAD

**Issue by KimberlyW30** [Nelos-VZW/dives-2#242]
**Beschrijf de bug**
Na het verwijderen van een duik uit het logboek door een medegebruiker blijven de statistieken ongewijzigd. 
Een kennis had mij per ongeluk gelogd in een duik. Ik was niet aanwezig tijdens deze duik. Hij heeft mij gisteren uit deze duik verwijderd en de juiste mede-duiker toegevoegd. Mijn statistieken (aantal duiken, uren, type duik, ...) passen zich niet opnieuw aan en blijft de duik meetellen.

**Verwachte resultaat**
De statistieken kijken naar de huidige duiken in het logboek en passen zich automatisch aan bij een verwijdering of aanpassing.

**Comment by ndsmyter** [comment]
Statistieken worden sowieso herberekend bij elke aanpassingen. Dus als je een nieuwe duik gaat loggen, zullen uw statistieken zich terug goed zetten.

Maar ik zal kijken om die herberekening te doen wanneer buddy's gewijzigd word.

**Comment by KimberlyW30** [comment]
Is dat enkel als ik de duik zelf log dat de statistieken wijzigen?
Er is namelijk een uur na het verwijderen een correcte duik ingegeven door een andere duikbuddy van mij. Er zijn dus wijzigingen aan mijn logboek doorgevoerd erna.

**Comment by ndsmyter** [comment]
Normaal zal bij het toevoegen van een nieuwe activiteit de herberekening gebeuren voor alle deelnemers van die duik.
Dus in jouw geval zou dat inderdaad wel moeten.

Ik zoek het sowieso nog verder uit !

**Comment by ndsmyter** [comment]
Hallo @KimberlyW30 ,
Je had inderdaad gelijk. Buddy's die verwijderd werden bij een activiteit, bleven ook die activiteit meetellen in de tellers.
Ik heb nu de nodige aanpassingen gedaan waardoor dit probleem nu opgelost zou moeten zijn.

De statistieken worden regelmatig opnieuw berekend, en bij de volgende herberekening zou dit terug in orde moeten komen.
