### ISSUE TITLE
[BUG] Nitroxduiken niet correct

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#243]
**Beschrijf de bug**
Beste

Ik heb gemerkt dat er in mijn DIVES2.0 het aantal Nitroxduiken is gedaald naar 27 duiken (ik vermoed dat dit in DIVES1.0 rond de 38 duiken was).

NELOS 35686

**Comment by ndsmyter** [comment]
@Cereal2nd 
Dit moeten we eens uitzoeken met de recalculate_stats functie. Die telt blijkbaar nog iets niet helemaal juist dan.

**Comment by Cereal2nd** [comment]
![afbeelding](https://user-images.githubusercontent.com/3715825/232313550-e8372ad0-392f-4457-8d99-51f52bddba66.png)
10 duiken met zuurstof > 21%
22 in initialisatie => dus 32 is het totaal
![afbeelding](https://user-images.githubusercontent.com/3715825/232313594-dab5f554-ce3b-4ff7-aabd-3e0bf857fc23.png)

dus weet niet waar hij dit ziet maar in de db ziet dit er ok uit

**Comment by ndsmyter** [comment]
Geantwoord via mail. Case afslutien.
