### ISSUE TITLE
Logboek: activiteit icoontjes in het logboek verdwenen en is er een foutieve text reflow (Firefox)

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#244]
**Beschrijf de bug**
Sinds vandaag zijn de activiteit icoontjes in het logboek verdwenen en is er een foutieve text reflow, ook in de list view.
Dit is enkel op Firefox. Ik heb dan de nieuwste versie van Firefox geinstalleerd maar het blijft. Chrome is OK

**Stappen om te reproduceren**
1. Ga naar 'Logboek'

**Verwachte resultaat**
Zoals voorheen en zoals in Chrome

**Screenshots**
Links: Chrome, rechts Firefox
![afbeelding](https://user-images.githubusercontent.com/121305742/231865959-abef89d3-f840-4a9d-87c8-ae5dffb73f00.png)
![afbeelding](https://user-images.githubusercontent.com/121305742/231865993-67c098ff-8904-46b9-b747-6f9a9c2a0cd5.png)

**Desktop (indien mogelijk aanvullen):**
 - Browser: Firefox 102 en 112 (64-bits)

**Comment by ndsmyter** [comment]
NELOS-517

**Comment by ndsmyter** [comment]
@KWillemse 
We krijgen de feedback van Endare dat ze het niet kunnen reproduceren.
Ik heb dit nu zelf ook even geprobeerd, en lukt bij mij ook niet om het te reproduceren zoals in jouw screenshot.

Kan het zijn dat je een oudere versie gebruikt die misschien eens update moet krijgen?
Of misschien een extensie die actief staat die dat kan veroorzaken? Je kan dat eens proberen om het in een private window te openen, en dan te zien of het er beter uitziet. Indien beter, dan ligt het mogelijks aan een extensie.

Als wij (of Endare) het niet kunnen reproduceren, is het ook beetje moeilijk om het op te lossen.

Ik sluit de taak voorlopig af, maar als het toch een probleem zou blijven, kan ik altijd terug opnen.

**Comment by KWillemse** [comment]
Idd, in 'Troobleshoot' mode is het in orde. Het is dus een extentie, theme, of iets anders.
