### ISSUE TITLE
Er is geen 'Cancel' knop eens dat je een nieuwe activiteit gestart bent of een activiteit aanpast

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#245]
**Beschrijf de bug**
Soms kan het voorkomen dat je tijdens het editeren vaneen activiteit (nieuwe of bestaande) toch graag de reeds gewijzigde zaken wil resetten. Normaal heb je dan een 'Cancel' knop om opnieuw te beginnen. Nu heb je die niet en zit je een beetje vast. Je moet dan 'back' doen in de browser of afsluiten en terug opstarten.

**Stappen om te reproduceren**
1. Maak een nieuwe activiteit en pas een bestaande activiteit aan
2. verander een bepaalde setting
3. er is geen mogelijkheid om de annuleren.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/121305742/231881612-b0608040-af92-4b57-91fc-b26cf65e308c.png)
![afbeelding](https://user-images.githubusercontent.com/121305742/231881864-7f119f89-575a-4c87-b010-1404afde9793.png)

**Comment by ndsmyter** [comment]
Weg navigeren van die pagina wordt gezien als "Annuleren". Een extra knop toevoegen lijkt mij persoonlijk te veel werk voor wat het waard is. Een Annuleren knop is in mijn ogen enkel relevant als je een popup opent in een scherm, of je een actie aan het doen bent.
