### ISSUE TITLE
[BUG] ERD duiken automatisch afgetekend

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#246]
**Beschrijf de bug**
Ik heb ook gemerkt dat er voor mijn openstaande opleiding OC NTD de voorwaarde 10 ERD-duiken automatisch is afgetekend, maar deze duiken heb ik nog niet volledig behaald.

NELOS ID 35686

TOEVOEGING DIVES COORDINATOR
Kan dit iets te maken hebben met het feit dat deze van 'overige' naar 'automatisch' gemigreerd zijn?
Ik zie bij een andere kandidaat dat als er voor DIVES 2 een vrijstellling werd gegeven dit genoteerd werd (was wel eentje die bij duik is blijven staan)

![image](https://user-images.githubusercontent.com/112652115/232087444-13673f05-7f33-49ad-bb63-8a252d299e60.png)
![image](https://user-images.githubusercontent.com/112652115/232087527-8a8f023b-ad6e-470f-b9d3-254b5bbb7358.png)
![image](https://user-images.githubusercontent.com/112652115/232114904-b3e3c8c5-f9fc-418e-b53b-2ce3e805435b.png)

**Comment by DIVEScoordinator** [comment]
Bekijk dit nog eens in detail want normaal krijg bij items die via vrijstelling werden in gebracht een vermelding wie en wanneer
![image](https://user-images.githubusercontent.com/112652115/232227820-dbe1b768-1c79-4441-9c57-d7d5daeb2d8f.png)

Bij alle kandidaten NTD is dit afgetekend zonder enige commentaar - lijkt mij een databank issue te zijn (bug)

**Comment by ndsmyter** [comment]
Dit probleem zou opgelost moeten zijn door het toevoegen van een falende preconditie.
