### ISSUE TITLE
[BUG] Reeds afgetekende proeven kunnen niet meer aangepast worden indien te lang geleden

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#247]
**Beschrijf de bug**
Zwembadproef van 9/3/23 kan niet meer aangepast. Er komt een melding (zie ook issue #213 dat over zwembad gaat)

**Stappen om te reproduceren**
1. Ga naar 'activiteit met proef' (in de life omgeving, niet test)
2. Klik op 'afgetekende proef'
3. Melding komt; 'Je kan deze evaluatie niet meer aanpassen'

**Verwachte resultaat**
Proeven uit het recente verleden (tot 6 maanden terug minimum) moeten nog aangepast kunnen worden om fouten te herstellen waar mogelijks om DIVES 2 release is gewacht

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.
![Schermopname (36)](https://user-images.githubusercontent.com/112652115/232084096-57676424-3f37-456a-a716-e96bdd458545.png)

**Comment by DIVEScoordinator** [comment]
@ndsmyter   kan je deze nog meenemen in de huidige sprint?

**Comment by ndsmyter** [comment]
@DIVEScoordinator ,
Blijkbaar was er een parameter om te bepalen hoe lang duiken aangepast kunnen worden, en een parameter die bepaalt hoelang proeven aangepast kunnen worden. Ik herinner me nu terug dat ik dat zo gevraagd had, maar was dat dus echt rats vergeten.

Ik heb het nu ook op 5 jaar gezet.

Let wel op: sommige proeven gaan geblokkeerd blijven, voornamelijk voor de presonen van wie de opleiding niet meer open staat.
