### ISSUE TITLE
[BUG] Automatisch items zonder berekening mogen niet afgetekend worden automatisch maar via vrijstelling

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#248]
**Beschrijf de bug**
Een aantal automatische items die nog niet voorzien zijn van een berekening lijken automatisch afgetekend te worden - zie verder voor details

Voor volgende voorwaarden moeten nog automatische berekeningen voorzien worden:

- [x] 5 nitrox duiken met decomengsel
- [x] Getuigschrift DHV of DR/HR
- [x] 10 ERD+NTD+ATD duiken
- [x] 10 uur ERD+NTD+ATD duiken
- [x] 10 ERD duiken
- [x] 10 uur ERD duiken
- [x] 10 NTD of ATD duiken
- [x] 10 uur NTD of ATD duiken
- [x] 5 NTx duiken
- [x] 5 uur NTx duiken
- [x] 5 ATD duiken
- [x] 7,5 ATD uren
- [x] 50 CCR-D-A duiken
- [x] 50 uren CCR-D-A duiken
- [x] 100 uren CCR-D-A / CCR-D-NTx duiken
- [x] 5 CCR-D-NTx duiken
- [x] 5 CCR-D-Tx duiken
- [x] 7,5 uren CCR-D-Tx
- [x] 15 zeeduiken niet OS(30)
- [x] 40 zeeduiken niet OS(30)
- [x] 75 zeeduiken niet OS(30)
- [x] 100 duiken CCR-D-A
- [x] 100 uren CCR-D-A
- [x] 10 CCR-D-NTx / CCR-D-Tx duiken
- [x] 10 uren CCR-D-NTx / CCR-D-Tx
- [x] 25 ERD+NTD+ATD duiken (vrijstelling indien CCR-D-A)
- [x] 25 uur ERD+NTD+ATD duiken (vrijstelling indien CCR-D-A)
- [x] 25 NTD of ATD duiken (vrijstelling indien CCR-D-NTx)
- [x] 25 uur NTD of ATD duiken (vrijstelling indien CCR-D-NTx)
- [x] 10 NTx duiken (vrijstelling met CCR-D-Tx brevet)
- [x] 10 uur NTx duiken (vrijstelling met CCR-D-Tx brevet)
- [x] 10 ATD duiken (vrijstelling indien CCR-D-Tx)
- [x] 10 uur ATD duiken (vrijstelling indien CCR-D-Tx)
- [x] 10 CCR-D-NTx duiken (vrijstelling bij ATD brevet)
- [x] 15 uren CCR-D-Tx (vrijstelling ATD brevet)
- [x] 10 CCR-D-Tx duiken (vrijstelling ATD brevet)
- [x] 25 CCR-D-NTx / CCR-D-Tx duiken (vrijstelling NTD brevet)
- [x] 25 uren CCR-D-NTx / CCR-D-Tx (vrijstelling NTD brevet)

**Comment by ndsmyter** [comment]
@DIVEScoordinator ,
Jij ging dit nog verder uitschrijven welke het juist over gaat?

**Comment by DIVEScoordinator** [comment]
@ndsmyter    ja ik zal dat doen, er is wel al een lijst maar ik zal die up-to-date houden

**Comment by DIVEScoordinator** [comment]
@ndsmyter   ik ben door de technische brevetten gelopen en de voorwaarden staan nu allemaal op automatisch maar ik ben niet zeker of ze allemaal afgeblokt staan (cfr. ERD case).
Bekijk je de volgende
-  5 GND duiken bij NI
- 25 scooterduiken bij scooter instructeur en idem bij sidemount instructeur
- ATD brevet: 10 NTX duiken, 5 NTX duiken en 10 NTx uren, 5 NTx uren (ik zie bij sommige kandidaten de datum waarop de vrijstelling is gegeven en bij anderen is dit gewoon afgetekend)
- CCR-D-NTx: 50 CCR-D-A duiken (denk dat die ok is)
- CCR-D-Tx: 100 uren en 10  en 5 CCR-D-NTx duiken
- Scooter en sidemount: 25 duiken sinds behalen van 2*D =>wordt dit effectief berekend

**Comment by ndsmyter** [comment]
NELOS ID 11070

**Comment by DIVEScoordinator** [comment]
@ndsmyter   Is dit nu afgerond?  Gaat er over dat automatische zaken niet afgetekend worden als er nog geen berekening achter staat, dus niet of die berekening al effectief werkt, daar is nog werk aan dat weet ik.
Indien ok dan mag deze afgesloten.

**Comment by ndsmyter** [comment]
Nog niet alle automatische proeven zijn automatisch. Zeker die CCR en die speciale duiken (ATD, NTD etc) staan op mijn TODO. Ik zou deze dus nog even laten open staan.

**Comment by ndsmyter** [comment]
@WalterVanN 
Aangezien het traject nog maar gestart is, zou ik voorstellen om aan te raden nog even geduld te hebben. Ik ben op dit eigenste moment bezig om de herkenning te doen van de technische duiken. Als ik die ganse resem aan voorwaarden kan wegwerken (zijn namelijk grotendeels gelijkaardig), zal die niet-Oosterschelde voorwaarde redelijk snel volgen.

**Comment by DIVEScoordinator** [comment]
Heb je een lijstje van wat nog moet berekend?  Krijg daar ook vragen over.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Tuesday, May 23, 2023 9:51:36 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Automatisch items zonder berekening mogen niet afgetekend worden automatisch maar via vrijstelling (Issue #248)


Terug 20 extra voorwaarden kunnen afvinken. De resterende zijn terug een stapje ingewikkelder omdat er meerdere types tegelijk geteld moeten worden. Dit wordt dus een volgende uitdaging.

**Comment by ndsmyter** [comment]
@DIVEScoordinator zie het allereerste bericht van deze pagina, daar staat het mooi opgesomd 😄 De afgevinkte zijn zoals je zou vermoeden reeds gedaan.

**Comment by DIVEScoordinator** [comment]
Prima. Ik check nog eens volgende week of ze er nu allemaal instaan of dat we toch nog eentje missen. Met infomap

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Wednesday, May 24, 2023 12:01:29 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Automatisch items zonder berekening mogen niet afgetekend worden automatisch maar via vrijstelling (Issue #248)


@DIVEScoordinator<https://github.com/DIVEScoordinator> zie het allereerste bericht van deze pagina, daar staat het mooi opgesomd 😄 De afgevinkte zijn zoals je zou vermoeden reeds gedaan.

**Comment by DIVEScoordinator** [comment]
Nicolas

Is de voorwaarde voor 1*I eentje die wel al werkt of ook nog een om toe te voegen (kreeg ik van iemand via whatsapp een vraag over).  Ik kan dat moeilijk testen daarom dat een lijst met wat er wel al is ook handig zou zijn (😊 ).  Maar misschien kan ik dat ook makkelijk zien eens de module om aanpassingen te doen er is en dan wacht ik daar wel op.
***@***.***

Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: woensdag 24 mei 2023 13:11
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Automatisch items zonder berekening mogen niet afgetekend worden automatisch maar via vrijstelling (Issue #248)


Gewoon voor alle duidelijkheid. Deze 38 voorwaarden bevatten niet ALLE technische voorwaarden. Dat was gewoon het lijstje van voorwaarden die ik toen nog moest doen (2 weken geleden ofzo)

**Comment by ndsmyter** [comment]
Normaal werken alle voorwaarden, behalve bovenstaande. Dus voor 1*I zou al moeten werken. Maar het is niet omdat het al zou moeten werken, dat het ook al 100% correct werkt. Ik heb die voorwaarden ook al moeten aanpassen omdat er bepaalde uitzonderingen waren, waar ik geen rekening mee heb gehouden.

Dus als je een case hebt die ze denken dat niet werkt, dan lijkt mij best om daar een bug voor te maken. Met NELOS is en de voorwaarde die niet werkt, en wat het zou moeten zijn. Dan kan ik dat eens uitzoeken en indien nodig bijsturen.

**Comment by ndsmyter** [comment]
Finished !
