### ISSUE TITLE
[BUG] Organisatie 1*I dient afgetekend met duik en niet met theorie

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#249]
**Beschrijf de bug**
Activiteit voor organisatie is nu theorie.
![image](https://user-images.githubusercontent.com/112652115/232117200-6cce0653-9462-40f3-bac4-d4c69a0c9361.png)
**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
Organisatie aftekenen met duik
**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
@Cereal2nd 
Dat is normaal gewoon activiteitstype aanpassen in de databank

**Comment by Cereal2nd** [comment]
![afbeelding](https://user-images.githubusercontent.com/3715825/232247063-f551cfba-876f-4d3b-9102-ebde17b0e9eb.png)

ik kijk morgen wel verder waar dit vandaan komt, maar de DB lijkt ok

**Comment by DIVEScoordinator** [comment]
Is ok in de productie omgeving.  Mag dus gesloten
