### ISSUE TITLE
[BUG] Brevetkaart AI didactiek - logischer schikken

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#251]
**Beschrijf de bug**
Didactisch gedeelte bestaat uit kijkstages (5 onderdelen 1x theorie, 2x zwembad en 2x OW + reflectie) geven van zwembadlessen (9 lessen + evaluatie + reflectie evaluatie), geven van theorielessen. en 10 stageduikleidingen staan   momenteel niet in een logische volgorde op de brevetkaart
![image](https://user-images.githubusercontent.com/112652115/232226731-1cb12de9-9423-450d-8f86-500c42c3d710.png)
![image](https://user-images.githubusercontent.com/112652115/232226794-d4232672-4e93-4bb0-9dab-8f98a247750b.png)

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
10 stageduikleidingen dienen na specifiek gedeelte didactiek (theorie examen) te komen
zwembadles geven als stage 1 dien voor zwembadles geven als stage 2 te komen
Laatste item: stage zwembadles - reflectie evaluatie dient achter zwembadlesgeven als stage - evaluatie te staan
evaluatie kijkstage wordt beter met activiteit 'theorie' afgetekend dan 'duik'

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
@Cereal2nd 
Als je heidisql openzet op de tabel test. En dan in filter query schrijft dat via module_test,module en license oplijst voor specifiek brevet kan je gewoon volgorde aanpassen.
Volgorde is per brevet, dus mag gewoon vanaf 0 starten tot oneindig
