### ISSUE TITLE
[Feature] DIVES laat niet meer zien of iemand AI is

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#252]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Ik hoor binnen mijn club frustratie bij de AI's dat zij nu als 3*D worden beschouwd.  Ook de kandidaten vinden het vreemd dat zij met een 3*D hun opleidingsduiken kunnen doen.  
**Beschrijf de oplossing die je zou willen**
Relevante brevetten bovenop basisbrevet laten zien: AI, mogelijks ook anders instructeurstitel (JIN, ERI, ....)

**Beschrijf alternatieven die je overwogen hebt**
Je kan hier een korte en bondige beschrijving geven van wat je verder nog overwogen had.

**Extra context**
Je kan hier eventueel context opgeven, of screenshots om de nieuwe functionaliteit duidelijk te maken.

**Comment by FrancescoVrijduik** [comment]
Hallo,
bij Vrijduikers net hetzelfde: het is heel vervelend dat we enkel het LUCHT brevet zien en niet het Vrijduik brevet. Zou het mogelijk zijn om ook eventueel vrijduik brevet te laten zien bij opzoeken kandidaat? Toch tenmiste bij het aanmaken van een Vrijduik activiteit? Laat maar weten of dit apart topic moet zijn (specifiek bij activiteit Vrijduiken) maar als bvb brevet aanduiding meerdere velden heeft (en Vrijduken is er bij :-) ) hoeft dit denk ik niet. 
grts Francesco

**Comment by ndsmyter** [comment]
@FrancescoVrijduik Maak daar maar een ander topic voor, want dat past niet echt bij dit topic.
