### ISSUE TITLE
[BUG] vrijstelling vandaag ingebracht krijgt als datum 23 maart

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#253]
**Beschrijf de bug**
Vandaag werd voor een kandidaat 3*D een vrijstelling ingebracht voor de duiken in de zone (30) en die staat op datum van 23 maart 2023 (46300 lidnummer)

**Screenshots**
![image](https://user-images.githubusercontent.com/112652115/232227623-208fe2a3-a25a-4795-baf5-b91680ca05f8.png)

**Comment by netdata-be** [comment]
@ndsmyter waarom laten we toe een vrijstelling te geven op een item dat automatisch afgetekend dient te zijn?
Dit lijkt me een kwestie van:
* Correct initialiseren
* Je duiken invullen in DIVES

**Comment by ndsmyter** [comment]
@netdata-be ,
Dat is omdat we op dit moment nog niet alle automatische proeven kunnen effectief automatisch berekenen. Die staan wel al op Automatisch omdat die dan beetje bij beetje automatisch zullen worden.

Nadien kunnen we daar over praten om die niet meer aftekenbaar te maken.

**Comment by DIVEScoordinator** [comment]
dit specifieke probleem wordt wel correct meegegeven - afgesloten
