### ISSUE TITLE
[BUG] Voorwaarde opleiding "minimaal" brevet werkt niet

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#255]
Een 1*I kan zich niet inschrijven voor GND en krijgt dit te zien:

<img width="386" alt="Scherm­afbeelding 2023-04-16 om 09 43 48" src="https://user-images.githubusercontent.com/494802/232281233-c7faf879-8326-4755-a83f-a9d01a743fba.png">

Hetzelfde is ook voor dit brevet:
<img width="388" alt="Scherm­afbeelding 2023-04-16 om 09 44 05" src="https://user-images.githubusercontent.com/494802/232281296-3fcaff98-73cc-4428-b9f0-725f41cd33a1.png">

Er zijn nog een reeks van opleidingen die je om dezelfde reden niet kan activeren ( ook een 1*I )
Hier is het zelfs zo dat AI tussen de lijst van mogelijke opleidingen staat, wat niet eens klopt.

<img width="400" alt="Scherm­afbeelding 2023-04-16 om 09 51 29" src="https://user-images.githubusercontent.com/494802/232283214-b45738c9-01af-4ec7-9d4d-196dd43ba651.png">

**Comment by DIVEScoordinator** [comment]
Er moet nog een opkuis gebeuren in de startvoorwaarden van brevetten. De lijst is er maar nog niet in het systeem ingebracht.

**Comment by ndsmyter** [comment]
@DIVEScoordinator Ik ben daar mee bezig om die wel in te brengen hoor ;-)

@netdata-be ,
Aha, whoops. Ik heb gisteren 2*D en 3*D als voorwaarde gezet; natuurlijk vergeten om daar "minimum 2*D" en "minimum 3*D" van te maken. Bij deze aangepast
