### ISSUE TITLE
[BUG] Nieuwe opleiding: voorwaarde Technisch Scooter Duiker ontbreekt

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#256]
Minimaal 2*D ontbreekt

**Comment by DIVEScoordinator** [comment]
Dat moet bij de inschrijving gecontroleerd worden en wordt geen brevetvoorwaarde op de kaart. 
Momenteel moeten ze die startvoorwaarden nog wat fine tunen
