### ISSUE TITLE
[Feature] Wie heeft de proef afgetekend?

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#257]
Momenteel kan je niet zien wanneer een proef goedgekeurd is, wie deze afgetekend heeft.
Dit kan soms zinvol zijn.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   voorstel om deze mee te nemen in sprint van juni. lijkt mij nuttig naar rapportage jaareinde om deze info ook te hebben.

**Comment by ndsmyter** [comment]
Dit is functionaliteit die we niet aan iedereen voor iedereen willen geven. We gaan nog eens moeten bekijken wie van wie en wanneer dingen kan zien. Voor de privacy hebben we dat altijd wat proberen afschermen zodanig dat niet elke instructeur van elke kandidaat kan zien met wie hij/zij proeven doet en wanneer. Daar moet toch altijd een gegronde reden voor zijn.

@DIVEScoordinator ,
Moeten we dus eens bespreken tijdens 1 van onze volgende meetings.

**Comment by ndsmyter** [comment]
@DIVEScoordinator gaat dit verder uitwerken

**Comment by DIVEScoordinator** [comment]
doorgegeven aan endare via Jira #607

**Comment by DIVEScoordinator** [comment]
al enige tijd geleden geimplementeerd
