### ISSUE TITLE
[BUG] Verduidelijk inschrijving nieuwe kandidaat

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#258]
**Beschrijf de bug**
Iemand die de eerste keer aanlogd op het systeem krijgt hetzelfde scherm als bestaande gebruikers. Het is niet duidelijk dat je op de 'vraag nieuwe paswoord' knop moet drukken.

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
Voeg toe naast Wachtwoord vergeten?  Nieuwe gebruiker?

**Screenshots**
![image](https://user-images.githubusercontent.com/112652115/232291202-b5e70116-a08c-46e8-a6e6-2bc80f43b5f9.png)
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by Cereal2nd** [comment]
aangepast

![afbeelding](https://user-images.githubusercontent.com/3715825/232313926-679037e2-4301-4cf0-ae01-4f6d1465c16c.png)

**Comment by ndsmyter** [comment]
Normaal gezien krijgen nieuwe leden ook een mail met een invite om hun wachtwoord in te stellen.
