### ISSUE TITLE
[BUG] in melding wordt verkeerde naam aangeduid als persoon die aanpassing heeft gedaan

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#26]
**Beschrijf de bug**
Mijn naam wordt vermeld voor het aanpassen van een duik die ik helemaal niet heb gedoken

krijg het niet gereproduceerd maar wilde het toch melden in het gavel dat andere mensen dit ook tegen komen
Het is wel zo dat ik zowel op mijn account als die van mijn man Mario test en dit in dezelfde sessie

**Screenshots**
![image](https://user-images.githubusercontent.com/112573476/187741633-8415c7a1-b80b-4a13-94cf-3e135ada5068.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 104.0.5112.102

**Comment by ndsmyter** [comment]
Moeten we dan inderdaad in de gaten houden. Ik ga deze nu even parkeren om te zien of iemand anders deze ook kan reproduceren en meer details kan geven. Nu is het misschien nog iets te vaag om ook al effectief in de code voor te duiken, maar dat kunnen we zeker later nog eens doen.

**Comment by ndsmyter** [comment]
@IngeVerding ,
Met meerdere gebruikers in dezelfde sessie inloggen gaan we nog niet ondersteunen. Dus dat is de oorzaak van het probleem dat je hier ondervindt. Dat uw naam nog niet aangepast is in 1 van de sessies, is omdat die pagina nog niet herladen werd. Indien die pagina herladen zou worden, zou het vermoedelijk ook jouw naam tonen (of de naam van de persoon die laatst inlogde).

Ik denk niet dat we ooit gaan ondersteunen om met meerdere mensen tegelijk in te loggen. Dat is namelijk redelijk complexe materie, en misschien net iets te complex voor het doeleinde van DIVES.

Ik ga deze afsluiten, omdat het volgens mij anders oneindig lang gaat blijven open staan.

**Comment by IngeVerding** [comment]
ok en akkoord dat we meedere mensen in 1 sessie niet moeten ondersteunen
