### ISSUE TITLE
[BUG] Automatisch aftekenenen van proeven 4*/AI op basis van eerder behaald brevet

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#260]
Van: Yuri Ocket <[yuri.ocket@duikclubbarracuda.be](mailto:yuri.ocket@duikclubbarracuda.be)>
Verzonden: vrijdag 14 april 2023 11:20
Aan: Secretariaat NELOS <[secretariaat@nelos.be](mailto:secretariaat@nelos.be)>
CC: David Meiresonne <[david.meiresonne@duikclubbarracuda.be](mailto:david.meiresonne@duikclubbarracuda.be)>; Jeroen Van Gestel <[jeroen.vangestel@duikclubbarracuda.be](mailto:jeroen.vangestel@duikclubbarracuda.be)>
Onderwerp: Dives - Opleiding AI

Geachte, 

naar aanleiding van het slagen voor ons brevet 4* duiker, merken we op dat er geen synchronisatie is naar bepaalde proeven bij onze opleiding AI. Zoals de theorie, 900m vinzwemmen,...

 

Kunt u dit voor ons nakijken? 

 

Het betreft volgende duikers (duikclub Barracuda):

- Jeroen Van Gestel

- David Meiresonne

- Yuri Ocket

 

Alvast bedankt!

 

Met vriendelijke groeten,

 

Yuri Ocket

**Comment by Cereal2nd** [comment]
NELOS-344

**Comment by DIVEScoordinator** [comment]
Maikel, hebben zij na het behalen van hun brevet een activiteit in het systeem gedaan?  Ik denk dat het systeem pas rekent als er effectief iets gebeurd.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   Dit gaat over mensen die recent 4*D zijn geworden en hun proeven van AI die gelijk zijn niet afgetekend krijgen.  Ofwel rekent het systeem niet automatisch ofwel werkt die vrijstelling niet correct.  Vandaar naar bug/high gezet om de komende weken toch eens te bekijken.

**Comment by ndsmyter** [comment]
@DIVEScoordinator ,
Ben ik eigenlijk niet mee akkoord. We doen dat al >4 jaar zonder in DIVES 1, dus waarom is dat nu opeens dringend. Ik ga het nu laten staan, maar wat mij betreft is dergelijke nieuwe functionaliteit (dus echt geen bug) geen hoge prioriteit. Hoge prioriteit is als er zaken kapot zijn, of zaken niet kunnen die normaal gezien wel zouden moeten kunnen. Daar valt dit probleem in mijn ogen totaal niet onder.

Zit sowieso al bij Endare

**Comment by DIVEScoordinator** [comment]
@ndsmyter   In DIVES 1 werkte dit wel.  Als iemand 4*D /AI of KDD was en inschreef voor AI of 4*D dan werden bepaalde proeven en lessen automatisch afgetekend via vrijstelling. 
Ik vraag niet om binnen twee simultaan lopende opleidingen activiteiten af te tekenen maar enkel als je een bepaald brevet hebt.  Want anders wordt dit werk voor het secretariaat om dit te gaan corrigeren (als OPLV).  Bespreken het donderdag wel even... maar ik zag het ticket bij ENDARE staan dus mogelijks binnenkort sowieso opgelost.

**Comment by ndsmyter** [comment]
Dat was niet automatisch volgens mij, dat was volgens mij allemaal met manuele vrijstellingen.

**Comment by DIVEScoordinator** [comment]
kan dit niet meer controleren voor deze personen want ondertussen een manuele vrijstelling gegeven. Wel getest met een kandidaat binnen mijn club en zijn theorie examen werd automatisch afgetekend na 'klaar voor eindexamen' in te brengen.
