### ISSUE TITLE
progress bar bij aantal duiken die nodig zijn om een opleidingingsonderdeel af te werken

### ISSUE THREAD

**Issue by rubenvanveerdeghem** [Nelos-VZW/dives-2#261]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Ik ben gestart met de opleiding voor 1* instructeur, daarvoor moet je 60 zeeduiken hebben naar zone 30. Dit onderdeeltje is nog 
niet afgewerkt, maar het is mij helemaal niet duidelijk op dit moment hoever ik sta. In Dives 1.0 had ik volgens mij 54/60 gedaan, 
maar in dives 2.0 is dit nergens goed zichtbaar.

**Beschrijf de oplossing die je zou willen**
Het zou eventueel goed zijn mochten bij de onderdeeltjes waar er over aantal duiken gesproken wordt een progressbar zijn, of
iets anders waar je kan zien hoever je staat. Of bijvoorbeeld gewoon in een string "54/60".

**Beschrijf alternatieven die je overwogen hebt**
In je profiel kan je zien hoeveel duiken je van iets hebt, maar het is voor mij niet helemaal duidelijk wat allemaal meetelt hiervoor.
Dus dit was volgens mij een alternatief, maar ik kom er niet meteen uit.

**Extra context**
![image](https://user-images.githubusercontent.com/63357196/232448859-376edf35-c22e-4191-8609-3c561d4d3edf.png)

**Comment by Cereal2nd** [comment]
duplicate of #209
