### ISSUE TITLE
[BUG] OPLV aanpassen voor bepaalde brevetten (GND, compressor handler) lukt niet

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#262]
**Beschrijf de bug**
Je kan bij de opleiding GND en compressor handler de OPLV niet aanpassen, ook niet in NELOS admin.
Dit blijft op de duikschoolleider staan.

**Stappen om te reproduceren**
1. Ga naar 'ledenadmin'
2. Klik op 'GND brevet'
3. Scroll naar 'OPLV
4. Zie fout: kan niet aangepast

**Verwachte resultaat**
Voor opleidingen die niet onder DO-NELOS of VR-NELOS vallen moet de OPLV kunnen aangepast en niet op DSLV blijven staan.

**Comment by ndsmyter** [comment]
Dit is eigenlijk geen bug, dit is de huidige manier van werken.

We hebben ooit beslist om enkel opleidingsverantwoordelijken binnen de club te zoeken (dit kan altijd aangepast worden indien nodig). Naast deze conditie geldt in dat veld ook dat enkel mensen zichtbaar zijn die ook effectief proeven kunnen afnemen van die specifieke opleiding.

De duikschoolverantwoordelijke kan je altijd selecteren, en staat ook standaard geselecteerd.

Dus, specifiek voor uw case: als er een nitrox-instructeur binnen uw club aanwezig is, dan zal die ook kunnen fungeren als opleidingsverantwoordelijke.
