### ISSUE TITLE
[BUG] afgetekend en geldig examen/stageles komen niet mee door

### ISSUE THREAD

**Issue by Celinevancau** [Nelos-VZW/dives-2#263]
Mijn theorieles als stage 1 staat plots niet meer af gevinkt. 

Zou het mogelijk zijn dat de 2 te behalen examens (start to coach en specifiek deel didactiek) niet (meer)mee door komen? (zie ook foto in de bijlage)

**Comment by DIVEScoordinator** [comment]
Nicolas, in DIVES 1 moest de eerste theorie  2x afgetekend, een bug die we nooit opgelost kregen. Kan dit hier iets mee te maken hebben? 
![image](https://user-images.githubusercontent.com/112652115/232726892-45f05f00-3bc8-4914-beb2-37c4a2b58d7a.png)

**Comment by ndsmyter** [comment]
@DIVEScoordinator ,
Ik vermoed dat je daar inderdaad gelijk in hebt. Ik zie dat er in de databank 2 records zitten om deze proef af te tekenen. Maar de ene staat op "Geslaagd", en de andere "In opleiding". En je zal altijd maar zien, een ongeluk komt niet alleen, de verkeerde werd als "juist" gezien.
Ik heb de verkeerde als "verwijderd" gemarkeerd, en dat loste het probleem op.

@Celinevancau ,
Dit zou normaal gezien jouw probleem oplossen.
Ik zie dat er ook nog een proef "Zwembadles 6" open staat voor jou, maar die zou nog open staan bij Frank Verstraete denk ik.

Is het probleem hiermee opgelost?
