### ISSUE TITLE
[BUG] zwembadexamen voor AI staat open terwijl nog niet alles is afgelegd (predecessor)

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#264]
**Beschrijf de bug**
In DIVES 1 moest 'klaar voor eindexamen' afgetekend worden vooraleer het zwembadexamen open komt. Dit is blijkbaar verdwenen in DIVES 2.

**Stappen om te reproduceren**
1. Ga naar '...'
2. Klik op '...'
3. Scroll naar '...'
4. Zie fout

**Verwachte resultaat**
Predessors aanpassen zodat dit niet meer openstaat  of lijn enkel aftekenbaar maken door admin (enhancement)

**Screenshots**
![image](https://user-images.githubusercontent.com/112652115/232725018-14a4e65b-0b51-47fa-a4f0-c7d42bde9af0.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
@DIVEScoordinator Was deze ondertussen opgelost? Of heb ik dat niet ergens zien passeren dat het nu wel OK was? Misschien bij ticket van Endare.
