### ISSUE TITLE
[BUG] Gegevens decompressiegassen niet overgedragen

### ISSUE THREAD

**Issue by j-montforts** [Nelos-VZW/dives-2#265]
**Beschrijf de bug**
Bij het controleren van mijn duiken ben ik erachter gekomen dat de decompressiemengsels die ik in de vorige versie opgegeven heb niet mee geconverteerd zijn.

**Stappen om te reproduceren**
1. Bewerk een duik waarbij je in de vorige versie een decomengsel toegevoegd had
2. Decomengsel is in de nieuwe versie niet meegenomen

**Verwachte resultaat**
Decompressiemengsels die in de vorige versie ingegeven zijn, zijn mee overgenomen

**Comment by ndsmyter** [comment]
@j-montforts ,
Jammer genoeg kunnen we hier niet zo heel veel meer aan doen. De gasmengsels die ingebracht zijn in DIVES 1 werden heel ongestructureerd opgeslagen, terwijl we bij DIVES 2.0 een veel vastere structuur gaan hanteren. Een structuur die toelaat om gasmengsels ook te gaan gebruiken in berekeningen.

Het is daardoor jammer genoeg niet mogelijk geweest om gasmengsels altijd volledig 100% correct over te nemen. Er werden soms heel originele notaties gebruikt bij de gasmengsels, waardoor het omzetten naar een vaste structuur niet rechtlijnig was.

Daarnaast was er ook nog een gekende bug in DIVES 1 waardoor de gasmengsels jammer genoeg ook niet altijd correct opgeslagen werden. Soms werden die namelijk niet opgeslagen, ondanks dat de persoon die dus wel correct heeft ingebracht.

We hebben wel so goed als mogelijk alles proberen overnemen.

Jammer genoeg ga ik dit ticket nu afsluiten, aangezien er volgens mij niet zo heel veel meer is dat ik hiermee kan doen. Je kan hopelijk wel nog eens controleren adhv uw persoonlijke papieren logboek welke gasmengsels je gebruikt hebt en die retroactief inbrengen.
