### ISSUE TITLE
Een lid (-14jaar) kon voor het brevet 1*D ingeschreven worden in Dives (en vervolgens alles afwerken)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#266]
**Beschrijf de bug**
Een 1*D (-14jaar) kon geactiveerd en volledig afgewerkt worden in Dives
Volgens de infomap is de minimumleeftijd van 14 jaar een vereiste voor deelname. Dus als een persoon jonger is dan 14 jaar zou de opleiding niet geactiveerd mogen worden.

**Stappen om te reproduceren**
1. Ga naar 'Beheer - "jouw club"'
2. Klik op "Clublid"
3. Klik op "de drie puntjes"
4. Klik op "start opleiding"
5. Werk vervolgens 'zwembad, theorie en open water' af
6. Dit zou niet mogelijlk mogen zijn

**Verwachte resultaat**
Leden jonger dan 14 jaar mogen enkel ingeschreven worden voor opleidingen waarvoor ze in aanmerking komen.

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by CarlAnto** [comment]
Dit zou gaan over een lid (jeugdduiker) die dan ingeschreven werd voor de opleiding 1*D terwijl dit lid dan de leeftijd van 14 nog niet bereikt had. Na de inschrijving voor het brevet 1*D werd kon dan alles eenvoudig getekend worden.
Ik kon dit geval ook niet simuleren daar we zo geen leden hebben in onze club.

**Comment by ndsmyter** [comment]
Dit kon volgens mij enkel voorkomen volgens mij in het jaar dat die jeugdduiker 14 zou worden, maar ook nog niet effectief 14 jaar geworden was. Want er staat wel als sinds het begin een conditie dat je 1*D pas kan starten als je 14 bent. Maar dat was nog de oude regel dat het in het jaar was dat je 14 werd. Nu is dat strenger geworden.

Verder kan ik het ook niet reproduceren.

Aangezien er al ingepland stond om die functie vandaag of morgen aan te passen (aanpassing is al gebeurd in code, maar werd nog niet op productie uitgerold); ga ik deze afsluiten.

**Comment by DIVEScoordinator** [comment]
In onze club niet jeudduiker voor 14 jaar ingeschreven.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Saturday, April 22, 2023 6:50:23 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Een lid (-14jaar) kon voor het brevet 1*D ingeschreven worden in Dives (en vervolgens alles afwerken) (Issue #266)


Dit kon volgens mij enkel voorkomen volgens mij in het jaar dat die jeugdduiker 14 zou worden, maar ook nog niet effectief 14 jaar geworden was. Want er staat wel als sinds het begin een conditie dat je 1*D pas kan starten als je 14 bent. Maar dat was nog de oude regel dat het in het jaar was dat je 14 werd. Nu is dat strenger geworden.

Verder kan ik het ook niet reproduceren.

Aangezien er al ingepland stond om die functie vandaag of morgen aan te passen (aanpassing is al gebeurd in code, maar werd nog niet op productie uitgerold); ga ik deze afsluiten.
