### ISSUE TITLE
[BUG] Adventure diving brevetkaart komt niet door

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#268]
**Beschrijf de bug**
De kandidaten voor de opleiding die in het systeem als 'actieve inschrijving' staan komen door in DIVES 2 maar er kan geen brevetkaart geselecteerd.  Dit probleem was er enkele weken geleden ook voor onder meer de 2*D opleiding. 

**Verwachte resultaat**
Brevetkaart zichtbaar maken

**Screenshots**
![image](https://user-images.githubusercontent.com/112652115/232882681-78d397df-daac-431d-a6f5-14167cbd0186.png)

**Comment by ndsmyter** [comment]
De vorige keer (bij 2\*D) was dit omdat de huidige gebruiker geen proeven kon afnemen van die personen. Veel kans dat ook hier dit het probleem is. Want de personen volgen vermoedelijk wel een opleiding (anders zouden ze niet in die lijst mogen komen); maar de persoon in kwestie heeft geen rechten om die opleidingen te bekijken.

Dit kan zijn omdat er iets scheelt aan de zichtbaarheid van de brevetten. Die rechten werden bepaald tijdens de migratie, maar misschien moeten we ook een systeem voorzien dat die rechten opnieuw gaat berekenen als er aanpassingen gebeuren aan de opleidingen in de databank.

Volgens mij gerelateerd aan NELOS-201 en NELOS-503

**Comment by DIVEScoordinator** [comment]
Is getest met VR-NELOS

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Wednesday, April 19, 2023 9:16:15 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Adventure diving brevetkaart komt niet door (Issue #268)


De vorige keer (bij 2*D) was dit omdat de huidige gebruiker geen proeven kon afnemen van die personen. Veel kans dat ook hier dit het probleem is. Want de personen volgen vermoedelijk wel een opleiding (anders zouden ze niet in die lijst mogen komen); maar de persoon in kwestie heeft geen rechten om die opleidingen te bekijken.

Dit kan zijn omdat er iets scheelt aan de zichtbaarheid van de brevetten. Die rechten werden bepaald tijdens de migratie, maar misschien moeten we ook een systeem voorzien dat die rechten opnieuw gaat berekenen als er aanpassingen gebeuren aan de opleidingen in de databank.

Volgens mij gerelateerd aan NELOS-201<https://endare.atlassian.net/browse/NELOS-201> en NELOS-503<https://endare.atlassian.net/browse/NELOS-503>

**Comment by ndsmyter** [comment]
Zoals verwacht, blijkbaar kon VR-NELOS (3*FDI) de brevetten D-APNEA en 1*-APNEA niet zien.

Voor alle personen uit de screenshot was dat het probleem. De opleiding was dus wel actief, maar de 3*FDI kon deze nog niet zien.

**Comment by DIVEScoordinator** [comment]
Ok bekijk nog opmerkingen die specifieke personen maakten als testcase of het nu wel goed is.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Saturday, April 22, 2023 4:44:24 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Adventure diving brevetkaart komt niet door (Issue #268)


Zoals verwacht, blijkbaar kon VR-NELOS (3FDI) de brevetten D-APNEA en 1-APNEA niet zien.

Voor alle personen uit de screenshot was dat het probleem. De opleiding was dus wel actief, maar de 3*FDI kon deze nog niet zien.
