### ISSUE TITLE
[BUG] duikduur in profiel wordt in dagen getoond

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#27]
**Beschrijf de bug**
De duikduur wordt in dagen getoond ipv uren

**Stappen om te reporduceren**
open profiel 

**Verwachte resultaat**
duikduur in uren zoals in dives 1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/112573476/187741989-812bd95a-544d-42c4-bf63-97e0b203abc7.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 104.0.5112.102

**Comment by ndsmyter** [comment]
@IngeVerding ,
Dit is eigenlijk geen bug, om het leesbaar te houden voor de gebruiker. Bijvoorbeeld bij jou zal je ergens om en bij de 13*24 =312 uren zitten. Dat is toch wel een pak minder leesbaar dan "13 dagen" ?

En eigenlijk kloppen die tellers ook nog niet volledig, zie #8 .

**Comment by ndsmyter** [comment]
Laat gerust weten als je niet akkoord bent, maar voor nu ga ik deze bug dus sluiten :-)

**Comment by IngeVerding** [comment]
Nicolas, voor bepaalde brevetten moet je een aantal uren hebben dus ik vind het toch wel belangrijk dat je weet aan hoeveel uren je zit
Als ik dan 2 dagen zie staan dan weet ik dat ik meer dan 48 heb en minder dan 72, maar niet of ik aan 60u zit, toch?
