### ISSUE TITLE
[Feature] Elearning mogelijkheid tot het aanpassen van een cursus

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#271]
Het aanpassen van een cursus is op dit moment niet mogelijk, dit is puur een database actie.

nieuwe GUI die:
- lijst met cursussen geeft voor club X
- de mogelijkheid om aan een cursus nieuwe studenten en instructors toe te voegen
- de mogelijkheid om een cursus op te kuisen/verwijderen (dit is niet belangrijk nu)

**Comment by ndsmyter** [comment]
Lijst met cursussen voor club X staat op de `elearning` branch.
