### ISSUE TITLE
[BUG] Startvoorwaarden  brevetten lucht & nitrox aan te passen 

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#272]
**Beschrijf de bug**
Startvoorwaarden voor de open circuit brevetten zijn niet allemaal correct.

- CCR-DA: ERD en NI verwijderen
![image](https://user-images.githubusercontent.com/112652115/232988637-5ea15285-8ba4-4212-b4f9-442411b7715b.png)
- toe te voegen bij AI opleiding: mag geen van minstens 1 van de volgende brevetten hebben: 1*I, 2*I, 3*I
- Nitrox blender: voorwaarde is enkel 18 jaar
![image](https://user-images.githubusercontent.com/112652115/232991918-1134feb6-e19d-45c1-b727-e5b9be802515.png)
- CCR-I-TX: ontbreekt CCR-I-NTx en CCR-D-Tx brevetten (geen voorbeeld uit systeem, uit databank lijst review zondag)
- CCR-I-A: aan te passen, moet beide breevetten CCR-D-A en 2*I (geen voorbeeld uit systeem, uit databank review lijst zondag)
- Technisch scooter duiker: toevoegen minstens 2*D zijn (kan nu al ingeschreven door kandidaten 1*D)
- Scooter instructeur: toevoegen minstens 2*I of 3*I zijn en in bezit van alle brevetten technische scooter duiker en GND
- Sidemount instructeur: toevoegen minstens 2*I of 3*I zijn en in het bezit van alle brevetten sidemoun duiker en GND

-

**Comment by ndsmyter** [comment]
Hey @DIVEScoordinator ,

Niet helemaal correct wat je zegt.

* ERD: NI is correct. NI is de overtreffende trap van GND, dus moet er wel blijven staan.
* CCR-D-A: Zelfde opmerking ivm NI als hierboven. En eigenlijk valt ERD daar dan ook onder. Want als je ERD hebt, dan zou dat ook voldoende moeten zijn toch?
* AI: OK


Andere moet ik nog doen

**Comment by DIVEScoordinator** [comment]
@ndsmyter 
CCR-D-A: moet je GND of NI zijn naast minimum 3*D (maar dat was al ok), ERD hoort hier absoluut niet bij thuis (CC vs OC brevetten kunnen apart gehaald worden), dus ERD verwijderen.

**Comment by ndsmyter** [comment]
* CCR-D-A: ERD verwijderd
* Nitrox-Blender: Trimix-blender is overtreffende trap, dus moet volgens mij niet veranderen
* CCR-I-TX: Aangepast
* CCR-I-A: Voorwaarden zaten blijkbaar wel al in systeem
* TSD: Voorwaarden al in systeem sinds #256 
* Scooter intstructeur: Toegevoegd. Voorwaarde TSD is automatisch omdat opvolgt
* Sidemount instructeur: Toegevoegd. Voorwaarde SMD is automatisch omdat opvolgt
