### ISSUE TITLE
[BUG] Overbodige melding van aanpassen duik gegevens

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#273]
Ik kreeg net een bericht binnen dat datum en uur aangepast werd door een buddy van me.
Bij nazicht in de historiek zie ik dit:

```
18/04/2023 - 21:26 De datum en tijd werd aangepast van 02/04/2023 11:03:39 naar 02/04/2023 11:03:00.
```

Dit lijkt me dus hetzelfde te zijn, aangezien je bij een activiteit de seconden niet kan aanpassen begrijp ik niet goed waar dit vandaan komt.

Mijn vermoeden is dan ook dat bij het aanmaken van een duik de seconden worden opgeslagen.
En bij het aanpassen van een duik deze afgerond worden?

**Comment by DIVEScoordinator** [comment]
@ndsmyter  ook op sprint zetten. Uur beperken tot uur en minuut en geen seconden. Ik kon dit reproduceren.  Minor als er tijd is.

**Comment by ndsmyter** [comment]
Zou in de huidige versie veel beter moeten zijn.
