### ISSUE TITLE
[BUG] proef of activiteit verwijderen niet mogelijk

### ISSUE THREAD

**Issue by JoeriAquapol** [Nelos-VZW/dives-2#274]
**Beschrijf de bug**
Instructeur wil proef verwijderen die hij foutief heeft ingegeven en opgeslagen.
Proef kan niet verwijderd worden en activiteit ook niet.
https://dives.nelos.be/activities/activity/239027

**Verwachte resultaat**
Proef zou moeten kunnen worden verwijderd van de activiteit of de activiteit zelf

**Screenshots**
![59b8e5a4-feff-48ee-82ac-db1ecfedea37](https://user-images.githubusercontent.com/131270873/233101268-9419dd6a-bdee-4a36-a6f7-4a92e4a1eafc.jpg)

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: iPad
 - Besturingssysteem: iPadOS 
 - Versie: 16.4.1
 - Browser: Safari

**Comment by DIVEScoordinator** [comment]
@JoeriAquapol    Joeri, op dit moment kunnen activiteiten van meer dan 14 dagen geleden niet aangepast (zou een opmerking over moeten komen).  Kan je vragen dit nogmaals te proberen want Nicolas heeft dit terug opengezet en ik kan nu aanpassingen doen in de productie (heb het wel niet opgeslagen).

**Comment by ndsmyter** [comment]
@JoeriAquapol , @DIVEScoordinator ,
Ik sluit deze nu af, aangezien dit probleem zoals @DIVEScoordinator  zegt ondertussen opgelost zou moeten zijn. Moest het probleem blijven, dan kunnen we ticket altijd nog opnieuw openen.

**Comment by AlphaDuikschool** [comment]
Het spijt me te moeten melden dat het fenomeen er nog altijd is : activiteit van jaren geleden kan ik niet verwijderen, maar zou enkel door de toenmalige organisator kunnen verwijderd worden - kan ik nog snappen.   Krijg advies om mezelf als deelnemer te verwijderen, maar als ik dat probeer krijg ik nog steeds als melding dat ik mezelf niet kan verwijderen...

**Comment by DIVEScoordinator** [comment]
Beste staan er meer dan twee personen in de activiteit? Zo niet kan je je niet verwijderen. Ook niet als er een proef aanhangt.


Gr

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: AlphaDuikschool ***@***.***>
Verzonden: Friday, April 21, 2023 8:23:34 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] proef of activiteit verwijderen niet mogelijk (Issue #274)


Het spijt me te moeten melden dat het fenomeen er nog altijd is : activiteit van jaren geleden kan ik niet verwijderen, maar zou enkel door de toenmalige organisator kunnen verwijderd worden - kan ik nog snappen. Krijg advies om mezelf als deelnemer te verwijderen, maar als ik dat probeer krijg ik nog steeds als melding dat ik mezelf niet kan verwijderen...
