### ISSUE TITLE
[Feature] Vinkje registratie uittreksel strafregister

### ISSUE THREAD

**Issue by ghost** [Nelos-VZW/dives-2#276]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**

Waar kan de registratie van ontvangst en evaluatie Uittreksel Strafregister nu worden opgevolgd ?

**Beschrijf de oplossing die je zou willen**

Vinkje op de detailkaart.

**Beschrijf alternatieven die je overwogen hebt**

Melding per mail bij ontvangst, evaluatie en registratie aan ledenadministrateur, maar dat is minder waterdicht op langere termijn.

**Comment by netdata-be** [comment]
Dit vind je terug in de [ledenadministratie](http://ledenadministratie.nelos.be)

* ga naar leden 2023
* Kies een lid en klik op "Historiek"
* Onder "Registratie medische keuringen" vind je dat terug
<img width="446" alt="Scherm­afbeelding 2023-04-20 om 12 08 43" src="https://user-images.githubusercontent.com/494802/233334844-0ad3e067-6425-4a90-b499-dbd9fd2231a0.png">


Heeft op zich niets met DIVES2.0 te maken, en kan wat mij betreft dicht

**Comment by AlphaDuikschool** [comment]
En dus geen plannen voor opname in Dives ?

In de ledenadministratie is het immers niet toegankelijk voor andere personen dan de ledenadministrateur vb. aan de waterkant bij het duiken met een minderjarige…

 

Met vriendelijke groeten,

 

 

  

Philip VERSTRAETEN

Administratief Beheerder, Secretaris & Ledenadministrateur

GDPR verwerkingsverantwoordelijke / Aanspreekpunt Integriteit & Mental Coaching

Duikschool Alpha – Liedekerke

 



 

GSM : + 32 (0)476 60 60 97   

 

Go Green, Keep it on screen !!!

**Comment by netdata-be** [comment]
Dat laat ik even aan @ndsmyter , maar zover ik weet zal dit niet zichtbaar worden in dives.

Een NELOS kaderlid dat niet in orde is ( hetzij omdat die geen attest heeft binnen gebracht, hetzij omdat er een negatieve beoordeling is) zal binnen NELOS op non-actief worden gezet als kaderlid en zal niet meer in staat zijn om proeven af te nemen, hij/zij krijgt dus de bevoegdheid van een 4*D of 3*D zonder de kader functies.

Het is aan de club om verder op te volgen of zijn kaderleden in orde zijn bij NELOS, dit aan de hand van de stapjes die ik je bezorgde, de ledenadminstrator kan dit binnen het bestuur / API dan verder opnemen.

Dit zichtbaar maken voor iedereen zou willen zeggen dat er een heksenjacht mogelijk is, dat schiet uiteraard zijn doel voorbij.

Voor meer info verwijs ik je door naar de documenten op het documenten centrum.

**Comment by ndsmyter** [comment]
Ik heb gevraagd aan @DIVEScoordinator om dit mee op te nemen in de bestuursvergadering van NELOS. We kunnen dat visualiseren, maar mijn vraag is of dat gewenst is.

Verder lijkt het me in elk geval een slecht idee om dit te visualiseren op de brevetkaart. Het zal dan volgens mij hoogstens in de ledenadministratie van DIVES komen.

Maar we wachten eerst even de beslissing van. Bestuur af voor we hier verdere stappen nemen. Ik zet deze taak nog even On Hold.
