### ISSUE TITLE
25 duiken sinds het behalen van 2 ster niet afgevinkt (als 3 ster met 100+duiken)

### ISSUE THREAD

**Issue by Celinevancau** [Nelos-VZW/dives-2#279]
<img width="1029" alt="Scherm­afbeelding 2023-04-22 om 10 58 54" src="https://user-images.githubusercontent.com/131143376/233774435-48c82f6e-19a0-4ce0-9826-254eb96566f6.png">

Zie afbeelding aub, mezelf 25 duikleidingen toeschrijven helpt niet :)

Mvg,

Céline

**Comment by ndsmyter** [comment]
Blijkbaar zat er nog geen echte logica achter die specifieke automatische proef. Bij scooter- en sidemountduiken lopen we inderdaad nog beetje achter, aangezien dat dat redelijk nieuwe brevetten zijn.

Normaal gezien zou het nu wel afgetekend moeten zijn.

**Comment by Celinevancau** [comment]
Yes, dankjewel!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
