### ISSUE TITLE
[BUG] bijkomend bericht evaluator

### ISSUE THREAD

**Issue by Piet-TD** [Nelos-VZW/dives-2#280]
ik heb zelf de cursus Comp Operator gevolgd in groep en heb een "bijkomend bericht evaluator" bij de proef dat ik geslaagd ben, doch het is niet mijn naam die ik zie , maar die van de eerste persoon in de lijst. 

**Stappen om te reproduceren**
1. Ga naar Logbook
2. Klik op op een proef (theorie/praktijk) die je zelf gevolgd hebt in groep
3. Scroll naar je eigen naam en klik achteraan op "bijkomend bericht evaluator"
4. Zie screenshot

![image](https://user-images.githubusercontent.com/112510347/233836600-89a973dd-2b98-4b1e-b569-9730ef3593e0.png)

**Comment by Piet-TD** [comment]
oeps, dit is bij alle proeven waarbij meerdere personen hebben deelgenomen. Ook bij de theorie die ikzelf afgenomen heb.
De meldingen worden automatisch gegenereerd.
![image](https://user-images.githubusercontent.com/112510347/233837002-1649247c-ce24-4746-afaa-642390066c5c.png)

**Comment by ndsmyter** [comment]
Dit is inderdaad een probleem, maar niet zo eenvoudig aan te passen omwille van de migratie van DIVES 1 naar DIVES 2. We zullen daar dus mee moeten leren leven volgens mij. Eenmaal proeven in gebruik genomen worden in DIVES 2, zou dit geen probleem meer mogen zijn.

Ik ga dit ticket sluiten, aangezien we hier niet zo heel veel meer kunnen aan doen. En dit gaandeweg zichzelf zal oplossen.
