### ISSUE TITLE
[BUG] duik verwijderen waar eerder een proef aanhing, gaat niet.

### ISSUE THREAD

**Issue by Piet-TD** [Nelos-VZW/dives-2#281]
het verwijderen van een duik met proef verwijderen, gaat niet ook al is de proef terug verwijderd.

**Stappen om te reproduceren**
1. Ga naar Logbook
2. Klik op "aanpassen" in een duik met proef
![image](https://user-images.githubusercontent.com/112510347/233837310-c94a0880-4af7-4c26-ac11-bae34e918781.png)

3. unselect field "proef deelgenomen"
4. select "aanpassen"
5. de proef lijkt verwijderd uit de duik
6. verwijder nu de duik

![image](https://user-images.githubusercontent.com/112510347/233837423-e99102e8-0567-4708-9380-4d6584645acd.png)

**Comment by DIVEScoordinator** [comment]
@ndsmyter  overweeg om mee te nemen in de sprint van juni

**Comment by DIVEScoordinator** [comment]
@ndsmyter  misschien ook eentje om eens op de sprint te plaatsen
