### ISSUE TITLE
[Feature] Link naar duikplaats

### ISSUE THREAD

**Issue by bruno-v-b** [Nelos-VZW/dives-2#284]
De uitgebreide lijst met duikplaatsen in Dives was altijd een grote meerwaarde. In de tijd van Dives 1.0 was het mogelijk een link naar een duikplaats te delen, bijvoorbeeld in een uitnodiging voor een clubduik. zoals bijvoorbeeld [https://www.nelos.be/duikplaats/PL-OS-13-73] voor Sint Annaland. Deze links werken niet meer waardoor we nu genoodzaakt zijn om als Nelos club links te delen naar bijvoorbeeld Duikersgids.nl. 

Het lijkt boeiend om het opnieuw mogelijk te maken rechtstreeks naar de duikplaats in Dives een link te maken.

**Comment by ndsmyter** [comment]
Dit is een duplicaat van #98 
Ik sluit deze taak af, aangezien we verder kunnen opvolgen op die andere taak.
