### ISSUE TITLE
[Feature] zichtbaar maken statistiek kandidaten 

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#285]
**Is uw nieuwe functionaliteit gelinkt aan een probleem?**

Bij het niet aftekenen van voorwaarden is het niet mogelijk om analyse te doen van het probleem.  Inzicht in de statistieken van kandidaten zou nuttig zijn, 

**Beschrijf de oplossing die je zou willen** 
Statistiek zichtbaar voor OPLV en/of DSV?  Of creatie van een kijk mogelijkheid in TEST voor super instructeur.

**Comment by ndsmyter** [comment]
Dit valt onder het stuk rapportering. Iets dat we beschikbaar zullen maken voor DSV, en dus ook eventueel voor bovenliggende rollen (NELOS-secretariaat etc)

**Comment by ndsmyter** [comment]
Deze functionaliteit werd ondertussen geïmplementeerd

**Comment by DIVEScoordinator** [comment]
wanneer gaan we deze functionaliteit dan zien?

**Comment by ndsmyter** [comment]
Je kan nu toch al zien hoeveel duiken zijn bij proeven die vereisen dat je meerdere hebt gedaan? (Bv x duiken dieper dan 25m)

Of bedoelde je iets anders met dit ticket?

**Comment by DIVEScoordinator** [comment]
Ok is alternatief dat ook werkt.  Case closed

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Monday, June 19, 2023 9:58:52 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [Feature] zichtbaar maken statistiek kandidaten (Issue #285)


Je kan nu toch al zien hoeveel duiken zijn bij proeven die vereisen dat je meerdere hebt gedaan? (Bv x duiken dieper dan 25m)

Of bedoelde je iets anders met dit ticket?
