### ISSUE TITLE
Zeeduiken van boot tekenen niet automatisch af

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#287]
**Beschrijf de bug**
"Zeeduiken van boot" tekenen niet automatisch af

Na inschrijving 2*I zouden alle voorwaarden automatisch afgetekend moeten worden. Zeeduiken vanaf een boot (20stuks) worden niet automatisch afgetekend.
Misschien een fout in het overnemen van de historische data van DIVES 1.0

**Verwachte resultaat**
Alle brevetvoorwaarden zouden automatisch afgetekend moeten worden.

**Screenshots**
![image](https://user-images.githubusercontent.com/130435688/234276199-7b377f50-c909-423a-a391-64d89e8b0395.png)
![image](https://user-images.githubusercontent.com/130435688/234276247-d8b4a921-c1da-4d3e-b164-aa12376109a2.png)
![image](https://user-images.githubusercontent.com/130435688/234276151-2678b452-fec1-418c-bdfa-0c50bda30d44.png)
![image](https://user-images.githubusercontent.com/130435688/234276431-085992f5-3a75-4ac5-a43d-764376759de4.png)

**Comment by ndsmyter** [comment]
@CarlAnto ,
Is dit probleem vandaag nog steeds?
Ik heb gisteren een aanpassing gedaan aan de functie die dit berekende, ook voor andere automatische proeven dus.

Moest dit probleem er nog steeds zijn, kan je me dan eens een NELOS ID doorsturen? Dan kan ik gerichter gaan zoeken wat het probleem juist is.

**Comment by CarlAnto** [comment]
Ik heb dit getest in de test.dives.nelos.be maar daar had ik duiken gelogd om te kijken als de voorwaarde verdween. Echter resetten de gegevens van test en dev momenteel niet waardoor ik het niet kan reproduceren.
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: zaterdag 29 april 2023 13:25
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: CarlAnto ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Zeeduiken van boot tekenen niet automatisch af (Issue #287)


@CarlAnto<https://github.com/CarlAnto> ,
Is dit probleem vandaag nog steeds?
Ik heb gisteren een aanpassing gedaan aan de functie die dit berekende, ook voor andere automatische proeven dus.

Moest dit probleem er nog steeds zijn, kan je me dan eens een NELOS ID doorsturen? Dan kan ik gerichter gaan zoeken wat het probleem juist is.

**Comment by ndsmyter** [comment]
Ah, maar op Test staat het niet 🙂 
De aanpassing die ik gedaan heb voor deze bug, heb ik rechtstreeks in de databank van productie gedaan. Omdat het een databankwijziging is, en geen code.

We zijn van plan om binnenkort de productiedatabank op test te zetten, maar we willen daarvoor eerst onze backupstrategie wat hertekenen. Dus dat is nog niet voor onmiddellijk.

Ik laat deze bug even open staan, maar ik denk dat het wel opgelost zal zijn.

**Comment by ndsmyter** [comment]
@CarlAnto 
Kijk je eens of dit ondertussen wel werkt? We hebben in Test terug elke week een nieuwe versie, waarmee je dus kan testen.
