### ISSUE TITLE
Brevetten duiken met handicap tonen een lager brevet

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#288]
**Beschrijf de bug**
Brevetten duiken met handicap tonen een lager brevet

**Stappen om te reproduceren**
In het beheer van je club staat er een ander brevet dan dat er zichtbaar is op de ledenadministratie.

**Verwachte resultaat**
Juiste brevet tonen.

**Screenshots**
![image](https://user-images.githubusercontent.com/130435688/234277794-8d072991-5f9b-4c33-9b9f-a8e1a606bde7.png)
![image](https://user-images.githubusercontent.com/130435688/234278063-86a807c0-3a35-4dde-97ee-8971f022dcf7.png)

**Comment by ndsmyter** [comment]
Hey @CarlAnto ,
Blijkbaar is dit een specifieke situatie waarbij het brevet enerzijds de verkeerde volgordes had, en anderzijds de einddata niet goed ingevuld werden.

Volgens mij enkel beperkt tot duikers met een handicap, maar kan dat niet zo goed achterhalen voor gans NELOS.

Zie jij nog personen waarbij dit foutief is? Want anders mag je eens de NELOS IDs doorsturen, dan kijk ik die na. Ik weet niet echt hoe ik dat op een automatische manier kan controleren voor gans NELOS.

**Comment by CarlAnto** [comment]
Deze is voor onze club enkel nog fout voor Andre Hendrickx (NELOS-ID: 20968). Hij heeft een WW-A als brevet.
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: zaterdag 29 april 2023 13:31
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: CarlAnto ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Brevetten duiken met handicap tonen een lager brevet (Issue #288)


Hey @CarlAnto<https://github.com/CarlAnto> ,
Blijkbaar is dit een specifieke situatie waarbij het brevet enerzijds de verkeerde volgordes had, en anderzijds de einddata niet goed ingevuld werden.

Volgens mij enkel beperkt tot duikers met een handicap, maar kan dat niet zo goed achterhalen voor gans NELOS.

Zie jij nog personen waarbij dit foutief is? Want anders mag je eens de NELOS IDs doorsturen, dan kijk ik die na. Ik weet niet echt hoe ik dat op een automatische manier kan controleren voor gans NELOS.

**Comment by ndsmyter** [comment]
Ik heb een manier gevonden om alle brevetten te overlopen en te corrigeren. Het was wel wat manueel werk, maar ben er wel aan uitgeraakt. Normaal gezien zou het nu voor iedereen van NELOS OK moeten zijn.
