### ISSUE TITLE
[BUG] Status van laatste proef van een opleiding wordt niet weergegeven in de details van een activiteit

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#289]
Stel je voegt 1 proef toe aan een activiteit:

<img width="1104" alt="Scherm­afbeelding 2023-04-26 om 16 24 06" src="https://user-images.githubusercontent.com/494802/234613081-2f52880c-64fa-4774-a4ad-3ff50dfded88.png">

In het overzicht zie je netjes:
1) Welke proef er toegevoegd is
2) de status van een proef 

Zodra je de laatste proef toevoegt en deze bijvb op niet geslaagd zet, komt het ook goed:

<img width="1111" alt="Scherm­afbeelding 2023-04-26 om 16 43 04" src="https://user-images.githubusercontent.com/494802/234615597-ff8eb4a6-079e-407d-8c07-d3a83d502af7.png">

Echter zodra je die proef goedkeurt, dan verdwijnt de proef van de activiteit:
<img width="1073" alt="Scherm­afbeelding 2023-04-26 om 16 43 29" src="https://user-images.githubusercontent.com/494802/234615895-ab83f6ac-0f34-4490-b738-204f9b6c7af9.png">

Ik vermoed dat dit komt omdat het brevet "afgewerkt" is. 
Echter er zijn daar 2 bedenking aan:

1) Bij een vergissing is het niet meer mogelijk de status te veranderen
2) Je verliest het overzicht waar die proef afgetekend was...

**Comment by ndsmyter** [comment]
@netdata-be ,
Je hebt hier een redelijk grote bug naar boven gehaald. Alhoewel minimale impact in de frontend, liep er in de backend vanalles mis. Blijkbaar werden in de databank zaken weggegooid ipv dat ze gedeactiveerd werden. Door het afwerken van de opleiding werd de lopende opleiding verwijderd. Op dat moment was die natuurlijk niet meer lopend, maar op de website is het wel belangrijk dat die opleidingen blijven bestaan (lopend of niet).

Ik heb hier een paar uur werk aan gehad, maar volgens mij ben ik er in geslaagd om de databank terug samen te puzzelen waardoor de ontbrekende records nu terug zijn. Ik heb er ook voor gezorgd dat de records vanaf nu gedeactiveerd worden, en niet verwijderd.

**Comment by ndsmyter** [comment]
Normaal gezien zou je de proeven nu ook terug op de activiteit moeten zien staan, als mijn restore correct was natuurlijk.
