### ISSUE TITLE
[Feature] proeven die niet afgetekend mogen worden niet tonen

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#29]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Als AI mag je BL3 niet afnemen
Uiteindelijk wordt dit niet ook niet toegelaten, maar het lijkt dat het wel mogelijk is

**Beschrijf de oplossing die je zou willen**
duidelijker aangeven dat bepaalde proef niet afgenomen mag worden

![image](https://user-images.githubusercontent.com/112573476/187743709-38256b73-cbfe-4739-8ad6-c0bcfd48a2f4.png)

**Comment by ndsmyter** [comment]
@IngeVerding ,
Hoe zou je dat zelf duidelijker willen zien? Want je kan geen beoordeling geven op de BL3, dus betekent dat je die proef niet kan afleggen.

Ik wil gerust duidelijker aangeven, maar op dit moment weet ik niet zo goed hoe we dat goed kunnen doen?

**Comment by IngeVerding** [comment]
het kan inderdaad zijn omdat ik de werking nog niet gewoon ben.
Maar ik zou precies liever een melding hebben zoals de melding wanneer je nog niet alle diepe duiken hebt gedaan vb
en dan de melding dat je die proef niet kan aftekenen omdat je niet gemachtigd bent of zo
Al leek ik te verstaan dat het mogelijk gaat zijn dat je een proef 'doorstuurt' naar de instructeur, dus dan zou het misschien beter een melding worden in de aard van 'er heeft geen persoon meegedoken die deze poref kan aftekenen'

**Comment by ndsmyter** [comment]
Hey @IngeVerding ,

Het moet inderdaad mogelijk zijn dat je als kandidaat in DIVES 2.0 ook proeven gaat toevoegen. Je kan deze proeven dan natuurlijk niet beoordelen, dat moet nog altijd door een instructeur gebeuren. Maar je kan dus wel zeggen dat je als kandidaat proef X gedaan hebt met instructeur Y.
Hierdoor willen we vermijden dat kandidaten te lang moeten wachten op de instructeurs om dingen af te tekenen, omdat die het misschien vergeten zijn.

Ik denk wel dat het niet zo nuttig is om een tekst te tonen dat je niet gemachtigd bent om die proef af te tekenen, aangezien iedereen dat normaal gezien wel al zou moeten weten. DIVES komt namelijk pas na de feiten op de proppen, die proef is al afgelegd geweest ondertussen.
Laat maar weten als je aan een betere tekst zou denken, dan kunnen we zien of we dat er bij kunnen zetten.

Ik laat deze hier nog even On Hold staan. Want ik geef je gelijk dat het misschien niet zo duidelijk is, maar weet niet goed hoe je het duidelijker kan maken.

**Comment by DIVEScoordinator** [comment]
deze wordt gesloten omdat het een kwestie is van gebruik van het systeem en het werkt niet blokkeren of foutief dat er niet voor alles een melding komt.
