### ISSUE TITLE
[BUG] Bewerkingsgeschiedenis is niet correct als je proef aftekent in 1 handeling  

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#290]
Deels gerelateerd aan: #289
Door dit gedrag is het onmogelijk om terug te kijken wat er goedgekeurd is tijdens een activiteit.

Indien je een de volgende stappen uitvoert:

* Activiteit aanmaken
* Opslaan
* Activiteit aanpassen => proef aanhangen
* Opslaan
* Proef goedkeuren

Dan krijg je dit in het overzicht van de bewerkingsgeschiedenis.
<img width="635" alt="Scherm­afbeelding 2023-04-26 om 16 57 58" src="https://user-images.githubusercontent.com/494802/234617588-3f97cbf1-996b-457c-b92f-6109181191d7.png">

Je ziet mooi elke stap die uitgevoerd werd

Echter als je alles in 1 doet dat wil zeggen:
* Activiteit aanmaken
   proef aanhangen
   Proef goedkeuren
* Opslaan

Dan ziet de Bewerkingsgeschiedenis er zo uit:

<img width="494" alt="Scherm­afbeelding 2023-04-26 om 17 02 31" src="https://user-images.githubusercontent.com/494802/234618046-50623b56-d99d-4927-b721-66d8c82a0f72.png">

Ik begrijp deels waarom, het is immers maar 1 actie, de activiteit aanmaken.
Mijn verwachting is dan ook dat voor proeven het HEEL duidelijk moet zijn wat er gebeurd is, ik verwacht dan ook steeds de 3 stappen zoals in voorgaande screenshot. ( Activiteit / proef aangehangen / status proef )

Op dit moment is het echter niet duidelijk genoeg en heeft al tot meerdere vragen geleid van ons kader.

**Comment by DIVEScoordinator** [comment]
@ndsmyter  lijkt mij ook eentje die eigenlijk al gedeeltelijk gedaan is, ook even in sprint van juni
