### ISSUE TITLE
[BUG] Behaald brevet staat nog steeds in de kolom opleidingen ( hetzij in het grijs)

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#292]
Dit is het enigste lid waarbij de opleiding 2*I in het grijs actief blijft in de opleidingen kolom:

<img width="1117" alt="Scherm­afbeelding 2023-04-26 om 17 33 12" src="https://user-images.githubusercontent.com/494802/234626797-951bc5b9-61a2-41a0-b0d1-83628277ef0c.png">

Ik verwacht dat net zoals alle andere brevetten dit brevet verwijderd wordt uit die kolom zodra het behaald is.

**Comment by DIVEScoordinator** [comment]
Deze opleiding stond in status 'geannuleerd'.  Aangepast en grijze knop is verdwenen.
![image](https://user-images.githubusercontent.com/112652115/234899192-629c4ddc-c3e3-44de-851b-645cf172705c.png)

**Comment by ndsmyter** [comment]
Weten we waarom die opleiding geannuleerd stond? Wie geeft die geannuleerd en mocht die wel terug open?

@DIVEScoordinator

**Comment by DIVEScoordinator** [comment]
Hij had het brevet al, vermoed dat dit manueel ooit is toegekend (2*I van enkele jaren geleden, ik ga dat niet meer uitzoeken).

Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: donderdag 27 april 2023 16:48
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Behaald brevet staat nog steeds in de kolom opleidingen ( hetzij in het grijs) (Issue #292)


Weten we waarom die opleiding geannuleerd stond? Wie geeft die geannuleerd en mocht die wel terug open?

@DIVEScoordinator<https://github.com/DIVEScoordinator>

**Comment by Ivo-Hubert** [comment]
Is er nog een van 2019, annulatie veranderen in gecertificeerd is hier geen probleem omdat die opleiding kosteloos is.
Voor opleidingen die wél een kost hebben moet er omzichtig met annulatie-wijzigingen omgesprongen worden omdat die dan plots een aanrekening ten gevolge kunnen hebben of omgekeerd een teruggave.

**Comment by ndsmyter** [comment]
Ik denk ook dat we voorzichtiger moeten omgaan met het veranderen van dergelijke statussen. 
Ik wil ook vooral weten waarom die status daar zo staat, want dan kan ik dat oplossen bij de bron.

**Comment by DIVEScoordinator** [comment]
Mijn vermoeden: kandidaat is 2*I geworden, manueel toegekend en men heeft achteraf de brevetkaart die nog openstond niet meer afgetekend maar gewoonweg geannuleerd.  Weet niet of je dat kan terugvinden in het systeem?

Zal de volgende keer het laten staan.

Misschien interessant om te weten of er zo nog gevallen in het systeem staan die geannuleerd zijn voor een opleiding maar wel het brevet hebben (2*I en 3*I is dat mogelijk)



Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: donderdag 27 april 2023 17:05
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Behaald brevet staat nog steeds in de kolom opleidingen ( hetzij in het grijs) (Issue #292)


Ik denk ook dat we voorzichtiger moeten omgaan met het veranderen van dergelijke statussen.
Ik wil ook vooral weten waarom die status daar zo staat, want dan kan ik dat oplossen bij de bron.
