### ISSUE TITLE
Vrijgestelde proeven hebben geen vervaldatum

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#296]
**Beschrijf de bug**
Ik kan begrijpen dat voor sommige vrijstelling geen vervaldatum nodig is maar ik heb een specifiek geval waargij een lid werd vrijgesteld voor de theorieles BND. Niet omdat hij een inschaling doet maar ik denk eerder een fout van de instructeur die het heeft goedgekeurd.
Anyway, voor deze vrijstelling is er geen 'vervaldatum' terwijl je zou kunnen vermoeden dat als deze werd vrijgesteld op 14/03/2019, de vervaldag zou moeten worden weergegeven van 14/09/2023.

**Verwachte resultaat**
Vrijgestelde proeven moeten ook een vervaldatum tonen.

**Screenshots**
Een vrijgestelde proef zonder vervaldag:
![image](https://user-images.githubusercontent.com/121305742/234932691-1ea7f889-3e58-49dd-9693-e66215b69080.png)
Dezelfde proef bij een ander lid, een paar maanden later als 'geslaagd' gemarkeerd heeft wel een vervaldag:
![image](https://user-images.githubusercontent.com/121305742/234932893-70960f4c-5ce4-4889-88ab-da3afaa1b9d4.png)

**Comment by DIVEScoordinator** [comment]
@ndsmyter   Nicolas, hier hadden we afgesproken om alle vrijstellingen van DIVES 1 op 1/1/2019 als datum te zetten omdat je de echte datum niet kon achterhalen of je kan een query maken die uit een tekst datum haalt (mocht dat kunnen)

**Comment by ndsmyter** [comment]
@KWillemse ,
Correcte opmerking.

@DIVEScoordinator ,
Deze bug heeft niet echt veel te maken met de datum waarop de vrijstellingen zouden moeten staan. Daarnaast hebben we dat volgens mij nooit echt beslist, we hebben daarover nagedacht. Maar we gingen wachten om te kijken hoeveel van die proeven er nog zouden open staan die hier niet meer aan voldoen.

**Comment by DIVEScoordinator** [comment]
Datum ingave is ook OK.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Saturday, April 29, 2023 3:30:46 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Vrijgestelde proeven hebben geen vervaldatum (Issue #296)


@KWillemse<https://github.com/KWillemse> ,
Correcte opmerking.

@DIVEScoordinator<https://github.com/DIVEScoordinator> ,
Deze bug heeft niet echt veel te maken met de datum waarop de vrijstellingen zouden moeten staan. Daarnaast hebben we dat volgens mij nooit echt beslist, we hebben daarover nagedacht. Maar we gingen wachten om te kijken hoeveel van die proeven er nog zouden open staan die hier niet meer aan voldoen.

**Comment by KWillemse** [comment]
Mogelijks is dit intern wel op de datum ingave gezet maar de tekst geeft nog altijd 'er zijn nog geen proeven die kunnen vervallen'. Zie screenshots in de beschrijving en de rode kaders, ik zie nog steeds hetzelfde.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   ik denk dat dit stilgevallen is door de discussie welke datum. Mij lijkt het meest correcte de datum dat het ingebracht is want ik zie dat op mijn brevetkaart ook items met vrijstelling werd ingebracht en die zijn nog niet aan verval toe (bijwonen nitrox instructeur les).

Is dat technisch makkelijk te realiseren om het huidige datumveld dat bij een vrijstelling staat op te vullen met de datum van h et aanmaken van de vrijstelling voor die items zonder een datum?  Dan zou ik dat op korte termijn doen want vanaf 1 juli start het automatisch vervallen van proeven.
