### ISSUE TITLE
[BUG] Proef niet zichtbaar in logboek maar wel geregistreerd

### ISSUE THREAD

**Issue by didiergonze** [Nelos-VZW/dives-2#297]
**Beschrijf de bug**
Betreft: [https://dives.nelos.be/activities/activity/246576]
Op deze duik, is een proef geassocieerd (hoedje op de kaart)
Maar als de kaart open is, de proef is niet zichtbaar (zou moeten onder ruimt bericht zijn)
In de berwerkingsgeschiedenis is de proef wel zichtbaar
In de aantal afgenomen proeven (statistiek) is dit proef ook niet gerekend...
Voor de kandidaat is dit proef wel getekend... (was laatste proef voor 1*D --> is nu 1*D)

het is zichtbaar op de PC als op de mobile

**Stappen om te reproduceren**
Niet zeker maar hiet lijk te gebeuren als de proef niet onmiddelijk toegevoegd bij de creatie maar als bijkomend edit.

**Verwachte resultaat**
Proef zou zichtbaat zijn + ddie zou moeten geteld worden bij de statistiek (status evaluator_  

**Screenshots**

![image](https://user-images.githubusercontent.com/132095935/235226485-047e209a-68d7-4bbb-bf3b-a19c06923790.png)
![image](https://user-images.githubusercontent.com/132095935/235226568-58d1cfd4-62a4-432b-a99f-21c2fb9506ba.png)
![image](https://user-images.githubusercontent.com/132095935/235226610-e66c068f-ceb8-4c2b-a29b-a49cc92a21c9.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: windows
 - Browser: firefox
 - Versie: 

**Smartphone (indien mogelijk aanvullen):**
 - Toestel:samsung galzi S21
 - Besturingssysteem: [Android 
 - Browser std
 - Versie

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Er was inderdaad een probleem met proeven bij het inbrengen van de laatste proef. Dit probleem zou normaal gezien moeten opgelost zijn, en dus hopelijk zie je de proeven terug staan op die pagina.

Gelinkt aan #289

**Comment by didiergonze** [comment]
Het is inderdaad opgelost

Groeten

Didier

**Comment by didiergonze** [comment]
Toch niet volledig:
er is nog een probleem tov de statistiek "Status Evaluator".  De proef die
een probleem had is niet geteld (23/04/2023)
Ook de proef van vandaag is niet meegeteld (maar misschien zijn de
statistieken alleen maar om de dag upgedated?)

Groeten

Didier

**Comment by ndsmyter** [comment]
Hallo @didiergonze ,
De statistieken worden telkens opnieuw berekend als je de pagina opent, dus daar lag het niet aan.
Maar er zat wel nog een foutje in onze berekening, waardoor je inderdaad de 2 proeven miste in jouw statistieken. Ik heb de berekening nu aangepast, dus dat zal binnenkort ook correct zijn.

Let op: De aangepaste code staat nog niet op de productie website, dus dat zal vermoedelijk pas voor binnen een paar dagen (of misschien zelf langer) zijn. We wachten elke keer tot de wijzigingen in de code groot genoeg zijn.

**Comment by didiergonze** [comment]
Bedankt.  Ik zal attent blijven.

Groeten

Didier

**Comment by didiergonze** [comment]
Statistics zijn nu OK
