### ISSUE TITLE
Ik kan geen nieuwe Apnea opleidingen activeren.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#298]
**Beschrijf de bug**
Ik kan geen enkele kandidaat 1*Apea inschrijven. 1*Pool is geen probleem maar 1*Apnea staat niet in de lijst (zie eerste screenshot) 
Ook niet als een kandidaat reeds als 1*Pool is ingeschreven (zie tweede screenshot) 

Dit is een belangrijk probleem want wij hebben nu 5 nieuwe kandidaten die starten voor een opleiding 1*Apnea 
BTW ik heb hetzelfde probleem voor 2*Apnea en ook daar hebben we 1 nieuwe kandidaat. 

**Verwachte resultaat**
Ik begrijp dat het vrijduiken niet op prio 1 staat maar deze is wel super belangrijk want de opleiding van deze vrijduikers ligt nu stil. Je zou pragmatisch gezien voorlopig alles kunnen toelaten en niet onmiddelijk het te verwachten 'treintje' implementeren,

**Screenshots**
![image](https://user-images.githubusercontent.com/121305742/235604139-535befab-fb46-45a4-b8cb-17528955638e.png)
![image](https://user-images.githubusercontent.com/121305742/235604161-df41d19e-72e4-40f6-96be-c2da755add47.png)

**Comment by ndsmyter** [comment]
@KWillemse ,
Dat was eigenlijk een heel stomme fout, de opleiding stond gewoon op inactief, waardoor er geen nieuwe opleidingen meer gestart konden worden. Bij deze gecorrigeerd en zou nu voor allebei de brevetten in orde moeten zijn.
