### ISSUE TITLE
[BUG] Niet mogelijk om DD1 toe te voegen aan een duik 

### ISSUE THREAD

**Issue by didiergonze** [Nelos-VZW/dives-2#299]
**Beschrijf de bug**
Bij het creëren van een duik met een 1*D kandidaat die zijn eerste open water duik doet, is het niet moglijk om de DD1 toe te voegen

**Stappen om te reproduceren**
1. Crëeren een duik
2. Voeg toe de kandidaat 1*D (die in order is tov van vereist voor DD1
3. Vraag om een prof toe te voegen: DD1 is niet zichtbaar, being alleen maar met DD1

**Verwachte resultaat**
DD1 zou selecteerbaar moeten zijn

** Workaround:
1. Ga naar kandidaat
2. Selecteer de kandidaat 
3. Ga naar open water duik : DD1 is zichtbaar en er is een knop "Aktiviteit aanmaken"   
4. creëren van daar de duik --> OK

**Screenshots**
Niet beschikbaar (was op mijn smartphone niet thuis) Met workaround kan ik niet meer reproduceren :-(

Groeten

Didier

**Comment by DIVEScoordinator** [comment]
DD1 staat in de selectielijst helemaal achteraan, zou het kunnen dat je het daarom niet hebt gezien (getest met een kandidaat van mijn club die nog zwembad proeven moet doen, dus alles staat daarom nog rood).

![image](https://user-images.githubusercontent.com/112652115/236561954-fb250ee6-61c1-4849-8568-682f77c4faf2.png)

@ndsmyter   volgorde van de proeven voor aftekenen ook logischer plaatsen (is uit productie data genomen)

**Comment by didiergonze** [comment]
Het is een mogelijkheid.   ik kan mij niet herinneren als ik tot op het
einde van de lijst gegaan ben of niet. ik denk van wel maar ben niet 100%
zeker.

ik heb niemand in de club exacte in de zelfde situatie. ik heb geprobeert
en kandidaat 1*D in dezelfde situatie in nelos te vinden maar het is niet
gemakkelijk....

nu er is een gemakkelijk workaround dus niet super belangrijk...

groeten

Didier
