### ISSUE TITLE
[BUG] scherm schuift niet correct achter linker menu-balk 

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#3]
**Beschrijf de bug**
Bij het openen van de pagina https://test.nelos.be/secretariaat/125 op een half computerscherm ; als je de horizontale scroll-balk verschuift van links naar rechts zijn er een aantal velden die achter de linker menu-balk schuiven. Sommige van deze velden zijn nog zichtbaar door deze menu-balk heen

**Stappen om te reproduceren**
1. Ga naar ['Scherm secretariaat'](https://test.nelos.be/secretariaat/125)
2. zet de webpagina op een half computerscherm (vertikaal gesplitst)
3. Scroll met de horizontale scroll-balk van links naar rechts
4. Zie fout

**Verwachte resultaat**
Deze velden zouden volledig achter de linker menu-balk moeten schuiven

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187540212-65296900-02b7-49c8-a6c5-7787994ba68c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 home
 - Browser chrome
 - Versie 105.0.5195.54 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
Ik heb deze ook al voorgehad, maar kon het dan dag later niet meer reproduceren. Zal het nog eens bekijken. Mogelijks 1 of andere randscenario. Of seen specifieke resolutie.

**Comment by ndsmyter** [comment]
@pieter-mouton ,
Ik heb deze zelf ook al eens gezien, maar kon die ook niet altijd reproduceren.
Ik had er toen ook een screenshot van gemaakt en doorgestuurd naar jullie, maar enkele dagen later kon ik niet meer reproduceren.

Misschien dat er toch iets mis is met een specifieke resolutie van het scherm?

++ @KimEndare

**Comment by ndsmyter** [comment]
@RubenDeSadeleer ,
Ik kan deze nu niet meer reproduceren, ik weet niet of het bij jou wel nog lukt?
Ik weet dat ik het soms wel en soms niet kan reproduceren, dus heel moeilijk om zeker te zijn dat het opgelost effectief is :-)

**Comment by RubenDeSadeleer** [comment]
![image](https://user-images.githubusercontent.com/112517511/190093143-ab655b19-b8f9-48d6-b77f-86cd7ec59e92.png)

@ndsmyter is nog steeds het geval; nu ook op mijn computer van het werk.

**Comment by ndsmyter** [comment]
Vreemd.
Ik heb zelf nu ook al op 2 toestellen geprobeerd, en kan het niet reproduceren. Nochtans ook Windows 10 en 11, met Chrome.

Ik zal het doorgeven aan Endare dat ze er eens naar kijken en misschien op basis van de screenshot iets kunnen afleiden.

**Comment by ndsmyter** [comment]
@RubenDeSadeleer ,
Kan je eens uw cache leegmaken? Want ik zie nu ook dat je nog "Beheer DE WATERTROLLEN & DUIVELS VZW" hebt staan in het menu. Dit terwijl we nu eigenlijk aangepast hebben door "Beheer " weg te laten.
Dus misschien kan dat de oorzaak zijn van het probleem, dat er nog bepaalde delen van de code verouderd in uw cache zitten.

**Comment by ndsmyter** [comment]
Lijkt opgelost nu
