### ISSUE TITLE
[BUG] Aftekenen vrijduik proef lukt enkel via brevetkaart kandidaat en niet via maak vrijduik activiteit

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#301]
**Beschrijf de bug**
Als je een vrijduik activiteit aanmaakt kunnen er geen proeven geselecteerd worden (24940 als voorbeeld). 
Als je via kandidaten deze kandidaat ophaalt en op zijn brevetkaart op 'vrijduik' klikt, kan je wel een activiteit aanmaken en de proef aftekenen
**Stappen om te reproduceren**
1. Ga naar '.VR-NELOS
2. Klik op 'maak vrijduik'
3. Scroll naar 'proef toevoegen'
4. Zie fout

**Verwachte resultaat**
Aftekenen van vrijduik proeven moeten ook via aanmaken van een activiteit kunnen en niet enkel via de brevetkaart

**Screenshots** 
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/c4ce78e2-4e9e-4d4b-ac3d-8f84f5b35442)

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/9a43b6c3-132c-4e4e-986e-5f5aee8fae40)
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/0e6bcabc-f533-4e8d-90a8-9744ddf10dcd)

via aanmaak activiteit en proeven toevoegen:
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/3fed3700-6bc6-4861-ba88-44e9513edd33)

**Comment by ndsmyter** [comment]
Probleem opgelost in productie.

Was nog een ontbrekend deel van de migratie dat ik blijkbaar niet gedaan had. Had dit getest geweest voor de migratie, dan had ik dit niet moeten oplossen.

**Comment by ndsmyter** [comment]
(zelfde aanpassing eerst gedaan op Test, als je eens wil proberen)
