### ISSUE TITLE
Proeven 2*APNEA niet beschikbaar

### ISSUE THREAD

**Issue by FrancescoVrijduik** [Nelos-VZW/dives-2#302]
**Beschrijf de bug**
Vrijduiken: Proeven van brevet 2*APNEA (Advanced Vrijduiker) niet beschikbaar bij activiteit Vrijduiken

**Stappen om te reproduceren**
1. Maak een Vrijduik activiteit aan
2. Voeg een buddy toe die kandidaat Advanced  (= 2*APNEA) is (bvb Robin Valgaeren)
3. Klik op Proeven Toevoegen
4. Je vindt niks. 

**Verwachte resultaat**
Ter vergelijking: als je een kandidaat Adventure (= 1*Apnea) toevoegt, vb Koen Willemse, zie je WEL zijn proeven. 
**Screenshots**
ik heb beide toegevoegd:
![image](https://github.com/Nelos-VZW/dives-2/assets/133043610/ddcec6d1-7608-46c3-b1b7-d76b08cec618)
![image](https://github.com/Nelos-VZW/dives-2/assets/133043610/e6a2c670-024a-46d5-900d-c6c9ab80386b)
![image](https://github.com/Nelos-VZW/dives-2/assets/133043610/8afe55cf-c378-4898-9426-ae7facb3aa88)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows 11 Enterprise
 - Browser: Chrome
 - Versie: 01/04/2020

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: CAT S52
 - Besturingssysteem: Android 10
 - Browser Chrome
 - Versie onbekend

**Extra informatie**
Ik heb denk ik de meeste Vrijduik brevetten getest daar lijkt alles in orde, het is enkel bij Advanced dat ik dit issue zie. Noteer: 1) bij dit brevet (zoals ook 1*Apnea daar werkt het echter WEL) is er GEEN onderscheid theorie/zwembad/Open Water, misschien dat de link met Vrijduik activiteit ontbreekt? 2) zie vorig issue Vrijduiken waar beide brevetten niet actief stonden 3) misschien dat Voorwaarde voor inschrijving 2*Apnea=1*Apnea zijn hier roet in eten gooit want met die voorwaarden hebben we in Dives 1.0 wat gesukkeld

**Comment by DIVEScoordinator** [comment]
Aanvullend: voor deze kandidaat via brevet gegaan en daar kan je wel een activiteit aanmaken en aftekenen (via TEST omgeving gecheckt om af te tekenen; in productie enkel om onderstaande te zien)

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/ba08ba96-55d1-41ed-9317-0d0ad8b80400)
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/f04e99c7-3fc6-464f-839f-874c85360921)

**Comment by DIVEScoordinator** [comment]
ook bij 1*apnea zijn proeven niet altijd zichtbaar.  Zie vorige github nummer met kandidaat als test, die komt nog steeds niet tevoorschijn bij het aanmaken van een activiteit terwijl dit wel voor Koen is. Kan het iets te maken hebben met datum van inschrijvinge?

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/579cdf69-3b1e-4c71-95d3-aa136e37042f)

**Comment by DIVEScoordinator** [comment]
@FrancescoVrijduik    Zou moeten opgelost zijn - kan je nog eens kijken aub.

**Comment by ndsmyter** [comment]
Ik sluit deze af, aangezien deze vermoedelijke opgelost.
