### ISSUE TITLE
Zichtbaarheid opleiding AI als 2*I

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#303]
Voor de opleiding Assistent Instructeur is de ene kandidaat (NelosId 40495, geen clublid) wel zichtbaar als 2*I NelosId 1312) maar een andere (NelosId 43865, eigen clublid) niet. Er komt de melding dat er geen rechten zijn om dit te bekijken.
Het lijkt persoonsgebonden want als 1*I (NelosId 13948) komen de brevetkaarten wel normaal naar voor.

**Stappen om te reproduceren**
Zoek kandidaten op via "kandidaten" op Dives

**Verwachte resultaat**
Brevetkaarten moeten openen op basis van wat je mag zien. Als 2*I zou je zicht moeten hebben op alle lopende opleidingen AI

**Screenshots**
Screenshots via chat 

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by DIVEScoordinator** [comment]
Ter info via Nelos secretariaat en mijn account allebei zichtbaar. Ook AI can mijn club zichtbaar.  Moet iets met instellingen in rechten te maken hebben?

**Comment by ndsmyter** [comment]
Blijkbaar werd er enkel gekeken naar de nog openstaande proeven, en of de gebruiker in kwestie daar dan rechten op had om die te zien. Jij (Carl) hebt daar wel rechten op omdat jij ook ledenadmin bent van je club (dacht ik), maar NELOS-1312 is dat dan vermoedelijk niet.

Ik heb nu de code aangepast zodanig dat alle proeven van alle open opleidingen in rekening wordt gebracht. Dat zou het probleem moeten oplossen.
