### ISSUE TITLE
[BUG] 25 scooter duiken voor opleidingen scooter instructeur tekenen niet automatisch af

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#305]
**Beschrijf de bug**
Een kandidaat SMI (33556) heeft via initialisatie 30 scooter duiken ingebracht maar het item 25 scooter duiken tekent niet af.

**Stappen om te reproduceren**
1. Ga naar 'kandidaat '
2. Klik op 'open brevetkaart van de betreffende kandidaat'

**Verwachte resultaat**
25 scooter duiken tekenen automatisch af.

Gevraagd of het via de OPLV kan om dit voorlopig zo op te lossen.  Wacht nog op antwoordt

**Screenshots**
I![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/bb667045-884a-462b-9b1f-d98464c0e89a)

**Comment by ndsmyter** [comment]
Deze zullen vanaf nu ook automatisch geteld worden
