### ISSUE TITLE
[BUG] Starten van opleidingen in test lukt niet 

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#306]
**Beschrijf de bug**
Om bepaalde testen te doen; vb. tekenen proeven van KDD kandidaat automatisch af als hij inschrijft voor 4*D, kunnen niet getest omdat er niet kan ingeschreven worden, ik krijg volgende foutmelding

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/a16e1cc8-5730-4722-837d-788cb6680d19)

**Comment by ndsmyter** [comment]
Probleem opgelost
