### ISSUE TITLE
Kan 4 ster opleiding

### ISSUE THREAD

**Issue by Tvpsaildive** [Nelos-VZW/dives-2#307]
Dag Nicolas, 

Proef bij kan 4sters wordt niet afgetekend bij het behalen van dhv. Dient door duikschoolverantwoordelijke te worden gedaan? 

Kan volume duikken niet meer zien die reeds behaald zijn of nog moeten gebeuren bij bv 20 duiken 40m. Vorige versie kon je de status zien van het aantal. Eveneens voor aantal duiken sinds kandidaat ... 

Gebruik android chrome. S20 full update.

**Comment by ndsmyter** [comment]
Hallo @Tvpsaildive ,

Momenteel moet de opleidingsverantwoordelijke nog een vrijstelling geven voor de DHV opleiding. We gaan hier ook nog wel een automatische controle voor voorzien, maar dat is momenteel nog niet uitgewerkt. Maar staat wel op onze planning.

Wat betreft de voortgang van voorwaarden waarbij je er X moet behalen, daar zijn er ook nog aanpassingen voor nodig. Die staan ook al gepland en gelogd onder #209 

Ik laat deze open staan, voornamelijk voor het eerste punt ivm 4*D en DHV. Als dat uitgewerkt is, zal ik deze taak afsluiten.

**Comment by Tvpsaildive** [comment]
Top badankt!


Op ma 19 jun. 2023 21:25 schreef Nicolas De Smyter ***@***.***
