### ISSUE TITLE
[BUG] mijn profiel/overzicht duiken niet correct 

### ISSUE THREAD

**Issue by wim-** [Nelos-VZW/dives-2#308]
Als ik naar het overzicht van mijn duiken ga kijken zie ik 18 zeeduiken >=25m terwijl dit er 36 zouden moeten zijn.
Ik heb niet ergens specifiek 18 duiken gedaan die eruit springen, ik kan dus niet direct zeggen waar dit aan zou kunnen liggen.
De 36 duiken zijn de volgende:
<html>

<body link="#0563C1" vlink="#954F72">

nummer | datum | diepte | plaats
-- | -- | -- | --
109 | 14/09/2019 | 30 | NL   - OS - Wemeldinge Parking
110 | 23/09/2019 | 30 | EG   - El Quesir
111 | 23/09/2019 | 30 | EG   - El Quesir
113 | 24/09/2019 | 26 | EG   - Marsa Alam
114 | 24/09/2019 | 27 | EG   - Marsa Alam
116 | 25/09/2019 | 30 | EG   - Marsa Alam
118 | 26/09/2019 | 30 | EG   - Marsa Alam
119 | 26/09/2019 | 30 | EG   - Marsa Alam
120 | 26/09/2019 | 30 | EG   - Marsa Alam
122 | 27/09/2019 | 26 | EG   - Marsa Alam
125 | 28/09/2019 | 30 | EG   - El Quesir
126 | 28/09/2019 | 29 | EG   - El Quesir
127 | 28/09/2019 | 29 | EG   - Marsa Alam
128 | 29/09/2019 | 26 | EG   - Marsa Alam
131 | 5/10/2019 | 30 | NL   - OS - Wemeldinge Parking
152 | 21/03/2020 | 25 | MX   - Cancún
163 | 19/07/2020 | 25 | NL   - OS - Den Boer
168 | 8/08/2020 | 30 | NL   - OS - Wemeldinge Parking
179 | 10/09/2020 | 30 | NL   - OS - Vuilnisbelt
180 | 12/09/2020 | 27 | NL   - OS - Galjoen zonder Poen
231 | 16/05/2021 | 27 | NL   - OS - Wemeldinge Tetjes
236 | 30/05/2021 | 30 | NL   - OS - Wemeldinge paal 1602-1603
244 | 26/06/2021 | 29 | NL   - OS - Stavenisse - Oostnol
248 | 10/07/2021 | 30 | NL   - OS - Gorishoek De Punt
253 | 18/07/2021 | 27 | NL   - OS - Vuilnisbelt
254 | 21/07/2021 | 30 | NL   - OS - Vuilnisbelt
263 | 5/08/2021 | 30 | NL   - OS - Vuilnisbelt
279 | 11/09/2021 | 30 | NL   - OS - Goes Putti's Place
309 | 29/05/2022 | 40 | NL   - OS - Wemeldinge Parking
313 | 18/06/2022 | 38 | NL   - OS - Wemeldinge Tetjes
320 | 21/07/2022 | 30 | NL   - OS - Vuilnisbelt
328 | 10/09/2022 | 27 | NL   - OS - Vuilnisbelt
351 | 12/11/2022 | 40 | NL   - OS - Wemeldinge Parking
362 | 22/11/2022 | 30 | TZ   - Zanzibar
368 | 3/12/2022 | 37 | NL   - OS - Wemeldinge Parking
376 | 10/04/2023 | 26 | NL   - OS - Den Boer

</body>

</html>

Ik zie ook maar 16 nitrox duiken staan ipv 19.
<html>
<body link="#0563C1" vlink="#954F72">

nummer | datum | diepte | plaats
-- | -- | -- | --
34 | 9/10/2018 | 15 | BE   - Dongelberg
35 | 9/10/2018 | 20 | BE   - Dongelberg
246 | 3/07/2021 | 19 | NL   - NZ - Christiaan Huygens
247 | 4/07/2021 | 27 | NL   - Boschmolenplas
313 | 18/06/2022 | 38 | NL   - OS - Wemeldinge Tetjes
314 | 22/06/2022 | 19 | BE   - put van Ekeren
315 | 28/06/2022 | 40 | BE   - Dongelberg
318 | 19/07/2022 | 20 | BE   - Dongelberg
319 | 19/07/2022 | 30 | BE   - Dongelberg
323 | 23/08/2022 | 30 | BE   - Dongelberg
329 | 13/09/2022 | 30 | BE   - Dongelberg
331 | 25/09/2022 | 30 | BE   - Dongelberg
333 | 4/10/2022 | 30 | BE   - Dongelberg
334 | 5/10/2022 | 15 | BE   - put van Ekeren
335 | 7/10/2022 | 30 | DU   - Kreidesee - Einstieg 5
336 | 7/10/2022 | 19 | DU   - Kreidesee - Einstieg 1
337 | 8/10/2022 | 19 | DU   - Kreidesee - Einstieg 0
340 | 8/10/2022 | 22 | DU   - Kreidesee - Einstieg 1
341 | 9/10/2022 | 30 | DU   - Kreidesee - Einstieg 3
</body>

Ik denk dat er ook 1 bootduik teveel opstaat (maar die houd ik in mijn excel file niet apart bij).

Mijn nelos email is wim.uytterhoeven@gmail.com
Mijn nelosnummer is 47476

Als je meer info nodig hebt, geef dan maar een seintje.

Groeten,

Wim

**Comment by ndsmyter** [comment]
@wim- 
Als ik nu kijk naar uw tellers, dan zie ik dat er 39 duiken geteld worden voor "Zeeduiken >=25m", dus ik ga er van uit dat dit probleem ondertussen opgelost is. Er was in elk geval wel iets verkeerd met de tagging van sommige duikplaatsen, dat recent opgelost werd en dit probleem dus zou kunnen veroorzaakt hebben.

Aangezien deze rapportering nu niet zo prioritair was, is dat wel beetje blijven liggen.

Ik ga deze afsluiten aangezien het mij lijkt opgelost te zijn. Laat gerust weten moest er toch nog iets zijn.

**Comment by wim-** [comment]
Hallo,

Ik heb nochtans sinds 10 april geen >25m duiken gedaan
Het totaal zou dus nog altijd 36 moeten zijn....


Wim

Op ma 19 jun 2023 om 21:34 schreef Nicolas De Smyter <
***@***.***>:

**Comment by DIVEScoordinator** [comment]
sluiten deze af want basis probleem is opgelost met herbekijken tagging duikplaatsen.
