### ISSUE TITLE
[Feature] Notificaties in email/app

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#309]
Het lijkt me wel handig om de notificaties, die vandaag achter het belletje zitten ook te kunnen ontvangen in je emailbox.
Er zou dan ook wel de mogelijkheid moeten bestaan om opt-in/out voor deze functionaliteit.

Voordeel is dat je als duiker/instructeur sneller op de hoogte gebracht wordt van activiteiten.

Bijkomende feature zou zijn dat de app native notificaties kan verzenden, en het icoon het bijhorende (x) meldingen krijgt.

**Comment by ndsmyter** [comment]
Deze functionaliteit staat reeds gepland, maar heeft de boot van DIVES 2.0 net gemist. We zijn bezig om deze uit te werken, maar heeft nog een paar wijzigingen nodig om echt in productie gebruikt te worden. We willen zeker zijn dat we niet te veel, maar ook niet te weinig mails gaan sturen :-)

Deze functionaliteit is dus onderweg.

Als deze functionaliteit er is, zal ik deze taak afsluiten.

**Comment by ndsmyter** [comment]
Vanaf de huidige versie zou je normaal gezien mails moeten krijgen.
Je moet de mails wel eerst zelf activeren via Profiel > Instellingen.

Moest je de knop Instellingen nog niet zien, vergeet dan zeker niet eerst eens de cache van je browser leeg te maken. Meestal kan dat met de toetsenbordcombinaties Ctrl+Shift+R of Ctrl+F5 op je toetsenbord.
