### ISSUE TITLE
[Feature] extra witregel boven tijd en diepte indicatie

### ISSUE THREAD

**Issue by IngeVerding** [Nelos-VZW/dives-2#31]
als je nu een duik logt met lange plaatsnaam of veel duikers komt de data zeer dicht op mekaar
Lijkt me mooier dat er altijd een witregel boven staat
Onder het motto een beeld zegt 1000 keer meer dan woorden:
![image](https://user-images.githubusercontent.com/112573476/188182268-4140702b-45ff-4e79-b670-fa8dd1d012a9.png)

links is niet mooi, midden is beter

**Comment by ndsmyter** [comment]
Volledig terecht. Heb deze bug net toevallig ook deze middag doorgestuurd naar Endare. Als ik mij niet vergis, hebben ze zelf ook al iets aan gedaan. Ik moet nog eens bekijken.

**Comment by ndsmyter** [comment]
Ze hadden het zogezegd opgelost, maar het lijkt nog steeds een probleem te zijn.

Ook Lutgart meldt het probleem op haar iPhone:
![image](https://user-images.githubusercontent.com/648669/189870196-40564ca5-24f9-403f-92ff-02b57005d9ea.png)
