### ISSUE TITLE
[BUG] Tags worden niet correct getoond GND proeven

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#310]
**Beschrijf de bug**
Sommige tags (pills) zijn leeg bij GND proeven

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/2fec857b-650d-474c-9438-8323782633b1)

**Comment by ndsmyter** [comment]
Dit probleem zou ondertussen opgelost moeten zijn. Mogelijks niet voor alle meldingen in het verleden, maar wel voor toekomstige meldingen.
