### ISSUE TITLE
[BUG] Aantal duiken sinds 2*D niet correct indien deze via initialisatie gebeurd zijn.

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#311]
**Stappen om te reproduceren**

1. Duiker (44378) heeft 2* brevet behaald op 25/09/2017
2. Duiker heeft initialisatie gedaan in dives in 2019
3. Sinds DIVES zijn er "slechts"  27 duiken gelogd in DIVES
4. Hierdoor staat de teller incorrect op 27

Ik begrijp dat dit komt omdat je bij de initialisatie niet weet WANNEER je de duiken gedaan hebt, deze kunnen immers voor 2*D of na 2*D gedaan worden.

**Verwachte resultaat**

* Bij de initialisatie een teller toevoegen die zegt: "Aantal duiken sinds het behalen van 2*D"

Momenteel zijn we geholpen door aan de opleidingsverantwoordelijke te vragen om dit via een vrijstelling af te tekenen.

**Comment by ndsmyter** [comment]
We gaan dergelijke zaken via vrijstelling laten gebeuren
