### ISSUE TITLE
Verwijderen nog af te tekenen proeven

### ISSUE THREAD

**Issue by FrancescoVrijduik** [Nelos-VZW/dives-2#312]
De lijst  'nog af te tekenen proeven' is niet logisch door de opzet Activiteit--> proef--> kandidaat

VOORBEELD: 
Ann en Lies zijn beiden kandidaat 1*Apnea. Beiden moeten proef CWT en FIM nog afleggen. Tijdens een sessie legt Ann FIM af en Lies doet CWT. Instructeur maakt sessie aan en voegt CWT en FIM toe, omdat deze bij beide kandidaten open staat woren er dus 4 open proeven aangemaakt. Daar worden er us 2 van afgetekend, maar de andere blijven open staan a;s 'nog af te tekenen'. Dit is voor ALLE activiteiten met meerdere  kandidaten voor hetzelfde brevet een probleem, indien ze niet allemaal dezelfde proef afleggen. 

Kan opgelost worden door per combinatie proef en kandidaat ook de mogelijkheid te voorzien 'niet uitgevoerd' of 'niet van toepassing',of 'negeer proef' oid,  en die waarde dan ook weg te filteren bij lijst af te tekenen proeven. Nu lopen we het risco dat er proeven per vergissing onterecht gaan worden afgetekend.

Alternatieven:
1) aparte sessies aanmaken maar dat is heel onoverzichtelijk, en dat gaat ook dubbeltellingen geven
2) bij SELECTIE proeven, enkel de kandidaten aanduiden die deze proef hebben gedaan
3) per kandidaat kunnen kiezen welke proef (dus volgorde omdraaien; eerst activiteit dan per buddy alle proeven APART kunnen selecteren, eventueel keuze 'koppel aan buddy' of 'koppel aan activiteit'. BVB voor theorie is huidig systeem van koppelen aan activiteit HEEL HANDIG!!!

![image](https://github.com/Nelos-VZW/dives-2/assets/133043610/7d7a7782-3ca4-4f73-a0e0-f0aab17ac813)

**Comment by DIVEScoordinator** [comment]
Beste, die mogelijkheid is voorzien in het systeem.  Dit staat ook vermeld op de help pagina.
Je kan bij elke proef de kandidaten die niet aan de proef hebben deelgenomen wegklikken.

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/c78c7b28-9f04-432a-b5c3-3413662edfba)
