### ISSUE TITLE
[BUG] Eenheden dicht bij de waarden.

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#313]
**Beschrijf de bug**
(via mail ontvangen)

Ik was zelf even in de war bij het invullen van een duikactiviteit. Ik vind dat de eenheden te dicht bij het volgende onderdeeltje staan.
Nu lijkt het dat men vraagt naar de minimum diepte. Misschien zijn het enkel mijn gedachten die van die gekke kronkels maken natuurlijk.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/648669/9cfe4aab-cead-499d-a922-adf1faf87bd3)

**Comment by DIVEScoordinator** [comment]
aangepast in de komende release
