### ISSUE TITLE
Wanneer ik een vrijduik of BND opleiding start, een instructeur selecteer en dan registreer, krijg ik een foutmelding

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#314]
**Beschrijf de bug**
Ik heb een 4 tal vrijduikers een opleiding 1*Pool en Adventure (1*Apnea) gestart. Ik heb telkens de 2 tesamen geselcteerd en voor beide heb ik 'Eric De Graef' gekozen. Als ik op Registreer klik, krijg ik een foutmelding (zie screenshot) maar de registratie is uiteindelijk wel gelukt. 
Ter info, ik heb het ook met BND ook voor met mezelf als instructeur.

**Stappen om te reproduceren**
1. Ga naar een vrijduik lid zonder opleidingen
2. Klik op 'start een opleiding'
3. By default staat de DSL geselecteerd, ik kies voor beide 'Eric De Graef'.
4. Klik op Registreer
5. Zie fout

**Verwachte resultaat**
Geen foutmelding

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/d80144fe-ec72-435b-8666-8df703a4a42d)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/f3cf75c1-178a-481a-8490-1e5e2cbaed96)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Win10 21H2
 - Browser: Firefox 102.11.0esr (32-bit)

**Comment by ndsmyter** [comment]
Probleem zou nu opgelost moeten zijn in de versie die binnen paar minuten klaar staat.
