### ISSUE TITLE
Grotduiken werden niet mee gemigreerd en tellen ook niet verder op

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#315]
**Beschrijf de bug**
We hebben een lid die veel aan grotduiken doet. Hij had zelfs voor DIVES 1.0 verschillende duikplaatsen door Ivo Madder laten toevoegen, inclusief de 'tag' voor grotduiken. Na de migratie, staat zijn teller nu op 0 (zie eerste screenshot), dus de grotduiken van DIVES 1.0 zijn niet correct gemigreerd. (Je kan wel zien dat hij zelf nog een persoonlijke tag bijhoud met het aantal grotduiken en uren, tevens ook voor sidemount)
Daarnaast blijft hij grotduiken uitvoeren (zie tweede screenshot) en ook deze duiken tellen niet verder op. 

**Verwachte resultaat**
De duikplaatsen met een 'tag' voor grotduik, terug van deze tag voorzien zodat ze terug meetellen
Marc De Hoon, NELOS-ID: 46524

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/1ebf8a99-b30f-4eb0-8b13-8a5896aec4cb)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/1313c16c-709c-4443-a160-77ea001c6e56)

**Comment by ndsmyter** [comment]
Dat zou nu beter moeten zijn. De tagging van DIVES 1 is totaal anders dan die van DIVES 2, waardoor ook niet alles zomaar 1 op 1 overgenomen kon worden.

**Comment by KWillemse** [comment]
Klopt. De grot-duikplaatsen die nelos kent worden nu mee opgeteld.
