### ISSUE TITLE
Proef aanpassen in bestaande activiteit, als de opleiding nadien werd geactiveerd geeft bizarre melding.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#316]
**Beschrijf de bug**
Ik heb een week geleden een theorieles BND gegeven aan nieuwe K1sterD/BND, een opfrissing voor 2 K1sterD/BND en een nieuwe Kandidaat BND (die reeds 2ster is).
Ik had de activiteit reeds gemaakt en de proeven toegevoegd voor de nieuwe nieuwe K1sterD/BND. 
Voor de opfrissing voor 2 K1sterD/BND was geen proef nodig (reeds vroeger uitgevoerd)
Voor de nieuwe Kandidaat BND (die reeds 2ster is) kon ik geen proef toevoegen omdat de opleiding nog niet was gestart.
=> zie screenshot 1
Vandaag heb ik deze gestart en wilde ik de proef toevoegen, maar ik kreeg een 'grayed out' en een melding 'proef reeds ge-evalueerd'.
=> zie screenshot 2
als ik op toch op aanpassen klik wordt de proef wel juist toegeveogd en ik kan ze goedkeuren.
=> zie screenshot 3

**Stappen om te reproduceren**
1. Acitivteit aanpassen
2. Proef aanpassen
3. ik zie de juiste proef voor de juiste kanidaat maar wel 'grayed out' en een melding 'proef reeds ge-evalueerd'.
4. 'Aanpassen' kiezen, proef word juist toegevoegd.

**Verwachte resultaat**
Ik verwacht de proef in het zwart, misschien de 'checkbox' grayed out, maar zeker geen melding 'proef reeds ge-evalueerd'.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/accb0f1b-b251-4b4b-960b-2f7fb8dcbafb)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/aef63dfd-dded-4a93-b3c7-5a68e698caab)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/3be99512-e021-44d1-aad1-596fc109ade9)

**Comment by DIVEScoordinator** [comment]
Hier zou beter een melding komen 'proef als geselecteerd' omdat automatisch een proef aan alle deelnemers in een 'activiteit' die kunnen deelnemen wordt gekoppeld ook als later de brevetkaart komt.  Je moet al over het geheel hooveren om de opmerking te zien.  Vermits het in het grijs kwam staan heb ik gewoon 'aanpassen' geselecteerd en kreeg ik geen opmerking.  Iets om mee te nemen in verbeteren van de diverse meldingen in DIVES 2.2 (2024)

**Comment by ndsmyter** [comment]
Volgens mij zou dit nu beter moeten werken. Ik sluit deze dus af.

Indien je denkt dat dit toch nog niet goed werkt, mag je gerust heropenen. Maar zet er dan ook graag nog even bij waarom het nog niet goed werkt :-)
