### ISSUE TITLE
Enhancement - mogelijkheid voorzien om aanpassingen te doen aan niet-NELOS buddy

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#317]
Momenteel kunnen niet-nelos Buddies niet verwijderd noch aangepast.  Dit moet op termijn voorzien worden.

**Comment by AndreVanhecke** [comment]
Zou idd een mogelijkheid moeten zijn om dit aan te passen en/of te verwijderen.
Welke termijn zie hiervoor haalbaar?

**Comment by DIVEScoordinator** [comment]
zal niet voor op korte termijn zijn - low priority

**Comment by DIVEScoordinator** [comment]
Werkt in test mode.
