### ISSUE TITLE
[Feature] Lijnview als preference instellen

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#319]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Momenteel is de standaard view de tegelview.  Kan dit aangepast worden dat het ook lijnview kan zijn en dat dit behouden wordt en ook terug aangepast naar tegelview.

**Beschrijf de oplossing die je zou willen**
Je kan hier een korte en bondige beschrijving geven van wat je zou willen dat er gebeurt.

**Beschrijf alternatieven die je overwogen hebt**
Je kan hier een korte en bondige beschrijving geven van wat je verder nog overwogen had.

**Extra context**
Je kan hier eventueel context opgeven, of screenshots om de nieuwe functionaliteit duidelijk te maken.

**Comment by jenno-verdonck** [comment]
Duplicaat van #216 ?

**Comment by ndsmyter** [comment]
Inderdaad duplicate van #216 . Ik sluit deze af
