### ISSUE TITLE
[BUG] Foto's niet volledig overgenomen-geen placeholder's

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#32]
**Beschrijf de bug**
Bij het opzoeken van buddy hebben een aantal mensen geen foto; bij deze personen komt er een no picture placeholder

Het ophalen van de image ([https://test.nelos.be/api/user/9397/image.png?_=0.8881246006535659](https://test.nelos.be/api/user/9397/image.png?_=0.8881246006535659)) geeft volgende fout terug
```
{
status: 500,
error: "No avatar found"
}
```

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Maar nieuwe duik
2. Zoek naar buddy
3. Zie fout

**Verwachte resultaat**
Of een placeholder voor de personen die geen foto hebben.
Of oplossen van migratieprobleem zodat iedereen een foto heeft

**Screenshots**
![image](https://user-images.githubusercontent.com/8513610/188266395-88b6af33-c54f-4eed-be7e-cf60ab8a8e75.png)

**Comment by ndsmyter** [comment]
Probleem zou normaal gezien maandag opgelost moeten zijn bij een nieuwe deploy
