### ISSUE TITLE
[BUG] Brevetkaart zilveren dolfijn heeft bij zwembad vermelding van bronzen dolfijn

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#320]
Bij een kandidaat zilveren dolfijn vermeldt de brevetkaart bij zwembad "BD" i.p.v. "ZD"

**Stappen om te reproduceren**
1. Open 'brevetkaart van een kandidaat zilveren dolfijn' 
2. Zie fout

**Verwachte resultaat**
Bij zwembad: vermelding "Zwembad ZD" i.p.v. "Zwembad BD"

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/115356929/af51dab0-ea82-4bfd-809e-7a007024c4f8)

**Comment by ndsmyter** [comment]
Goed opgemerkt. Bij deze opgelost.
