### ISSUE TITLE
[BUG] Zwembad activiteit bij AI kan enkel via vrijstelling maar niet via activiteit afgetekend

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#322]
**Beschrijf de bug**
Bij kandidaat met NELOS nummer 26452kan je al DO-NELOS wel zwembadlessen aftekenen. Via activiteit zie je enkel zwembad examen.  

**Stappen om te reproduceren**
1. Ga naar 'brevetkaart en kijk welke zwembadlessen nog open staan
2. Klik op 'maak zwembad activiteit'
3. Scroll naar 'proeven toevoegen'
4. Zie fout

**Verwachte resultaat**
JAlle nog open zwembad proeven moet je via activeit kunnen selecteren. Wat wel vreemd is dat hier wel al de 10de stageles als evaluatie is afgetekend, die kan normaal pas nadat de rest is afgetekend.  Mogelijks een migratie issue?

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/8bb3271d-de60-43c4-92a4-02f9c4a5902b)
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/7a1edbaa-ba74-4429-829c-5a9a2d386a7e)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Deze werkt volgens mij wel OK. Ik zie dat er nog proeven open staan als Theorie, die eerst afgevinkt moeten worden vooraleer het zwembadexamen in orde kan gemaakt worden.

Dit werd ook al via mail gestuurd naar de persoon die de vraag origineel stelde.
