### ISSUE TITLE
[BUG] Duiken dubbel getoond

### ISSUE THREAD

**Issue by WebMaster-Acuatica** [Nelos-VZW/dives-2#324]
**Beschrijf de bug**
Duiken worden dubbel getoond (zowel in card view als in lijst view, op laptop als smartphone)

**Stappen om te reproduceren**
1. In het logboek : pas een filter toe
2. Toegepaste filter resetten

**Verwachte resultaat**
Alle duiken terug zichtbaar (zonder dubbele weergave).

**Workaround**
pagina refreshen

**Screenshots**
![Schermafbeelding Dives 2023-06-07 (duiken dubbel)](https://github.com/Nelos-VZW/dives-2/assets/48988353/1bad9e29-9b00-4638-abf8-458e91fae1bd)

**Comment by DIVEScoordinator** [comment]
Idem als github #195 dat al bij ENDARE zit.  Daarom wordt deze gesloten
