### ISSUE TITLE
Persoonlijke tags zijn niet zichtbaar op Win10, Chrome 91, wel op mijn app

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#325]
**Beschrijf de bug**
In de app zie ik bij "mijn profiel alle type duiken EN onderaan ook de samenvatting van mijn persoonlijke tags. Op de laptop zie ik de persoonlijke tags niet staan. Op de laptop valt ook de bovenste lijn (logboek) onder de blauwe balk.  

**Verwachte resultaat**
Ik wil mijn persoonlijke tags ook zien op de laptop.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/f76d0c48-4037-4e75-904c-eafd539d9351)

**Desktop (indien mogelijk aanvullen):**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/350f5e46-f5e1-4e35-accc-9788f84a359d)
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/72fa23eb-baba-4112-aa77-e4deec971c5b)

**Smartphone (indien mogelijk aanvullen):**

**Comment by ndsmyter** [comment]
Hey @KWillemse ,
Dat lijkt me eerder een probleem met cache. Dus je zal eens moeten geforceerd proberen vernieuwen. Ctrl+Shift+R kan mogelijks helpen.

Ik merk ook op dat de versie van Chrome wel al wat ouder is. Dus ofwel moet je eens de updates lopen, ofwel test je dit op een computer van je werkgever. In het tweede geval kan het zijn dat er daardoor ook andere regels zijn die de website impacteren, waar wij niet zo heel veel aan kunnen doen.

Ik sluit deze af, want dit valt niet te reproduceren.

**Comment by ndsmyter** [comment]
Is dit probleem nog steeds in de laatste nieuwe versie? Zorg zeker dat je een cache clear doet. In Chrome idealiter zelf met een force reload nadien. Met Ctrl+Shift+R of iets gelijkaardig is dat eigenlijk nog niet helemaal.

Je kan dus best eens testen in een private window.
Of de developer console openen via de settings, en dan op de Reload knop rechts klikken om dan te kiezen voor de keuze die alles verwijdert en gaat herladen (onderste optie)
