### ISSUE TITLE
[BUG] Opleiding discovery apnea diver

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#327]
**Beschrijf de bug**
Er kan niet ingeschreven worden voor de opleiding discovery apnea diver. Ik vind ook niemand in het systeem terug die een lopende opleiding heeft. Kan het zijn dat deze niet mee gemigreerd is of niet openstaat?  Ze stond wel in de Excel DIVES 1 dus is ooit aangemaakt.

**Stappen om te reproduceren**
1. Ga naar 'VR NELLS
2. Klik op '.kandidaten
3. Kies voor discovery
4. enkel pool is zichtbaar

**Verwachte resultaat**
opleiding kan geselecteed worden
**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/56c55915-ad27-4268-98fc-fdf023882f6e)

**Comment by ndsmyter** [comment]
De opleiding "Discovery Vrijduiker" (code D-APNEA) werd blijkbaar "uitgeschakeld" gemigreerd van DIVES 1 naar DIVES 2. Ik heb eens nagekeken en er zitten nochtans wel proeven onder:
![image](https://github.com/Nelos-VZW/dives-2/assets/648669/43b2d010-7a8e-4474-b8ce-67d3c53873dc)

Dus waarom die voorheen uitgeschakeld was kan ik zelf niet achterhalen, maar ik kan ze wel aanzetten. Wat ik dus nu wel gedaan heb. Normaal gezien zou je die nu wel moeten kunen zien.
