### ISSUE TITLE
[Feature] Excel download mogelijkheid per club in afwachting van rapportage module

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#328]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
voor begeleiding van kandidaten is het nu te omslachtig om telkens de brevetkaart te moeten openen
Daarom zouden we graag van deze lopende opleidingen weten wanneer ze gaan vervallen en ook van alle proeven wanneer ze gaan vervallen en vooral diegen die nog niet werden uitgevoerd. ..]

**Beschrijf de oplossing die je zou willen**
Zou het niet mogelijk zijn om dit als pragmatische tijdelijke oplossing aan te bieden. Dat bijvoorbeel een club een paar keer per jaar zo'n lijst mag opvragen (via mail of zo) of dat er een 'Exporteer' knop komt met 1 query erachter  die alle lopende opleidingen en proeven met verval data exporteert. Filteren kunnen we dan zelf wel doen in Excel. 

Indien jullie dit idee niet zien zitten voor alle clubs, zouden wij,dan toch uitzonderlijk eens éénmalig deze lijst kunnen ontvangen. 
Als wij dat moeten uitzoeken voor al onze lopende opleidingen moeten we 66 keer een 'opleidingskaart opendoen', Klikken tot we de proeven zien, alles noteren, teruggaan naar het club beheer en terug opnieuw filteren. Even opgeteld, dat is in totaal '528' keer klikken. 

**Beschrijf alternatieven die je overwogen hebt**
Je kan hier een korte en bondige beschrijving geven van wat je verder nog overwogen had.

**Extra context**
Je kan hier eventueel context opgeven, of screenshots om de nieuwe functionaliteit duidelijk te maken.

**Comment by ndsmyter** [comment]
Een Excel download is ook redelijk wat werk, dus ik denk dat het beter is om de energie in de rapportage te steken en niet nog tussentijdse Excel downloads te gaan voorzien. Denk dat we dan beter dan al een kleinere rapportage voorzien, dan onze energie te steken in Excel downloads.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   ok misschien dan een gefaseerde rapportage tool opstellen

**Comment by ndsmyter** [comment]
Dit zou sinds deze namiddag via "Profiel" van de DSV or Ledenadministrator beschikbaar moeten zijn.
We gaan dit binnenkort verplaatsen naar de knop "Rapportering", alsook mogelijks extra statistieken aanleveren via een betere rapporteringstool.
