### ISSUE TITLE
[BUG] Verkeerd aantal gelogde duiken in opleiding vs. statistieken

### ISSUE THREAD

**Issue by Calinatus** [Nelos-VZW/dives-2#329]
Aantal duiken 10-20 m onder "Opleiding" (voor 2*D althans) stemt niet overeen met het aantal bij de statistieken.

Overigens worden duiken gelogd op 20 m hier niet bij meegeteld.

![FIG1](https://github.com/Nelos-VZW/dives-2/assets/133597620/5a91a016-8617-45ca-98b0-51538524378e)

![FIG2](https://github.com/Nelos-VZW/dives-2/assets/133597620/d029f6a8-d13d-45bf-8567-cc57953ce202)

**Comment by ndsmyter** [comment]
@Calinatus ,
Ik zal dit nog wel eens verder bekijken in de code ook, maar zou het kunnen zijn dat het verschil te maken heeft met de "Open water" voorwaarde? Want een duik in bijvoorbeeld Nemo33 telt niet mee als een "Open water" duikplaats. Dus in de eerste screenshot zou die niet meetellen, maar in de 2e wel.

Kan zijn dat het effectief een fout is in de berekening, maar ik denk dat we dit nochtans goed getest hebben :-)

**Comment by Calinatus** [comment]
> @Calinatus , Ik zal dit nog wel eens verder bekijken in de code ook, maar zou het kunnen zijn dat het verschil te maken heeft met de "Open water" voorwaarde? Want een duik in bijvoorbeeld Nemo33 telt niet mee als een "Open water" duikplaats. Dus in de eerste screenshot zou die niet meetellen, maar in de 2e wel.
> 
> Kan zijn dat het effectief een fout is in de berekening, maar ik denk dat we dit nochtans goed getest hebben :-)

Hoi Nicolas, bedankt alvast voor de input. Nee hoor, alle openwaterduiken waren wel degelijk in open water, dus er moet ergens op een of andere manier toch een foutje in geslopen zijn.

Kunnen de intervallen van de dieptezones overigens aangepast worden zodat de grenswaarden geïncludeerd worden? Zo heb ik bv. 2 duiken gelogd op 20 m diepte, die dan in 20-30 m terechtkomen, en niet meetellen voor de vereiste van 15 duiken op 10-20 m. Op zich geen probleem met het aantal duiken dat nog komen zal, maar kan wel vervelend worden naarmate de vereisten strenger worden bij hogere brevetten.

**Comment by DIVEScoordinator** [comment]
we sluiten deze af.  twee redenen dat dit afwijkend is:
- recent nog aanpassing gedaan aan steengroeves die niet meetelde voor aantal duiken 2*D
- duiken op 20m tellen wel degelijk mee voor 2*D voorwaarde maar staan niet in de statistieken 10-20 m omdat daar begrensd wordt tot 19,99m (statistieken is van tot en niet van tot en met).
