### ISSUE TITLE
[Feature] Omwisselen diepte-tijd

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#330]
In de papieren logboekjes staan de kolommen van diepte en tijd omgekeerd als op de pagina bij het invullen van een nieuwe duik.
Veel mensen vullen nog steeds de papieren boekjes in aan de waterkant, en vullen Dives op een later moment in.
Bij het overnemen van de data van het logboekje naar de dives kan dit fouten opleveren doordat deze in een andere volgorde staan.

**Beschrijf de oplossing die je zou willen**
Omwisselen van de velden bij het aanmaken van een nieuwe duik om de volgorde van de papieren boekjes te volgen

**Comment by ndsmyter** [comment]
Dit werd al paar keer gemeld. Maar persoonlijk (en nog andere mensen delen die mening) vind ik het logischer in de mond als je eerst de tijd en dan diepte hebt. Dus "x minuten op y meter".

Dus deze gaat waarschijnlijk niet uitgevoerd worden, want ik vind persoonlijk niet logisch. En het is ook niet de bedoeling dat we de duikboekjes gaan 1 op 1 overnemen.

**Comment by dr-zone** [comment]
Wat dan wel als extra feature kan toegevoegd worden is dat er een waarschuwing word gegeven als er gedoken wordt buiten de limieten van het laagste brevet in de ploeg. bvb een 2*D ipv 60min op 30m, 30min op 60m ingeeft. En hierdoor kunnen fouten vermeden worden.
