### ISSUE TITLE
Kan de tooltip bij het starten van een opleiding weggelaten worden

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#332]
**Beschrijf de bug**
Als ik een opleiding wil starten als ledenadmin, dan krijg je een tool tip als je met de muis over het groene checkmark beweegt. Deze tooltip val over de checkbox die je wil aanvinken. Ik heb zonet 12 'compressor operator' opleidingen geactiveerd en 12 keer heeft die tooltip mijn ingave 'vertraagt'.

**Stappen om te reproduceren**
1. in het club beheer, kies één van de leden
2. start een opleiding 
3. probeer een opleiding te activeren, de tool tip verschijnt snel in beeld.

**Verwachte resultaat**
Een tool tip die een groene checkmark verduidelijkt is volgens mij overbodig. Ofwel weglaten ofwel pas tonen nadat je enkele seconden blijft staan met de muis op die check mark.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/946470b1-3e3a-4513-9710-a64b370b7b46)

**Comment by ndsmyter** [comment]
We vinden het belangrijk dat we op een deftige manier informeren wat alles wil zeggen, hier hebben we dat met tooltips gedaan (ipv een legende dat toch wel iets lelijker is). Dus ik ben beetje terughoudend om die tooltip dan ook terug weg te laten. Zeker nu DIVES 2.0 nog in een opstartfase is (=mensen zijn het nog aan het verkennen), zou ik dit niet weglaten. Overtijd kunnen we wel over nadenken, maar dan nog ...

Ik ga deze nu even on-hold zetten denk ik.

**Comment by DIVEScoordinator** [comment]
Ik heb echt moeite moeten doen om die tooltip te zien door over de opleiding te hooveren.
Als ik direct naar het hokje ga om aan te klikken zie ik dat niet.  In testfase heb ik vaak ingeschreven en voor mij werkte dat niet storen.

Kan dit te maken hebben met een bepaalde instelling op computer die niet iedereen heeft.

**Comment by KWillemse** [comment]
De tooltip komt alleen als je over het 'groene' item hoovered, niet als je op de text staat en ook niet op de checkbox. Dus als je snel en vlot naar de checkbox gaat dan komt die tooltip niet of maar eventjes. Als ik op (of over) het groene checkbox hoover dan is die tooltip daar onmiddelijk (chrome en firefox). Ik vind dat wel heel storend vooral omdat die info ons zelfs niet verder helpt. Een groene checkbox is heel duidelijk. Als je over een rood uitroep teken hoovered dan komt er geen tool tip, wat goed is want dat is niet nodig, de reden waarom staat er gewoon onder.
Ik begrijp het statement van 'deftige manier informeren' en daar hou ik ook van, maar een groene checkbox gaan verduidelijken lijkt me er wel over.
