### ISSUE TITLE
Logboek (aangeven HW / LW in het logboek)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#334]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Dit is geen probleem. Eerder een toevoeging aan de functionaliteit van het logboek.

**Beschrijf de oplossing die je zou willen**
Een extra veld om aan te geven of je met hoog of laag water gedoken hebt.

**Comment by ndsmyter** [comment]
Als je HW of LW toevoegt, moet je vermoedelijk ook "doodtij" en "springtij" toevoegen, en vermoedelijk ook het uur waarop dat juist was. Dus denk dat er iets meer bij komt kijken, maar ik vind het ook niet echt een slecht idee. Denk dat we eens gaan moeten zien hoe we dat op een propere manier doen.

Staat wel niet bovenaan de planning op dit moment, maar lijkt mij wel iets dat er ooit zal komen.

**Comment by DIVEScoordinator** [comment]
Wij zien hier weinig toegevoegde waarde in wat het DIVES systeem betreft. Als je dit voor jezelf wilt bijhouden kan je een persoonlijke tag aanmaken. We gaan nog introduceren dat persoonlijke tags ook gedownload worden in Excel .
