### ISSUE TITLE
Logboek (aantal duiken weergeven op mobiele versie)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#335]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Dit is eerder een toevoeging aan het logboek op de mobiele versie. Op de desktop staat het aantal duiken al zichtbaar rechtsboven zonder dat je door je profiel moet scrollen.

**Beschrijf de oplossing die je zou willen**
Bij het openen van dives zou het leuk zijn om in het eerste overzicht al het aantal duiken te zien staan. Op de desktop kan je dit wel zien rechtsboven naast je avatar.

**Beschrijf alternatieven die je overwogen hebt**
Een nummering voorzien van duiken zou een alternatief kunnen zijn op de mobiele versie. In je logboekje is dit veld ook voorzien aan de linkerzijde.

**Comment by ndsmyter** [comment]
We hadden dit eerst staan op dezelfde manier zoals op de computerversie van de site. Maar dit was te druk en gaf niet zo heel veel meerwaarde. Aangezien het aantal duiken wel zichtbaar was via de profielpagina, hebben we beslist het rechtsboven weg te halen.

Aangezien er geen echt goede oplossing is door de beperkte schermruimte op een GSM/tablet, zullen we dit niet terugzetten.

Als je op een mobiel toestel dus je aantal duiken wil zien, zal je naar je Profiel moeten gaan.
