### ISSUE TITLE
[Feature] Viewkeuze onthouden

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#337]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
De weergave van het logboek staat default op "raster".
Als je deze in "lijstweergave" zet en een gelogde duik bekijkt, springt de weergave terug op "raster".

**Beschrijf de oplossing die je zou willen**
Kan de weergave van het logboek default als 'lijst" weergegeven ipv "raster"?

![image](https://github.com/Nelos-VZW/dives-2/assets/112781010/551edadd-f364-498c-8c8e-bb225e30bd9c)
![image](https://github.com/Nelos-VZW/dives-2/assets/112781010/db1ba1df-995f-4add-8417-c83a9fa6dc5d)

**Comment by ndsmyter** [comment]
Dit is een duplicaat van #216 dat reeds op onze radar staat; ik sluit daarom deze af.
