### ISSUE TITLE
Persoonlijke duikplaats zoeken/ingeven is niet echt mogelijk

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#338]
**Beschrijf de bug**
Situatie, ik ben gaan duiken op wrak en de schipper heeft mij een naam gezegd namelijk 'Duward' maar uiteraard geen coördinaten ;-). We zijn vanuit Neeltje Jans vertrokken dus ik weet dat ik moet zoeken op 'Noordzee - Nederland - ....' en ik weet ook ongeveer op de kaart waar het wrak ligt.
Ik heb eerst gezocht op naam => geen resultaat omdat:
1. de naam niet juist is, na lang zoeken op het internet vond ik dat het Durward is ipv Duward.
2. ook op de naam Durward geen resultaat kon gevonden worden.
Dan dacht ik, ik start met typen in de locatie: Noordzee - Nederland - en zoek in de drop down => niet mogelijk:
3. de drop down geeft maar 10 items (zie screenshot 1)
Dan wil ik gaan zoeken op het kaartje => geen resultaat omdat:
4. je kan niet kan 'hooveren' over een speld om te zien welke locatie het is (see screenshot 2), dus moet je één voor één op spelden klikken 
Als je dan een volgend speld wil bekijken dan is dat moeilijk:
5. alle andere spelden zijn weg en klikken op "zoeken in dit gebied" brengt ze niet terug (zie screenshot 3) 
6. Je moet de locatie terug verwijderen en dan "zoeken in dit gebied" om de spelden terug te krijgen (zie screenshot 4)
Aangezien ik de locatie niet gevonden heb, wilde ik ze gewoon intypen: Noordzee - Nederland - Durward (wrak) => is niet toegelaten
7. ik moet deze op het kaartje aanduiden (zie screenshot 5)
Dus ik kan enkel kiezen voor 'Noordzee - Nederland - (algemeen) en de wraknaam in de notities schrijven :-(

**Stappen om te reproduceren**
Zie beschrijving

**Verwachte resultaat**
- je moet gemakkelijker kunnen zoeken op duikplaatsen (drop down, hooveren over spelden, zoeken in een gebied ook als je al een speld hebt geselecteerd
- je moet een 'persoonlijke duikplaats' ook moeten kunnen ingeven

**Screenshots**
screenshot 1 :
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/382776d7-3a4e-40b9-ad1b-44ba6b2c4e30)
screenshot 2:
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/f875b14e-c576-4c51-af4b-800dc619e0c8)
screenshot 3
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/40fcb581-2f71-4093-abac-e210e2b1d5e0)
screenshot 4:
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/497d1dc6-3318-4b77-abb7-d87daa892e48)
screenshot 5:
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/4460646a-22f2-43c0-8b56-112208af5985)

**Comment by DIVEScoordinator** [comment]
In 2024 gaan we nadenken hoe duikplaatsen beter kunnen opgezocht en ingebracht.  In die specifieke geval is de duikplaats niet beschikbaar in het systeem en zal er informatie van de gebruiker moeten komen wat lokatie betreft. Het zelf ingeven is wat moeilijker en je moet effectief eerst de naam van je eigen duikplaats ingeven en dan met de tooltip op de kaart dit aanklikken.  Ik heb er ook in de volgende hippocampus een item van gemaakt.  Maar het kan werken hoewel nog niet erg gebruiksvriendelijk.

**Comment by KWillemse** [comment]
In die specifieke geval is de duikplaats niet beschikbaar in het systeem ==> maar dat kan ik nu niet controleren omdat de dropdown maar 10 items toont. Is het niet mogelijk om alles te laten zien, dan kan ik tenminste zoeken of een duikplaats bestaat of niet.

**Comment by DIVEScoordinator** [comment]
Feature voor 2024. Nog veel anderen zaken die voorgaan op dit moment en daar moet eerst grondig over nagedacht.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Tuesday, July 18, 2023 9:47:16 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; State change ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Persoonlijke duikplaats zoeken/ingeven is niet echt mogelijk (Issue #338)


In die specifieke geval is de duikplaats niet beschikbaar in het systeem ==> maar dat kan ik nu niet controleren omdat de dropdown maar 10 items toont. Is het niet mogelijk om alles te laten zien, dan kan ik tenminste zoeken of een duikplaats bestaat of niet.
