### ISSUE TITLE
Assistent-Instructeur telt als 'extra brevet' in plaats van titel.

### ISSUE THREAD

**Issue by fornuftig** [Nelos-VZW/dives-2#339]
**Beschrijf de bug**
AI (Assistent-Instructeur) is een titel maar is als brevet getoond in de profiel.

**Stappen om te reproduceren**
Onder profiel > Brevetten > Extra brevetten: Assistent-Instructeur

**Verwachte resultaat**
Ik had verwacht dat er ook een plaats was voor titels naast 'Hoofdbrevet' in het geval van AI.

**Comment by ndsmyter** [comment]
@DIVEScoordinator gaat dit even intern opnemen.

**Comment by DIVEScoordinator** [comment]
Assistent instructeur is een kaartje dat je maar 1 malig krijgt en waarop 'specialisatie'  staat.
Binnen DIVES spreken we enkel over 'hoofdbrevet'  en andere 'brevetten'.  Voor een AI is het hoofdbrevet 3*D of 4*D.
Infomap (versie 20024) werd ook aangepast.   Dit wordt afgesloten zonder aanpassing in het systeem
'
