### ISSUE TITLE
sidemount duiken van buddy worden ook geteld op mijn profiel

### ISSUE THREAD

**Issue by rubenvanveerdeghem** [Nelos-VZW/dives-2#340]
**Beschrijf de bug**
Ik deed 3x een duik met een buddy die sidemount deed. Ikzelf deed nog nooit een sidemount duik. Maar in mijn statistieken op dives staat wel dat ik 3 sidemount duiken heb. Het lijkt er dus op dat de sidemount duiken van mijn buddy's ook geteld worden op mijn profiel.

**Stappen om te reproduceren**
duik toevoegen waarvan buddy als sidemount staat. Dan wordt deze toegevoegd in jouw profiel. Ook de tijd wordt op die manier toegevoegd.

**Verwachte resultaat**
Geen duiken toevoegen die niet van jou zijn.

**Screenshots**
niet nodig volgens mij

**Desktop (indien mogelijk aanvullen):**
is pure programma bug

**Smartphone (indien mogelijk aanvullen):**
is pure programma bug

**Extra informatie**
-

**Comment by ndsmyter** [comment]
@rubenvanveerdeghem ,

Correcte opmerking, want er werd inderdaad gekeken naar die sidemount/scooter tags over de verschillende buddy's van een activiteit heen. Ik heb de code nu aangepast waardoor het probleem opgelost zou moeten zijn.

Ik heb vervolgens ook alle statistieken van iedereen opnieuw laten berekenen, waardoor dit probleem opgelost zou zijn voor jouw profiel ook. Bekijk je eens dat het aantal sidemountduiken voor jou ook terug op 0 staat?

Bedankt om het probleem te melden !

**Comment by rubenvanveerdeghem** [comment]
Dit ziet er bij mij alvast goed uit. Bedankt voor de snelle service!
