### ISSUE TITLE
Proef in opleiding getekend geeft een vertekend beeld.

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#342]
**Beschrijf de bug**
Een proef die in opleiding getekend werd en nadien met succes werd afgetekend komt niet als afgewerkt in het overzicht op de brevetkaart. Tevens komt de datum van het opnieuw aftekenen niet beschikbaar op die proef.

In dit geval gaat het over proef CL4 die ondertussen wel afgewerkt is maar zonder dat de datum beschikbaar komt van het aftekenen van deze proef. Ook blijft deze het symbool "in opleiding" tonen terwijl er in principe ook een groen vinkje voor zou moeten staan.

**Stappen om te reproduceren**
1. Ga naar 'Kandidaten'
2. Klik op 'kandidaat 3*D'
3. Scroll naar 'opleidingen'
4. Zie fout

**Verwachte resultaat**
Indien een proef getekend werd nadat deze "in opleiding" stond dan zou deze de voorwaarde op de brevetkaart in totaal moeten aftekenen.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/d0807798-70bc-4896-9e73-95d52af12b06)

**Desktop (indien mogelijk aanvullen):**
 - Windows (chrome)

**Smartphone (indien mogelijk aanvullen):**
 - Oneplus 2T 5G (android)

**Comment by DIVEScoordinator** [comment]
@CarlAnto   carl, ik heb eerst een proef bij een kandidaat van mij in opleiding afgetekend en daarna als geslaagd en bij mij komt dit correct door.  Ik kan het dus niet reproduceren. 
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/9f1d4763-5b9b-42d4-aa5b-4a785251b2b3)

**Comment by CarlAnto** [comment]
In dit geval gaat het over Rob Nuyts (50916) waar proef cl4 in opleiding getekend werd. Daags nadien werd deze proef succesvol afgelegd en afgetekend.
Als ik een duik aanmaak om een openstaande proef op te roepen bij deze kandidaat dan komt er niets meer beschikbaar.
Toch blijft het blauwe symbool staan alsof het in opleiding getekend werd, en is er in het overzicht sprake van 2 openstaande punten voor dit brevet. Enerzijds de bootduiken en anderzijds de proef cl4.

Met vriendelijke groeten,


Carl Antonissen
________________________________

**Comment by DIVEScoordinator** [comment]
Carl,

Geen idee waarom dit is, ik kan ook niet meer zien dan zijn brevetkaart en het staat als niet afgetekend.  Via activiteit kan ik het ook niet zien.

De logging van de afgetekende proeven in de twee activiteiten eens opvragen zou interessant zijn. Ik laat deze open indien we dit nog gemeld krijgen dan kan er dieper naar gekeken.

Kan de OPLV nog een vrijstelling geven?  Dat is waarschijnlijk een uitweg dat ik recent ook gebruikte voor een ander geval (maar dat had met de migratie te maken vermoedde ik toen).


Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: CarlAnto ***@***.***>
Verzonden: vrijdag 23 juni 2023 0:17
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Proef in opleiding getekend geeft een vertekend beeld. (Issue #342)

In dit geval gaat het over Rob Nuyts (50916) waar proef cl4 in opleiding getekend werd. Daags nadien werd deze proef succesvol afgelegd en afgetekend.
Als ik een duik aanmaak om een openstaande proef op te roepen bij deze kandidaat dan komt er niets meer beschikbaar.
Toch blijft het blauwe symbool staan alsof het in opleiding getekend werd, en is er in het overzicht sprake van 2 openstaande punten voor dit brevet. Enerzijds de bootduiken en anderzijds de proef cl4.

Met vriendelijke groeten,


Carl Antonissen
________________________________

**Comment by CarlAnto** [comment]
In principe zou hij na de vakantie in Kroatië (halverwege juli) rond moeten zijn. Ik volg het sowieso op en bekijk last minuten of ik de vrijstelling al dan niet zou moeten toepassen. Momenteel staat onze DSV als oplv.

Met vriendelijke groeten,


Carl Antonissen
________________________________

**Comment by DIVEScoordinator** [comment]
afgesloten want ondertussen werd proef via vrijstelling afgetekend, geen meldingen meer gekregen hierover dus een eenmalig probleem?

**Comment by CarlAnto** [comment]
Werd inderdaad via vrijstelling afgetekend en zou vandaag in de namiddag bij het loggen van de volgende duik zijn brevet volledig afgewerkt hebben. Ik was nog aan het wachten of er een issue zou zijn na het afleggen van de laatste voorwaarde alvorens terug te koppelen.
