### ISSUE TITLE
Geen tellers in profiel.

### ISSUE THREAD

**Issue by Stevendaems** [Nelos-VZW/dives-2#343]
**Beschrijf de bug**

Beste, 
ik heb gemerkt dat bin profiel, niet alle tellers werken… Bv wrak duik, zeeduiken etc hoe komt dit?

**Comment by ndsmyter** [comment]
Hey @Stevendaems ,
Kan je hier wat meer informatie over geven waarom je denkt dat dit niet werkt?
Zijn er bepaalde acties die je gedaan hebt waardoor je denk dat dit niet werkt?

Want voor zover ik kan zien, lijkt dit wel OK te werken. Misschien zijn er specifieke gevallen waardoor het bij jou niet werkt.

PS: Wrakduiken worden niet meer geteld in DIVES 2. Bij sommige duiklocaties is het niet altijd duidelijk of je effectief op het wrak gedoken hebt of niet. Op verschillende duikplaatsen in de Oosterschelde liggen er bijvoorbeeld wel wrakken, maar daarom wil dat nog niet zeggen dat je er ook effectief gedoken hebt. Het geeft dus een vertekend beeld als je de ene wrakken wel en andere wrakken niet gaat tellen. Je kan die wel nog steeds zelf tellen door er een "persoonlijke tag" aan te hangen.

**Comment by Stevendaems** [comment]
Beste,

thanks voor de update over wrakken.

 de andere teller waar ik het over het was zeeduiken deze blijft ook op 0 staan,alsook  de zeeduiken >25m lijken niet bij te tellen. Komt dit eventueel om dat de Oosterschelde niet meer aanzien wordt als zeeduiken? 

MVG

**Comment by ndsmyter** [comment]
Oosterschelde wordt wel aanzien als een "Zeeduik" normaal gezien. Heb je toevallig ook een specifieke duik waarbij je opmerkt dat het niet optelt? Want als ik naar mijn eigen profiel kijk, dan kan ik wel degelijk de tellers zien verhogen.

Je kan eventueel eens proberen om in https://test.dives.nelos.be een paar duiken aan te maken en te zien of de tellers verhogen.

**Comment by Stevendaems** [comment]
Sinds de migratie naar dives 2.0 staat er bij zeeduiken niets meer…. Telt ook niet bij. 

bijvoorbeeld sinds dives 2.0 ben ik 6 keer in de Oosterschelde gaan duiken onderd de 25 m en deze worden niet bij geteld. 

Ook denk ik dan dat de andere die vroeger gedoken geweest zijn hier ook moeten bij staan ?

![CAD13E2D-3E83-4B77-8E92-AB4C8D20F044](https://github.com/Nelos-VZW/dives-2/assets/137054770/bfcddd33-9fc9-49db-9795-67f9d6f7ca30)


Zeeduiken staat niet in het lijstje zelfs
Zeeduiken >25m wel

**Comment by DIVEScoordinator** [comment]
Ik heb zelf getest en de volgende plaatsen verhoogd bij mij zeeduiken wel (diepte 30m genomen): Wemeldinge parking en tetjes, Stavenisse Oostnol, Putti's place, Vuilnisbelt.  Kan je eens doorgeven welke Oosterschelde duik plaatsenbij u niet meetellen bij zeeduiken > 25m.    Dan kunnen we eens gerichter kijken.

@ndsmyter   tag zeeduik eventueel ook terug laten zien?

**Comment by ndsmyter** [comment]
Zou nu in orde moeten zijn.
