### ISSUE TITLE
[] Locatie ingeven

### ISSUE THREAD

**Issue by HanneBortels** [Nelos-VZW/dives-2#344]
GIsteren deden we een duik met de club in Luxemburg. 
Enkelen slaagden erin om de duik in te geven, anderen, waaronder ik, konden de locatie niet ingeven. 
Zowel op de kaart als via de tekst verscheen de locatie niet. 
De locatie heet Lac de la Haute Sur plage 1 of Insenborn P1. Beiden verscheinen niet. 
We probeerden op meerdere toestellen, waaronder enkele laptops. 
Ook het maken van een nieuwe locatie werkt niet, want je kan noch Luxemburg, noch Europa selecteren. Dus je kan de locatie enkel fout registreren. 

**Stappen om te reproduceren**
Maak duik activiteit
Locatie

**Verwachte resultaat**
Zowel op de kaart als via de tekst zou de locatie vindbaar moeten zijn. 

**Screenshots**
![Schermafbeelding 2023-07-02 om 10 29 49](https://github.com/Nelos-VZW/dives-2/assets/138361337/6210904d-e03c-4bd8-a89a-5c9dcc7e4456)
![Schermafbeelding 2023-07-02 om 10 30 24](https://github.com/Nelos-VZW/dives-2/assets/138361337/a9be7773-2d00-4fa8-85b7-a664639a075e)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: ios
 - Browser: Google Chrome en Safari 
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: iPhone 12, iPhone 13 en verschillende Android gsm's
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by DIVEScoordinator** [comment]
Beste, ik heb dit zelf geprobeerd en dit lukte wel.  Het is niet erg praktisch maar voorlopig staat een verbetering op het vlak van nieuwe duikplaatsen zelf aanmaken nog op de TODO lijst en dit zal eerder voor 2024 zijn om dit uit te werken. 

Dit zijn de stappen:
1) Tik de naam van de nieuwe duikplaats die je wilt aanmaken en klik op box die verschijnt
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/5160e2bd-2981-4a83-a16d-90f1c1b24f55)
2) zoom in op het kaartje en klik de locatie aan (ik vermoed dat jullie dat niet zagen omdat je voorgaande stap niet correct uitgevoerd hebt - best nog eens proberen)
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/f5069715-1bf0-409f-b1a1-56368ec08979)
3) kies de locatie die het beste fit met de duikplaats - dat is nog beperkt en enkel om de juiste tagging toe te voegen.
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/498bc34f-80dd-4bf8-8f14-2a7b609be504)

**Comment by ndsmyter** [comment]
Ik denk dat door het antwoord van @DIVEScoordinator dit ticket afgesloten mag worden. Laat gerust weten moest je daar anders over denken.

**Comment by HanneBortels** [comment]
Dag Nicolas

We hadden ondertussen inderdaad ook gekozen voor wereld - zoetwater. Maar
hoe komt het dat de duikplaats (die wel gekend is, want bij sommigen lukte
het wel) niet verschijnt. Dat vonden we vooral heel verwarrend..

Groetjes
Hanne

Op ma 3 jul 2023 om 21:25 schreef DIVEScoordinator ***@***.***
