### ISSUE TITLE
Meldingen in Dives

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#345]
Meldingen in Dives verdwijnen niet ondanks er geklikt werd op "markeer alle meldingen als gelezen."

**Stappen om te reproduceren**
1. Ga naar 'dives.nelos.be'
2. Klik op 'het belletje naast je avatar'
3. Scroll naar 'Markeer alle meldingen als gelezen'
4. Aantal meldingen blijft nog steeds zichtbaar bovenaan.

**Verwachte resultaat**
Wanneer men klikt op "Markeer alle meldingen als gelezen", zouden deze bovenaan ook moeten verdwijnen.

**Comment by CarlAnto** [comment]
Melding kwam binnen via dives-limos

**Comment by DIVEScoordinator** [comment]
Ik heb wat getest: bij mij wordt dit altijd leeggemaakt tot op heden;
Bij mijn echtgenoot zie ik dat het verminderde maar blijft op 1 staan.  Ik heb dan alle meldingen geopend en er stond er nog 1 niet gelezen van iets langer geleden.  Het lijkt erop dat enkel de laatste 30 items worden als gelezen gemarkeerd en oudere niet.
Kan je eens navragen of dat ook in dit geval zo te verklaren valt?  dan heb ik minstens een aanknooppunt

**Comment by CarlAnto** [comment]
Verhaal is idd gelijklopend. De laatste items in de lijst kan je als gelezen markeren terwijl "oudere items" manueel per item afgevinkt moeten worden.

**Comment by ndsmyter** [comment]
Werd ondertussen al in de code aangepakt
