### ISSUE TITLE
Teller aantal duiken voor brevet klopt niet

### ISSUE THREAD

**Issue by commeyner** [Nelos-VZW/dives-2#346]
**Beschrijf de bug**
Voor 2*D is er een proef waar je 15 duiken moet hebben tussen 10 - 20m. De teller heeft aan dat er maar 3 duiken zijn terwijl dit er 19 zijn. 

**Stappen om te reproduceren**
1. Profiel
2. Opleidingen
3. Brevet 2*D: OW-proeven en duikleidingen
4. Proef 15 duiken in openwater tussen 10 en 20 meter
5. Hover over balk en tooltip zal de progress tonen

**Verwachte resultaat**
Ik verwacht dat deze proef al afgerond zou moeten zijn

**Screenshots**
![dives_auto_duiken](https://github.com/Nelos-VZW/dives-2/assets/55080508/e1f795dd-3e48-4fad-9195-83d9c1caf5c7)

**Desktop (indien mogelijk aanvullen):**
 - Browser: Chrome 
 - Versie: 114.0.5735.199

**Extra informatie**
Dit voor nelos-id 51923

**Comment by commeyner** [comment]
Eerste idee was dat alle duiken dieper dan 20m niet zouden meetellen. Er waren dus duiken gelogged naar 21m, 22m... enz. Want je hebt 10% marge op je duiken volgens nelos. Wij hebben dan alle duiken aangepast naar 20m maar hier is geen herberekening op gedaan.

**Comment by commeyner** [comment]
Bij het ingeven van 19,9m word het aangepast in de statistieken maar niet bij de duiken die nodig zijn voor het behalen van het brevet dus in de tab opleidingen. Die 10% is denk ik een ongeschreven regel je kan altijd wel eens de diep gaan per ongeluk. Of je buddy gaat iets dieper waardoor je eventjes volgt. Die duiken zouden hoe dan ook moeten meetellen voor een brevet.

**Comment by DIVEScoordinator** [comment]
Beste
Ik leg het voor aan het Brevetten comité want binnen de bevoegdheden van DIVES kunnen we enkel de infomap programmeren zoals het beschreven staat.

Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: commeyner ***@***.***>
Verzonden: dinsdag 4 juli 2023 18:42
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Teller aantal duiken voor brevet klopt niet (Issue #346)


Bij het ingeven van 19,9m word het aangepast in de statistieken maar niet bij de duiken die nodig zijn voor het behalen van het brevet dus in de tab opleidingen. Die 10% is denk ik een ongeschreven regel je kan altijd wel eens de diep gaan per ongeluk. Of je buddy gaat iets dieper waardoor je eventjes volgt. Die duiken zouden hoe dan ook moeten meetellen voor een brevet.

**Comment by AndreVanhecke** [comment]
"Die 10% is denk ik een ongeschreven regel....." dat is een regel die jaaaaaaaren geleden werd afgeschaft. 20m is 20m.

**Comment by commeyner** [comment]
Daar heb ik geen idee van of dit afgeschaft is. Hoe dan ook het is een bug in het systeem. 
Dit kan eventueel wel eens bekeken worden want mensen die van andere federatie komen waar ze een brevet hebben die wel dieper mag, dan tellen deze duiken niet mee.

**Comment by DIVEScoordinator** [comment]
Zonet getest met een kandidaat in mijn club die 11/15 duiken had
- duik 12m ingebracht put van ekeren: telde op tot 12, aangepast naar 20m werkte het nog steeds
- duik 19,9m ingebracht in wemeldinge telde op tot 13
- duik op 20m ingebracht in barges telde niet meer op, lokatie aangepast aan wemeldinge telde wel verder naar 14
deze duiken moeten in open water gebeuren - ik denk dat er een probleem is met identificatie van steengroeves als open water waardoor duiken daar niet meetellen.   De diepte tot 20m werkt wel degelijk.

@ndsmyter   nakijken definitie open water bij de duikplaatsen, steengroeves (Barges, Vodelee werken alvast niet)

**Comment by commeyner** [comment]
Ok top! Dit kan inderdaad kloppen want bijna alle duiken zijn in Barges.

**Comment by ndsmyter** [comment]
Steengroeves stonden inderdaad niet gemarkeerd als "Open water". Dat is bij deze gecorrigeerd. Elke paar uur worden de tellers opnieuw gecontroleerd, dus dat zal dan ook gecorrigeerd worden voor iedereen waar dit verkeerd was.

Door deze aanpassing zal ik deze taak ook aflsuiten.
