### ISSUE TITLE
+ knop bij startpagina niet aanwezig

### ISSUE THREAD

**Issue by rubenvanveerdeghem** [Nelos-VZW/dives-2#347]
**Beschrijf de bug**
Als je inlogt op dives is het niet mogelijk om de + knop te gebruiken, want deze is niet zichtbaar. Deze komt wel zichtbaar als je de
pagina meteen refresht.

**Stappen om te reproduceren**
1. inloggen op dives
2. onderaan rechts is + knop niet zichbaar
3. refresh pagina
4. + knop komt zichtbaar onderaan rechts

**Verwachte resultaat**
+ knop moet meteen zichbaar zijn

**Smartphone (indien mogelijk aanvullen):**
 - android chrome

**Comment by ndsmyter** [comment]
We zijn afgestapt van de "+" knop en die zal normaal gezien in volgende versie volledig verwijderd worden. Ik sluit deze taak af, aangezien we daar geen tijd meer in moeten steken.

PS: We hebben die verwijderd omdat die eigenlijk voor vele mensen verwarrend was, en ook vaak in de weg stond op mobiele toestellen.
