### ISSUE TITLE
meerdere duikleiders en hekkensluiters mogelijk

### ISSUE THREAD

**Issue by rubenvanveerdeghem** [Nelos-VZW/dives-2#348]
**Beschrijf de bug**
Je kan meerdere buddy's als duikleider zetten. (zelfde issue voor hekkensluiter)

**Stappen om te reproduceren**
1. nieuwe duik loggen
2. kies buddy's
3. buddy1 als duikleider plaatsen
4. buddy2 als duikleider plaatsen

**Verwachte resultaat**
Als je iemand kiest als duikleider zou die selectiemogelijkheid moeten vervallen voor de andere buddy's

of

Als je andere buddy als duikleider zet, dan zou de andere automatisch terug als deelnemer moeten komen

**Comment by ndsmyter** [comment]
We zijn afgestapt van de "+" knop en die zal normaal gezien in volgende versie volledig verwijderd worden. Ik sluit deze taak af, aangezien we daar geen tijd meer in moeten steken.

PS: We hebben die verwijderd omdat die eigenlijk voor vele mensen verwarrend was, en ook vaak in de weg stond op mobiele toestellen.

**Comment by ndsmyter** [comment]
Op verkeerde ticket aan het reageren :-)

**Comment by KamielKempeneers** [comment]
Het is mogelijk om tijdens de duik van duikleider te wisselen, er bestaat daar een duikteken voor.
In zo'n geval is het wenselijk meerdere duikers als duikleider te kunnen loggen.

**Comment by ndsmyter** [comment]
Naar aanleiding van de feedback, sluit ik deze taak af.
