### ISSUE TITLE
[Feature] Totaal aantal duiken op iedere duik tonen (in lijst van duiken in logboek)

### ISSUE THREAD

**Issue by revodiver** [Nelos-VZW/dives-2#349]
In logboek:
 - activteiten overzicht
 - op iedere duikactiviteit het totaal aantal duiken tonen, zoals we vandaag in logboek invullen.

**Comment by Cereal2nd** [comment]
DIt is iets wat ik ook al miste :)

**Comment by ndsmyter** [comment]
Het volgnummer van de activiteiten gaan we niet invullen, aangezien dit te veel problemen zou veroorzaken in de databank. Onder andere om onderstaande redenen:

* Volgnummers zijn heel erg persoonlijk, dus1 activiteit zal meerdere volgnummers hebben
* Volgnummers zijn afhankelijk van de volgorde waarin duiken worden ingebracht in de tijd. Dus bijvoorbeeld als duik 2 van een dag eerst wordt ingebracht, dan moet bij het inbrengen van duik 1 (die voor duik 2 viel) de volgnummers herberekend worden. En dit voor alle buddy's van die activiteit.
* Zolang duik 1 van hierboven niet ingebracht werd, zal ook het volgnummer van duik 2 foutief zijn. Dit is heel erg verwarrend.

Aangezien de volgnummers ook persoonlijk zijn per buddy, is het ook niet haalbaar dat we daarvoor een persoonlijk veld zouden voorzien. Want dan is iets dat dan iedereen zou willen aanpassen.

Dus, omwille van de grote kans op fouten of heel veel werk om het in te brengen, ga ik deze taak afsluiten als iets wat we niet gaan doen.
