### ISSUE TITLE
[BUG] knop 'Activiteit opslaan' niet bereikbaar

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#35]
**Beschrijf de bug**
Ik wil een nieuwe duik-activiteit maken. De knop om ze effectief op te slaan is niet bereikbaar. Deze zit 'verstopt' onder de balk met Logboek. Als ik het scherm naar boven schuif kan ik er niet op drukken en die verdwijnt ook weer direkt

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar 'Aanmaken duik-activiteit'

**Verwachte resultaat**
Die knop moet zeker bereikbaar zijn

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15,6
 - Browser safari

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare
https://endare.atlassian.net/browse/NELOS-280 (link enkel voor mij toegankelijk)

**Comment by ndsmyter** [comment]
Hey @davegeysemans ,
Zou je toevallig een screenshot kunnen maken van je scherm waarop je niet aan de knop kan om op te slaan? Want blijkbaar kan Endare het niet volledig reproduceren, maar ze wisten toen wel nog niet op welk toestel ze konden testen. Ik heb hen nu jouw  versies doorgestuurd.

Moest je een screenshot kunnen maken, dan kunnen ze misschien ook daaruit afleiden hoe het kan opgelost worden.

**Comment by davegeysemans** [comment]
Twee screenshots toegevoegd.
De 'niet gescrold' is het scherm zoals ik het zie staan zover mogelijk naar
beneden maar niet 'vastgehouden' en dan screenshot genomen
De 'gescrold' is screenshot genomen terwijl ik zover mogelijk verder wil
scrollen en dus effectief de vinger op het scherm hield bij het maken van
de screenshot

Hopelijk ben je hier iets mee?
Nog even ter bevestiging: safari browser - ios 15.7 - iPhone 13 Pro

**Comment by ndsmyter** [comment]
@davegeysemans Ik zie de screenshots niet op GitHub staan. Dus misschien lukt het niet om die op te laden met bijlages.

Probeer je aub nog eens door eerst de GitHub pagina te openen met de "view it on GitHub" link onderaan? Dan kan je daar een comment toevoegen de screenshots opladen.

Indien dat niet lukt, stuur je ze anders even door naar nicolas.desmyter@nelos.be, dan kan ik ze opladen.

Bedankt alvast voor het maken van de screenshots!

**Comment by davegeysemans** [comment]
![knop_niet_zichtbaar_niet_gescrold](https://user-images.githubusercontent.com/112888105/192699653-a2e2d269-8f1d-475c-8478-31a2f37faea2.jpeg)
![knop_niet_zichtbaar_gescrold](https://user-images.githubusercontent.com/112888105/192699656-519fb2a9-42ac-40ff-940d-2826946ac53f.jpeg)

**Comment by davegeysemans** [comment]
zouden er nu bij moeten staan

**Comment by ndsmyter** [comment]
Zou nu in orde moeten zijn
