### ISSUE TITLE
[Feature] Gasmengsels onthouden bij technisch duiken

### ISSUE THREAD

**Issue by revodiver** [Nelos-VZW/dives-2#350]
Wanneer we een ccr duik toevoegen moeten we telkens percentage helium invullen.
Kan er per gebruiker niet bijgehouden worden wat hun standaard gas is. Meeste van de ccr duiken zijn in onze wateren luchtduiken.

**Comment by ndsmyter** [comment]
Dit zal binnenkort mogelijk zijn met "Favorieten"
