### ISSUE TITLE
[BUG] Duiken filteren op buddy resulteert in melding "niet juiste rechten"

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#351]
**Beschrijf de bug**
Wanneer ik mijn duiken probeer te filteren op een bepaalde buddy, krijg ik de melding dat ik niet de juiste rechten heb om zijn profiel te bekijken. Soms gaat de error melding heel snel weg zodat je ze amper ziet.

**Stappen om te reproduceren**
1. Ga naar dev.dives.nelos.be/activities
2. begin een naam te typen in het zoekveld en klik op een buddy
3. Zie error en niet toegepaste filter

**Verwachte resultaat**
Een werkende filtering van al mijn duiken op buddy.

**Gifs**
![bug](https://github.com/Nelos-VZW/dives-2/assets/42772246/a1e9c042-83fd-4030-8be3-8caedb155e4d)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows 11 build 22621.1992
 - Browser: zowel chrome als edge getest

**Comment by KimEndare** [comment]
@jenno-verdonck zou je nog eens opnieuw kunnen testen op DEV?

**Comment by DIVEScoordinator** [comment]
Stel voor dit te sluiten als het niet kan gereproduceerd worden.  Er is een aanpassing in de code gebeurd die dit moet vermijden. @ndsmyter

**Comment by ndsmyter** [comment]
Aangezien code aangepast werd, kunnen we deze inderdaad sluiten. Moest probleem zich terug voordoen kunnen we nieuwe taak aanmaken of deze heropenen.

**Comment by jenno-verdonck** [comment]
Ik was op reis en kon even niet testen hierdoor. Net de dev site geprobeerd op gsm en lijkt nog steeds dezelfde melding te geven.
