### ISSUE TITLE
Brevetkaarten laden de gegevens van de initialisatie niet mee

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#352]
**Beschrijf de bug**
Wanneer je al dook voor de introductie van DIVES heb je wellicht de initialisatie moeten doen om al je duiken in je statistieken te krijgen. Als je vandaag een openstaand brevet hebt dan worden de statistische gegevens van deze initialisatie niet meegenomen in de brevetvoorwaarden.

**Verwachte resultaat**
Gegevens uit de initialisatie moet mee in rekening gebracht worden wanneer er nieuwe lopende brevetten zijn.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/de52c2dd-900b-4cbb-a02f-f3efef1bbf3b)
Voor een kandidaat 3*duiker die zijn 2*duiker behaalde sedert 2012 zouden de 40 duiken vereist voor het brevet niet in orde zijn.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   volgens mij is het niet mogelijk behalve als we een lijn gaan bijmaken in de initialisatie om dit te berekenen. Dit gaat ook heel weinig voorkomen omdat je verwacht dat iemand die al 2* was bij de start van DIVES nu al 40 duiken in het systeem had zitten (of de persoon is pas heel recent gestart met te loggen).  Je kan onmogelijk uit het aantal duiken dat je initialiseert zien hoeveel er waren voor voor of na het behalen van het brevet 2*D. Ik denk dat je hiervoor beter via een vrijstelling werkt.  Als de persoon voldoende gedoken heeft weet de OPLV dit. Ik zou deze afsluiten zonder verdere actie dan terugkoppeling hoe je dit kan oplossen.

**Comment by ndsmyter** [comment]
Deze gaan we inderdaad niet via een initialisatie kunnen doen, aangezien we niet weten hoeveel van de duiken ingebracht via initialisatie meetellen voor de voorwaarde ("sinds 2*D"). Het wordt moeilijk (en ook een lelijk boeltje) als we dat voor alle gelijkaardige voorwaarden gaan beginnen doen.

Dergelijke zaken zullen we dus moeten oplossen met een vrijstelling door de opleidingsverantwoordelijke, maar gaan we dus niet verder kunnen automatiseren.
