### ISSUE TITLE
Tagging zeeduiken klopt niet

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#353]
**Beschrijf de bug**
Wanneer men inschrijft voor 2*I zouden er duikleidingen gedaan moeten worden in zee. Oosterschelde-duiken tellen mee voor zeeduiken maar komen niet in de pool van de duikleidingen in zee.

**Verwachte resultaat**
Tagging Oosterschelde mankeert wellicht de tag zeeduik waardoor deze niet mee gegeneerd worden in de voorwaarden voor dit brevet.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/5c00a5c6-2aa1-4af6-9bd4-c9fada5a2d9c)

**Comment by DIVEScoordinator** [comment]
@ndsmyter   in het kader van een andere opmerking hierover heb ik al eens getest in het systeem en de duikplaatsen parking, tetjes, putti's, oostnol geven in mijn statistieken telkens een verhoging van aantal zeeduiken>25m.  Het moet dus iets te maken hebben met de berekening van deze voorwaarde, wordt er naar een bepaalde diepte gekeken?  of is de berekening van zeeduiken > 25m gebaseerd op duiken in heldere zee + getijdewater en is hier getijdewaters weggevallen?

**Comment by ndsmyter** [comment]
Bij de 2e voorwaarde "10 zeeduiken als duikleider sinds 1*I" liep het blijkbaar gewoon mis bij de berekeningen. Er werd in de verkeerde tags gezocht :-)

Ik heb dit nu aangepast op TEST, en kan nu zien dat er 6 duiken zijn die aan die voorwaarden voldoen voor @CarlAnto . Dat lijkt me dan al realistischer.

Ik heb de code aangepast, maar zal pas op productie komen bij de volgende release naar productie. Voorzien vóór het einde van de maand.
