### ISSUE TITLE
[BUG] dubbele naam bij eenzelfde duik

### ISSUE THREAD

**Issue by Piet-TD** [Nelos-VZW/dives-2#354]
Evi Godfroid heeft op 5 maart 2023 een duik proberen loggen via gsm. Nog in de vorige Dives dus. Tijdens het aanmaken voegde ze Ailien Aida AERTS toe, niemand anders. Ailien was toegevoegd tijdens het aanmaken van de duik. Bij het opslaan van de duik bleef het systeem lang draaien om op te slaan. De duik was uiteindelijk opgeladen maar in het overzicht bleek dat Ailien niet was toegevoegd als buddy. Ze heeft de duik dan bewerkt en het systeem bleef terug draaien bij het toevoegen van Ailien als buddy. Ze heeft daarop de pagina vernieuwd en toen stond ze wel als buddy toegevoegd in de duik, maar wel 2x.
Daarop heeft ze de duik opnieuw bewerkt door Ailien 1x te verwijderen, maar dan werd zij automatisch 2x verwijderd. Evi heeft haar opnieuw toegevoegd en zij werd terug automatisch 2x toegevoegd. Hetzelfde blijft gebeuren in  dives2 als ik deze duik bewerk.
Ailien zelf ziet maar 1 duik staan, maar denkt dat haar statistieken niet kloppen.

In bijlage toegevoegde screenshorts:
* Afbeelding met zwarte achtergrond is het overzicht van Ailien haar duiken op 5 maart 2023. Daarop is te zien dat zij maar 1 duik heeft met mij.
* Afbeelding met witte achtergrond is het overzicht van de duik bij mij op 5 maart 2023
Daarop is te zien dat zij 2x toegevoegd is.
* Afbeelding van uit de nieuwe Dives is het overzicht van de duik bij Ailien alsook bij mij. Ook daar is te zien dat zij 2x in de duik staat geregistreerd.
![Screenshot_20230719_124111_Messenger](https://github.com/Nelos-VZW/dives-2/assets/112510347/988b07ef-a809-40cb-a345-6587e6ded70f)
![Screenshot_20230719_124055_Messenger](https://github.com/Nelos-VZW/dives-2/assets/112510347/e22c82d3-142d-4a18-be82-64300aefab9f)
![Screenshot_20230719_124036_Messenger](https://github.com/Nelos-VZW/dives-2/assets/112510347/d01d570a-b964-461c-8cfa-7e8897865ba9)

**Comment by CarlAnto** [comment]
Ik zou eventueel eens proberen om de duik in zijn geheel te verwijderen en opnieuw aan te maken aangezien er geen proeven aan deze duik hangen.

**Comment by Piet-TD** [comment]
Duik werd verwijderd en opnieuw aangemaakt. 
Het klopte inderdaad dat deze duik (aangemaakt in dives1) 2 keer werd aangerekend bij Ailien. Haar startsaldo was 77 duiken, na het verwijderen was het saldo 75. De duik werd opnieuw aangemaakt en haar saldo is nu 76 duiken. Voor hen is het probleem dus opgelost, maar dat wil niet zeggen dat er niet ergens een issue is.
bedankt alvast.

**Comment by DIVEScoordinator** [comment]
lijkt mij te wijten aan een probleem met DIVES 1 waar er op het einde vreemde dingen aan het gebeuren waren. Moest dit nog eens voorvallen kan het dan bekeken worden.
