### ISSUE TITLE
Activiteit opent niet

### ISSUE THREAD

**Issue by FrankyCardoen** [Nelos-VZW/dives-2#357]
Hallo Nicolas,

Vanavond een foutje tegen gekomen.
Na het aanmaken van de activiteit kan ik die nadien niet meer openen.
Enkel die activiteit; de andere openen wel.

Het gaat om deze activiteit.
![image](https://github.com/Nelos-VZW/dives-2/assets/141068467/accad62a-cb71-407e-841d-6e293b16a32b)

Kort videofragment om de fout te illustreren
https://github.com/Nelos-VZW/dives-2/assets/141068467/6e2bf49e-e126-48df-a5e4-a566d30d80a4

Er knippert kort een rode balk met foutboodschap. Ik heb die in de video kunnen pauzeren, zodat hij leesbaar wordt.
![image](https://github.com/Nelos-VZW/dives-2/assets/141068467/38138fc2-ff77-4f34-9115-981c35ad8453)

Speciaal aan deze input - heeft het daar iets mee te maken?

- Een niet nelos duiker als duikbuddy
- Kleine oveerschreiding van max diepte

Vriendelijke groeten,
Franky.Cardoen@gmail.com
0477 900 568

**Comment by ndsmyter** [comment]
Gelijkaardige bug als #356 . Ik heb #356 net opgelost, en dus sluit ik deze ook af.
