### ISSUE TITLE
[BUG] Kleuren verdwenen bij evaluatie duimpjes

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#358]
**Beschrijf de bug**
Sinds nieuwe versie van 30 juli zijn de kleurtjes bij het evalueren  verdwenen
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/a903e02b-addb-4ee7-ba10-8cb5c59bda8a)

**Comment by DIVEScoordinator** [comment]
ENDARE JIRA #610

**Comment by ndsmyter** [comment]
Aangezien NELOS-610 opgelost aan de kant van Endare, kan ik dit hier ook afsluiten.
