### ISSUE TITLE
[BUG] DSV ziet enkel brevetkaarten binnen eigen bevoegdheid

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#359]
**Beschrijf de bug**
Net melding gekregen dat een DSV geen brevetkaarten kan zien van opleidingen waarvoor niet bevoegd (GDN).
Alle brevetkaarten van leden van een club (1ste of 2de) zouden door DSV moeten kunnen geconsulteerd worden.
Ook niet zichtbaar op recent brevetten overzicht

**Stappen om te reproduceren**
1. Ga naar 'kandidaten' of 'rapportering'
2. Zoek naar kandidaat met vb. GND opleiding (als geen NI) 

3. Zie fout

**Comment by netdata-be** [comment]
Graag vermeld ik ook dat dit voor alle brevet kaarten zo is, ik als 1*I zie ook enkel maar wat van toepassing is op mij ( lees wat ik mag aftekenen).
Ikzelf ben ook nog eens ledenadministrator ( en poweruser) waardoor het moeilijk is om vragen te beantwoorden op opleidingen die ik niet mag aftekenen.
Een voorbeeld hiervan is het probleem gelogd in #360 waarbij ik deze persoon niet kon helpen omdat ik zijn brevet kaart niet kon zien.

Was er een reden om enkel maar de brevetkaarten te laten zien waar je instructeur voor bent?

**Comment by ndsmyter** [comment]
We hadden eerst alles open gezet voor instructeurs, maar dat werd uiteindelijk niet goed gekeurd tijdens bepaalde vergaderingen met Bureau (of andere, weet niet meer 100%). We wilden wel af van coach, en dan was deze tegemoetkoming wel goed.

Dus van dit systeem zelf afstappen gaan we vermoedelijk niet onmiddellijk meer kunnen. Maar we kunnen een DSV wel rechten geven om enkel van zijn eigen leden meer te zien.

Wat betreft rollen voor Power users. Ik weet dat er nu nog wat kinderziektes zijn met de tellers, maar we moeten rechten voor alle power users los zien van deze kinderziektes. Als er blijvende problemen zijn, waardoor deze rechten noodzakelijk zijn, kunnen we die wel geven. Maar op dit moment kunnen we dat als admin ook allemaal niet zien 🙂

**Comment by ndsmyter** [comment]
Deels opgenomen in NELOS-573

**Comment by DIVEScoordinator** [comment]
Opgenomen in JIRA ticket https://endare.atlassian.net/browse/NELOS-638

**Comment by DIVEScoordinator** [comment]
Dit zou met de release van gisteren opgelost zijn.
