### ISSUE TITLE
[BUG] Buddies niet allemaal zichtbaar

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#36]
**Beschrijf de bug**
Als ik een nieuwe duik wil aanmaken, en ik geef de voornaam in van mijn buddy, dan worden niet alle duikers met die voornaam getoond.
Het scroll-scherm toont maar een aantal duikers.

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar 'Maar duik activiteit'
2. Klik op 'Zoek een buddy om toe te voegen'
3. Type 'Jeroen'
4. 'Jeroen Marstboom' wordt niet in de lijst getoond

**Verwachte resultaat**
zoekresultaat moet door te scrollen zijn met alle te verwachten resultaten

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: iOS 15,6
 - Browser safari

**Comment by ndsmyter** [comment]
Dit probleem zou normaal gezien opgelost moeten zijn bij een nieuwe deploy op maandag

**Comment by davegeysemans** [comment]
Dit is niet opgelost. Hetzelfde probleem blijft zich voordoen. Zowel op gsm als op de laptop

**Comment by ndsmyter** [comment]
Hey @davegeysemans ,
Als je zoekt op "Jeroen" dan kunnen we niet alle resultaten tonen, want dat zijn er te veel. Als je "Jeroen Marstboom" moet hebben, moet je ook beginnen typen aan zijn achternaam om hem te zien verschijnen. Het is niet de bedoeling dat je met een autocomplete venster gaat beginnen scrollen.

We gaan later nog wel een filter toevoegen om enkel de namen van de club te tonen, dit zal deze bug misschien ook beter maken. Maar dat was geen onderdeel van de originele bug.

Wat mij betreft is deze bug dus wel degelijk opgelost.

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
