### ISSUE TITLE
OC NTD: 10 ERD-duiken en 10 uur ERD-duiken (verkeerde en ontbrekende berekening)

### ISSUE THREAD

**Issue by MartijnBomans35686** [Nelos-VZW/dives-2#360]
Beste

Voor de technische opleiding NTD dient men 10 ERD-duiken en 10 uur ERD-duiken gelogd te hebben (beginvoorwaarde voor de deep dives te mogen starten).

Momenteel zijn voor mij al deze duiken op dezelfde manier gelogd: eerst de duik zelf aanmaken. Daarna eerst opslaan. Dan gasmengsel toevoegen, optie "technisch duiken - OC" waarna ik telkens het bodemgas correct invul (mengsel en volume) en ook het decompressiemengsel correct invul (mengsel en volume).

Hierbij stel ik twee problemen vast i.v.m. deze automatische voorwaarden:
1) Bij de berekening van het aantal ERD-duiken worden enkel de gelogde duiken voor DIVES2.0 meegeteld. De vier duiken die vorig jaar destijds via DIVES1.0 zijn ingevoerd worden niet meegeteld in deze berekening, terwijl ik dit jaar wel de parameter gasmengsel heb gewijzigd naar technisch duiken OC en de mengsels correct hebt ingevoerd.
2) Bij de berekening van het aantal ERD-uren is er geen voortgangsbalk zichtbaar en staat deze voorwaarde als nog uit te voeren. 

Momenteel zou ik volgens mijn persoonlijke tag voldoen aan bovenstaande twee voorwaarden. De opleidingsverantwoordelijke van de NTD-opleiding kan blijkbaar deze niet manueel aftekenen als uitgevoerd (klopt dit of is dit ook een bug?)

Mvg
Martijn Bomans
35686

**Comment by MartijnBomans35686** [comment]
<img width="300" alt="Persoonlijke tag ERD" src="https://github.com/Nelos-VZW/dives-2/assets/141562202/dc4e0be5-0727-4436-a28c-60f57c837f5e">
<img width="1120" alt="Opleidingsfiche" src="https://github.com/Nelos-VZW/dives-2/assets/141562202/6af9b7ab-c582-4d3a-b7f5-f0d7be2a110f">

**Comment by netdata-be** [comment]
Gerelateerd aan #359  ?

**Comment by MartijnBomans35686** [comment]
Lijkt er inderdaad op.

Verstuurd vanaf mijn iPhone

Op 6 aug. 2023 om 21:29 heeft Wouter ***@***.***> het volgende geschreven:

﻿

Gerelateerd aan #359<https://github.com/Nelos-VZW/dives-2/issues/359> ?

**Comment by ndsmyter** [comment]
Inderdaad duplicaat van #355 en hierdoor dus ook opgelost.
