### ISSUE TITLE
[BUG] Scrollen in het documenten centrum is best lastig

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#362]
op IOS is het lastig om te scrollen door de documenten, ga naar het documenten centrum en als ik scroll gebeurd er niets.
Dit komt omdat ik start met scrollen op een item.

Indien ik bij het starten mijn vinger plaats op de hoofditem om de devider, dan kan ik wel scrollen.

**Comment by ndsmyter** [comment]
Aiaiai, ik vind altijd grappig hoe iPhones toch ook altijd speciaal doeb 😛 Er is technisch geen enkele reden waarom die daar zou willen scrollen... We bekijken het eens.

**Comment by DIVEScoordinator** [comment]
@ndsmyter  heb deze verplaatst naar volgende versie want is i-Phone specifiek en als je weet hoe het moet...

**Comment by ndsmyter** [comment]
Dit probleem zou normaal gezien opgelost moeten zijn.
