### ISSUE TITLE
[BUG] Info verval proeven bovenaan op brevetkaart niet correct

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#363]
**Beschrijf de bug**
Enkele brevetkaarten geopend en krijg systematisch de melding dat geen enkele proef kan vervallen terwijl er wel degelijk proeven met vervaldata op de kaart staan.

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/e0c90f84-dfb9-41c3-bdcd-6aeb96d2fa4e)

**Comment by ndsmyter** [comment]
En indien het toch een probleem blijft, kan je eens NELOS id doorsturen van die persoon waar je naar keek in uw screenshot? Dan kan ik misschien kijken of ik het aan de hand van dat profiel kan reproduceren

**Comment by DIVEScoordinator** [comment]
Al onze kandidaten in de club hebben dit fenomeen, dus niets specifiek maar heel algemeen

2*D: 51156
3*D: 45288
Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: maandag 7 augustus 2023 20:43
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Info verval proeven bovenaan op brevetkaart niet correct (Issue #363)


En indien het toch een probleem blijft, kan je eens NELOS id doorsturen van die persoon waar je naar keek in uw screenshot? Dan kan ik misschien kijken of ik het aan de hand van dat profiel kan reproduceren

**Comment by ndsmyter** [comment]
Probleem lijkt te zijn omdat die personen een eerdere opleiding hadden, waarop proeven staan die zouden vervallen (of vervallen zijn). Ik heb dat normaal gezien zonet opgelost.
