### ISSUE TITLE
[BUG] ERI en NTD opleiding uren  tekenen nog niet correct af

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#364]
**Beschrijf de bug**
Aanpassing van 7 augustus tekent nu wel aantal ERD or ERD+NTD+ATD duiken af maar niet de duikuren.
Te checken voor NTD opleiding via 40424 en voor ERI opleiding onder 30380.

**Comment by ndsmyter** [comment]
Ik heb deze bug deze morgen al opgelost toen ik mail kreeg ivm #355 .

Blijkbaar had ik bij de berekening van de tijd ook identiek dezelfde code genomen om de duiken te berekenen, dus werd het aantal duiken ook gebruikt om te bepalen of je genoeg tijd had afgelegd. Ik heb deze morgen mijn code gecorrigeerd zodanig dat de tijd gebruikt wordt, zoals het hoort.

Copy-paste foutje dus :-)

**Comment by DIVEScoordinator** [comment]
Werkt nu prima!

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Tuesday, August 8, 2023 10:38:28 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] ERI en NTD opleiding uren tekenen nog niet correct af (Issue #364)


Closed #364<https://github.com/Nelos-VZW/dives-2/issues/364> as completed.
