### ISSUE TITLE
[BUG] Opleidingsverantwoordelijke aanpassen niet mogelijk

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#365]
Ik kan de opleidingsverantwoordelijke van een opleiding niet aanpassen in beide gevallen:
* Bij de start van een opleiding
* bij een reeds gestarte opleiding

De popup toont de huidige verantwoordelijke:
<img width="1137" alt="Scherm­afbeelding 2023-08-08 om 12 25 59" src="https://github.com/Nelos-VZW/dives-2/assets/494802/1ff7280a-9ab5-4fa7-be89-973b3d4ac1b3">

Echter zodra ik het veld leeg maak en begin te typen verspringt de onderliggende pagina en krijg een JSON parse error:

<img width="1146" alt="Scherm­afbeelding 2023-08-08 om 12 26 58" src="https://github.com/Nelos-VZW/dives-2/assets/494802/44b1f0d3-502c-4b8c-a599-f27afb2bedad">

**Comment by CarlAnto** [comment]
Ik ervaar hetzelfde probleem. Ik voeg nog even een screenshot toe van de foutcode die getoond werd als ik een nieuwe naam probeer in te typen in het veld van de opleidingsverantwoordelijke.

![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/6689588c-18e0-4869-8430-7dc10afeab01)

**Comment by DIVEScoordinator** [comment]
Als er in deze club geen jeugduikinstructeur is dan kan je de OPLV niet aanpassen en is dit de DSV.  Als je het veld leegmaakt kan je ook nadien de DSV niet toevoegen.  Ik heb idem issue gehad met mezelf in te schrijven voor ERD opleiding.  Dit hangt samen met tickets #277, #359 en #176  en voor dergelijke opleidingen waar niet standaard een correcte OPLV in een club aanwezig is een oplossing zoeken die werkbaar is. @ndsmyter  ter info ivm volgend overleg.

**Comment by ndsmyter** [comment]
Ik heb nu een aanpassing gedaan die het mogelijk maakt om OPLV te selecteren van buiten clubs, dit probleem zou daarmee dan ook opgelost moeten zijn.

In het overzicht voor het selecteren van de OPLV zal het volgende gebeuren:

- De DSV komt _altijd_ bovenaan in de dropdown suggesties
- De personen van de club die voldoen aan de zoekopdracht op naam en de juiste brevetten hebben komen daaronder opgelijst
- De personen buiten de club die voldoen aan de zoekopdracht op naam en de juiste brevetten hebben komen daaronder opgelijst

De lijst is in totaal maximaal 20 personen lang. Op deze manier zou het mogelijk moeten zijn om snel een OPLV te selecteren van binnen de club, maar toch mogelijkheden hebben om ook buiten clubs te selecteren.

**Comment by ndsmyter** [comment]
@CarlAnto Werkt enkel nog maar op de DEV omgeving. Dus je zal nog een beetje geduld moeten hebben om deftig te testen.
Maar om te vermijden dat we elke 5 min naar productie gaan, moeten we een beetje workload bundelen. En om te vermijden dat we overzicht houden wat wel al aangepakt en wat niet, daarom zet ik het hier in GitHub status op "Opgelost, maar nog niet op dives.nelos.be" status.
