### ISSUE TITLE
[BUG] Initialisatie van bootduiken werkt niet correct

### ISSUE THREAD

**Issue by slegers** [Nelos-VZW/dives-2#366]
**Beschrijf de bug**
Bootduiken die werden geinitialiseerd worden niet meegenomen tijdens proeven voor K3ster. 

**Verwachte resultaat**
Bootduiken die werden geinitialiseerd worden meegenomen tijdens proeven voor K3ster. (Momenteel 3boot duiken gedaan + 1 bootduik geinitialiseerd.) Momenteel staat er dat ik maar 3 van de 4 boot duiken heb uitgevoerd. 
**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   deze moet je eens bekijken, ondertussen heeft een kandidaat van mijn club 4*D ook geinitialiseerd en de volgende werken automatisch: zoetwater duiken zone 30, 20 duiken zone 40, en 30 zeeduiken zone 30.  Rest was al afgetekend via logboek DIVES

**Comment by DIVEScoordinator** [comment]
zie ook github #373 waar een voorbeeld staat rond bootduiken die niet meegenomen worden in de initialisatie

**Comment by ndsmyter** [comment]
Blijkbaar is dit specifiek probleem al opgelost, waardoor het iets te complex wordt om te achterhalen wat er nu juist verkeerd liep. Ik sluit deze taak af, en ik zie dan wel als deze terug naar boven komt met een nieuwe case die ik dieper kan bekijken.
