### ISSUE TITLE
[BUG] Negatieve initialisatie?

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#367]
Mogelijkheid om negatief te initialiseren.

In mijn Profiel staan er nu 93 ERD duiken.

ERD duiken  93 stuks   85 u 1 min

In werkelijkheid zijn er dit maar 45.

ERD   duiken: 45 :Stuks   40 u 13 min 

Hoe kan ik deze aanpassen?
Hoe wordt een onderscheid gemaakt tussen een ERD en GND duik?
De teller Nitroxduiken, omvat deze alles of zijn dit enkel de BND duiken?

**Comment by DIVEScoordinator** [comment]
Beste, 
De duiken die volgens u niet als ERD mogen meegeteld zijn dit duiken die u deed vooraleer u dit brevet had?
Om te berekenen of iets een ERD duik is hebben wij de volgende parameters ontvangen.
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/ac7b7e4b-1cac-42ac-96e6-19932c9bc9cb)


Een duik met bodemmengsel 21% en decofles wordt als nitroxduik geteld.  Ik zie het niet als GND duik, dat neem ik nog even verder op hoe dat berekend wordt maar op basis van mengsels is het bijna niet mogelijk om het verschil tussen ERD en GND duik te maken, dat gaan we ook verder navragen of een ERD duik ook een GND duik is (zoals een duik op 40m ook een duik op 30m is0:

**Comment by DelangheM** [comment]
Beste, 

 

Zowel bij een GND-duik als bij een ERD-duik is het bodemgas lucht en doe je een verkorte decompressie aan de hand van een decofles.

Het grote verschil is dat je bij een GND duik max. 20min decotrap mag hebben (was toen geen verplichting om Nitrox als bodemgas te gebruiken) met je bodemgas en dat dit niet meer van toepassing is bij een ERD duik.

Ik ben begonnen met GND-duiken vanaf 30/4/2018, proeven GND na theorie, tot 7/6/2020.
Vanaf 14/7/2020 ben ik begonnen met de ERD duiken tot 5/3/22
Nadien ben ik overgeschakeld naar een rebreather.

 

Overzicht: Met Nitrox-duiken = BND duiken. Bodemgas groter dan 21% O2.

 


ERD duiken:

2413 min

40 h

13 min

45

:Stuks


GND duiken:

1525 min

25 h

25 min

33

:Stuks


Nitroxduik:

2298 min

38 h

18 min

40

:Stuks

 

In Dives1 heb ik steeds het mengsel van de decofles ingegeven.

 

Mvg

Mario

Van: DIVEScoordinator ***@***.***> 
Verzonden: maandag 21 augustus 2023 20:53
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: DelangheM ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Negatieve initialisatie? (Issue #367)

 

Beste,
De duiken die volgens u niet als ERD mogen meegeteld zijn dit duiken die u deed vooraleer u dit brevet had?
Om te berekenen of iets een ERD duik is hebben wij de volgende parameters ontvangen.
 <https://user-images.githubusercontent.com/112652115/262122936-ac7b7e4b-1cac-42ac-96e6-19932c9bc9cb.png> 

Een duik met bodemmengsel 21% en decofles wordt als nitroxduik geteld. Ik zie het niet als GND duik, dat neem ik nog even verder op hoe dat berekend wordt maar op basis van mengsels is het bijna niet mogelijk om het verschil tussen ERD en GND duik te maken, dat gaan we ook verder navragen of een ERD duik ook een GND duik is (zoals een duik op 40m ook een duik op 30m is0:

**Comment by DelangheM** [comment]
Beste, 

 

Zowel bij een GND-duik als bij een ERD-duik is het bodemgas lucht en doe je een verkorte decompressie aan de hand van een decofles.

Het grote verschil is dat je bij een GND duik max. 20min decotrap mag hebben met je bodemgas (was toen geen verplichting om Nitrox als bodemgas te gebruiken) en dat dit niet meer van toepassing is bij een ERD duik.

Ik ben begonnen met GND-duiken vanaf 30/4/2018 tot 7/6/2020.
Vanaf 14/7/2020 ben ik begonnen met de ERD duiken tot 5/3/22
Nadien ben ik overgeschakeld naar een rebreather.

 

Overzicht: Met Nitrox-duiken = BND duiken. Bodemgas groter dan 21% O2 en geen decofles.

 


ERD duiken:

2413 min

40 h

13 min

45

:Stuks


GND duiken:

1525 min

25 h

25 min

33

:Stuks


Nitroxduik:

2298 min

38 h

18 min

40

:Stuks

 

In Dives1 heb ik steeds het mengsel van de decofles ingegeven.

Duikdiepte op 35m zetten is ook niet correct. Voor ERD is er geen minimumdiepte.
Dus in jullie geval kan een ERD duik een GND duik zijn en omgekeerd.
Volgens mij is de enige correcte trigger via het gasmengsel.
BND en GND zijn geen technische brevetten en kan via “Lucht & Nitroxduiken”.
ERD is een technisch brevet en dienen we dan onder” Technische duiken – OC” in te geven.
Als dit kan wil ik gerust de duiken vanaf 2019 aanpassen in Dives bij wijze van tests.
Duiken vroeger dan 2018 dien ik dan via de initialisatie te kunnen aanpassen. 

 

Vandaar de vraag om ook negatief te kunnen initialiseren.

 

Mvg

Mario

Van: DIVEScoordinator ***@***.***> 
Verzonden: maandag 21 augustus 2023 20:53
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: DelangheM ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Negatieve initialisatie? (Issue #367)

 

Beste,
De duiken die volgens u niet als ERD mogen meegeteld zijn dit duiken die u deed vooraleer u dit brevet had?
Om te berekenen of iets een ERD duik is hebben wij de volgende parameters ontvangen.
 <https://user-images.githubusercontent.com/112652115/262122936-ac7b7e4b-1cac-42ac-96e6-19932c9bc9cb.png> 

Een duik met bodemmengsel 21% en decofles wordt als nitroxduik geteld. Ik zie het niet als GND duik, dat neem ik nog even verder op hoe dat berekend wordt maar op basis van mengsels is het bijna niet mogelijk om het verschil tussen ERD en GND duik te maken, dat gaan we ook verder navragen of een ERD duik ook een GND duik is (zoals een duik op 40m ook een duik op 30m is0:

**Comment by ndsmyter** [comment]
We gaan geen verschil maken tussen een gewone "nitroxduik" of "ERD-duik". Wij hanteren de limieten die reeds doorgegeven worden door @DIVEScoordinator . We kunnen ons niet gaan baseren op versnelde decompressie of niet. Dit gaat te ver voor het doel waarvoor DIVES gemaakt werd.

Indien de juiste tagging toch gebruikt moet worden, kan je ook altijd persoonlijke tags gaan gebruiken om je GND of ERD duiken te gaan taggen.
