### ISSUE TITLE
[BUG] Export naar Excel werkt niet

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#368]
Export naar Excel werkt niet

**Stappen om te reproduceren**
1. klik op knop "Expoteer naar Excel"
2. Geef begin en einddatum in
3. klik op Expoteer

**Verwachte resultaat**
Excel-file van de gevraagde periode.

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.
![image](https://github.com/Nelos-VZW/dives-2/assets/112561123/15038e7e-3a60-4e50-b4d3-c68273b46199)

Eens op Exporteer geklikt gebeurt er niets meer.
Zie geen activiteit in het programma en vind ook geen file terug.
Knop Annuleer werkt dan nog wel

**Comment by AndreVanhecke** [comment]
Tegen wanneer zou dit terug moeten werken?

**Comment by DIVEScoordinator** [comment]
Doorgegeven aan endare Jira ticket #608

**Comment by ndsmyter** [comment]
@AndreVanhecke ,
Ik kan dit probleem momenteel niet reproduceren. Kan je in de huidige versie nog eens proberen?

**Comment by ndsmyter** [comment]
Ik heb net eens gecontroleerd, ticket NELOS-608 werd door Endare reeds opgepikt en staat dus ondertussen al op productie. Vandaar dat ik het niet meer kan reproduceren.

**Comment by AndreVanhecke** [comment]
Bij mij werkt de export naar Excel nu wel.
Ik zag dat de naam van mijn buddy (als het een niet-nelos buddy is) niet meegenomen wordt. Zie bijlage.
[dives2_activiteiten_export-2023-09-06.xlsx](https://github.com/Nelos-VZW/dives-2/files/12534169/dives2_activiteiten_export-2023-09-06.xlsx)

**Comment by ndsmyter** [comment]
Voor de laatste heb ik bug #381 aangemaakt en heb ik ook onmiddellijk doorgegeven aan Endare in NELOS-625
