### ISSUE TITLE
OC NTD: verkeerde tagging

### ISSUE THREAD

**Issue by MartijnBomans35686** [Nelos-VZW/dives-2#369]
Een OC NTD duik is een duik waarbij wordt gedoken met een Trimixmengsel en 2 decompressieflessen.

1) Iedere duik die als bovenstaand wordt ingegeven (Gasmengsel --> Technisch duiken OC, bodemgas met He, decompressiefles 1 en decompressiefles 2), wordt wel correct getagd als een NTD duik onder type duiken, maar wordt ook verkeerdelijk getagd als een ERD duik (Technisch duiken OC zonder toevoeging He).
2) Trimix mengsels met minder dan 20% He worden niet getagd als een NTD duik, alhoewel de infomap hierover geen richtlijnen geeft.

**Comment by DIVEScoordinator** [comment]
Beste, hierbij wat wij vanuit het technisch duiken als richtwaardes hebben gekregen om ERD, NTD te taggen
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/201b099f-01b4-4a1b-979c-d97391350c18)
Er is ergens opgegeven het aantal decoflessen.

**Comment by ndsmyter** [comment]
Aangezien dit momenteel geïmplementeerd is zoals aan ons werd doorgegeven vanuit de sectie technisch duiken, kan ik hier niet zo heel veel meer voor doen.
