### ISSUE TITLE
[Feature] Locatie-veld bij aanmaken activiteit voorzien van een 'clear'-kruisje

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#37]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
bij het invullen van de locatie bij een nieuwe duik-activiteit is er geen 'kruisje' voorzien om het input-veld terug leeg te maken

**Beschrijf de oplossing die je zou willen**
'kruisje' voorzien op het input-veld waarmee je de volledige input leeg kan maken

**Comment by ndsmyter** [comment]
Aangepast in de code

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be

**Comment by davegeysemans** [comment]
Dit kruisje is alleen maar beschikbaar als je iets intypt dat effectief ook
in de lijst van locaties tevoorschijn komt. Als je een onbekende naam
intypt, dan is het kruisje er niet.

**Comment by ndsmyter** [comment]
Inderdaad.
Dat werkt op zelfde manier als bij deelnemers.

Maar anderzijds ga je die locatie toch ook niet veel willen leegmaken? Je zoekt naar een locatie en gaat de naam misschien licht willen aanpassen, maar toch zelden volledig weg doen?

Zie dus de use case nog niet onmiddellijk voor het volledig weg doen van de tekst. Open voor suggesties natuurlijk
