### ISSUE TITLE
[BUG] Clubbeheer-Clubinformatie geeft niet iedereen weer

### ISSUE THREAD

**Issue by KamielKempeneers** [Nelos-VZW/dives-2#371]
Onder de tab clubinformatie (clubbeheer) worden maar een beperkt aantal personen weergegeven, en er is geen mogelijkheid om verder te scrollen naar de anderen.
Nochtans zitten alle personen met de juiste rollen in de databank, want door de sorteervolgorde aan te passen (vb achternaam Z->A ipv A->Z) worden die wel zichtbaar.

**Stappen om te reproduceren**
1. Ga naar 'club' (in mijn geval 'Salvanos')
2. Klik op 'clubinformatie'

4. Zie fout

**Verwachte resultaat**
Hetzij meer personen (iedereen) zichtbaar maken in de lijstweergave, hetzij de mogelijkheid verder door te scrollen naar degenen die (nog) niet zichtbaar waren

**Screenshots**

![image](https://github.com/Nelos-VZW/dives-2/assets/115356929/9a424666-9004-4498-ba65-e3ec11dd7626)

![image](https://github.com/Nelos-VZW/dives-2/assets/115356929/ee712ae3-f426-4096-8654-7ea946f3ec53)

Zelfde weergave zowel op desktop als smartphone
**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows
 - Browser: Firefox
 - Versie:

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: Galaxy S23
 - Besturingssysteem: Android
 - Browser: Firefox
 - Versie:

**Extra informatie**

**Comment by ndsmyter** [comment]
Hey @KamielKempeneers ,
Ik snap niet zo goed dat dit niet werkt bij jou, want ik kan dit perfect laten werken op mijn computer en GSM. Ik kan in beide richtingen scrollen.

Ik heb dit wel geprobeerd in Chrome.

Maar als dit werkt in Chrome, zou dit normaal gezien ook moeten werken in Firefox. We mikken sowieso voornamelijk op Chrome qua ondersteuning, aangezien dit de meest gebruikte browser is (>60%) [[bron]](https://gs.statcounter.com/browser-market-share)

Dus ik zou voorstellen dat je eens probeert in Chrome, en hopelijk is het daarmee dan opgelost.

**Comment by ndsmyter** [comment]
Ik kan dit probleem niet reproduceren op de huidige versie. Wat ik ook probeer, ik krijg altijd alle personen te zien. Ik zie dat er eigenlijk maar 1 load is, en dat daarna niet meer naar de server gegaan wordt als de sortering verandert. Dus het "verdwijnen" van de personen zou dan in de frontend moeten gebeuren. Maar de frontend heeft ook niets van filters ingesteld blijkbaar, die toont gewoon alles wat binnenkomt.
