### ISSUE TITLE
[BUG] Dubbele proef in opleiding AI

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#372]
**Beschrijf de bug**
Voor de opleiding AI is er proef dubbel "Zwembadles geven als stage 1" de eerste is afgevinkt, een tweede is nadien toegevoegd.

**Verwachte resultaat**
Dubbele proef verwijderen.

![Screenshot_2023-08-20-17-26-05-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nelos-VZW/dives-2/assets/93061973/cbeb59c9-633d-4b30-9d85-9c38f02e0c6b)

**Comment by ndsmyter** [comment]
@DwfBE Dit is eigenlijk een fout dat nog meekomt uit DIVES 1. In DIVES 1 ontstonden er in speciale gevallen waarbij een proef van Zwembadlessen dubbel voorkwam. We hebben nooit begrepen waarom dat probleem ontstaan is, want in de code en databank van DIVES 1 was het te moeilijk om daar je weg in te vinden.

In DIVES 2 kan ik dat probleem op zich wel oplossen, maar dan moet ik het NELOS ID van de kandidaat in kwestie hebben. Want het is ook niet voor alle kandidaten het geval.

Laat je me iets weten, dan bekijk de brevetkaart van die persoon eens.

**Comment by DwfBE** [comment]
Bedankt voor de feedback!
Bij ons twee leden:
46863 - Frans De Wolf
48215 - Niels Van Bouwel

**Comment by ndsmyter** [comment]
Bij deze in orde
