### ISSUE TITLE
[BUG] Initialisatie niet OS werkt niet correct

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#373]
**Beschrijf de bug**
Voor de opleiding 1\*I, 2\*I en 3\*I moet je een aantal duiken hebben niet OS > 25m. De duiken als initialisatie ingebracht worden niet meegenomen in de berekening van deze voorwaarde.  Hieronder voorbeeld vanuit DEV omgeving:
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/db5be7be-4a01-446a-9fa4-36123f3e5113)

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/103091aa-cda2-4fa7-9f51-d4b73e4d3b65)

**Comment by ndsmyter** [comment]
Zou nu opgelost moeten zijn op productie en dev, test komt maandag ook automatisch.
