### ISSUE TITLE
[BUG] TEST omgeving blokkeert

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#374]
**Beschrijf de bug**
Test omgeving gaat niet meer open:
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/77578aab-35bf-40df-bb1a-19a134e098d5)

**Comment by ndsmyter** [comment]
Bij het aanmaken van de view in de databank voor Ivo (ivm onkostenvergoedeing) had ik blijkbaar niet de juiste rechten gegeven aan die view. Ik heb dat nu rechtgezet, en de import van de testdatabank herstart. Hopelijk is het deze keer wel OK :-)
