### ISSUE TITLE
categorisering type duiken

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#375]
Klopt de indeling van deze duiken? 
13 duiken: 11 zoetwaterduiken / 12 zeeduiken / ....

Of iemand mag mij uitleggen hoe de indeling in elkaar zit ;-)

**Screenshots**

![Jordy](https://github.com/Nelos-VZW/dives-2/assets/112781010/5c2b3a16-9a28-4411-b43e-7e7c5f35a9b9)

**Comment by DIVEScoordinator** [comment]
Lijkt erop dat de heldere zeeduinen ook als zoetwater zijn gelabeld.  Exact evenveel minuten, enig idee waarmee gedoken werd?

**Comment by ndsmyter** [comment]
Daar haal je mogelijks wel een geldig punt aan @DIVEScoordinator . Misschien is het "zoet" ipv "zout" water geworden voor de gedoken locaties. Is maar 1 letter verschil, maar maakt in code natuurlijk groot verschil.

Ik probeer dat binnenkort eens te bekijken; bij de dagelijkse herberekening zal dat dan sowieso wel rechtgezet worden als ik de aanpassing gedaan heb.

**Comment by DIVEScoordinator** [comment]
Er is een aanpassing gebeurd in de tag wereld(zoet) waar verkeerd ook heldere zee bijstond. We kunnen niet checken of dit het probleem oplost omdat van de kandidaat het ID niet zichtbaar is. Kan je dit even doorgeven zodat we kunnen checkedn of het nu allemaal ok is of er nog andere duikplaatsen verkeerde tagging hebben. @AndreVanhecke

**Comment by AndreVanhecke** [comment]
![image](https://github.com/Nelos-VZW/dives-2/assets/112781010/13d7defe-5484-4c33-a607-1c4585350fa8)

**Comment by DIVEScoordinator** [comment]
@ndsmyter   met 14 duiken zijn er maar 12 getagd - 11 met zoet en 1 met zee/getijde.  Vermits dit een beperkt aantal duiken is toch interessant om in de databank te kijken welke plaats dan niet getagd wordt met zee of zoet of indoor.  
Ik sluit dit wel af want probleem van heldere zee is wel opgelost<
