### ISSUE TITLE
 teller komen bij het  vereiste aantal duiken  

### ISSUE THREAD

**Issue by Fabmichiels** [Nelos-VZW/dives-2#376]
Niet duidelijk hoeveel  vereiste duiken een kandidaat nog moet doen. 

Kan er een tellerstand komen bij het onderdeel vereiste aantal duiken voor een bepaald brevet aub. Dat is duidelijker dan het streepje dat je nu ziet. 

Bedankt

**Comment by ndsmyter** [comment]
Op een computer kan je gewoon met je muis over dat streepje gaan om de details te zien. Op een mobiel toestel (smartphone of tablet) kan je dat inderdaad niet, en kunnen we mogelijks wel wat verbeteren. Maar ik zet het even op "Low priority", want is op dit moment niet zo dringend.

**Comment by Fabmichiels** [comment]
Bedankt voor je antwoord.

vriendelijke groeten,
Faby Michiels
tel +32476357711

Op ma 28 aug. 2023 14:39 schreef Nicolas De Smyter ***@***.***
