### ISSUE TITLE
Fout in aantal afgelegde proeven in rapportering ? 

### ISSUE THREAD

**Issue by Fabmichiels** [Nelos-VZW/dives-2#377]
Een kandidaat 2ster D  heeft 1 niet geslaagde DL.  
In  ' rapportering ' staat voor die kandidaat in het overzicht   :  11/11 . De niet geslaagde dl wordt dus meegeteld.  
Op brevetkaart staat die dl nog in opleiding (wat correct is)

**Comment by ndsmyter** [comment]
Kan je het NELOS ID van deze persoon eens linken?
En eventueel eens wat screenshots doorsturen, want nu is het een beetje vaag om te gaan uitzoeken wat het probleem is.

**Comment by Fabmichiels** [comment]
Zie bijlagen



vriendelijke groeten,
Faby Michiels
tel +32476357711

Op ma 28 aug. 2023 14:40 schreef Nicolas De Smyter ***@***.***

**Comment by ndsmyter** [comment]
@Fabmichiels ,
Jammer genoeg kan ik de bijlagen niet zien als die via mail aangehangen waren. Ik vermoed dat je dus best het GitHub ticket opent ( https://github.com/Nelos-VZW/dives-2/issues/377 ) en daar een nieuwe commentaar met de bijlagen maakt.

**Comment by DIVEScoordinator** [comment]
in de rapportering worden ook de proeven in opleiding of die nog moeten afgetekend worden meegenomen in het aantal.  Best aan te passen dat enkel effectief geslaagde proeven getoond worden zodat het sneller zichtbaar is wie nog items niet in orde heeft.
