### ISSUE TITLE
[BUG] Bootduiken via initialisatie worden niet meegenomen om voorwaarde af te tekenen

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#378]
**Beschrijf de bug**
Indien je onvoldoende bootduiken in DIVES hebt en initialiseert je bootduiken van voor 2019 dan worden deze niet afgetekend.
Zie hieronder screenshots van Carl die zich als 2*I in testomgeving inschreef.
**Stappen om te reproduceren**
![1000023017](https://github.com/Nelos-VZW/dives-2/assets/112652115/fcd24c73-ae92-412b-9b6e-892dc1aded1c)µ
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/90b0189d-3eb6-4d40-a1ae-d6ef2f3d4407)

**Comment by ndsmyter** [comment]
@DIVEScoordinator Probleem is eigenlijk dat die "10 zeeduiken van boot" eigenlijk tweeledig is. Je hebt het gedeelte "zeeduiken" en het gedeelte "boot". Het gedeelte "boot" kunnen we wel tellen adhv de tag "Bootduik", maar daarmee weten we dan in feite nog niet dat je ook effectief in zee gedoken hebt.

We zouden wel kunnen stellen dat de meeste bootduiken ook effectief op zee gebeuren, maar er zijn plaatsen waar je op een meer ook van een boot kan duiken. Lac de l'eau d'heure schiet me zo te binnen. Het is wel uitzondering.

@DIVEScoordinator Wat doen we? Gewoon gedeelte "zeeduik" even negeren en enkel kijken naar bootduiken voor de initialisatie?

**Comment by ndsmyter** [comment]
Zal door @CarlAnto opgenomen worden met het NELOS-secretariaat om dit via een vrijstelling te doen.
We kunnen beter vrijstellingen gebruiken om dergelijke uitzonderingen op te vangen, in plaats van de code/applicatie minder correct te maken. Met de tijd zal het aantal dergelijke uitzonderingen ook verminderen, aangezien mensen dan hun duiken in DIVES zullen zitten.
