### ISSUE TITLE
[BUG] Ledenadministratie - Onmogelijk om een een jeugdduiker in te schrijven voor DHV

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#379]
Ook een jeugdduiker kan zich aanmelden voor een opleiding DHV.
Echter dit is niet beschikbaar bij de keuze die ik krijg.

**Comment by DIVEScoordinator** [comment]
Wordt aangepast als module brevetten afgerond is. Zal wel nog enkele weken duren.  Dringend?

**Comment by netdata-be** [comment]
Het examen DHV is voorzien voor 14 oktober, dus bij voorkeur iets voor die datum.
Ik vermoed als het niet lukt tegen die tijd dat het secretariaat dit ook wel kan doen?

**Comment by DIVEScoordinator** [comment]
Beste
inschrijvingen voor DVH in DIVES kan enkel voor leden ingeschreven onder lucht@nitrox.  Op termijn gaan we hier een oplossing voor zoeken maar in tussentijd moet je dergelijke kandidaten als volgt inschrijven:

•	Als de persoon 14 jaar is: inschrijven voor lucht&nitrox, laten inschrijven voor DHV, daarna L&N terug laten verwijderen.
•	Als de persoon geen 14 jaar is;  de betrokkene  doorgeven aan Lien (via nelos secretariaat mail adres) die de DHV-dingen doet en die kan die behandelen als ‘extern aan NELOS’. En dan in agenda zetten die DHV toe te kennen na 14de verjaardag

**Comment by ndsmyter** [comment]
Zou sinds deze namiddag opgelost moeten zijn.
