### ISSUE TITLE
[BUG] in logboek duik openen, persoonlijke tags beheren, annuleer => scherm blanco

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#38]
**Beschrijf de bug**
bij het annuleren van beheren persoonlijke tags en dan annuleren kiezen. Het scherm is daarna blanco

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar een gelogde duik
2. Klik op 'Beheer je persoonlijke tags'
3. Klik op  'Annuleer'
4. blanco scherm wordt getoond

**Verwachte resultaat**
Terug het scherm van de geopende duik tonen

zowel desktop als iphone - beide met safari browser

**Comment by ndsmyter** [comment]
Dit probleem zou opgelost moeten zijn na een nieuwe deploy op maandag

**Comment by ndsmyter** [comment]
Duplicaat van #22

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
