### ISSUE TITLE
Clubinformatie geeft een dubbele functies

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#380]
Voor sommige functies worden dubbel aangegeven.

Trouwens de penningmeester is sinds kort, NELOSID 2793 (Gert Mattheussen), kan ik dat via hier laten veranderen of moet dat via Ivo Hubert of NELOS secretariaat?

![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/2905cd75-6b6f-48ac-8a02-77336ad67d4d)

**Comment by DIVEScoordinator** [comment]
Aanpassingen club bestuur dienen via het secretariaat te gebeuren.

Ik kan dit niet reproduceren en vermits we nog een ticket hierover hebben binnengekregen ivm aantal zichtbare functies lijkt mij dit een browser/computer specifiek probleem.  Op te volgen bij TWIZZIT integratie met DIVES

**Comment by DIVEScoordinator** [comment]
Koen ik ook op drie computers en iPhone. Zie het altijd maar 1 keer. Ook al ledenadministratie gecheckt met Ivo Hubert of jullie er dubbel instaan. Ook niet het gevallen dus heel vreemd

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Monday, September 4, 2023 9:16:29 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Clubinformatie geeft een dubbele functies (Issue #380)


Niks browser/computer specifiek. Getest op 2 computers en verschillende browsers. Chrome, Firefox, Edge

**Comment by ndsmyter** [comment]
Kan ook wel zijn dat het voor de club van Koen is dat er iets vreemd in de databank zit langs de kant van DIVES. Ik zal deze week eens nakijken wat het probleem is, maar is natuurlijk niet zo prioritair omdat er niets in brand staat :-) Maar ik moet daar toch eens naar kijken wat Endare daar gedaan heeft in kader van andere ticketjes ook.

**Comment by DIVEScoordinator** [comment]
Misschien omdat zij ook vrijduiken aanbieden?

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Monday, September 4, 2023 10:55:53 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Clubinformatie geeft een dubbele functies (Issue #380)


Kan ook wel zijn dat het voor de club van Koen is dat er iets vreemd in de databank zit langs de kant van DIVES. Ik zal deze week eens nakijken wat het probleem is, maar is natuurlijk niet zo prioritair omdat er niets in brand staat :-) Maar ik moet daar toch eens naar kijken wat Endare daar gedaan heeft in kader van andere ticketjes ook.

**Comment by ndsmyter** [comment]
Probleem is blijkbaar omdat de personen die dubbele rollen hebben ook in meerdere clubs zitten. Hierdoor tellen ze meerdere keren mee in de lijst. Maar het feit dat ze in meerdere clubs zitten zou geen impact mogen hebben op deze tabel, dus dat heb ik zonet aangepast.

**Comment by DIVEScoordinator** [comment]
Dacht het al dat het hiermee te maken had.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Tuesday, September 5, 2023 8:44:09 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Clubinformatie geeft een dubbele functies (Issue #380)


Closed #380<https://github.com/Nelos-VZW/dives-2/issues/380> as completed via ***@***.***

**Comment by KWillemse** [comment]
Ik vermoed niet dat het hier mee te maken heeft want ik weet zeker dat Bob en Tom geen dubbele rollen hebben in meerder clubs en van mezelf ben ik heel heel zeker.

**Comment by ndsmyter** [comment]
@KWillemse 
Heeft heel zeker hiermee te maken. Mijn commentaar is geschreven nadat ik het opgelost heb in de code.
Zou nu namelijk opgelost moeten zijn.

**Comment by KWillemse** [comment]
Nu is het inderdaad opgelost, in het zou perfect kunnen dat in jullie database we meerdere rollen hebben in meerdere clubs maar in het echte leven niet hoor. Ik zit maar in 1 club.... Ik heb daar wel meerdere rollen en Tom ook. Bob zit maar in 1 club en heeft maar 1 rol.

**Comment by DIVEScoordinator** [comment]
Vrijduiken en luchtbuizen zijn twee rollen 😉

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Wednesday, September 6, 2023 8:30:40 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Clubinformatie geeft een dubbele functies (Issue #380)


Nu is het inderdaad opgelost, in het zou perfect kunnen dat in jullie database we meerdere rollen hebben in meerdere clubs maar in het echte leven niet hoor. Ik zit maar in 1 club.... Ik heb daar wel meerdere rollen en Tom ook. Bob zit maar in 1 club en heeft maar 1 rol.

**Comment by KWillemse** [comment]
Dan klopt het wel
