### ISSUE TITLE
[BUG] Proef met voorwaarden aftekenen

### ISSUE THREAD

**Issue by slegers** [Nelos-VZW/dives-2#382]
**Beschrijf de bug**
Voor bepaalde proeven(c5 bv) te kunnen laten aftekenen moet je aan een aantal voorwaarden voldoen. (Bijvoorbeeld meer dan 25 duiken hebben in zone 25. Wanneer je echter aan dit aantal diepe duiken komt kan je deze proef toevoegen aan iedere voorgaande duik (voor die 25 behaalde duiken.)

Ik zou verwachten dat je deze proef pas kan aftekenen/toevoegen bij iedere duik startende vanaf je behaalde diepe duiken en dus niet bij de voorgaande duiken. 

**Stappen om te reproduceren**
1. Ga naar Logboek en vul minstens 25 duiken in die dieper zijn dan 25 meter
2. Klik op een eerste duik en voeg proef C5 toe (als je bezig bent met 3ster d)
4. Zie fout ( je kan deze proef laten aftekenen.)

**Verwachte resultaat**
Ik zou verwachten dat je deze proef pas kan aftekenen/toevoegen bij iedere duik startende vanaf je behaalde diepe duiken en dus niet bij de voorgaande duiken. 

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Comment by ndsmyter** [comment]
Het is op zich wel een correcte opmerking, maar op dit moment vinden we dat eigenlijk niet echt een bug. We hopen dat (assistent-) instructeurs in dergelijke gevallen zelf ook nog eens kijken of de voorwaarden op dat moment voldaan waren.

Moesten we dit toch willen doen, dan zouden we voor elke voorwaarde moeten bijhouden sinds welke activiteit of tijdstip die afgewerkt werd, en dat is nu ook net iets te veel informatie om te gaan bijhouden.
