### ISSUE TITLE
[BUG] Layout van opleidingskaart niet ok

### ISSUE THREAD

**Issue by Cereal2nd** [Nelos-VZW/dives-2#384]
**Beschrijf de bug**
Je kan hier een korte en bondige beschrijving geven van de bug.

Zie screenshot

**Screenshots**

![Screenshot_20230919-172930.png](https://github.com/Nelos-VZW/dives-2/assets/3715825/260924e6-a981-4dab-871a-f7aee80624c5)

**Comment by ndsmyter** [comment]
Gelogd bij Endare als NELOS-632

**Comment by ndsmyter** [comment]
Probleem zou sinds deze middag opgelost moeten zijn. Bekijk je nog eens?

Ik sluit deze taak alvast af.
