### ISSUE TITLE
Grotduiken en Sidemount zijn niet meer zichtbaar

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#385]
**Beschrijf de bug**
In het overzicht van de 'Type' duiken in 'Mijn Profiel' zijn de Grotduiken en Sidemount duiken niet meer zichtbaar.
Zie afbeelding in #315 => grot en sidemount zichtbaar (juni 2023)

**Zie onderstaande onderstaande afbeelding => grot en sidemount zijn weg**

![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/56be5009-dac9-48a3-b56a-611bc611a7b5)

**Bij het ingeven van een duik kan je ook niet meer kiezen voor 'Grot' of 'Sidemount', zie afbeelding hieronder:**

![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/30013574-ab00-419d-bda5-900393c4fe1f)

**Comment by ndsmyter** [comment]
Grotduiken worden getagd aan de hand van de locatie.
Sidemount en scooter kan je taggen eenmaal de activiteit aangemaakt is. Dit omdat die tags persoonlijk zijn, tov de tag Bootduiken die voor iedereen geldt.

Dus in feite is alles nog steeds zoals het zou moeten werken en lijkt mij dit geen bug?

**Comment by KWillemse** [comment]
Grotduiken, dat begrijp ik, maar het feit dat sidemount en scooter op een andere manier werkt dan bootduiken, lijkt me verwarrend en dat is nu ook bewezen. De persoon die dit escaleerde had al grotduiken en sidemount gedaan en die was dus weeral vergeten hoe het werkte...

**Comment by KWillemse** [comment]
Dat overzicht bevat ook geen grot/sidemount duiken meer. Is daar een reden voor?

**Comment by KWillemse** [comment]
**Links = Juni 2023, rechts = nu**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/f5083487-b51d-4a2e-86b6-0548b9c0d168)
