### ISSUE TITLE
[Feature] Melding bij nieuwe opmerking

### ISSUE THREAD

**Issue by Calinatus** [Nelos-VZW/dives-2#386]
Momenteel krijgen mededuikers geen melding in DIVES als door een andere duiker in de duikploeg, na het loggen van een duik, een opmerking wordt geplaatst bij die duik. Kan interessant zijn, ook voor feedback van (assistent-)instructeurs bij proeven.

Merk op dat er bij de vorige versie van DIVES wel nog meldingen waren bij opmerkingen, nu niet meer.

**Comment by ndsmyter** [comment]
@DIVEScoordinator Kan jij dit eens testen aub?

**Comment by DIVEScoordinator** [comment]
Getest gisteren commentaar bij Wim ingebracht duik met mij en ik krijg geen melding in mijn inbox in DIVES

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Monday, December 18, 2023 9:07:43 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [Feature] Melding bij nieuwe opmerking (Issue #386)


@DIVEScoordinator<https://github.com/DIVEScoordinator> Kan jij dit eens testen aub?

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare: NELOS-659

**Comment by DIVEScoordinator** [comment]
dit is geimplementeerd bij volgende release (eind juli)
