### ISSUE TITLE
Vervallen proef niet te identificeren

### ISSUE THREAD

**Issue by FrankyCardoen** [Nelos-VZW/dives-2#387]
![image](https://github.com/Nelos-VZW/dives-2/assets/141068467/ccef750e-bf6d-44b7-a399-262b8241ae3e)
Hallo,
Bij Kandidaten - Dirk Hof - Opleiding GND 
Eerste proef verviel op 29/03/2023
Alle vrijstellingen staan nog steeds aangevinkt. Het is dus niet te achterhalen of er iets moet opnieuw gedaan worden.
Mvg,
Franky

**Comment by ndsmyter** [comment]
@FrankyCardoen ,
Sinds deze namiddag is er een nieuwe versie van DIVES waarin dit een beetje herwerkt werd. Ik weet niet of je bovenstaande probleem nog kan bekijken, of dat de persoon ondertussen gehomologeerd is.

Ik ga deze taak afsluiten, maar heropen gerust moest dit probleem er nog steeds zijn. Ik kan het zelf niet reproduceren in elk geval.
