### ISSUE TITLE
[BUG] Automatisch afvinken nitrox duiken GND

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#388]
**Beschrijf de bug**
Jozsef Jansen (NELOS 36720) heeft 10 nitrox duiken uitgevoerd. Deze worden niet automatisch afgevinkt voor zijn opleiding GND (8/10 duiken uitgevoerd)

**Verwachte resultaat**
Correct weergeven op de proef waardoor deze automatisch kan worden afgevinkt.

**Screenshots**
![Screenshot_2023-10-14-14-01-13-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nelos-VZW/dives-2/assets/93061973/630f1ee6-81aa-40b6-a89a-ec549a20b403)

**Comment by ndsmyter** [comment]
@DwfBE ,
Er werden in lijn met deze bug al recent een paar aanpassingen gedaan. Ik zou vermoeden dat daarmee het probleem opgelost zou moeten zijn.
Ik sluit het ticket alvast af. Moest dit probleem er toch nog steeds, heropen dan gerust dit ticket.
