### ISSUE TITLE
Ik kan geen duikplaats toevoegen voor persoonlijk gebruik.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#389]
**Beschrijf de bug**
Als ik een duikplaats gebruik die niet gekend is, dan kan ik deze positioneren op de kaart, maar als ik dan de duik wil loggen/aanpassen dan krijg een foutmelding.

**Stappen om te reproduceren**
1. Ga naar 'een gelogde duik'
2. Klik op 'aanpassen'
3. Typ een nieuwe duikplaats in
4. Zet het 'duikvlagje' op een bepaalde plaats
5. Kies 'Aanpassen' van de duik
6. Zie de foutmelding (screenshot toegevoegd)

**Verwachte resultaat**
Volgens de 'DIVES' Help pagina zou dit toch mogelijk moeten zijn.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/6bc3305d-697f-4574-8d7d-b8f30a3afad5)

**Comment by DIVEScoordinator** [comment]
Is mij gisteren nog gelukt. Je moet ook de zone selecteren.

**Comment by KWillemse** [comment]
Sorry, maar het lukt mij niet.
Ik heb een duik  gelogd aan de 'Middellandse Zee - Zuid-Frankrijk - Cavalaire - Prophète (wrak)' maar ik had deze locatie gekozen omdat dit het dichts bij de eigenlijke locatie was.

1. ik kies 'aanpassen'
2. verander de naam naar 'Middellandse Zee - Zuid-Frankrijk - Cavalaire - Cap Taillat', 
3. ga naar het kaartje en kies de locatie op de kaart en zet het vlagje
4. kies dan zone 'Middellandse Zee',
5. klik OK
6. kies dan 'aanpassen' om te bevestigen
En dan krijg ik die error.

Chrome en Firefox

**Comment by DIVEScoordinator** [comment]
Je mag niet eerst iets kiezen. Je moet de naam ingeven en dan scrollen op de kaart. Anders lukt het niet. Nog niet gebruiksvriendelijk.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Wednesday, October 18, 2023 1:36:52 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Ik kan geen duikplaats toevoegen voor persoonlijk gebruik. (Issue #389)


Sorry, maar het lukt mij niet.
Ik heb een duik gelogd aan de 'Middellandse Zee - Zuid-Frankrijk - Cavalaire - Prophète (wrak)' maar ik had deze locatie gekozen omdat dit het dichts bij de eigenlijke locatie was.

  1.  ik kies 'aanpassen'
  2.  verander de naam naar 'Middellandse Zee - Zuid-Frankrijk - Cavalaire - Cap Taillat',
  3.  ga naar het kaartje en kies de locatie op de kaart en zet het vlagje
  4.  kies dan zone 'Middellandse Zee',
  5.  klik OK
  6.  kies dan 'aanpassen' om te bevestigen
En dan krijg ik die error.

Chrome en Firefox

**Comment by KWillemse** [comment]
Dus het werkt alleen als je een nieuw duik logt? Ik begrijp niet goed wat je bedoeld met 'Je mag niet eerst kiezen'?

**Comment by KWillemse** [comment]
Met 'ik kies 'aanpassen', bedoelde ik. Ik kies 'Activiteit aanpassen'.

**Comment by DIVEScoordinator** [comment]
Het loopt vast als je een bestaande plaats wilt overschrijven met een eigen naam.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Wednesday, October 18, 2023 2:06:58 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Ik kan geen duikplaats toevoegen voor persoonlijk gebruik. (Issue #389)


Met 'ik kies 'aanpassen', bedoelde ik. Ik kies 'Activiteit aanpassen'.

**Comment by KWillemse** [comment]
OK, het werkt inderdaad voor een nieuwe duik. Goed om te weten. Misschien kan je deze info toevoegen aan de Help pagina:
Kan ik zelf duikplaatsen toevoegen?
Ja, dat is mogelijk, maar op dit moment alleen voor persoonlijk gebruik **en alleen bij het aanmaken van een nieuwe duik**.
