### ISSUE TITLE
[Feature] Tonen van gebruikte gassen tijdens de duik

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#39]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Een gelogde duik in productie-dives waar andere gassen toegevoegd zijn. Als ik deze editeer in die productie-dives dan kan ik daar de gebruikte gassen zien. In dives 2 niet.

**Beschrijf de oplossing die je zou willen**
De gebruikte gassen tonen, en ook niet alleen als je de duik wil bewerken.

**Comment by ndsmyter** [comment]
De gassen moeten nog geïmplementeerd worden, ik zet deze dus even on hold.
