### ISSUE TITLE
De eerste proef die vervalt moet de datum van het aantal duiken niet mee in rekening brengen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#390]
**Beschrijf de bug**
Bij een K2*duiker is één van de '2*D: OW-proeven en duikleidingen' de voorwaarde: '15 duiken in openwater tussen 10 en 20 meter '
De datum van deze voorwaarde is soms vermeld als vervaldag van de eerste proef, maar deze voorwaarde kan eigenlijk niet vervallen.

**Stappen om te reproduceren**
kijk even naar de 'detailkaart' van bijvoorbeeld:  Eric HERBOSCH 1*D NELOS ID: 41127 

**Verwachte resultaat**
de datum van de eerste proef die vervalt mag enkel een theorieles of OW-proef en Duikleiding zijn. Voorwaarden kunnen in principe niet vervallen en die datum mag dus niet genomen worden om aan te geven als vervaldag van de eerste proef.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/324cb9b6-cd2b-4436-9a9f-e7f58fd032f9)

**Comment by ndsmyter** [comment]
Vrijstellingen hebben ook een einddatum. Aangezien het gaat over een automatische vrijstelling, zal deze vrijstelling ook wel terug automatisch opnieuw afgetekend worden op het moment van vervallen. Als de nodige voorwaarden natuurlijk nog steeds voldaan zijn.

Mijn inziens werkt dat dus wel naar behoren en correct; dus ik sluit dit af.
