### ISSUE TITLE
Ex-leden inschrijven voor een opleiding

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#391]
**Beschrijf de bug**
Wanneer je als ledenadmin/secretaris in je cluboverzicht scrollt dan krijg je een slider te zien waarmee je de oud-leden zichtbaar kan maken.
Voor een van onze oud-leden probeerde ik een inschrijving te vervolledigen. Ik kreeg een foutmelding terug maar als je de opleidingskaart bekijkt dan is de opleiding daadwerkelijk geopend.

**Stappen om te reproduceren**
1. Ga naar 'cluboverzich'
2. Klik op 'filter, en verander actieve leden naar alle leden'
4. Scroll naar 'start opleiding (bij een niet-lid'
5. Foutmelding komt naar voor
6. Na het openen van de opleidingskaart is de opleiding toch actief (in dit geval bij iemand die zelfs volledig niet meer duikt.)

**Verwachte resultaat**
Opleidingen kunnen enkel gestart worden bij de huidige leden.

**Comment by ndsmyter** [comment]
Ik heb het doorgegeven aan Endare in NELOS-647

**Comment by ndsmyter** [comment]
Zou nu opgelost moeten zijn.
