### ISSUE TITLE
[BUG] Nitroxduiken komen niet in statistiek overzicht indien nul-waarde in statistieken

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#392]
**Beschrijf de bug**
Nitroxduiken statistiek is niet zichtbaar indien je in de initialisatie een nul-waarde h ebt staan

**Stappen om te reproduceren**
1. Ga naar 'statistieken'
2. Klik op zie geen nitroxduiken lijn staan
3. nitroxduiken zijn wel degelijk ingebracht en het werkt wel indien je al nitroxduiken statistiek hebt
**Verwachte resultaat**
nitroxduiken statistiek moet geteld ongeacht een nulwaarde in de intialisatie

**screenshots
FIGUUR 1: met nulwaarde in de initialisatie
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/53bb7800-64ce-468f-86aa-73de985b0d53)

FIGUUR 2: met ingevulde waarde in de initialisatie

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/c36b59d5-ce82-4503-a2da-991df1f1745c)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS]
 - Browser: [bv chrome, safari]
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Probleem is opgelost, en zal mee komen naar productie met de volgende release.
