### ISSUE TITLE
[Feature] Default persoonlijke tags

### ISSUE THREAD

**Issue by revodiver** [Nelos-VZW/dives-2#393]
Ik duik bv altijd met een rebreather dus ik zou graag hebben dat elke nieuw duik ik log mijn standaard tag CCR gebruitk wordt.
Of zoals bootduiken iets kan aanvinken ipv altijd naar tags te gaan.

Dus in profiel een standaard tag kunnen kiezen zou handig zijn.

**Comment by DIVEScoordinator** [comment]
bootduik is een tag die voor de ganse ploeg geldt, duiken met een rebreather is een persoonlijke tag en dat gaan we niet kunnen verplaatsen. Deze even op hold; in de toekomst kan overwogen worden om bepaalde tags standaard aan te kruisen via een beheersplatform maar dat zal eerder voor 2025 zijn.

**Comment by ndsmyter** [comment]
Deze functionaliteit zal in de volgende versie beschikbaar worden. Via `Profiel > Favorieten` zal je bepaalde instellingen kunnen kiezen die standaard toegepast zullen worden bij nieuwe activiteiten.
