### ISSUE TITLE
Foutief aantal ERD duiken

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#394]
**Beschrijf de bug**
Ik heb enkel de nodige ERD duiken gedaan die nodig waren voor de opleiding ERD. Toch staan er 53 ERD duiken in mijn profiel

<img width="399" alt="Schermafbeelding 2023-11-27 om 16 48 11" src="https://github.com/Nelos-VZW/dives-2/assets/112781010/71f97a68-e361-4767-9e6e-ab42fd63af6e">

**Verwachte resultaat**
Juiste aantal ERD duiken

**Screenshots**
zie bijlage

**Comment by ndsmyter** [comment]
Dat is een gekend probleem aangezien voor DIVES alle GND duiken ook als ERD duiken aanzien zijn. Er is geen manier voor DIVES om dit automatisch te detecteren. Dus van zodra je ERD bent, zullen alle GND duiken ook als ERD tellen.

We kunnen hier op dit moment niet heel veel aan doen.
