### ISSUE TITLE
[BUG] Voorwaarden niet altijd even goed zichtbaar in viewport

### ISSUE THREAD

**Issue by JonCot** [Nelos-VZW/dives-2#395]
**Beschrijf de bug**
Bij een groot aantal voorwaarden voor een proef verdwijnt een deel achter de viewport en zijn deze niet zichtbaar. Uitzoomen, kan maar dan is de tekst niet leesbaar. Zelfde probleem doet zich voor op de gsm, daar kan echter niet uitgezoomd worden.

**Stappen om te reproduceren**
1. Ga naar Profiel
2. Klik op Opleidingen
3. Open submenu indien nodig
4. Scroll naar een proef met heel veel voorwaarden
5. Zie fout

**Verwachte resultaat**
In Dives 1.0 werd een lijst gebruikt en werd alles onder elkaar weergegeven. Met de huidige weergave wordt alles naast elkaar weergegeven, ofwel terug in lijstvorm presenteren, ofwel de scroll functie gebruiken

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/11026392/64e4986f-71f1-49f2-97c0-f20ed9e14eb3)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows 11
 - Browser: Chrome
 - Versie: Versie 119.0.6045.160

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: iPhone14
 - Besturingssysteem: iOS 17.1
 - Browser Safari

**Comment by ndsmyter** [comment]
Ik ga deze afsluiten, aangezien er al een gelijkaardige bug gelogd werd: #384 Zodanig dat we het maar op 1 plaats hoeven op te volgen.

Bedankt om te melden in elk geval !
