### ISSUE TITLE
[BUG] Duiken gelogd in een andere tijdzone worden herrekend naar GMT+1

### ISSUE THREAD

**Issue by Wollig-Konijntje** [Nelos-VZW/dives-2#396]
**Beschrijf de bug**
Als je -op vakantie- een duikactiviteit aanmaakt met een toestel dat werkt in lokale tijd (standaard voor een smartphone) dan wordt de duik gelogd in GMT+1. Een duik om 20:12 uur op 5 december in Curaçao wordt bijvoorbeeld opgeslagen als 1:12 uur op 6 december in België.

**Stappen om te reproduceren**
1. Stel een andere tijdzone in op een smartphone.
2. Klik op "maak een duik activiteit".
3. Geef uw duikgegevens in met een fictieve tijd en sla op.
4. In uw logboek staat de duik nu x uur later of vroeger. 

**Verwachte resultaat**
Je zou verwachten dat de tijd die je ingeeft ook de gelogde tijd wordt. Je kan argumenteren dat de tijd correct is (20:12 op 5/12 in Curaçao is inderdaad 1:12 op 6/12 in België) maar dat boeit niet echt. Je wil doorgaans je duik loggen in lokale tijd en zeker op de juiste (lokale) datum. 

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: Nokia X20
 - Besturingssysteem: Android 13
 - Browser: Chrome
 - Versie: 120.0.6099.43

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Sinds deze namiddag zou dit probleem opgelost moeten zijn.
Het is wel zo dat duiken die eerder ingebracht waren, wel de foutieve tijdzone blijven behouden. Je kan de tijdstippen natuurlijk gaan aanpassen, maar dat is natuurlijk nog eens extra werk op dit moment.

Hopelijk kunnen we het vermijden naar de toekomst toe dat dit voorkomt.

**Comment by user4294** [comment]
Deze bug lijkt nog steeds aanwezig. Duiken ingegeven op duikverlof hebben nu allemaal -6u tijdsverschil. Heb er ter plaatse niet opgelet of de tijdconversie meteen gebeurde/zichtbaar was.

**Comment by ndsmyter** [comment]
Er is daar vorige week nog een aanpassing voor gebeurd. Ik ga deze afsluiten aangezien ik vermoed dat het laatste bericht dateert van een duik ingevoerd vóór deze aanpassing.

**Comment by user4294** [comment]
Ja, gaat inderdaacd over duiken begin april
