### ISSUE TITLE
[BUG] Layout issue veel precondities

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#398]
**Beschrijf de bug**
Bij opleidingen met veel precodities is de layout niet optimaal. Lijkt me beter om de precondities onder elkaar te zetten.
Wat volgens mij ook kan is om een progressbalkje te zetten, met een uitklapfunctie om te zien wat er nog gedaan moet worden

**Screenshots**
Fout
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/406dc75f-9340-4ebc-81c0-9e8da5d991c0)
Correct(er)
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/2d58dfcb-80c4-49c6-8fc0-d6fad8427a40)

CSS Foute layout:
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/45e0a4af-9fd7-4430-81d9-ea252327e5a3)
CSS Correcte layout
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/5332df82-0495-4022-8710-568d7f7a0c4d)

**Comment by Cereal2nd** [comment]
duplicate of #384
