### ISSUE TITLE
duiken >=35m komen niet in de profielgegevens terecht

### ISSUE THREAD

**Issue by BartDeDeene** [Nelos-VZW/dives-2#399]
duiken >=35m komen niet in statistieken van de profielgegevens terecht.
wanneer een duik >= 35m toegevoegd wordt via initialisatie, worden de andere diepe duiken wel geteld en getoond in de profiel gegevens. 
De extra diepe duik via initialisatie terug wegdoen doet de andere in Dives gelogde diepe duiken ook opnieuw verdwijnen in het profiel overzicht.

**Comment by BartDeDeene** [comment]
ik merk nu dat het zelfde zich voordoet met nitrox duiken.

**Comment by ndsmyter** [comment]
Ik sluit deze af, omwille van een duplicaat van #392
