### ISSUE TITLE
[BUG] Zoekfunctie werkt niet goed

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#4]
**Beschrijf de bug**
De zoekfunctie in het menu 'kandidaten' werkt niet goed. 
Als ik zoek op 'Bart Dammans' (een lid van onze club); kan ik hem niet terugvinden. 
favorieten staan uitgeschakeld (staat op 'iedereen'). 
Ook heb ik eerst onze club aangevinkt en nadien terug verwijderd zoals getoond in de presentatie --> helpt niets. 
Zoek ik op 'bard' dan staat hij ineens wel in de lijst?; Als ik de 'd' verwijder en terug 'bart' schrijf blijft hij wel in de lijst staan...

Verder: als ik een andere naam van iemand uit onze club intyp (Gunnar); dan komen er in de lijst een heleboel namen zichtbaar van mensen die geen 'gunnar' in hun naam hebben zitten. 

verder: als je zoekt op een club (vb: de watertrollen & duivels vzw) dan staan niet alle leden zichtbaar (16 van de 39 zijn zichtbaar?)

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar het menu 'kandidaten'
2. typ bij 'zoeken op naam' verschillende namen in; de juiste personen komen niet tevoorschijn

**Verwachte resultaat**
Als je een naam intypt moet de zichtbare lijst overeenkomen met wat je getypt hebt

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187541907-4c825a90-1904-4ae0-a840-4e7b5ded4028.png)

![image](https://user-images.githubusercontent.com/112517511/187542028-ec41553f-a3d0-428d-9010-951afc5b8cd1.png)

![image](https://user-images.githubusercontent.com/112517511/187542484-9b1828de-9739-40d2-a926-b623c911d9df.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 home
 - Browser chrome
 - Version Versie 105.0.5195.54 (Officiële build) (64-bits)

**Additional context**
Op de 2de printscreen is ook te zien: 1-3 (onderaan op het scherm); terwijl er maar 2 personen in de lijst staan?

**Comment by ndsmyter** [comment]
@RubenDeSadeleer ,

Enkele zaken die hierbij interessant zijn om te weten:
* het gaat hier enkel over kandidaten, dus dat je leden niet ziet is vermoedelijk omdat ze geen lopende opleiding hebben
* De search zou normaal gezien niet helemaal exact moeten werken, aangezien we ook wat proberen zoeken andere versies van de naam. De zoekopdrachten gebeuren fonetisch, vandaar dat Bart en Bard hetzelfde resultaat zou moeten geven. We gebruiken hiervoor enkele fuzzy search algoritmes. Maar je zou natuurlijk wel de juiste namen moeten kunnen vinden. 

Ik zal uw opmerkingen wel eens bekijken, want er zitten zaken tussen die we zeker moeten oplossen.

**Comment by RubenDeSadeleer** [comment]
@ndsmyter 
ivm die kandidatenlijst: op mijn printscreens is te zien dat de personen die wel in de lijst staan ook geen lopende opleidingen hebben :-); dus ik kan aannemen dat er toch iets anders aan de hand is...
