### ISSUE TITLE
Ontbrekende proef op profiel / Opleidingen

### ISSUE THREAD

**Issue by StephMaerten** [Nelos-VZW/dives-2#40]
**Beschrijf de bug**
Op mijn profiel mis ik bij opleidingen de proef D1 900m Vinzwemmen die niet kan worden afgevinkt

**Stappen om te reporduceren**
1. Ga naar '.Profiel Stephane 3* (48260)
2. Klik op 'opleidingen"
3. Klik op "4*D OW-proeven en duikleidingen"
4. Zie fout: D1 Vinzwemmen 900m  ontbreekt

**Verwachte resultaat**
Palmproef toevoegen zodat deze kan worden afgevinkt

**Screenshots**
![image](https://user-images.githubusercontent.com/112578493/188589404-d4a675ae-0504-48e6-9f57-1533228a1670.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] 2022

**Comment by ndsmyter** [comment]
De ontbrekende proeven zullen bij volgende migratie (op 30/09/22) ook meegenomen worden
