### ISSUE TITLE
[BUG] Proef voor andere duiker toegevoegd aan eigen (theorie)activiteit

### ISSUE THREAD

**Issue by Calinatus** [Nelos-VZW/dives-2#400]
Bij aanmaken theorie-activiteit en afleggen van proef (theorie-examen 3sterD) van mezelf (rood in afbeelding) kwam, na afvinken door instructeur (geel in afbeelding), bij de bewerkingsgeschiedenis ook te staan dat een andere proef (V1: Ademen zonder duikbril) werd toegevoegd door mezelf, voor een andere duiker (geen lid van zelfde club; blauw in afbeelding); overigens komt de proef ook niet overeen met het brevetniveau en vermoedelijke opleiding van die duiker (3sterD):

![Schermafbeelding 2023-12-22 165854](https://github.com/Nelos-VZW/dives-2/assets/133597620/d4adb658-1383-485a-97ac-493cb1d7fc1e)

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare: NELOS-660

**Comment by ndsmyter** [comment]
@Calinatus 
Kan je eens uw NELOS ID eens delen, dat maakt het debuggen ook eenvoudiger.

**Comment by Calinatus** [comment]
52582

**Comment by ndsmyter** [comment]
Zou nu opgelost moeten zijn.
