### ISSUE TITLE
[Feature] Tabs onder profiel logischer sorteren en lege tabs weglaten

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#402]
Momenteel zijn er diverse tabs op profiel. Deze zouden logischer als volgt gesorteerd worden:
- mijn profiel
- brevetten
- opleidingen
- bijscholingen
- persoonlijke gegevens
- initialisatie

Verder zou indien er geen info is die tab gewoon niet zichbaar moeten zijn zoals opleidingen, bijscholingen indien niet relevant

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/e0f7893f-7717-4172-b3f5-ec6b7aee84e1)

**Comment by ndsmyter** [comment]
Zijn er tabs die nu leeg zijn die je ziet? Want normaal is dat al de bedoeling dat die dan verborgen worden. Denk dat bijvoorbeeld bijscholingen en opleidingen al optionele tabs zijn.

**Comment by DIVEScoordinator** [comment]
Nicolas
Bijvoorbeeld als je geen opleiding volgt komt dit tab er toch te staan (vb. mijn echtgenoot0:


Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: maandag 25 december 2023 4:54
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [Feature] Tabs onder profiel logischer sorteren en lege tabs weglaten (Issue #402)


Zijn er tabs die nu leeg zijn die je ziet? Want normaal is dat al de bedoeling dat die dan verborgen worden. Denk dat bijvoorbeeld bijscholingen en opleidingen al optionele tabs zijn.

**Comment by DIVEScoordinator** [comment]
JIRA-719
