### ISSUE TITLE
[Feature] Uitbreiding statistieken naar duiken > 40 m

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#403]
Momenteel wordt in de statistiek enkel duiken dieper dan 30 m getoond.  Aangezien om mee te doen met de stage als kandidaat maar ook als jury duiken dieper van 40 m ook relevant is wordt dit ook beter zichtbaar gemaakt zodat dit niet via een omweg van het logboek moet opgevolgd worden.

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/43c59ac7-ff98-45b2-8c8d-734de542305e)

**Comment by ndsmyter** [comment]
@DIVEScoordinator Zit Sven op dezelfde lijn? Want ik heb dat in DIVES 1 ooit nog moeten weghalen, die 40m lijn. Dus ik wel echt wel vermijden dat we hier tijd en energie in steken om nadien terug weg te halen?

**Comment by DIVEScoordinator** [comment]
Zal dit navragen.

Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Nicolas De Smyter ***@***.***>
Verzonden: zondag 24 december 2023 16:24
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [Feature] Uitbreiding statistieken naar duiken > 40 m (Issue #403)


@DIVEScoordinator<https://github.com/DIVEScoordinator> Zit Sven op dezelfde lijn? Want ik heb dat in DIVES 1 ooit nog moeten weghalen, die 40m lijn. Dus ik wel echt wel vermijden dat we hier tijd en energie in steken om nadien terug weg te halen?

**Comment by DIVEScoordinator** [comment]
Vermits ik volgend moet zichtbaar bij status instructeur lijkt mij dit toevoegen dan toch ook iets dat zinvol is: mail van Joris Steven:

Aangaande ons telefonisch contact van deze middag.
Zoals je weet zijn de toelatingsvoorwaarden voor de 2*I en 3*I stage gewijzigd: Minstens 40 duiken in openwater uitgevoerd in het jaar van deelname aan de zeestage, waarvan minstens 10 decompressieduiken in de zone 40m.
Om een telling/controle te kunnen doen hadden we graag een TAG ‘decompressieduik’  in DIVES gehad.
