### ISSUE TITLE
[Feature] Inbox melding 6 maanden voor verval van brevetkaart

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#404]
Bijkomende melding aan DSV en secretaris 6 maanden vooraleer een brevetkaart gaat verlopen.

**Comment by DIVEScoordinator** [comment]
JIRA-720

**Comment by ndsmyter** [comment]
Dit werd ondertussen geïmplementeerd en zal met de volgende versie mee komen. Ik sluit dit ticket alvast af.
