### ISSUE TITLE
[Feature] Excel overzicht ook zichtbaar maken voor ledenadministrator

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#405]
Momenteel kan enkel de DSV de Excel met informatie over de opleidingen zien. Het zou interessant zijn om dit ook voor de ledenadministrators toe te laten.  Voorstel is om dit te combineren met het verplaatsen van deze informatie in de rapportage module.

**Comment by ndsmyter** [comment]
Zou nu opgelost moeten zijn.
