### ISSUE TITLE
[Feature] Geen informatie meer over opleiding indien afgerond

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#406]
Indien een opleiding is afgerond is het niet meer te achterhalen wie de laatste proef/proeven heeft afgenomen.

deze informatie zou ook in de rapportage mee kunnen opgenomen worden

**Comment by KimEndare** [comment]
@DIVEScoordinator bestaat hier al een Jira ticket van?

**Comment by DIVEScoordinator** [comment]
Kim
Ja dat is de 717 waar ze een combinatie maken van het laten zien van de brevetkaart na verval maar ook na vervollediging.


Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: KimEndare ***@***.***>
Verzonden: vrijdag 7 juni 2024 11:52
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [Feature] Geen informatie meer over opleiding indien afgerond (Issue #406)


@DIVEScoordinator<https://github.com/DIVEScoordinator> bestaat hier al een Jira ticket van?

-

**Comment by DIVEScoordinator** [comment]
reeds ingevoerd bij sprint van juli - bij sprint van november nog wat verder uitgebreid naar ook vervallen maar ook vervolledigde brevetten momenteel in DEV omgeving al te raadplegen. Komt ook in komende Hippocampus artikel.
