### ISSUE TITLE
Foutmelding bij inschrijven van een opleiding, maar verder werkt het wel.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#409]
**Beschrijf de bug**
Ik krijg telkens een foutmelding als ik een persoon inschrijf voor een opleiding. Ik kan op OK klikken en dan dan is de inschrijving juist uitgevoerd. 

**Verwachte resultaat**
Je moet geen foutmelding geven als er geen fout is.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/20f68f98-96b1-43c1-84aa-1ceab7b4eab0)

**Comment by DIVEScoordinator** [comment]
Dit probleem werd doorgegeven aan ENDARE voor de april sprint onder nummer https://endare.atlassian.net/browse/NELOS-673

**Comment by KimEndare** [comment]
Dit kan ik niet meteen reproduceren op TEST / DEV.
Komt deze foutmelding voor bij elke opleiding die gestart wordt?
Of enkel in specifieke gevallen?

zo ja, graag wat meer info;
- club naam
- naam van club lid
- opleiding die gestart wordt

**Comment by ndsmyter** [comment]
@KimEndare ,
Die foutmelding is iets dat voorkomt bij het aanroepen van de NLQ databank.

Bij het aanmaken van de opleiding wordt er ook een bericht gestuurd naar nlq via een functie om aan te geven dat de opleiding gestart is. Aangezien NLQ nog meer zaken kan controleren dan DIVES, is er ook een mogelijkheid dat de inschrijving zal falen aan de kant van de NLQ. In feite zou de transactie waarin die beide zaken gebeuren (DIVES updaten + NLQ updaten) moeten falen indien er een probleem is langs de kant van NLQ.

Maar ik heb al gemerkt dat er soms geen transactie wordt gestart, en ik vrees dat dit te maken heeft met de functies die we aanroepen op de andere databank. Ik vermoed dat MySQL geen transacties over 2 databanken heen kan maken en beheren.

Indien het niet lukt om met transacties te werken, gaan we beter kijken om de logica vanuit NLQ binnen te trekken in DIVES. Zodanig dat we enkel maar informatief een bericht moeten sturen naar NLQ, en we geen transacties meer nodig hebben.

**Comment by KWillemse** [comment]
Ik heb het voor met elke inschrijving. Ik moet net iemand inschrijven voor
een opleiding BND, dus als iemand wil meekijken, dan kan dat. Teams meeting
opzetten en even overlopen.

Met vriendelijke groeten,
Koen Willemse
***@***.***
+32 494 56 02 37


Op di 12 mrt 2024 om 15:42 schreef Nicolas De Smyter <
***@***.***>:

**Comment by DIVEScoordinator** [comment]
dit zou bij de volgende release moeten opgelost zijn - ik heb het niet meer in de testomgeving.  Release gebeurd een van de komende dagen.  Graag terugkoppeling als je het toch nog vaststeld:  ik laat dit ticket voorlopig nog open staan

**Comment by DIVEScoordinator** [comment]
gesloten wegens geen opmerkingen meer dat het nog een probleem zou zijn. Is normaal met de sprint van juli opgelost
