### ISSUE TITLE
Keuzemogelijkheid "deelnemer" bij theorie & Zwembadactiviteit

### ISSUE THREAD

**Issue by StephMaerten** [Nelos-VZW/dives-2#41]
**Stappen om te reporduceren**
1. Ga naar 'Logboek'
2. Klik op 'Maak Theorie activiteit'
3. Klik op knop 'selecteer rol'
4. Zie fout: keuzemogelijkheid: deelnemer / Duikleider / Evaluator / Hekkensluiter / Helper

**Verwachte resultaat**
Ik veronderstel dat de keuzemogelijkheden  Duikleider / Hekkensluiter / Helper overbodig zijn.
Idem bij zwembadactiviteit

**Screenshots**
![image](https://user-images.githubusercontent.com/112578493/188604404-bcfe7984-6cf8-4728-9da8-769f256d49e4.png)

**Comment by DIVEScoordinator** [comment]
Toegevoegd aan sprint 2024-02 als JIRA ticket NELOS-667

**Comment by DIVEScoordinator** [comment]
Reeds uitgevoerd in DEV omgeving komt in de loop van november ook in de productie
