### ISSUE TITLE
Het zoeken naar een opleidingsverantwoordelijke verloopt traag

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#410]
**Beschrijf de bug**
Als je een opleidingsverantwoordelijke wil aanpassen dan duurt dat telkens meer dan 3 seconden vooraleer de filter een lijst van namen geeft. Dit komt waarschijnlijk om dat de volledige lijst met instructeurs wordt gefilterd.

**Stappen om te reproduceren**
Bij het starten van een opleiding of bij het aanpassen van een OPLV van een bestaande opleiding, type gewoon een voornaam en tel het aantal seconden vooraleer je de gefilterde lijst ziet. 

**Verwachte resultaat**
Je zou eenzelfde switch kunnen toepassen zoals bij verschillende andere lijsten, die by default op 'Actieve leden' staat.

**Screenshots**
Voorstel:
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/d58281d0-fafd-4b8e-9622-cf80445746b0)

**Extra informatie**
3 seconden lijkt niet lang maar als ik 10 nieuwe kandidaat 1ster Duikers moet inschrijven met telkens andere OPLV voor 1* en BND, dan verlies ik al snel 1 minuut van mijn kostbare tijd.

**Comment by KWillemse** [comment]
Gisteren opnieuw 6 leden ingeschreven voor een 2 ster opleiding, ik moet de volgende weken nog 6 leden inschrijven voor 2 ster opleiding en waarschijnlijk terug 10 leden voor een 1 ster opleiding.
Omdat wij een grote club zijn werken we met opleidingsverantwoordelijke per brevet en het inschrijven neemt dus echt wel wat tijd in beslag.
Als ik dezelfde instructeurs zoek bij een duik activiteit bv, met de 'Zoek enkel binnen clubleden' aangevinkt, dan krijg ik onmiddelijk een resultaat. Zelfs met de deze optie afgevinkt krijg ik onmiddelijk resultaat.

**Comment by DIVEScoordinator** [comment]
recent idem topic aangemaakt

**Comment by KWillemse** [comment]
Inderdaad, ik had nochthans gezocht in de database want ik kon me herinneren dat ik dat al eens gelogd had. Niet goed genoeg gezocht dus.
Wel even meegeven dat in case #461 het al 7 seconden duurt, dus het wordt trager en trager :-(
