### ISSUE TITLE
Ontbrekende opleiding gnd bij kandidaten 

### ISSUE THREAD

**Issue by Fabmichiels** [Nelos-VZW/dives-2#411]
Kandidaat GND 
51261	Sara VLEMINX	3*D	GND
Club A70  Safe Diving Merksem 

In 'rapportering' staat opleiding vermeld.
Maar bij ' kandidaten ' is haar opleidingsfiche niet terug te vinden. 

**Smartphone **
 - Besturingssysteem: android app 
 - Browser: chrome

**Comment by DIVEScoordinator** [comment]
Momenteel kan je enkel brevetkaart zien als je ook de bevoegdheid als instructeur voor die opleiding. Dus enkel nitrox instructeurs kunnen dat zien.  Dit is een bug die momenteel bij ENDARE zit.  Kan dit de reden zijn?
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/db033cc9-b101-4056-95b0-b626da04450b)

**Comment by Fabmichiels** [comment]
Dat is het inderdaad. Ik ben geen nitrox instructeur.😉

 Als DSV  zou je toch alle opleidingen van al je leden mogen  zien.
Je hebt er niets over te zeggen maar je behoudt zo wel het overzicht.

Bedankt voor de verduidelijking.

vriendelijke groeten,
Faby Michiels
tel +32476357711

Op za 24 feb 2024 16:17 schreef DIVEScoordinator ***@***.***>:

**Comment by DIVEScoordinator** [comment]
Klopt maar dit krijg ik maar niet in orde – staat al enkele maanden bij ENDARE en recente aanpassing werkt het nog steeds niet zoals het hoort.


Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: Fabmichiels ***@***.***>
Verzonden: zaterdag 24 februari 2024 16:25
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Ontbrekende opleiding gnd bij kandidaten (Issue #411)

Dat is het inderdaad. Ik ben geen nitrox instructeur.😉

Als DSV zou je toch alle opleidingen van al je leden mogen zien.
Je hebt er niets over te zeggen maar je behoudt zo wel het overzicht.

Bedankt voor de verduidelijking.

vriendelijke groeten,
Faby Michiels
tel +32476357711

Op za 24 feb 2024 16:17 schreef DIVEScoordinator ***@***.***>:

**Comment by KimEndare** [comment]
Opgelost op DEV; https://endare.atlassian.net/browse/NELOS-638

**Comment by Fabmichiels** [comment]
Bedankt.

vriendelijke groeten,
Faby Michiels
tel +32476357711

Op ma 11 mrt 2024 10:17 schreef KimEndare ***@***.***>:

**Comment by DIVEScoordinator** [comment]
Met de release van gisteren is dit nu normaal opgelost.  Kan je even checken.

**Comment by Fabmichiels** [comment]
Dat blijkt nu in orde te zijn .

Goed gewerkt. Bedankt.

vriendelijke groeten,
Faby Michiels
tel +32476357711

Op zo 7 apr 2024 16:47 schreef DIVEScoordinator ***@***.***>:
