### ISSUE TITLE
Vervallen brevetkaart inkijken als ledenadministrator

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#413]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Er kwam de vraag om de vervaldata van de proeven na te kijken op een vervallen brevetkaart. Met deze info zou de kandidaat dan beslissen om al dan niet het brevet opnieuw te laten openen.

**Beschrijf de oplossing die je zou willen**
Vervallen brevetkaarten zichtbaar maken voor de ledenadministrators en eventueel ander publiek die deze vraag zou kunnen ontvangen zoals bijvoorbeeld secretariaat Nelos, powerusers, duikschoolverantwoordelijken.

**Beschrijf alternatieven die je overwogen hebt**
Voor dit probleem zijn er geen alternatieven. Eens het brevet is komen te vervallen kan je de data niet meer raadplegen.

**Extra context**

**Comment by CarlAnto** [comment]
Voorlopig als oplossing gegeven dat er een excel gedownload kan worden waar al deze gegevens ook in opgenomen zijn.

De persoon in kwestie zal dan wel zelf de vervaldata moeten berekenen indien het over proeven gaat.

**Comment by DIVEScoordinator** [comment]
JIRA-717

**Comment by DIVEScoordinator** [comment]
Dit is met nieuwe release een van de komende dagen mogelijk voor ledenadministrators via club pagina.
