### ISSUE TITLE
Brevet BND (certificatie vanaf 1*duiker)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#414]
**Beschrijf de bug**
Het brevet van een basis nitrox duiker heeft als voorwaarde tot certificatie dat de persoon minimaal houder is van het brevet 1*duiker.
De brevetvoorwaarde lijkt automatisch afgetekend te zijn zelfs al is deze persoon geen houder van het brevet 1*D.
Bijgevolg vertrekt dit brevet (BND) gewoon voor certificatie  wanneer de duiken en de theorieles afgerond zijn.

**Stappen om te reproduceren**
1. Ga naar 'brevetkaart nieuwe kandidaat 1*D + BND'
2. Klik op 'Brevet BND'
3. Werk de theorie en de 2 opleidingsduiken af
4. Brevet is gecertificeerd en de persoon is nu houder van 'Hoofdbrevet BND'
    Na het afwerken van het brevet 1*D komt deze wel als hoofdbrevet en BND als extra brevet. (Dat loopt dus wel goed)

**Verwachte resultaat**
Brevet BND mag niet gecertificeerd worden zolang de persoon geen houder is van minimaal 1*D-brevet.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/79ca2bcc-3de5-4296-804d-3194d14ba22d)
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/a94ad58a-24b3-4599-adbc-ae6c7ecc52b5)
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/8a73164c-ae4f-482f-97e2-6afb28b8de77)

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Ik heb dit nu eens bekeken bij enkele k1D van bij ons in de club, en bij hen gaat dat wel goed. Ook de databankfuncties gecontroleerd die achter die voorwaarde zit; en ook die zien er goed uit. Dus ik heb niet echt het vermoeden dat dit niet zou werken.

FYI: De voorwaarde die er achter zit, is dat de persoon 1 van de volgende brevetten moet hebben om afgevinkt te geraken: 1D, 2D, 3D, 4D, 1I, 2I of 3I. Dus dat is wel OK

Ik ga deze afsluiten, aangezien ik deze niet kan reproduceren en er alles op wijst dat het wel OK is.
