### ISSUE TITLE
[BUG] Kan geen proeven aftekenen van opleiding die vervallen was

### ISSUE THREAD

**Issue by jodekbe** [Nelos-VZW/dives-2#415]
**Beschrijf de bug**
Kandidaat 2*D waarvan de opleiding vervallen was, kandidaat heeft zich opnieuw ingeschreven, er zijn nog een aantal proeven geldig.
Op de duik activiteit staan alle proeven terug open, op de opleidingsfiche zie je wel de correcte info.

Wanneer je een proef die op de brevetkaart reeds is afgevinkt wil toevoegen krijg je deze foutmelding:
App\Domain\Activity\Repository\ActivityRepository::createActivityTestAddedAudit(): Argument #3 ($activityTestId) must be of type int, null given, called in /srv/backend/src/Domain/Activity/Service/ActivityService.php on line 66

Een proef die op de brevetkaart wel nog correct open staat kan je wel normaal afvinken.

Het werkt functioneel dus wel, het is echter verwarrend dat alle proeven terug open staan.

**Stappen om te reproduceren**
Zie info en screenshots

**Verwachte resultaat**
Enkel af te leggen proeven mogen zichtbaar zijn.

**Screenshots**
Brevetkaart:
![image](https://github.com/Nelos-VZW/dives-2/assets/104502399/d5216e63-9a65-4847-a6b7-f055e18344e1)

Duik activiteit
![image](https://github.com/Nelos-VZW/dives-2/assets/104502399/91db717b-c5ec-4eca-bc02-dbd561da90f0)

**Desktop (indien mogelijk aanvullen):**
Niet relevant, komt overal voor

**Smartphone (indien mogelijk aanvullen):**
Niet relevant, komt overal voor

**Extra informatie**
Contacteer me gerust voor een concreet voorbeeld

**Comment by DIVEScoordinator** [comment]
Dit werd opgelost in de mei sprint sinds gisteren in productie
