### ISSUE TITLE
[BUG] Timezones create issues with divelogs

### ISSUE THREAD

**Issue by ShaunPauwels** [Nelos-VZW/dives-2#416]
When you're in a different timezone the datetime off the dives in the logbook do not adjust. 
When creating a dive in the logbook while in a different timezone will create a discrepancy in the logbook.

Reproduce:
 - Change timezone of your device
 - Log a dive
 - Set timezone back

Expected result:
Dives adjusts the datetime off the logged dives to the timezone your device is set to.

**Comment by ndsmyter** [comment]
Doorgegeven NELOS-682

**Comment by DIVEScoordinator** [comment]
ENDARE ticket verwerkt in sprint in productie sinds 16 mei - zou opgelost moeten zijn
