### ISSUE TITLE
[BUG] Afdrukken van pagina's heeft incorrecte inhoud

### ISSUE THREAD

**Issue by ovlaere** [Nelos-VZW/dives-2#417]
**Beschrijf de bug**

Ik wou voor mijn opleiding AI een overzicht afdrukken van mijn proeven om voor te leggen aan de begeleiding. Bij het uitklappen van alle secties is er behoorlijk wat bladvulling maar bij het afdrukken detecteert de print preview maar 1 pagina. Idem bij bv de help pagina.

**Stappen om te reproduceren**
1. Ga naar dives, eender welke pagina (die meer dan 1 pagina inhoud zou hebben bij afdrukken)
2. Open afdruk opties
3. Zie in de preview dat er maar 1 pagina gedetecteerd wordt

**Verwachte resultaat**
Printer friendly versie met de juiste inhoud

**Screenshots**
<img width="400" alt="dives_print1" src="https://github.com/Nelos-VZW/dives-2/assets/2300860/f54e5116-7f96-4379-9e6e-d44d913ef1ad"> <img width="400" alt="dives_print2" src="https://github.com/Nelos-VZW/dives-2/assets/2300860/14827d54-0e90-47dd-9dd9-506fec90d1d7">
<img width="400" alt="dives_print3" src="https://github.com/Nelos-VZW/dives-2/assets/2300860/a24a827f-b72c-441d-aae7-9369701aae37"> <img width="400" alt="dives_print4" src="https://github.com/Nelos-VZW/dives-2/assets/2300860/b9158c02-725b-4439-82f1-a8fec3114074">

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: macOS
 - Browser: Safari
 - Versie: 17.4

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare: NELOS-686

**Comment by ndsmyter** [comment]
In de volgende versie van DIVES, die er heel binnenkort zal aankomen, zal deze functionaliteit toegevoegd worden. Er zal een speciale print weergave zijn om bepaalde zaken weg te halen of beter te visualiseren.

**Comment by ovlaere** [comment]
Dankjewel alvast!
