### ISSUE TITLE
Brevetkaart - activiteit aanmaken/vrijstelling verlenen staat er dubbel in.

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#418]
**Beschrijf de bug**
Brevetkaart - activiteit aanmaken/vrijstelling verlenen staat er dubbel in.

**Stappen om te reproduceren**
1. Bekijk een brevetkaart van een kandidaat
2. Scroll naar de openstaande proeven
3. Het aftekenen van een proef via vrijstelling heeft twee buttons, zo ook het aanmaken van activiteit.

**Verwachte resultaat**
Buttons zouden maar eenmaal getoond moeten worden

**Screenshots**
Brevetkaart - activiteit aanmaken/vrijstelling verlenen staat er dubbel in.

**Comment by DIVEScoordinator** [comment]
@CarlAnto   Bekende bug en die zou nu opgelost moeten zijn met de release van gisteren.  Kan je eens checken (in test was het gisteren ok).
