### ISSUE TITLE
[BUG] Bepaalde leden kan ik nu plots niet meer toevoegen aan een duikactiviteit.

### ISSUE THREAD

**Issue by Wollig-Konijntje** [Nelos-VZW/dives-2#419]
**Beschrijf de bug**
Sinds mijn laatste duik kan Dives maar een beperkt aantal clubleden terugvinden. Het lijkt brevet gebonden. 3* en hogere brevetten kan ik niet vinden, de aspiranten tot 2* wel. 
Zelf ben ik 3* en AI.
Omgekeerd lukt het wel, clublid "Gerrit" 3* en geen AI kan mij wel toevoegen. 
Het zou dus aan het AI brevet kunnen liggen of ... ?

**Stappen om te reproduceren**
1. Log in met een 3* & AI brevet
2. Ga naar 'Maak duik activiteit'
3. Klik op 'Zoek een buddy'
4. Vul de naam in van een buddy die lid is en een hoger brevet heeft.
5. Merk op dat je hem niet vindt

**Verwachte resultaat**
Tot vorige week kon je alle clubleden en bij uitbreiding alle Nelos leden terugvinden.

**Screenshots**
<img width="758" alt="Schermafbeelding 2024-03-25 094956" src="https://github.com/Nelos-VZW/dives-2/assets/53346150/bb86b029-0285-496a-94e7-0c544e6f2b5f">

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: Windows 11
 - Browser: Chrome
 - Versie: 123.0.6312.58

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: Nokia X20
 - Besturingssysteem: Android 13
 - Browser Chrome

**Comment by Wollig-Konijntje** [comment]
Intussen lukt het opnieuw. Bizar.

**Comment by ndsmyter** [comment]
Aangezien het ondertussen opnieuw lukt, ga ik deze taak afsluiten.

Ik heb het zelf nog eens getest, en heb er zelf geen problemen mee. Misschien een probleem tijdens het laden van de personen, of misschien een probleem bij de specifieke buddy. Moeilijk om nog te achterhalen als het nu wel terug werkt.
