### ISSUE TITLE
[BUG] ontbreken van brevetitems die via overige afgetekend worden

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#42]
**De proef organisatie bij nitrox instructeur ontbreekt bij het raadplegen van opleidingen.  Een gelijkaardige opmerking is gegeven over de palmproef dus ik denk dat dit een systematisch  probleem is met alles wat niet via duik/theorie of zwembad wordt afgetekend

**Verwachte resultaat**
alle onderdelen aftekenbaar maar ik begrijp dat overige gaat vervallen in het nieuwe systeem, ergens dit automatisch laten aanpassen want dit zal bij data migratie ook nodig zijn

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ndsmyter** [comment]
De ontbrekende proeven zullen bij de volgende migratie (op 30/09/22) ook meegenomen worden
