### ISSUE TITLE
[BUG] SQL error: Cardinality violation 1242: Subquery returns more than 1 row

### ISSUE THREAD

**Issue by jefdriesen** [Nelos-VZW/dives-2#420]
**Beschrijf de bug**
Ik krijg regelmatig de SQL foutmelding "Cardinality violation 1242: Subquery returns more than 1 row", waardoor bepaalde functies niet meer werken.

**Stappen om te reproduceren**
1. Ga naar pagina 'Logboek'
2. Ga naar pagina 'Kandidaten'
3. Start met typen in 'Zoek op naam'
4. De foutmelding verschijnt even en de actieve pagina verspringt terug naar de vorige pagina (Logboek).

**Verwachte resultaat**
De huidige pagina blijft actief en de zoekresultaten worden getoond.

**Screenshots**
![dives-error](https://github.com/Nelos-VZW/dives-2/assets/28502821/21cb18b5-5466-42e9-b2a6-0559478ea2b9)

**Desktop:**
 - Besturingssysteem: Linux
 - Browser: Firefox
 - Versie: 124

**Smartphone:**
 - Besturingssysteem: Android
 - Browser: Firefox
 - Versie: 124

**Extra informatie**
Ik krijg de foutmelding soms ook op andere pagina's, maar daar is het gedrag minder voorspelbaar. In het beschreven scenario kan ik het elke keer reproduceren.

**Comment by ndsmyter** [comment]
@jefdriesen ,

Ik heb dit eens bekeken, en zag inderdaad in de logs een probleem hierover. Het bleek uiteindelijk een probleem te zijn omdat je meerdere clubs hebt. Vreemd dat dit nu pas naar boven komt, want er zijn nog veel mensen die meerdere clubs hebben.

In elk geval is het aangepast in de code waardoor het geen probleem meer zou mogen vormen. Probeer gerust nog eens of het nu wel werkt.

**Comment by jefdriesen** [comment]
Ik kan het probleem niet direct meer reproduceren, dus het lijkt inderdaad opgelost.
