### ISSUE TITLE
[Feature] Datumformaat duiken in 24 uur formaat i.p.v. AM/PM. 

### ISSUE THREAD

**Issue by n3wjack** [Nelos-VZW/dives-2#421]
In België en Europa is de 24-uur notatie in gebruik, dus de US AM/PM manier om de tijd in te voeren bij een nieuwe activiteit is verwarrend. Zeker als de uren rond de middag liggen.

Voor het gebruiksgemak zou ik dit graag in de 24-uur notatie zien gebeuren.

**Comment by ndsmyter** [comment]
Hallo @n3wjack ,
Normaal zou het overal in 24u formaat moeten zijn. Op de plaatsen waar jij dat ziet, is het vermoedelijk omdat je een browser gebruikt die dat op die manier toont. Indien anders, zou het nuttig zijn om een screenshot toe te voegen, of te zeggen waar het is. Want nu is dat heel moeilijk uit te zoeken.

Bij mij zie ik dit in elk geval nergens.

Dus ik ga deze bug afsluiten aangezien dit volgens mij langs onze kant OK is.

**Comment by n3wjack** [comment]
Ik heb dit in zowel Chrome als Firefox.

![image](https://github.com/Nelos-VZW/dives-2/assets/2250770/00a964f0-745e-43ad-9769-535981da1bd3)

**Comment by ndsmyter** [comment]
Dan zal het een instelling zijn van uw computer. Want dat veld luistert naar uw taalinstellingen van uw browser en/of computer.

Zo ziet het er bij mij uit:

![Screenshot_20240331-133402.png](https://github.com/Nelos-VZW/dives-2/assets/648669/b6da3f19-ead0-4773-8908-91d4073fec88)

**Comment by n3wjack** [comment]
In Firefox moet ik daar blijkbaar een instelling voor aanpassing in about:config om dat goed te krijgen.
https://superuser.com/questions/1751692/firefox-date-format

Ik gebruik wel de Developer Edition, en die is standaard in het Engels. Misschien daarom dat die het OS niet volgt.

Voor Chrome weet ik niet waarom dat niet goed komt. Die is ook met een Engelse UI, maar ik gebruik die toch niet veel, dus op zich geen probleem. Ik zou verwachten dat die de OS instellingen gebruiken.
