### ISSUE TITLE
[BUG] Bewerken van naam voor custom duiklocatie 

### ISSUE THREAD

**Issue by denbatte** [Nelos-VZW/dives-2#423]
**Beschrijf de bug**
Ik heb de eerste keer een foute naam ingegeven van de Duiklocatie en wou dit aanpassen. Dit loopt echter mis.

**Stappen om te reproduceren**
1. Ga naar duik toevoegen
2. Klik op custom Duiklocatie toevoegen
3. Sla op
4. Bewerk duikgegevens
5. Geef nieuwe locatie op
6. Zie fout SQL error

**Verwachte resultaat**
Ik verwacht dat ik de naam van de Duiklocatie kan aanpassen.

**Screenshots**
![Screenshot_20240403-183642~2](https://github.com/Nelos-VZW/dives-2/assets/505196/dde5d9d0-a6fe-45fd-a994-a4eba1efd594)

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: pixel 7
 - Besturingssysteem: Android laatste versie
 - Browser Edge laatste versie

**Comment by DIVEScoordinator** [comment]
Er is zaterdag een nieuwe release geweest dat ook aan de duikplaatsen iets heeft aangepast. Kan je nog een kijken of dit probleem hiermee verdwenen is.  Ik kan het immers niet reproduceren.

**Comment by denbatte** [comment]
Hallo,

Ik heb net nog eens getest en dezelfde SQL-Error is er nog steeds.

**Comment by DIVEScoordinator** [comment]
ok - wordt verder opgevolgd, rond duikplaatsen plannen we nog later dit jaar een grotere aanpassing.

**Comment by DIVEScoordinator** [comment]
heb je geprobeerd om de naam van je eigen persoonlijke duikplaats (moet wel door u zelf ingebracht zijn) aan te passen via profiel pagina/beheer pagina.  Ik gebruik dat om alles correct te zetten nadat ik een persoonlijke plaats aanmaak.

![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/3b153d52-702c-4073-ad9f-f35fb8167158)

**Comment by ndsmyter** [comment]
De naam van een bestaande persoonlijke locatie kan je normaal gezien aanpassen via de pagina die @DIVEScoordinator linkte:  https://dives.nelos.be/profile/manage

De reden dat je deze fout wel krijgt, is omdat het systeem een nieuwe locatie probeert aan te maken als je dat doet via Aanpassen van een activteiten. Hierdoor kom je in feite in dezelfde situatie als #433 

Ik ga deze taak dus even als duplicate markeren. De oplossing zal voornamelijk via #433 komen, omdat deze al aan Endare werd doorgegeven.

**Comment by DIVEScoordinator** [comment]
Issue is normaal opgelost begin augustus - de zone werd niet correct meegegeven. Laat maar horen als je dit nog steeds hebt. Ik sluit het voorlopig af.
