### ISSUE TITLE
[BUG] Excel export sorteert op activity id ipv. datum

### ISSUE THREAD

**Issue by Maximvdw** [Nelos-VZW/dives-2#426]
Wanneer je een excel file export van je duiken, staan deze op volgorde van activity ID.
Het lijkt logischer dat dit gesorteerd is op datum.

Scenario:
Stel, je bent op duikreis en je vraagt aan je buddy om de duik in te geven. Zelf geef je ook enkele duiken in, maar je buddy doet
dit pas als hij thuis is. Op dat moment heb je bij de excel export dus een vrij grote sprong tussen je duiken en staan ze niet mooi gesorteerd.

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare: https://endare.atlassian.net/browse/NELOS-713

**Comment by KimEndare** [comment]
Op te nemen onder [NELOS-718](https://endare.atlassian.net/browse/NELOS-718)

**Comment by ndsmyter** [comment]
Binnenkort zal deze functionaliteit beschikbaar worden. Het is al ontwikkeld, maar staat nog niet op productie.
