### ISSUE TITLE
BUG Rollen over tijd werkt niet correct

### ISSUE THREAD

**Issue by tijlclerckx** [Nelos-VZW/dives-2#429]
De nieuwe functie rollen over tijd werkt niet correct, ik ben verschillende keren duikleider geweest dit jaar 
![image](https://github.com/Nelos-VZW/dives-2/assets/167974062/66ddcfac-3297-45db-92e0-5af1c40f1858)

**Comment by ndsmyter** [comment]
Hey @tijlclerckx ,
Er zat inderdaad iets niet helemaal goed in het ophalen van die data. Dit probleem werd nu verholpen, en zal binnen enkele minuten ook beschikbaar zijn op de [dives.nelos.be.](https://dives.nelos.be/profile/stats)
