### ISSUE TITLE
[BUG Overboedige informatie bij opleidingsverantwoordelijke

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#43]
**Beschrijf de bug**
Langs de gegevens van de opleidingsverantwoordelijke staat info over 'buddy'

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. buddy
2. Klik op tab opleidingen
3. rechts bovenaan
4. Zie fout

**Verwachte resultaat**
weglaten overbodige info

**Screenshots**

![image](https://user-images.githubusercontent.com/112652115/188799251-4737cf1e-0baa-43b8-b79d-e585e7ea9486.png)

**Desktop (please complete the following information):**
 - 
 - Browser chrome
 - ?

**Comment by ndsmyter** [comment]
De essentie van het probleem is hier in feite dat de tekst "Buddy Wim RUBBEN" eigenlijk een avatar/afbeelding zou moeten zijn. Dit heeft te maken met een migratieprobleem dat we deze week hadden. Ik heb het nu aangepast en zou opgelost moeten zijn tegen de volgende deploy (nu maandag)

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
