### ISSUE TITLE
Geen weergave aantal duikzn

### ISSUE THREAD

**Issue by Tijsvandewoestyne** [Nelos-VZW/dives-2#430]
Bij het aantal duiken heb ik geen duiken volgens dives ondanks het juist loggen en aftekenen door de duikleider. Als ik bij persoonlijke statistieken kijk vind ik de duiken dan wel terug. De teller blijft dus op 0 staan

**Comment by ndsmyter** [comment]
Hey @Tijsvandewoestyne ,
Kan je eens een screenshot sturen van waar je momenteel geen duiken ziet in DIVES? Want op dit moment is het mij niet duidelijk waar het probleem juist zit.

**Comment by ndsmyter** [comment]
In 2 maanden geen reactie gehad, dus ik ga deze afsluiten.
Deze kan gerust terug heropend worden als daar nood voor zou zijn.
