### ISSUE TITLE
Fout in de brevetkaart 'begeleider duiken met handicap'

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#431]
**Beschrijf de bug**
In de brevetkaart 'begeleider duiken met handicap' komt de referentie evaluatieles in jeugdduikschool voor bij de proeven:
-  redding van minstens 10m...
- als begeleider met niv C stimulerende duiker ...
Deze referentie zou naar een wet wheel opleidingscentrum moeten zijn in plaats van een jeugdduikschool.

**Stappen om te reproduceren**
1. Ga naar 'brevetkaart begeleider duiken met handicap'
2. Klik op 'duiken in open water'
3. Scroll naar 'proeven zoals hierboven omschreven'
4. Zie fout

**Verwachte resultaat**
Referentie jeugdduikschool veranderen naar Wet Wheels Opleidingscentrum of Opleidingscentrum duiken met handicap

**Screenshots**
![Screenshot_2024-04-27-22-51-30-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nelos-VZW/dives-2/assets/130435688/e7b5df09-5996-4543-9613-bf5c1cb6a92e)

**Comment by ndsmyter** [comment]
@DIVEScoordinator ,
Jij kan dat aanpassen via Brevettenbeheer?

**Comment by DIVEScoordinator** [comment]
Zou nu ok moeten zijn. Kan zelf brevetkaart niet zien.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Sunday, April 28, 2024 5:59:54 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Fout in de brevetkaart 'begeleider duiken met handicap' (Issue #431)


@DIVEScoordinator<https://github.com/DIVEScoordinator> ,
Jij kan dat aanpassen via Brevettenbeheer?

**Comment by CarlAnto** [comment]
De tekst is inderdaad aangepast.

Er is nog één probleem en dat is de voorwaarde van de zwembadlessen als assistent. Bij opleidingsduik 1 tekent die voorwaarde niet af terwijl die bij opleidingsduik 2 dan al afgetekend staat.

![IMG-20240427-WA0006](https://github.com/Nelos-VZW/dives-2/assets/130435688/c176a581-57b3-456d-8171-84995f1fd921)

**Comment by CarlAnto** [comment]
![IMG-20240427-WA0005](https://github.com/Nelos-VZW/dives-2/assets/130435688/0fc2a21c-8e1b-45b0-8948-e4f0fcc5b6fd)

**Comment by DIVEScoordinator** [comment]
Carl,
Ik heb de voorwaarde eens verwijderd en teruggevoegd maar dat lost het niet op. Vreemde is dat ik op 2 plaatsen een verkeerde voorwaarde heb aangepast (had een van jeugdduiken geselecteerd, mijn fout) maar zeker niet bij opleidingsduik 1 en 3 , was bij 2 open water proeven.  Ik zie de reden niet en dat moet dus door Nicolas eens bekeken in de databank.

Bij het origineel aanmaken van dit brevet ben ik vast komen te zitten omdat de beschrijvingen van de proeven zoals in INFOMAP te lang waren. Nicolas heeft dit in de databank toen opgelost.

Nicolas,
Kan daar een link mee zijn?

***@***.***


Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: CarlAnto ***@***.***>
Verzonden: zondag 28 april 2024 15:05
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Fout in de brevetkaart 'begeleider duiken met handicap' (Issue #431)


De tekst is inderdaad aangepast.

Er is nog één probleem en dat is de voorwaarde van de zwembadlessen als assistent. Bij opleidingsduik 1 tekent die voorwaarde niet af terwijl die bij opleidingsduik 2 dan al afgetekend staat.

IMG-20240427-WA0006.jpg (view on web)<https://github.com/Nelos-VZW/dives-2/assets/130435688/c176a581-57b3-456d-8171-84995f1fd921>

-

**Comment by ndsmyter** [comment]
@CarlAnto , @DIVEScoordinator ,
Bij deze is het opgelost in de productiedatabank.

Long story short:

* Toen @DIVEScoordinator de ene voorwaarde verwijderde van de "Opleidingsduik", bleef aan de oude Opleidingsduik wel nog steeds de vorige versie van die voorwaarde hangen.
* Personen die de voorwaarden al afgevinkt hadden; stonden blijkbaar wel al afgevinkt op de nieuwe voorwaarde. Dus vermoedelijk zit daar wel al een migratie op

Met andere woorden: ik denk dat er opgelet moet worden bij het verwijderen van proeven en voorwaarden die gedeeld worden als voorwaarde voor andere systemen. Want het delen van voorwaarden en proeven is iets dat via de databank redelijk eenvoudig zichtbaar is, maar niet via "Brevettenbeheer" via de DIVES-website.

**Comment by DIVEScoordinator** [comment]
Bedankt Nicolas, ik mag dat niet meer tussendoor doen mamet maar met de  nodige aandacht..

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Monday, April 29, 2024 12:38:45 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Fout in de brevetkaart 'begeleider duiken met handicap' (Issue #431)


@CarlAnto<https://github.com/CarlAnto> , @DIVEScoordinator<https://github.com/DIVEScoordinator> ,
Bij deze is het opgelost in de productiedatabank.

Long story short:

  *   Toen @DIVEScoordinator<https://github.com/DIVEScoordinator> de ene voorwaarde verwijderde van de "Opleidingsduik", bleef aan de oude Opleidingsduik wel nog steeds de vorige versie van die voorwaarde hangen.
  *   Personen die de voorwaarden al afgevinkt hadden; stonden blijkbaar wel al afgevinkt op de nieuwe voorwaarde. Dus vermoedelijk zit daar wel al een migratie op

Met andere woorden: ik denk dat er opgelet moet worden bij het verwijderen van proeven en voorwaarden die gedeeld worden als voorwaarde voor andere systemen. Want het delen van voorwaarden en proeven is iets dat via de databank redelijk eenvoudig zichtbaar is, maar niet via "Brevettenbeheer" via de DIVES-website.
