### ISSUE TITLE
[BUG] Aanpassen van persoonlijke naar publieke locatie

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#433]
**Beschrijf de bug**
(binnen gekregen via chat)

ik wou een locatie in Dives aanmaken maar ik krijg een error: 

![image](https://github.com/Nelos-VZW/dives-2/assets/648669/6e1c0f6d-376c-4ab1-a069-9c6858251177)
 
    SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dives`.`location`, CONSTRAINT `FKlocation619467` FOREIGN KEY (`zone_id`) REFERENCES `zone` (`id`))`

M'n buddy heeft eerst een persoonlijke locatie genaamd `Escampo` aangemaakt maar ik wou die aanpassen/updaten naar `Middellandse zee - Frankrijk - Hyères - Escampo`
 
Enig idee waarom dat niet lukt? Moet de naam van de locatie misschien globaal uniek zijn (ook al is het een persoonlijke locatie)?

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare in NELOS-712

**Comment by ndsmyter** [comment]
Zie ook #423 waar hetzelfde lijkt te gebeuren voor het aanpassen van de naam van de locatie van een persoonlijke naar een persoonlijke locatie.

**Comment by DIVEScoordinator** [comment]
opgelost bij volgende release van eind juli - rond duikplaatsen gaat nog wel e.e.a wijzigen in de toekomst
