### ISSUE TITLE
[BUG] Initialisatie 3*D brevetkaart bootduik werkt niet correct

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#434]
**Beschrijf de bug**
bootduiken die via initialisatie worden ingebracht worden niet meegenomen bij het berekenen van het aantal duiken voor de 3*D kaart.  Dit is nog al gemeld door andere en altijd aangeraden via vrijstelling op te lossen.  In de infomap staan 4 duiken vanaf een boot, ik denk dat vroeger er bootduik in zee stond en je daarom de initialisatie niet kon gebruiken. Dat is dus aangepast en elke bootduik mag nu meetellen.   Dit moet dus aangepast voor alle brevetten waar de initialisatie niet meegenomen zou worden.

**Comment by ndsmyter** [comment]
Het probleem lag er hier aan dat de initialisatie gewoon nog niet meegeteld wordt. Dat is een veiligheid dat ik heb ingebouwd, dat ik liever zelf aangeef wanneer initialisatie gebruikt mag worden. Als ik altijd overal initialisatie zou meetellen, heb je kans dat er  misschien te snel te veel afgetekend zou worden.

**Comment by DIVEScoordinator** [comment]
dus je laat hiervoor de initialisatie dan niet meerekenen en de OPLV moet dan een vrijstelling geven?

**Comment by ndsmyter** [comment]
Nu tellen ze wel mee. Voorheen telden ze nog niet mee. Dus nu is het normaal zonder tussenkomst en gaat het helemaal automatisch.

**Comment by DIVEScoordinator** [comment]
Is nog steeds niet afgetekend bij mijn dochter Astrid Rubben met19 in de initialisatie

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Wednesday, May 29, 2024 7:39:04 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Initialisatie 3*D brevetkaart bootduik werkt niet correct (Issue #434)


Nu tellen ze wel mee. Voorheen telden ze nog niet mee. Dus nu is het normaal zonder tussenkomst en gaat het helemaal automatisch.

**Comment by ndsmyter** [comment]
Staat nog niet op productie denk ik

**Comment by DIVEScoordinator** [comment]
Ok snap het… volg het verder op

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Wednesday, May 29, 2024 10:18:50 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Initialisatie 3*D brevetkaart bootduik werkt niet correct (Issue #434)


Staat nog niet op productie denk ik
