### ISSUE TITLE
[BUG] Tijdstip verkeerd bij aanmaken duik

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#435]
**Beschrijf de bug**
Bij het aanmaken van een duikactiviteit wordt het ingevoerde uur niet correct weergegeven. Bijvoorbeeld, 11 uur wordt weergegeven als 9 uur, wat betekent dat er telkens 2 uur wordt afgetrokken.
Dit via de mobiele app.

**Verwachte resultaat**
Ingevoerde tijd komt overeen met weergegeven tijd.

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: ?
 - Besturingssysteem: Android 
 - Browser: Chrome

**Comment by DwfBE** [comment]
![Screenshot_2024-05-20-12-49-43-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nelos-VZW/dives-2/assets/93061973/57191278-7c32-44b6-a012-8caa516dbb5a)

**Comment by DwfBE** [comment]
![Uploading Screenshot_2024-05-20-12-49-47-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by DwfBE** [comment]
![Uploading Screenshot_2024-05-20-12-49-47-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by DwfBE** [comment]
Hetzelfde probleem heeft zich ook voorgedaan bij andere leden.

**Comment by ndsmyter** [comment]
Hey @DwfBE ,
Dat is inderdaad een bug die we zelf ook al hadden opgemerkt en daardoor redelijk snel aangepakt hebben. Afgelopen zondag is er dan ook een fix in productie gezet voor dit probleem. Om de fix te laten werken, moet er wel een force refresh (Ctrl+Shift+R op een computer) om te zorgen dat de cache vernieuwd wordt.

Op een smartphone kan het helpen om eens uw pagina te herladen, maar afhankelijk van het besturingssysteem en de browser kan het wel zijn dat nog steeds de cache gebruikt wordt.

Activiteiten die aangemaakt zijn in de paar dagen dat deze bug in productie stond, kunnen aangepast worden qua tijdstip waar nodig. We willen dit liever niet automatisch doen, aangezien sommige mensen 1u bijgeteld hadden als workaround voor dit probleem.
