### ISSUE TITLE
[BUG] AI kan vaardigheden van kandidaat 1* afvinken

### ISSUE THREAD

**Issue by DwfBE** [Nelos-VZW/dives-2#436]
**Beschrijf de bug**
AI kan voor een kandidaat 1* de zwembadvaardigheden afvinken zonder instructeur.

**Verwachte resultaat**
Behoudens vergissingen kan dit enkel uitgevoerd afgevinkt worden door een instructeur.

**Screenshots**
![Screenshot_2024-05-26-01-10-29-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Nelos-VZW/dives-2/assets/93061973/aaabac77-10c8-43f9-a5c8-191e9bbed3ea)

**Comment by ndsmyter** [comment]
@DwfBE 

Dit is eigenlijk geen bug. Je kan als AI wel degelijk alle verschillende onderdelen in het zwembad afvinken. Dit omdat je die bevoegdheid hebt in het zwembad.

Het moet wel onder leiding van minstens een 1*I gebeuren en daarom hebben we nog eens de proef "Zwembad oefeningen" toegevoegd. Dus vooraleer de kandidaat in open water kan duiken, moet er een instructeur ook afgetekend hebben.

Dit is dus geen bug.
