### ISSUE TITLE
Verwijderen proef 

### ISSUE THREAD

**Issue by brechtdecausmaecker** [Nelos-VZW/dives-2#437]
Probleem: een foutief ingegeven proef kan niet meer verwijderd worden. In dit geval was de fout opgemerkt nadat de proef was goedgekeurd.

**Beschrijf de oplossing die je zou willen**
Mogelijkheid een proef te verwijderen

**Beschrijf alternatieven die je overwogen hebt**
De proef annuleren en een tweede proef aan de activiteit toevoegen

**Extra context**
Je kan hier eventueel context opgeven, of screenshots om de nieuwe functionaliteit duidelijk te maken.

**Comment by ndsmyter** [comment]
Hey @brechtdecausmaecker ,

Al sinds de invoering van DIVES 2 kan je proeven verwijderen. De evaluator kan de proef terug Resetten (verbodstekentje) en dan via het aanpassen van de activiteit kan je de proef terug verwijderen. Dus quasi gelijkaardig aan het aftekenen, maar dan in omgekeerde volgorde.
