### ISSUE TITLE
Attest 596.2 niet automatisch aangevinkt in DIVES

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#438]
**Beschrijf de bug**
Wij hebben 2 Assistent Instructeurs in opleiding (sportduiken en vrijduiken) en zij hebben hun Attest 596.2 aangeleverd en nadien de opleiding AI gestart. De 'certificatie' 'aanleveren strafregistereuitreksel ....' in DIVES staat nog steeds op uit te voeren.

**Stappen om te reproduceren**
Zoek op 'Filip DEBLOUDTS 4*D NELOS ID: 21037' en 'Parsifal VANGANSBEKE 1*D 2*APNEA NELOS ID: 22725' 

**Verwachte resultaat**
Bij het starten van een opleiding Begeleider Jeugdduiken, Begeleider DmH en Assistent-Instructeur (sportduiken en vrijduiken) zou deze de 'certificatie' 'aanleveren strafregistereuitreksel ....' onmiddelijk als uitgevoerd moeten worden gezet als deze reeds werd geregistreerd in de ledenadminstratie.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/121305742/e5499387-763f-4339-bef9-ba6d773de405)

**Comment by ndsmyter** [comment]
@DIVEScoordinator lijkt er op dat deze nog geen gebruik maakt van de automatische versie, maar wel van de administratieve aftekening.

Kan jij dat verder bekijken?

**Comment by DIVEScoordinator** [comment]
Dit heb ik aangepast naar automatisch en secretariaat had bevestigd dat het werkte. Ik krijg wel de vroegere evaluatie verplichting niet geschrapt.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Friday, May 31, 2024 5:38:14 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Attest 596.2 niet automatisch aangevinkt in DIVES (Issue #438)


@DIVEScoordinator<https://github.com/DIVEScoordinator> lijkt er op dat deze nog geen gebruik maakt van de automatische versie, maar wel van de administratieve aftekening.

Kan jij dat verder bekijken?

**Comment by DIVEScoordinator** [comment]
Het is wel niet de bedoeling dat dit certificaat bij de start van de opleiding wordt aangeleverd maar pas op het einde nadat de opleiding volledig is afgerond. Het is immers maar 1 maand geldig dit certificaat en dit item wordt ook na 1 maand automatisch terug geschrapt.  Zie infomap luchtduiken, bij de instelling mag het certificaat max 1 jaar oud zijn. Ik koppel dit op het bestuur terug dat dit ook voor het vrijduiken op die manier wordt ingevuld.

**Comment by KWillemse** [comment]
Ik begrijp het maar dat wil dus zeggen dat deze personen hun attest opnieuw moeten binnenbrengen op het einde van hun opleiding, klopt?

**Comment by KWillemse** [comment]
Ik lees ook in de infomap dat houders van een actieve NELOS-aanstellingsovereenkomst van onbepaalde duur voor
vrijwilligerswerk zijn vrijgesteld van het aanleveren een strafregisteruittreksel model Artikel 596.2.
Krijgen enkel gebreveteerde (AI of hoger) NELOS leden zo'n NELOS-aanstellingsovereenkomst?

**Comment by DIVEScoordinator** [comment]
dit wordt verder via het bestuur afgehandeld - geen DIVES aanpassing nodig wegens correct geimplementeerd versus INFOMAP voorwaarden
