### ISSUE TITLE
[BUG] Bewerkingsgeschiedenis 

### ISSUE THREAD

**Issue by Braafmanneke** [Nelos-VZW/dives-2#439]
**Beschrijf de bug**
Wanneer je bewerkingsgeschiedenis bekijkt van een duik met proeven op een mobiel apparaat krijg je proeven van iemand anders te zien die die dag ook een proef hebben afgelegd. 

![image](https://github.com/Nelos-VZW/dives-2/assets/171477623/41f83d3f-a9b9-4b42-ba46-25926e877e83)

**Comment by ndsmyter** [comment]
Dit is een oud probleem dat moeilijk retroactief opgelost kan worden blijkbaar. Het zou zich niet meer kunnen voordien bij nieuwe activiteiten, maar oudere activiteiten kan het soms een vertekend beeld geven.
