### ISSUE TITLE
[BUG]  Verwijder overbodige tekst onder titels van de proeven

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#44]
**Beschrijf de bug**
beschrijving van proeven start met 'beschrijving van theorie-examen; beschrijven van Bé).

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Buddy
2. Klik  opleidingen
3. open brevetite,
4. Zie fout

**Verwachte resultaat**
Weglaten van deze overbodige tekst die zeker op smartphone hinderlijk kan zijn

getest op chrome

**Comment by ndsmyter** [comment]
Die teksten moeten we nog eens doorgaan :-)
