### ISSUE TITLE
Geen horizontale scrollbar op het overzicht 'actieve opleidingen)

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#440]
**Beschrijf de bug**
Op het tabblad 'actieve opleidingen' zijn niet alle actieve opleidingen zichtbaar. Wanneer je de pagina uitzoomt zie je dat er nog een gedeelte verborgen staat waar je niet naartoe kan scrollen.

**Stappen om te reproduceren**
1. Ga naar 'actieve opleidingen'
2. Scroll naar 'rechts'
3. Zoom eventueel de pagina eens uit zodat je duidelijk ziet dat er meerdere opleidingen op dit venster staan.

**Verwachte resultaat**
In het overzicht van actieve opleidingen een horizontale scrollbar voorzien zodat alle opleidingen zichtbaar staan. Nu is er een beperkte view.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/7bb77bed-c0cc-46b3-8f25-54b0c7f7eb7c)

**Comment by ndsmyter** [comment]
Volgens mij is dit geen probleem meer. Of ik lijk het toch zelf niet te kunnen reproduceren.
