### ISSUE TITLE
[BUG] AI-BJD kan geen Duik 2 Bronzen Dolfijn of Duik 3 Bronzen Dolfijn aftekenen

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#442]
**Beschrijf de bug**
Een AI-BJD mag normaal gezien de doopduiken door voor de jeugd.
Echter bij het toevoegen van de proef krijgt hij de melding om een evaluator toe te voegen.

**Stappen om te reproduceren**

Het overzicht:
![overzicht](https://github.com/Nelos-VZW/dives-2/assets/494802/77ac9081-7728-42b5-949c-945842a62964)

Bij het toevoegen van de proef:
![evaluator](https://github.com/Nelos-VZW/dives-2/assets/494802/dbfc8d6c-1b33-4eb0-b0de-4da7cf5a93ae)

**Comment by ndsmyter** [comment]
@DIVEScoordinator Kan je deze ook eens bekijken aub?

**Comment by DIVEScoordinator** [comment]
AJ-BJD was eigenlijk een lapmiddel omdat binnen DIVES 1 omdat niet met twee brevetten kon gewerkt worden. Binnen de ledenadministratie is dat afgeschaft bij start van DIVES 2. Het systeem zocht wel nog naar dit brevet om af te tekenen. Dit heb ik enige tijd geleden nalv mail van Franklin aangepast omdat BJD die AI was niet meer kon aftekenen, op basis van info dat dit afgeschaft was in de ledenadministratie heb ik AI-BJD verwijderd .Nu checkt het systeem of je AI en BJD bent of JIN of JEV.  Nu zie ik dat deze persoon wel nog AI-BJD brevet heeft maar niet BJD. Ik kan echter AI-BJD niet meer toevoegen als evaluator omdat dit een niet bestaand brevet is in de lijst.  Dus dat gaat via aanpassing in de databank moeten gebeuren waarbij elke AI-BJD nu BJD wordt. 
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/3a89b503-9c13-46b9-873d-37c7a26d7a19) = DIVES2
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/7d96a528-fdf2-47f2-bbab-bc16407ae2cf) = LEDENADMIN

**Comment by netdata-be** [comment]
@DIVEScoordinator is het mogelijk om dit alvast even op te lossen voor Guy ? Deze begint namelijk dringend te worden omdat de kandidaat reeds meer dan 3 duiken gedaan heeft maar we nog aan het wachten zijn op de oplossing hiervoor.
Sorry voor de druk 😎

**Comment by DIVEScoordinator** [comment]
Ik kan dat niet. Moet door Nicolas gebeuren.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: netdata-be ***@***.***>
Verzonden: Sunday, June 30, 2024 9:33:31 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] AI-BJD kan geen Duik 2 Bronzen Dolfijn of Duik 3 Bronzen Dolfijn aftekenen (Issue #442)


@DIVEScoordinator<https://github.com/DIVEScoordinator> is het mogelijk om dit alvast even op te lossen voor Guy ? Deze begint namelijk dringend te worden omdat de kandidaat reeds meer dan 3 duiken gedaan heeft maar we nog aan het wachten zijn op de oplossing hiervoor.
Sorry voor de druk 😎

**Comment by ndsmyter** [comment]
Zou opgelost moeten zijn nu
