### ISSUE TITLE
[BUG] Tijden in e-mails zijn in UTC ipv CET / CEST

### ISSUE THREAD

**Issue by netdata-be** [Nelos-VZW/dives-2#443]
**Beschrijf de bug**
Het valt me op dat de tijden vermeld in de e-mails in UTC staan ipv CET/CEST
Momenteel is het UTC+2 

Melding in dives in de WebUI:

<img width="346" alt="Scherm­afbeelding 2024-06-06 om 08 44 33" src="https://github.com/Nelos-VZW/dives-2/assets/494802/5035c7b1-6a24-423a-861d-00bf51740ba1">

Meding in de e-mail:
<img width="364" alt="Scherm­afbeelding 2024-06-06 om 08 45 12" src="https://github.com/Nelos-VZW/dives-2/assets/494802/d5e0d003-66a7-4e5d-a2e7-5510e02ab912">

**Comment by ndsmyter** [comment]
Probleem werd opgelost en zal binnenkort op productie komen.
