### ISSUE TITLE
Proef " Gebruik octopus van mededuiker onder water op max 3m (stilstaand + zwemmend)" voor B-DmH kan niet afgevinkt worden.

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#444]
**Beschrijf de bug**
Proef " Gebruik octopus van mededuiker onder water op max 3m (stilstaand + zwemmend)" voor B-DmH kan niet afgevinkt worden.
Er wordt gevraagd om een evaluator aan te duiden terwijl deze in de duikploeg zit en aan alle voowaarden voldaan is.

**Stappen om te reproduceren**
1. Log een duik en voeg een proef toe.
2. Klik op Proef " Gebruik octopus van mededuiker onder water op max 3m (stilstaand + zwemmend)"
3. Zie fout

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/112561123/4562e7ba-2ce1-41f4-aad2-4b3ee8ad879a)

**Comment by DelangheM** [comment]
Blijkbaar is er een fout in de rolverdeling van de proef.
Als ik bij wijze van test een GB-DmH toevoeg kan ik deze wel valuator aanduiden.
Dit dient ook door een I-DmH kunnen afgevinkt worden

**Comment by ndsmyter** [comment]
@DIVEScoordinator Bekijk jij eens ?

**Comment by DIVEScoordinator** [comment]
aangepast - zou nu moeten werken - kan je nog eens kijken

**Comment by DelangheM** [comment]
Het is in orde.
Bedankt.

 

Mario

 

Van: DIVEScoordinator ***@***.***> 
Verzonden: vrijdag 21 juni 2024 16:12
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: DelangheM ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Proef " Gebruik octopus van mededuiker onder water op max 3m (stilstaand + zwemmend)" voor B-DmH kan niet afgevinkt worden. (Issue #444)

 

aangepast - zou nu moeten werken - kan je nog eens kijken
