### ISSUE TITLE
Configuratie Blended Learning opent niet.

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#445]
**Beschrijf de bug**
Wanneer men klikt op 'blended learning configuratie' komt er een foutmelding naar voor. Het scherm om een nieuwe klas te starten wil niet openenen.
Het platform blended learning opent wel zoals het hoort.

**Stappen om te reproduceren**
1. Ga naar 'DIVES'
2. Klik op 'blended learning configuratie'
3. Zie fout 'screenshot in bijlage'

**Verwachte resultaat**
Configuratiescherm zou moeten openen om een nieuwe klas aan te maken.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/130435688/caa87e74-fc3f-422e-8870-ea1b34fb903a)

**Comment by ndsmyter** [comment]
@CarlAnto ,
Het probleem was blijkbaar dat er in jullie club een opleiding was zonder leerlingen. Dat kon momenteel nog voorvallen, maar eigenlijk zouden die automatisch opgekuist moeten worden.

* Ik heb een aanpassing gedaan in de code waardoor de website overweg zou moeten kunnen met opleidingen die geen leerlingen of geen lesgevers hebben.
* Ik heb ook een aanpassing gedaan zodanig dat dergelijke opleidingen automatisch opgekuist gaan worden.

Een opleiding zonder lesgevers is moeilijk aan te maken. Want dan moet je een opleiding aanmaken waarna alle lesgevers gedeactiveerd zouden moeten worden (=geen lid). Maar het is wel mogelijk.

Een opleiding zonder kandidaten is eenvoudiger. Van zodra kandidaten de opleiding afgewerkt hebben, worden ze automatisch verwijderd uit EventBrite/elearning (licenties beperken). Dus als je start met een opleiding, dan zal na verloop van tijd de opleiding leeg zijn.

De fix staat nog maar in DEV versie, maar heb ze nu ook manueel al in productie gezet.
