### ISSUE TITLE
De duikduik bij persoonlijke tags is opeens totaal verkeerd

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#446]
**Beschrijf de bug**
Is er een update in dives geweest? De persoonlijke tags van één van onze leden zijn plots volledig verkeerd. Het aantal duiken klopt, 
 maar de duikduur is absurd groot.  
Vb: tot eergisteren had hij 20 duiken CCR voor 25 uur duiktijd. Gisteren heeft hij een nieuwe ccr gelogd en ziet hij plots 90u. Ook de andere persoonlijke tags geven een veel te hoge duikduur.

**Screenshots**
![WhatsApp Image 2024-06-19 at 23 51 56](https://github.com/Nelos-VZW/dives-2/assets/121305742/01c3d981-8dc0-4392-8887-2f27b5ff9c06)

**Comment by KWillemse** [comment]
De gebruiker heeft het probleem gevonden: 
In al zijn oude duiken worden zijn persoonlijke tags steeds 3x of 4x vermeld. Vandaar dat het aantal duiken klopt maar het aantal uren veel te veel is. Om het op te lossen kan hij elke oude duik één voor één openen, een nieuw tag kiezen, opslaan en deze dan terug deleten. Voor 2024 heeft hij dat al gedaan maar voor alle andere duiken is dat nog een serieus jobje. Graag een zo snel als mogelijk een oplossing.

**Comment by ndsmyter** [comment]
Ondertussen lijkt dit probleem opgelost met een UNIQUE constraint op de databank.
