### ISSUE TITLE
[BUG] Aantal duiken header en statistiek komen niet overeen

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#447]
**Beschrijf de bug**
Het aantal duiken in de header komt niet overeen met het aantal duiken in de statistieken.
We vermoeden dan verwijderde duiken mee in rekening worden gebracht.

**Screenshots**
![image](https://github.com/Nelos-VZW/dives-2/assets/8513610/c136f423-ccc2-41c3-bdc9-c02886f4c136)

**Comment by ndsmyter** [comment]
Het vermoeden was correct. Blijkbaar was Ewoud 1 maal verwijderd uit een duik, maar telde die toch nog mee in de tellers van de statistieken.
