### ISSUE TITLE
Engelse datum notatie

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#448]
In mijn logboek worden de data op de Engelse schrijfwijze weergegeven: zie printscreen

<img width="314" alt="image" src="https://github.com/user-attachments/assets/45700169-1f13-48f1-a01b-703317e101b7">

<img width="293" alt="image" src="https://github.com/user-attachments/assets/f911b0f5-cd91-4f12-a2fc-e5836b023239">

Graag terug Nederlands

**Comment by ndsmyter** [comment]
Probleem is opgelost, maar staat nog niet in productie. Heel binnenkort komt dit er aan.
