### ISSUE TITLE
Aanpassen vrijduik

### ISSUE THREAD

**Issue by CarlAnto** [Nelos-VZW/dives-2#449]
**Beschrijf de bug**
Twee kandidaten in een vrijduikactiviteit zouden aangeduid moeten worden als 'niet deelgenomen'. Het opslaan van deze aanpassing genereert een foutcode.

**Stappen om te reproduceren**
1. Ga naar 'vrijduikactiviteit 350833'
2. Klik op 'activiteit aanpassen'
3. Scroll naar 'gedeelte proeven en wijzig deelgenomen/niet-deelgenomen'
4. Zie fout '500 undefined array key 'deleted''

**Verwachte resultaat**
Aanpassing van proeven in een duik zouden zonder meer moeten werken

**Screenshots**
![thumbnail_Dives1](https://github.com/user-attachments/assets/81795742-860b-4cac-a837-4e822350a816)

![thumbnail_Dives2](https://github.com/user-attachments/assets/e47eaece-4f50-4095-a64e-993bff659ad1)

**Comment by ndsmyter** [comment]
Dit is een gekend probleem dat ondertussen opgelost zou moeten zijn. Dit zou al opgelost moeten zijn in de TEST versie en zal dus binnenkort ook beschikbaar worden op productie.
