### ISSUE TITLE
[BUG] Nieuwe persoonlijke tag toevoegen geeft fout

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#450]
**Beschrijf de bug**
Als je een nieuwe tag persoonlijke tag wil toevoegen komt er een fout:
`Call to undefined function App\Domain\Tag\Repository\iconv()`

**Stappen om te reproduceren**
Voeg tag toe aan duik.
Typ nieuwe tag

**Comment by ndsmyter** [comment]
Probleem werd opgelost en zal binnenkort op productie komen.
