### ISSUE TITLE
[BUG] CCR-D-A teller update niet meer in Profiel

### ISSUE THREAD

**Issue by Kristofluycx** [Nelos-VZW/dives-2#452]
**Beschrijf de bug**
Wanneer ik een duik log en als gasmengsel 'Technische Duik CC' selecteer (met ingave diluent en bailout mengsel), dan verandert er sinds 7/08 niets meer aan de teller "CCR-D-A Duiken" onder mijn profiel.

**Stappen om te reproduceren**
Ik maakte een testduik aan met CCR als gasmengsel, de teller veranderde niet.

**Verwachte resultaat**
De  teller "CCR-D-A Duiken" onder mijn profiel zou moeten toenemen met een extra duik en de bijhorende duiktijd zou moeten optellen.

**Desktop (indien mogelijk aanvullen):**
Zowel op Desktop als op mobiele App (iphone)

**Comment by slegers** [comment]
Zelfde probleem doet zich voor bij Nitrox.

**Comment by ndsmyter** [comment]
Het probleem met de CCR-D-A Duiken teller kan ik vinden, maar de link met Nitrox kan ik niet leggen hierbij.

@slegers kan je aub een nieuw ticket aanmaken en daar eens wat meer informatie geven waarom je denkt dat de tellers verkeerd zijn. Als je het weet, ook graag aangeven welke duik je denkt dat niet meegeteld wordt. Dan kan ik beter uitzoeken waar het misschien aan ligt.
