### ISSUE TITLE
[BUG] Automatische vrijstellingen vervallen

### ISSUE THREAD

**Issue by KobeVh** [Nelos-VZW/dives-2#453]
**Beschrijf de bug**
Automatische vrijstellingen vervallen.
Een kandidaat 3*D moet 6 maanden 2*D zijn. Deze vereiste wordt automatisch goedgekeurd door het systeem maar na een tijd vervalt deze goedkeuring. Hetzelfde is van toepassing op de vereiste "60 duiken en 30 duikuren".

**Stappen om te reproduceren**
Om dit te reproduceren heb je waarschijnlijk een kandidaat nodig die al lang genoeg bezig is met zijn opleiding.

**Verwachte resultaat**
 Zo'n zaken zouden niet mogen kunnen vervallen.

**Extra informatie**
Vermoedelijk zit er ergens een controle op de duur van zo'n automatische vrijstelling. Die tijd zal niet overeenkomen met de toegelaten duur van een opleiding (door corona of misschien een andere reden?).

**Screenshots**
![WhatsApp Image 2024-08-19 at 17 22 49](https://github.com/user-attachments/assets/cc0c1df3-6882-4f6e-a458-4f2638f79465)

**Comment by ndsmyter** [comment]
Alle vrijstellingen zouden sinds gisterenavond normaal gezien terug automatisch gegeven moeten worden. Dit was een paar weken niet actief geweest door een probleem.

Indien het nog steeds voorkomt, kan je eens het NELOS ID geven van een persoon bij wie je de fout ziet?

**Comment by ndsmyter** [comment]
Voor alle duidelijkheid nog even: ook vrijstellingen hebben een vervaldatum van 3 jaar. Als een vrijstelling vervalt, zal die ook onmiddellijk terug opnieuw herbereken worden. Is de vrijstelling nog steeds relevant, wordt die opnieuw toegekend.

Normaal gezien speelt Corona geen rol meer, aangezien quasi alle proeven van die periode allemaal al meer dan 4,5 jaar oud zouden moeten zijn. Daar was in elk geval rekening mee gehouden.

**Comment by ndsmyter** [comment]
Dan gaan we er van uit gaan dat de volgende situaties zich vanzelf oplossen. Want ik weet niet of het NELOS secretariaat veel gaat kunnen veranderen hebben aan deze situatie eigenlijk. Tenzij vrijstellingen nog eens opnieuw manueel geven.
