### ISSUE TITLE
Grafana geeft een foutieve teller voor 'jaren lid club'

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#455]
**Beschrijf de bug**
Als je in Grafana de statistiek van aantal jaren lid bekijkt, dan zijn de 'jaren lid NELOS' correct, maar de 'jaren lid club' zijn soms het dubbele of het driedubbele.
Volgens mij telt hij de verschillende sporten samen.
Bv. Eric Billiau is sportduiker, vrijduiker en onderwaterhockeyer en die is 33 jaar bij NELOS en 99 jaar bij CVD. Zo oud is hij nog niet hoor.
Voor leden die maar 1 sport is de teller 'jaren lid club' wel correct.

**Comment by KWillemse** [comment]
Dag Nicolas, 
Ik heb nu ook dubbele vermeldingen gezien bij de 'Functies' binnen de club. Ook daar vermoed ik dat de statistieken dubbel worden geteld omwille van leden die voor verschillende sporten zijn ingeschreven.

Mijn vrees is dan ook groot dat er nog wel andere statistieken niet correct zijn omwille van deze verschillende sporten. Het lijkt me dan ook aangeraden om 'alle' statistieken na te kijken.

Verder zijn wij eind okt - begin nov op duikreis geweest in Lanzarote met onze club. 40 duikers met gemiddeld 10 duiken per persoon. Dan zou je toch verwachten dat 'Lanzarote' moet voorkomen in de lijst van 'Top 10 duikplaatsen in periode' van onze club.

Mvgr,
Koen Willemse

**Comment by ndsmyter** [comment]
Ik heb eens de grafieken nagekeken en er waren er nog 2 die hetzelfde probleem hadden. Beiden opgelost. Nadeel als je dat niet met je eigen club kan testen :-)

Verder kan ik zien dat jullie 16 "duiken" gedaan hebben met 46 "duikers" op "Canarische Eilanden - Lanzarote (algemeen)" waarmee dit op plaats 13 komt te staan in jullie Top 10. De sortering gebeurt momenteel op basis van het aantal "duiken" en dus niet "duikers". Met andere woorden: 1 duik met 4 buddy's telt als 1 duik, maar wel als 4 duikers.

Maar misschien heb je wel ene punt ivm die sortering. Dus ik heb de sortering aangepast zodanig dat het nu sorteert op basis van het aantal duikers. Hiermee komt "Canarische Eilanden - Lanzarote (algemeen)" op plaats 5 te staan. Ik zag ook nog andere "Canarische Eilanden" staan, maar die vallen ook uit de Top 10.

**Comment by KWillemse** [comment]
Top, merci voor de aanpassingen.
Alvast nog prettige feestdagen en een gelukkig nieuwjaar hè.
