### ISSUE TITLE
[BUG] Niet mogelijk om proef apart te selecteren

### ISSUE THREAD

**Issue by MaximVanhockerhoutNelos** [Nelos-VZW/dives-2#456]
**Situatie**
Een ploeg opgesteld uit een AI & 2 1*Duikers.
Beide 1*Duikers zijn kandidaten BND en van beide staan hun opleidingsduiken BND open.
Enkel één 1*D heeft zijn opleidingsduik gedaan, de andere niet.

**Het probleem**
Er stond maar 1 checkbox en de AI kon dus niet apart de proef selecteren voor de desbetreffende duiker die wel zijn opleidingsduik gedaan heeft (Zie screenshot).

**Screenshot**
![image](https://github.com/user-attachments/assets/d179b7b2-32d2-414d-82d4-ac4493b971a8)

**Comment by Cereal2nd** [comment]
![afbeelding](https://github.com/user-attachments/assets/c2e73d45-9cd6-4c82-97f8-dc2b74177a4b)

je kan later bij het afvinken van de proeven aangeven dat desbetreffende persoon niet deelgenomen heeft aan de proef.

**Comment by Cereal2nd** [comment]
![afbeelding](https://github.com/user-attachments/assets/0fdacb04-5d71-423b-a584-ff59b81b5556)
