### ISSUE TITLE
[Feature] Mogelijk om ook in Grafana de andere brevetten te zien

### ISSUE THREAD

**Issue by MaximVanhockerhoutNelos** [Nelos-VZW/dives-2#457]
Op dit moment is het in Grafana enkel mogelijk om het hoofdbrevet te zien (onder de Leden panel) - zie screenshot.

Het zou interessant zijn om ook de andere brevetten te zien, eventueel in een apart kolom:
NAAM - HOOFDBREVET - EXTRA BREVETTEN

Dit zoals het is in DIVES als je een duiker selecteer en naar zijn/haar profiel gaat.

**Comment by ndsmyter** [comment]
Ik heb uw screenshot weggelaten, omdat de namen van de leden er op stonden. Beter dat we die niet te veel gaan delen, ook al is het maar gewoon een naam.

Ik vond het verder wel een goede suggestie en heb dit dan ook zonet toegevoegd in het Grafana dashboard bij de leden.
