### ISSUE TITLE
Details van een opleiding voor 'oud' lid opvragen 

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#458]
Het is nu al een paar keer voorgevallen dat een 'oud' lid terug contact opnemen met ons om zijn opleiding verder te zetten. Om dit praktisch te kunnen regelen moeten we weten hoe ver hij/zij al gevorderd was in de opleiding om dit lid zo efficiënt mogelijk in te plannen in onze duikscholing.
Maar....
Een oud lid is niet meer zichtbaar in DIVES en om dit dus te kunnen opvolgen moeten wij aan dat lid vragen om lidgeld te betalen anders zien we hem niet in DIVES. Het zou wel heel stom zijn om dan te moeten melden dat hij niet mee kan aansluiten aan een lopende opleiding omdat hij alles terug op nieuw moet doen bijvoorbeeld.

Ik had de vraag al gesteld aan DIVES AVOS maar nog geen antwoord ontvangen.
Heel concreet, kunnen jullie aan ons de status van Geert Gerard (NELOSID: 49491) doorgeven zodat we hem zo snel als mogelijk kunnen informeren over het verder zetten van zijn opleiding.

**Beschrijf de oplossing die je zou willen**
Mogelijkheid om de opleidingsgegevens van oud leden op te zoeken, zoals je nu in de ledendatabase ook oud leden kunt opzoeken om hun lidgeld te hernieuwen.

**Comment by KWillemse** [comment]
BTW, eerst en vooral proficiat met het behalen van je 3*I.

Ik heb het geprobeerd, maar ik kan hem niet vinden:
![image](https://github.com/user-attachments/assets/e07b1be2-e5e7-4cab-ad61-63c4c80b0d82)

Als ik het goed heb gezien is zijn theorie examen en zwembad examen toch nog geldig, als hij zijn opleiding terug opnieuw betaald, en zijn 15 duiken komt dan ook wel terug actief veronderstel ik.

**Comment by KWillemse** [comment]
Als ik deze situatie een export doe naar Excel dan staat die wel in de lijst

**Comment by DIVEScoordinator** [comment]
Heeft gewerkt in het verleden. Maak ik ticket van want dat was wel de bedoeling.

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: KWillemse ***@***.***>
Verzonden: Thursday, October 10, 2024 9:54:21 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Details van een opleiding voor 'oud' lid opvragen (Issue #458)


Als ik deze situatie een export doe naar Excel dan staat die wel in de lijst
