### ISSUE TITLE
[BUG] Brevet informatie in de geschiedenis van logberichten toont de actuele brevetten ipv de brevetten die geldig waren op het moment van aanmaken van het log bericht

### ISSUE THREAD

**Issue by spv9875** [Nelos-VZW/dives-2#463]
Als je terugkijkt in de geschiedenis van logberichten dan kloppen de brevetten niet meer als een duiker ondertussen een ander/hoger brevet gehaald heeft.
Bij het checken van vorige duiken met een buddy kan dit de perceptie geven dat iemand al lang een bepaald brevet heeft.
Het lijkt erop dat in de logberichten er enkel een pointer zit naar het profiel van de duikers en via deze weg de brevet info opgehaald wordt (maw het huidig brevet). 
Een optie zou kunnen zijn om bij creatie van een logbericht de brevet informatie over te nemen in het logbericht.

**Comment by ndsmyter** [comment]
Duplicate of #193
