### ISSUE TITLE
Specifieke duiker heeft behaalde brevetten maar in de detailkaart staan er onderdelen als 'vervallen'.

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#465]
**Beschrijf de bug**
Kiama Steenmans NELOS ID: 48412 is 2 ster duiker en BND. Deze brevetten staan als 'geslaagd in het club beheer', deze bevinden zich ook in de Brevetten tab van de 'Detailkaart' maar daarin kan je zien dat ze niet niet als volledig staan afgevinkt.

**Stappen om te reproduceren**
1. Ga naar Kiama Steenmans NELOS ID: 48412 => geslaagde brevetten
![image](https://github.com/user-attachments/assets/9c6163e4-d0bb-4519-9a62-bda62d0bc267)
2. click op 'Detailkaart' en klik op 'Brevetten' => onderdelen vervallen
![image](https://github.com/user-attachments/assets/f528bec2-9ba1-40b4-8974-9fbd57371b4e)

**Comment by ndsmyter** [comment]
Dat was een poging van Endare om de behaalde brevetten te tonen. Ik was daar zelf ook geen fan van, maar door zelf met andere zaken bezig te zijn geweest dit jaar, niet alert genoeg geweest.

Ik heb het nu teruggedraaid, zodanig dat het er terug ongeveer zoals vroeger uit ziet.

We gaan dan verder opnemen hoe we die informatie van de behaalde brevetten beter kunnen visualiseren.
