### ISSUE TITLE
[BUG] Brevettenkaart wordt getoond bij je behaalde brevetten

### ISSUE THREAD

**Issue by MaximVanhockerhoutNelos** [Nelos-VZW/dives-2#466]
Bij sommige duikers als je naar je _profiel - brevetten_ gaat wordt bij sommige behaalde brevetten de brevettenkaart getoond.
Op die brevettenkaart staan dan ook zaken die zogezegd verlopen zijn.
Zie afbeelding
![image](https://github.com/user-attachments/assets/7d3a2fbc-e360-4bab-b014-c4d73d3243da)

**Comment by ndsmyter** [comment]
Dat was een poging van Endare om de behaalde brevetten te tonen. Ik was daar zelf ook geen fan van, maar door zelf met andere zaken bezig te zijn geweest dit jaar, niet alert genoeg geweest.

Ik heb het nu teruggedraaid, zodanig dat het er terug ongeveer zoals vroeger uit ziet.

We gaan dan verder opnemen hoe we die informatie van de behaalde brevetten beter kunnen visualiseren.

**Comment by ndsmyter** [comment]
Duplicate of #465
