### ISSUE TITLE
[BUG] In het brevettenkaart van de opleiding 2*I staat de teller van de vereiste bootduiken niet correct.

### ISSUE THREAD

**Issue by MaximVanhockerhoutNelos** [Nelos-VZW/dives-2#467]
De teller van de vereiste bootduiken voor de opleiding 2*I komt niet overeen met de teller "Bootduiken".

Dit wordt getoond in "Mijn profiel"
![image](https://github.com/user-attachments/assets/08b83ba5-9d9e-41be-9a58-c1e99f8507e2)

Dit wordt getoond op de brevettenkaart 2*I
![image](https://github.com/user-attachments/assets/05c38fbe-78c5-40c4-a82e-9d94cb3dac1e)

Zoals je ziet komen de tellers niet overeen.

**Comment by ndsmyter** [comment]
Hey @MaximVanhockerhoutNelos ,
Ik heb dit even nagekeken in jouw profiel, maar kan blijkbaar nergens bootduiken vinden sinds 16 april 2024 (=datum dat je 1*I in DIVES werd geactiveerd). Je hebt wel al voor die datum bootduiken gedaan, die je ziet staan in de 2e teller.

De eerste teller is echt enkel de bootduiken sinds het behalen van je 1*I. Dus je gaat eerst nog eens bootduik moeten doen en loggen in DIVES om die teller te zien verhogen.

Het is dus logisch dat de tellers niet overeenkomen, vandaar ook dat er 2 tellers zijn 🙂

**Comment by MaximVanhockerhoutNelos** [comment]
Hey @ndsmyter 

De 1ste teller (10 bootduiken sinds 1*I) klopt inderdaad, ik heb sinds het behalen van 1*I nog geen bootduiken gedaan.

Het probleem ligt bij de 2de teller (20 duiken met tags Bootduik). Er wordt getoond dat ik nog maar 11 bootduiken heb, maar in mijn profiel zie ik 29 staan.

**Mogelijk probleem**
Na alles nog eens te bekijken heb ik gezien dat ik tijdens de initialisatie 18 bootduiken heb opgegeven.
Als ik die samen tel met de 11 bootduiken volgens de teller, dan kom ik inderdaad op 29 bootduiken in totaal.

Dit betekent dus dat die ene teller (20 duiken met tags Bootduik) geen rekening hou met de gegevens van de initialisatie.

Voor mij persoonlijk ga dit geen probleem vormen. Eenmaal ik 10 bootduiken gedaan heb zal beide tellers vol zijn en de proef automatisch afgetekend worden, maar voor andere duikers (los van kand. 2*I) kan dit mogelijk wel een probleem vormen in de toekomst.

**Comment by ndsmyter** [comment]
Correct @MaximVanhockerhoutNelos .
De initialisatie wordt op dit moment niet meegeteld voor deze tellers. Daarvoor gaat via de Opleidingsverantwoordelijke (DO NELOS in dit geval) een vrijstelling verkregen moeten worden.

De regels zouden te complex worden als ook overal de initialisaties in meegerekend zouden moeten worden. Want in sommige gevallen kan dat wel (zoals hier), maar in vele gevallen is dat vaak niet echt haalbaar (bv als het een boot- EN zeeduik moet zijn).
Uiteindelijk kan die initialisatie ook gezien worden als een overgangsmaatregel, want met de tijd zullen meer gegevens rechtstreeks vanuit DIVES komen.

Wat betreft nu uw specifieke situatie hier: daar is in feite geen actie voor nodig. Je moet nog 10 bootduiken doen om de 1e teller te verhogen en dan gaat automatisch ook de 2e teller telkens mee verhogen. Dus het probleem gaat zichzelf oplossen als uw eerste teller afgewerkt is.
