### ISSUE TITLE
[BUG] Duik activiteit - buddy toevoegen - geen persoon gevonden

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#5]
**Beschrijf de bug**
Bij het maken van een nieuwe duikactiviteit kan ik mijn buddy (Bart Dammans) niet vinden (zie printscreen 1)

Als ik enkel op zijn achternaam zoek (Dammans) dan krijg ik andere mensen te zien, die niets met 'dammans' te maken hebben (zie printscreen 2)

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar 'maak duik activiteit'
2. Klik op 'zoek een buddy om toe te voegen'
3. typ de naam in (voornaam + achternaam, of enkel voornaam)
4. Zie fout

**Verwachte resultaat**
De juiste personen moeten zichtbaar worden bij het ingeven van een naam. 

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187543002-5c7cdb55-fba9-4d58-9adb-92d9d12119f5.png)

![image](https://user-images.githubusercontent.com/112517511/187543099-d61aff56-f310-42f6-a6ca-2ab5094a97b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Version Versie 105.0.5195.54 (Officiële build) (64-bits)

**Additional context**

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
