### ISSUE TITLE
[BUG] Benaming van brevetten aligneren

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#50]
**Beschrijf de bug**
Voor de luchtduikenbrevetten wordt de afkorting tweemaal gebruikt, dit in tegenstelling tot Basis-Nitrox-Duiker waar de naam voluit gebruikt wordt en daarnaast de afkorting.  Een consistente benaming, volledig en verkort voor alle brevetten invoeren.

![image](https://user-images.githubusercontent.com/112652115/188944787-036b4f62-8770-4d4f-af53-b6111ed0a225.png)

**Comment by Cereal2nd** [comment]
ik denk dat dit komt omdat een 2*D niet echt een lange naam heeft, maar laat deze staan voor @ndsmyter

**Comment by DIVEScoordinator** [comment]
Maikel

Is  2*Duiker… maar staat misschien niet zo in jullie databank. Niet super belangrijk maar iets voor te bekijken

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Maikel Punie ***@***.***>
Verzonden: Thursday, September 8, 2022 8:21:28 AM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Benaming van brevetten aligneren (Issue #50)


ik denk dat dit komt omdat een 2*D niet echt een lange naam heeft, maar laat deze staan voor @ndsmyter<https://github.com/ndsmyter>

**Comment by ndsmyter** [comment]
Momenteel nemen we de namen van DIVES 1 over, maar daar worden de lange namen eigenlijk nooit gebruikt. Hierdoor hebben sommige brevetten wel een lange naam, en andere gewoon tweemaal de korte benaming.

Ik zal dit binnenkort eens aanpassen zodanig dat bij de migratie sommige brevetten toch de lange naam krijgen.
