### ISSUE TITLE
[BUG] Aantal bootduiken stijgt niet met toevoegen persoonlijke tag boot

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#51]
**Beschrijf de bug**
Bij het toevoegen van tag boot aan een duik die nog niet als bootduik getagt was (wemeldinge tetjes) stijgt de teller niet
Idem indien je in de duik het veld boot aanklikt.

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar bestaande duik
2. Klik op toeveogen persoonlijk tag
3. Selecteer boot
4. Ga naar statistieken - aantal is niet gestegen

**Verwachte resultaat**
aantal bootduiken moet stijgen als ik een persoonlijke tag toevoeg - of het moet niet toegelaten zijn om dit persoonlijk toe te voegen maar enkel voor het hele team:

Edge

![image](https://user-images.githubusercontent.com/112652115/188946399-9c2f338e-743d-4344-9857-b9f58229733a.png)

**Comment by ndsmyter** [comment]
Je mag volgens mij niet de persoonlijke tag "boot" gebruiken. Er is een interne tag "Boot" en die wordt gebruikt om te tellen. Om die teller te verhogen, moet je aangeven in de activiteit dat je met een boot dook.
ik heb dit nog niet getest, maar zal dat binnenkort zelf ook eens doen.

**Comment by ndsmyter** [comment]
Misschien is het ook nuttig dat we een melding maken dat als mensen "Boot" toevoegen als persoonlijke tag, dat deze niet meetelt.

**Comment by ndsmyter** [comment]
Blijkbaar werden de tellingen niet gedaan bij het aanmaken, maar wel bij het aanpassen. Het werd aangepast zodanig dat dit ook gebeurt bij het aanmaken, waar het uiteindelijk het meest logische is.
