### ISSUE TITLE
[BUG] duik saven duurt enorm lang (blijft in loop)

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#53]
**Beschrijf de bug**
Duik aangemaakt en na enkele minuten nog steeds draaiend wieltje. 
**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar 'duik aanmaken en vul alles in'
2. Klik op 'opslaan'
3. Wieltje blijft draaien
4. stop door bovenaan pijltje terug te selecteren, en dan staat de duik wel in het logboek

**Verwachte resultaat**
Na op knop saven te drukken ga je terug naar het logboek
**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.

**Desktop (please complete the following information):**
 - chro,e

*
**Additional context**

**Comment by davegeysemans** [comment]
Safari browser op mac geeft hetzelfde probleem

**Comment by ndsmyter** [comment]
Dit probleem zou nu opgelost moeten zijn.
