### ISSUE TITLE
[BUG] Foutief geselecteerde proef kan niet verwijderd worden

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#55]
**Beschrijf de bug**
Een proef die geselecteerd werd, maar wat eigenlijk niet de bedoeling was, kan ik niet verwijderen van de duik. Enkel aanpassen als niet volbracht

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
Nieuwe duik maken
Klik op proeven toevoegen
selecteeer een proef en klik op aanpassen
Kan daarna nergens een optie vinden om die terug te verwijderen

**Verwachte resultaat**
Optie om een geselecteerde proef terug te kunnen verwijderen (voordat de duik bewaard is toch minstens)

**Desktop (please complete the following information):**
 - Browser safari

**Comment by ndsmyter** [comment]
Werd opgelost
