### ISSUE TITLE
[BUG] foutief profiel bij inloggen

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#56]
**Beschrijf de bug**
Na enkele dagen kom ik nog eens op de testsite.
Laatste keer heb ik me niet afgemeld.
Nu ben ik automatisch ingelogd als **Pascal Bourry**

**Stappen om te reporduceren**
nog niet geprobeerd

**Screenshots**
![image](https://user-images.githubusercontent.com/112781010/189652401-18d232f3-5f26-41cc-8770-4b7ac7c15a65.png)
<img width="1176" alt="Schermafbeelding 2022-09-12 om 14 25 46" src="https://user-images.githubusercontent.com/112781010/189653131-b16a2a79-f3d1-4cba-96ee-d027c0c0aff8.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - Browser : chrome
 - Version [104.0.5112.101]

**Comment by AndreVanhecke** [comment]
afgemeld en opnieuw aangemeld: correct aangemeld met mijn profiel

**Comment by ndsmyter** [comment]
Dat heeft te maken met de migratie van de gegevens. Als je zondagavond ingelogd bent met je eigen persoon, zal je na de migratie (bv op maandagmorgen) de volgende dag mogelijks een andere persoon zijn.
Dat kunnen we omwille van de security die we overnemen van DIVES 1.0 niet onmiddellijk veranderen.

Je moet dus inderdaad eens uitloggen en terug inloggen. Dat heeft niet echt iets te maken met de code van DIVES 2.0 en kunnen we dus nog niet onmiddellijk iets aan doen vrees ik.

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
