### ISSUE TITLE
[BUG] systeem blijft draaien na aanmaak van nieuwe duik

### ISSUE THREAD

**Issue by AndreVanhecke** [Nelos-VZW/dives-2#57]
**Beschrijf de bug**
systeem blijft draaien na aanmaak van nieuwe duik.
als ik het logboek bekijk, minuten later, is de nieuwe duik niet toegevoegd

Is reeds meerdere malen gebeurd

**Comment by ndsmyter** [comment]
Dit probleem zou nu opgelost moeten zijn.
