### ISSUE TITLE
[Feature] startscherm smartphone

### ISSUE THREAD

**Issue by davegeysemans** [Nelos-VZW/dives-2#59]
Na het inloggen kom je op het overzichts-scherm van het logboek terecht.
Ik gebruik een iPhone 13Pro, wat al niet zo'n klein toestel is.

- De titel 'Activiteiten' is enorm groot voor dit scherm. Dit neemt al zeer veel plaats in waardoor nuttige info niet zichtbaar kan zijn.
- Is 'Exporteer naar Excel' echt nodig helemaal bovenaan? Dit lijkt me ook eerder iets dat op een pc gedaan wordt, en dus misschien niet (zo opvallend) zichtbaar moet zijn op een smartphone.
- De rest van het scherm wordt volledig ingenomen door de Zoek-functie. Mijn mening (en ook van een paar clubleden aan wie ik het liet zien) is dat dit niet prioritair is op een smartphone. Als ik op zo'n device Dives open, dan is dat om duiken te loggen en om gelogde duiken te openen. Het lijkt me dan beter om ineens te starten met de gelogde duiken te tonen - zonder dat zoek-gedeelte.  Voorzie op zo'n devices eventueel een 'Filter'-icoon (zoiets https://www.flaticon.com/free-icon/filter_6488674) wat dan een zoek-optie opent

**Comment by ndsmyter** [comment]
Ik weet niet of ik die titel perse groot vind. Op mijn GSM met vergelijkbare groot valt dit goed mee.

De export knop is een nieuwe knop sinds de laatste versie, dus die was me nog niet opgevallen. Ik zal het doorsturen naar Endare om die te verplaatsen of verbergen.

Er is inderdaad veel ruimte verloren met die filters bovenaan, dat is er eentje die al besproken is geweest met Endare om verder uit te werken want ik vind dat ook. Ik zal eens opzoeken wat de status daarvan is. Het voorstel was nu om de filters te verbergen onder een dichtgeklapt paneel, dat open geklapt kan worden wanneer het nodig is.
