### ISSUE TITLE
[Feature] Duik activiteit - buddy toevoegen - filter op eigen club (zoals in Dives 1)

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#6]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
bij het aanmaken van een duik-activiteit --> zoekfunctie voot het toevoegen van een buddy werkt niet goed. 

**Beschrijf de oplossing die je zou willen**
Graag zoals bij Dives 1 de functie om enkel binnen je eigen club(s) te zoeken

**Comment by ndsmyter** [comment]
Deze zit al in de pijplijn om te doen :-) Maar goed dat hij hier nu ook eens gelogd is.

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
