### ISSUE TITLE
[BUG] na ingave duik 1 met proef wordt bij duik 2 geen proeven meer gevonden

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#61]
**Beschrijf de bug**
1. duik aangemaakt met proef (Opleidingsduik BND (eerste duik BND)) + opgeslagen
2. deze duik is nog niet bevestigd geworden door evaluator
3. daarna direct duik 2 aanmaken om opleidingsduik 2 BND te kunnen ingeven: dives geeft aan: "geen proeven gevonden"

**Stappen om te reproduceren**
1. duik aanmaken met proef, in dit geval opleidingsduik BND
2. opslaan
3. duik 2 aanmaken met gegevens duik en druk op knop "proeven selecteren" of via "voeg proef toe"
4. Zie fout: dives open venster met melding 'geen proeven gevonden"

**Verwachte resultaat**
Meerdere duiken met proeven kunnen ingeven.

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] Win10 21H2
 - Browser: [bv chrome, safari] Firefox 104.0.2
 - Versie: [bv. 22]

**Extra informatie**
variant om te testen met validatie proef voor ingave 2e duik

**Comment by ndsmyter** [comment]
Zou nu niet meer mogen voorkomen
