### ISSUE TITLE
[BUG] zelfde proef meerdere keren aan verschillende duiken toegekend

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#62]
**Beschrijf de bug**
na vorige bug, venster dives gesloten en heropend. profiel bekeken en duiken toegevoegd. Heb nu proef uit vorige test (zie bug #61  ) opnieuw kunnen toekennen aan duik en buddy. is ook 3e keer gelukt

**Stappen om te reproduceren**
1. maak duik aan met proef
2. even wachten, profiel bekijken
3. 2e duik aanmaken met andere buddy en proef opnieuw toevoegen
4. weer even rondsurfen op dives
5. 3e duik aanmaken, en proef weer toekennen

**Verwachte resultaat**
als proef eenmaal aan duik is toegekend, deze niet meer selecteerbaar maken (tenzij aanpassen van duik)

**Screenshots**
![bnd1 1e keer](https://user-images.githubusercontent.com/112565895/190197596-8def52d0-e7a7-432f-b8f1-a154a9a8c484.JPG)
![bnd1 2e keer](https://user-images.githubusercontent.com/112565895/190197628-4c8cdd69-4f77-46ac-9ace-6704ad75a602.JPG)
![bnd1 3e keer](https://user-images.githubusercontent.com/112565895/190197649-35ac3a79-2234-440c-8762-6bd7b50d802c.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21h2
 - Browser: [bv chrome, safari] firefox 104.0.2
 - Versie: [bv. 22]

**Comment by ndsmyter** [comment]
Je haalt een nuttige case aan.

Eigenlijk zou je die proef oneindig aantal keren mogen koppelen aan duiken, maar zou die wel maar 1 keer mogen afgetekend worden. Dus dat wil zeggen dat je bijvoorbeeld kan zeggen dat je die proef gedaan hebt tijdens 2 of meer duiken, maar zou een instructeur die maar 1 keer mogen aftekenen. Eenmaal afgetekend, zouden de proeven verwijderd moeten worden van de andere activiteiten.

Ik denk dat we hier wel nog niets voor voorzien hebben, dus ik ga deze wel opnemen. Maar dan misschien wel iets anders dan jouw eerste intentie vermoed ik.

**Comment by ndsmyter** [comment]
Ik heb dit doorgegeven aan Endare.
https://endare.atlassian.net/browse/NELOS-276 (link enkel voor mij toegankelijk)

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
