### ISSUE TITLE
[BUG] teller duiken rechtsboven wordt niet aangepast.

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#63]
**Beschrijf de bug**
De teller met duiken rechtsboven wordt niet aangepast na toevoegen van duiken. Deze staan wel in logbook en in profiel staat aantal duiken wel juist

**Stappen om te reproduceren**
1. voeg duik toe
2. bekijk profiel
3. Zie fout

**Verwachte resultaat**
Tellers aanpassen na toevoegen duik.

**Screenshots**
![aantal duiken](https://user-images.githubusercontent.com/112565895/190208571-b9afac7e-7f18-4736-b0e7-6ea36dcdbb49.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win 10 21h2
 - Browser: [bv chrome, safari] Firefox 14.0.2
 - Versie: [bv. 22]

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare
https://endare.atlassian.net/browse/NELOS-277 (link enkel voor mij toegankelijk)
