### ISSUE TITLE
Vermeldingen clubs in de ledenadministratie

### ISSUE THREAD

**Issue by Frederic1958** [Nelos-VZW/dives-2#64]
**Dubbele vermelding van de club bij leden met meerdere opleidingen**

Bij enkele leden staat naast hun lopende opleidingen het clubnummer. Indien het geval ook het clubnummer van hun 2de club.
Bij andere leden staat hetzelfde clubnummer 2 x vermeld.

**Verwachte resultaat**
De dubbele vermeldingen verwijderen.

**Screenshots**
![image](https://user-images.githubusercontent.com/113551586/190252239-bfb0eeb7-0a72-459a-b45b-7f0edf03990d.png)

![image](https://user-images.githubusercontent.com/113551586/190252575-d24b069e-7828-4f2e-8d9a-ab98edf13d05.png)

**Desktop 
 - Besturingssysteem: Windows
 - Browser: Chrome
 - Versie: 105.0.5195.102 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
Deze pagina moet nog wat herwerkt worden door Endare, dit staat reeds op hun takenlijst. Ik ga deze bug deze even On Hold zetten tot wanneer ze de aanpassingen gedaan hebben. We kunnen het dan na de aanpassingen nog eens bekijken.

**Comment by DIVEScoordinator** [comment]
@ndsmyter   is volgens mij nu ook opgelost?  Best ook sluiten?

**Comment by ndsmyter** [comment]
Dit probleem is inderdaad ook opgelost.
