### ISSUE TITLE
[BUG] Niet mogelijk proef te verwijderen van een activiteit

### ISSUE THREAD

**Issue by StephMaerten** [Nelos-VZW/dives-2#65]
**Beschrijf de bug**
Het is niet mogelijk om een proef te verwijderen van een activiteit

**Stappen om te reproduceren**
1. Ga naar 'Maak Duik activiteit'
2. Klik op 'Proeven toevoegen'
3. Proef aanvinken, en nadien terug proberen af te vinken'
4. Proef blijft in duikactiviteit staan

**Verwachte resultaat**
Een eerst verkeerd gekozen proef zou na het inzien van fout opnieuw moeten kunnen verwijderd worden

**Screenshots**
![image](https://user-images.githubusercontent.com/112578493/190363797-508590fc-f81a-407b-bdd2-83a571e33c29.png)

**Comment by ndsmyter** [comment]
Deze bug staat al op de takenlijst van Endare, maar hebben ze blijkbaar nog niet opgelost.
https://endare.atlassian.net/browse/NELOS-240 (link enkel voor mij toegankelijk)
