### ISSUE TITLE
[BUG] meerdere (niet combineerbare) proeven kunnen toewijzen aan 1 duik

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#68]
**Beschrijf de bug**
Het is mogelijk meerdere, niet ccombineerbare, proeven aan duik toe te kennen. bvb BND1 en BND2 aan zelfde duik toegekend. 

**Stappen om te reproduceren**
1. Maak duik aan
2. selecteer proeven
3. opslaan van duik
4. Zie fout

**Verwachte resultaat**
Het is voor een kandidaat interessant (en mogelijk motiverend) om te zien welke proeven er nog openstaan voor een opleiding, maar niet combineerbare proeven in 1 duik zouden niet samen selecteerbaar mogen zijn (bvb opleidingsduiken BND1 en BND2 samen). Deze zouden wel aan meedere duiken toegekend moeten kunnen worden, ook voordat de evaluator aftekend (voor als deze bvb achterop loopt met afvinken goedkeuringen)...

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21H2
 - Browser: [bv chrome, safari]firefox 14.0.2
 - Versie: [bv. 22]

**Comment by ndsmyter** [comment]
Hey  @jro73 ,
Het is inderdaad niet logisch dat er 2 proeven aan een activiteit gekoppeld worden die niet logisch zijn. Maar ik denk dat dit niet onmiddellijk iets is dat we in DIVES 2 zullen oplossen.

Ik heb beetje zitten twijfelen, maar ga deze nog even On Hold zetten voor een later moment. Denk dat we in eerste instantie ook wat moeten rekenen op het gezond verstand van de kandidaat en instructeur.

De reden dat ik het nu nog even on hold zet, is omdat ik nog niet goed weet hoe we kunnen detecteren dat bepaalde zaken niet logisch zijn om samen te doen. Bijvoorbeeld vaardigheden kan je perfect samen uitvoeren, maar deze BNDs kan je dan weer niet samen uitvoeren. Hoe weet je eenvoudig het verschil?

Het lijkt me beter om er voor te zorgen dat BND 2 altijd na BND 1 gedaan moet worden, maar dat heeft dan ook weer complicaties. Want dan moeten instructeurs veel meer gaan afspreken, want de 2e instructeur kan het pas inbrengen na de 1e instructeur. Dat is ook niet ideaal.

Laten we deze dus even parkeren, en op een later tijdstip nog even op terugkomen.

**Comment by DIVEScoordinator** [comment]
we sluiten deze af omdat het te  complex wordt om dit te implementeren en als we dit zouden invoeren er ook op dat vlak weer veel vragen/opmerkingen komen zoals Nicolas al meldde.  We gaan van het gezonder verstand uit van een instructeur om niet alle proeven bij 1 activiteit af te tekenen.  Dit kon trouwens in DIVES 1 ook...
