### ISSUE TITLE
[BUG] verkeerde aanduiding kwalificatie evaluators

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#69]
**Beschrijf de bug**
Als er bij duik met meerdere buddies (allen mogelijke evaluatoren) +proef gekozen wordt, vervolgens de proef editeren om de evaluator aan te passen, dan verschijnt een lijst van mogelijke namen (uit de geselecteerde buddies van die duik) maar met verkeerde kwalificatie. Alle evaluatoren zijn 1*D geworden. (zie foto)

**Stappen om te reproduceren**
1. Maak duik aan met meerdere mogelijke evaluatoren en met proef
2. selecteer proef om evaluator aan te passen
3. Zie fout

**Verwachte resultaat**
overname juiste kwalificaties van buddy/evaluatoren

**Screenshots**

![evaluator met verkeerde kwalificatie](https://user-images.githubusercontent.com/112565895/190428820-a6884165-4fc3-4d30-878f-ee665533e3e8.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21H2
 - Browser: [bv chrome, safari] Firefox 104.0.2
 - Versie: [bv. 22]

**Comment by ndsmyter** [comment]
Inderdaad een gekend probleem dat recent is begon te verschijnen omdat we initieel enkel de huidige brevetten hadden, toen was de volgorde niet belangrijk. Maar ik heb dit nu opgelost en zal dan binnenkort ook op test verschijnen.

**Comment by ndsmyter** [comment]
Zou opgelost moeten zijn nu
