### ISSUE TITLE
[BUG] buddie (dubbel) in logbook activiteiten, niet in detail

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#70]
**Beschrijf de bug**
Heb duik aangemaakt, ben erin geslaagd een buddy (johan) dubbel toe te voegen. Hij is als buddy zichtbaar in de logbook activiteiten (met alle duiken in). Maar als de duik zelf geopend wordt, is dubbele buddy weg.. 2e duik aangemaakt met mij en enkel Johan als buddy en opgeslagen.  Na aanmaken staat duik met johan als buddy in logbook. Als duik detail geopend wordt is johan als buddy weer weg.... 

na inloggen in account johan:  bij johan's logboek staat duik met mij en johan maar duik detail gaat niet open (query blijft draaien), 

**Stappen om te reproduceren**
1. Zie boven
2.
3.
4. Zie fout

**Verwachte resultaat**
Alle buddies, zichtbaar in logbook activiteiten ook weergeven in detail + check hangende query. Zou oorzaak van deze issues kunnen zijn dat kwalificatie Johan ontbreekt in dives? 

**Screenshots**
poging1
![dubbele buddy in logbook, niet in detail 1](https://user-images.githubusercontent.com/112565895/190435648-cdbb1452-03db-4b86-9421-5f264f9ef122.JPG)
![dubbele buddy in logbook, niet in detail 2](https://user-images.githubusercontent.com/112565895/190435667-e44e3e90-0438-4475-9fd6-7d0754241f45.JPG)

poging 2
![buddy issue 2 logbook](https://user-images.githubusercontent.com/112565895/190435584-d7303a9e-bf1a-4d8f-b05b-3f428e98beb5.JPG)
![buddy issue 2 detail duik](https://user-images.githubusercontent.com/112565895/190435596-92869101-5a3e-42e1-8ad6-d13003d31b1c.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21h2
 - Browser: [bv chrome, safari] firefox 104.0.2
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Dit probleem zou opgelost moeten zijn
