### ISSUE TITLE
[BUG] dolfijntjes niet weergegeven (link met issue #70), logbook werkt, detail niet 

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#71]
**Beschrijf de bug**
bij duikers -14 worden de dolfijntjes niet weergegeven. Duiken met  dolfijn-buddies" kunnen aangemaakt worden voor *D duiker. Deze ziet deze in logbook de activiteit met alle (dolfijn)buddies, Als de *D duiker het detail bekijkt, zijn alle dolfijn-buddies weer weg. Bij inloggen in account dolfijn-buddy is evenzeer de duik met alle namen zichtbaar in logbook, echter bij het openen van detail van deze duik blijft de query hangen.

**Stappen om te reproduceren**
1. als *D duiker, maak duik aan met dolfijn duikers + sla op
2. ga naar logbook, deze duik staat tussen activiteiten en alle namen staan hier weergegeven
3. open deze duik in logbook om detail te bekijken en dan zijn de dolfijn-buddies weg
4. log out en log in in account dolfijn
5. in account dolfijn, klik op logbook. De duik in kwestie staat tussen de activiteiten met alle namen
6. klik op deze duik voor detail, het scherm verspringt naar detail maar de query zelf hangt

**Verwachte resultaat**
dolfijn kwalificaties nakijken en opnemen..

**Screenshots**
scherm logbook met activiteiten

![buddy issue 2 logbook](https://user-images.githubusercontent.com/112565895/190451773-aa3a7c59-8821-4229-92e4-d698940c128f.JPG)

scherm detail duik  - dolfijn buddies zijn weg

![buddy issue 2 detail duik](https://user-images.githubusercontent.com/112565895/190451981-9b74afab-3f45-419e-8387-43fc622b0c69.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21h2
 - Browser: [bv chrome, safari] firefox 104.0.2
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Opgelost
