### ISSUE TITLE
[Feature] Eigen duiklocatie toevoegen

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#72]
momenteel wanneer je een locatie ingeeft kan je hierin ook niet gekende duikplaatsnamen ingeven. Het zou leuk zijn om deze ook op een kaart te kunnen aanduiden zoals in DIVES 1.0 en eventueel zelf hieraan eigenschappen te kunnen toevoegen zoals zoet/zout water, getijden water, ...

**Comment by ndsmyter** [comment]
Je kan nu enkel maar nieuwe locaties toevoegen op basis van een naam. Maar we gaan hier inderdaad binnenkort nog extra functionaliteiten aan toevoegen zodanig dat je "zones" kan selecteren waarin de locaties liggen. De zones zullen dan bepalen welke tags er aan die locatie moet gehangen worden.
We willen vermijden dat mensen zelf tags kunnen hangen aan hun persoonlijke locaties, om toch iets of wat de fouten in de databank te beperken.

Deze feature komt dus binnenkort nog
