### ISSUE TITLE
[Feature] Brevet combinaties limiteren

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#74]
Ik weet niet goed of dit een bug is of een new feature. Momenteel is het mogelijk om een duik te maken met bijvoorbeeld alleen 1*D of jeugd. Een limitatie hierop zoals de Nelos normen het voorschrijft kan hierop toegepast worden.

**Comment by ndsmyter** [comment]
Dat is ook in DIVES 1.0 geen beperking. DIVES komt pas na de feiten, en dus is het sowieso al te laat om nu nog dergelijke verplichtingen te gaan opleggen. Het is beetje aan de deelnemers zelf om zich aan de NELOS regels te houden op dit gebied.

Ik sluit niet uit dat we dit later gaan toevoegen, maar op dit moment is dit nog niet aan de orde om dergelijke beperkingen op te leggen. Want dit wordt al zeker moeilijk als we gaan duiken met niet-NELOS leden, wat ook een optie is.

Ik ga deze dus op "Won't Fix" zetten vrees ik.
