### ISSUE TITLE
[BUG] Bewerkingsgeschiedenis fout

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#76]
**Beschrijf de bug**
Wanneer je na een bewerking gaat kijken in de geschiedenis klopt deze niet.

**Stappen om te reproduceren**
1. Maak een duik aan met alle gegevens in buiten een buddy bijvoorbeeld.
2. Open de duik en klik op aanpassen
3. Voeg nu een buddy toe
4. Zie dat in de bewerkingsgeschiedenis een verkeerde persoon als toegevoegd staat samen met de bewerking van uur zonder deze aan te passen.

**Verwachte resultaat**
Een correcte geschiedenis

**Screenshots**
De duiker Lieven DIERICK is toegevoegd maar de geschiedenis zegt Fabrice COTTENIER en het uur van de duik is nooit aangepast geweest.
![image](https://user-images.githubusercontent.com/42772246/190466937-ca9a5bea-aa7c-46fe-b7b2-88b485f75ca5.png)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: windows 10 21H2
 - Browser: chrome 105.0.5195.125

**Comment by ndsmyter** [comment]
Doorgegeven aan Endare
https://endare.atlassian.net/browse/NELOS-282 (link niet publiek toegankelijk)

**Comment by ndsmyter** [comment]
Probleem opgelost op DEV, komt binnenkort naar TEST
