### ISSUE TITLE
[BUG] Rapportering scherm laad niet

### ISSUE THREAD

**Issue by jenno-verdonck** [Nelos-VZW/dives-2#77]
**Beschrijf de bug**
Ik weet niet wat dit scherm hoort te doen in DIVES 2.0 maar momenteel laad het rapportering scherm niet. Dit kan ook aan mijn rechten liggen omdat ik zie dat dit onder instructor valt in het pad.

**Stappen om te reproduceren**
1. Ga naar https://test.nelos.be/instructor/reporting
2. Zie dat deze niet laad

**Verwachte resultaat**
De pagina moet laden ofwel moet de pagina gewoon niet getoond worden als je geen rechten hebt.

**Screenshots**
![image](https://user-images.githubusercontent.com/42772246/190469622-d436455d-4990-4668-bd84-4635ba787341.png)

**Comment by ndsmyter** [comment]
Probleem opgelost

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
