### ISSUE TITLE
[Feature] Rapportering naar Excel

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#79]
Momenteel kan je de rapportering van de gebruikers op de website bekijken, maar soms is het eenvoudiger om dit in een Excel te hebben zodanig dat er dan met eventuele andere operaties rapporten uit getrokken kunnen worden.
Deze functionaliteit is op dit moment nog niet voorzien, en is ook nog niet zo heel erg dringend. Daarom log ik deze feature request om dit niet te vergeten.

**Comment by DIVEScoordinator** [comment]
@ndsmyter  deze staat er nu twee keer in. Afsluiten? Een On hold

**Comment by ndsmyter** [comment]
Inderdaad duplicaat van #328 . Ik zal deze afsluiten en dan andere overhouden.
