### ISSUE TITLE
[BUG] Eigen profiel - opleidingen - minimaal aantal duiken voor een proef NOK

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#8]
**Beschrijf de bug**
Als ik naar mijn eigen profiel ga kijken, tab 'opleidingen'; bij mijn opleiding 4*D: 
ik heb volgens Dives 2.0 nog geen 20 duiken in zone 40m gedaan; geen 120 duiken gedaan en geen 40 duiken in zone 30 gedaan. 
Deze duiken werden wel uitgevoerd en zijn ingegeven in Dives 1.0

2de puntje hier: ik heb mijn theorie-examen voor 4*D reeds uitgevoerd bij het behalen van mijn AI; maar dit is niet zichtbaar (zie printscreen 2). Dit was een probleem dat ook al aanwezig was in Dives 1.0

**Stappen om te reporduceren**
De stappen om de bug te reproduceren:
1. Ga naar je eigen profiel
2. Klik op het tabje 'opleidingen
4. Zie fout

**Verwachte resultaat**
De correcte gegevens zouden moeten zichtbaar zijn

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187545367-b7ea1db5-3b7d-41ff-a4e4-507702df3584.png)

![image](https://user-images.githubusercontent.com/112517511/187545698-cd8f03cb-0861-4e4d-ba19-401f5d1c0cbe.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Version Versie 105.0.5195.54 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
Ik zie al het probleem volgens mij.

Je hebt nog geen 20 duiken gedaan naar zone 40m die in DIVES 1.0 ingegeven werden. Maar je hebt natuurlijk ooit wel eens geïnitialiseerd in DIVES 1.0, maar die werden nog niet meegeteld blijkbaar in de berekening van die precondities.

Dit is blijkbaar voor alle voorwaarden het geval, dus daar zal ik nog eens moeten naar kijken.

**Comment by ndsmyter** [comment]
Dit probleem zou nu normaal gezien opgelost moeten zijn.
