### ISSUE TITLE
Overzicht van openstaande proeven, zien van de profielen.

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#81]
**Beschrijf de bug**
Als 4*D / AI krijg ik geen overzicht van de openstaande proeven en heb ik geen mogelijkheid om het profiel te zien.
Binnen onze club verwachten de AI's en Instructeurs dat ze kunnen zien welke proeven er nog openstaan zonder deze te moeten ingeven als mededuiker.

**Stappen om te reproduceren**
1. Ga naar 'Kandidaten'
2. Schakel de favorieten uit
3. krijg ik een overzicht van de leden van Odyssee

**Verwachte resultaat**
Als 4*D/AI zou ik ook de proeven voor Vinzwemmen B1 en C1 + duikleidingen kandidaat 2*D (BL1 en BL2) en CL1 voor kandidaat 3*D moeten zien.
Krijg enkel te zien dat er "geen lopende opleidingen" zijn.

**Screenshots**
![image](https://user-images.githubusercontent.com/112561123/190680235-0abe81b8-1b3e-4a3c-a4c8-12abd5f590f5.png)

**Extra informatie**
Als ik inlog via het Testteam als 4*D zie ik dit wel.

**Comment by ndsmyter** [comment]
Ik moet deze eens bekijken.
Normaal gezien zou je altijd de brevetten moeten zien waar je zelf ook proeven voor kan afnemen. Maar normaal gezien kijk ik ook wel minstens naar 1*I. Dus volgens mijn weten, zou je eigenljik als 4*D of AI geen personen mogen zien.

Ik weet dat dit misschien nog wat raar overkomt omdat je wel proeven mag afnemen. Maar ik wil hiervoor liever niet zelf de beslissing nemen. Ik zal dit opnemen met Lutgart zodanig dat ze dit in de juiste kringen eens kunnen bespreken.

**Comment by DIVEScoordinator** [comment]
@ndsmyter dit is opgelost want AI's mogen nu ook brevetkaarten van kandidaten inkijken - afgesloten
