### ISSUE TITLE
Logboek is enkel aanpasbaar van lopende maand

### ISSUE THREAD

**Issue by DelangheM** [Nelos-VZW/dives-2#82]
**Beschrijf de bug**
De knoppen "verwijderen" en "Aanpassen" niet meer zichtbaar in de duiken van Augustus en later.

**Stappen om te reproduceren**
1. Ga naar 'logboek'
2. klik op een duik van Augustus of Juli.
3. knoppen niet meer zichtbaar

**Verwachte resultaat**
De knoppen "verwijderen" en "Aanpassen" dienen zichtbaar te blijven.

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.
![image](https://user-images.githubusercontent.com/112561123/190701559-7510bf3d-e10a-40aa-9a50-7ba29d5f3de5.png)

**Comment by ndsmyter** [comment]
Je kan enkel duiken aanpassen van de laatste 2 weken. Dus dat is in dit geval inderdaad beperkt tot augustus.

We gaan wel nog een melding toevoegen zodanig dat dit duidelijker wordt. Dat staat al gepland.

Aangezien er volgens mij niets moet gebeuren voor deze bug, ga ik die al onmiddellijk afsluiten 🙂
