### ISSUE TITLE
[BUG] duiken met niet-nelos buddy slaan niet op 

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#83]
**Beschrijf de bug**
Duiken, theorie, zwembadoefeningen met niet-nelos buddy worden niet opgeslagen: duik aangemaakt, niet nelos buddy toegevoegd, bij opslaan blijft query draaien. De activiteit wordt niet in de databank opgeslagen. Bij andere errors (oa issues met dolfijntjes - zie eerdere bugs) dan blijft ook alles hangen, maar staan de activiteit naderhand wel in de databank.

**Stappen om te reproduceren**
1. Ga naar duik aanmaken en geef alle parameters in
2. Klik op 'niet nelos buddy toevoegen'
3. opslaan lukt niet 
4. Zie fout

**Verwachte resultaat**
ook deze activiteiten kunnen registeren.. 

Maar direct ook volgende bedenking: wat er erkenning en inschalen certificaten van andere federaties? eventueel werken met dropdown voor meest voorkomende federaties (padi/iss/..)  om ook naam certificaten/bekwaamheden juist te hebben? 

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21 h2h
 - Browser: [bv chrome, safari] firefox 104.0.2

**Comment by ndsmyter** [comment]
We gaan nog geen rekening houden met de brevetten van andere federaties. Dit heeft namelijk een grote impact op het onderhoud van DIVES, want dan moeten we ook gaan zorgen dat die in sync blijven.

De rest van de bug werd doorgegeven aan Endare

**Comment by ndsmyter** [comment]
Nogmaals doorgegeven aan Endare onder https://endare.atlassian.net/browse/NELOS-465 (ik vond originele niet, dus nieuwe aangemaakt voor alle zekerheid)

**Comment by ndsmyter** [comment]
Is opgelost nu normaal gezien
