### ISSUE TITLE
[BUG] BND opleidingsduiken in profiel - verkeerde tekst

### ISSUE THREAD

**Issue by jro73** [Nelos-VZW/dives-2#84]
**Beschrijf de bug**
situatie: ik ben 1*D, heb BND thoerie afgelegd maar opleidingsduiken nog te doen. In profiel - opleidingen staat theorie afgevinkt als geslaagd (is correct) maar staat bij de opleidingsduiken de tekst "Proef Theorieles BND moet afgelegd zijn" op groene achtergrond. De opleidingsduiken zijn wel als proef te selecteren bij de duiken (activiteit)

**Stappen om te reproduceren**
1. Ga naar profiel - opleidingen
2. zie opleiding (screenshot bijgevoegd) met verkeerde tekst
3. ga naar duiken, duik met BND proef is aan te maken, wat correct is
4. Zie fout

**Verwachte resultaat**
Juiste tekst weergeven

**Screenshots**

![theorieles](https://user-images.githubusercontent.com/112565895/190843408-bd4b9cf6-2827-4503-91e0-7eb09613e17d.JPG)

**Desktop (indien mogelijk aanvullen):**
 - Besturingssysteem: [bv iOS] win10 21h2
 - Browser: [bv chrome, safari] firefox 104.0.2
 - Versie: [bv. 22]

**Smartphone (indien mogelijk aanvullen):**
 - Toestel: [bv iPhone6]
 - Besturingssysteem: [bv iOS8.1]
 - Browser [bv standaard browser, safari]
 - Versie [bv 22]

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by ndsmyter** [comment]
Die tekst is eigenlijk wel juist in mijn ogen. Om die proef te kunnen doen, moet die proef afgelegd zijn. En die proef is inderdaad afgelegd, want de kleur is groen. Moest het niet mogelijk zijn, dan had die rood geweest.

Dus de voorwaarde blijft "Proef Theorieles BND moet afgelegd zijn", of die al afgelegd werd of niet.

Aangezien ik denk dat er hier niets aangepast moet worden, ga ik deze taak afsluiten. Als je echt denkt dat er toch iets moet veranderen, kan je die terug openen. Maar dan gaan we dit toch eens wat concreter moeten bespreken denk ik.
