### ISSUE TITLE
[BUG] Label issue K4*D - Minimaal 20 duiken nodig tussen 35 en {{2}} meter

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#87]
**Beschrijf de bug**
Label voor minimum aantal duiken K4*D is incompleet, nu staat er Minimaal 20 duiken nodig tussen 35 en {{2}} meter

**Stappen om te reproduceren**
1. Maat testgebruiker aan
2. ga naar profiel/proeven

**Verwachte resultaat**
Minimaal 20 duiken nodig tussen 35 en **40** meter

**Screenshots**
![image](https://user-images.githubusercontent.com/8513610/192142785-465a924b-6316-4941-89c6-c40c5e7ba279.png)

**Comment by ndsmyter** [comment]
Gelijkaardig probleem als #46
