### ISSUE TITLE
[BUG] Fout bij afname proeven Niet-Nelos Duiker

### ISSUE THREAD

**Issue by dr-zone** [Nelos-VZW/dives-2#88]
**Beschrijf de bug**
Als je drukt op de knop proef toevoegen met een niet nelos duiker in de ploeg geeft de applicatie een fout

**Stappen om te reproduceren**
1. Ga naar maar nieuwe duik
2. Klik op niet nelos duiker toevoegen
3. Klik op Proeven toevoegen
4. Zie fout

**Verwachte resultaat**
Geen proeven / knop niet beschikbaar in deze configuratie

**Screenshots**

![image](https://user-images.githubusercontent.com/8513610/192143092-ac5166cc-ed20-4f22-9d41-7fe3730a0385.png)

![image](https://user-images.githubusercontent.com/8513610/192143108-a3aec547-b9cf-4d48-bf8a-8c3235678e14.png)

![image](https://user-images.githubusercontent.com/8513610/192143124-76d65eab-bdb3-4199-b477-1387c66d7b1c.png)

**Comment by DIVEScoordinator** [comment]
![image](https://user-images.githubusercontent.com/112652115/236684802-8e3aff18-2045-42cd-8f79-2e0656f92d9d.png)

Dit lijkt mij opgelost in test omgeving.

@ndsmyter   afsluiten?
