### ISSUE TITLE
[BUG] Help knop werkt niet

### ISSUE THREAD

**Issue by RubenDeSadeleer** [Nelos-VZW/dives-2#9]
**Beschrijf de bug**
In de linker menu-balk; de help-knop werkt niet. Als je er op klikt gebeurt er niets. 

**Screenshots**
![image](https://user-images.githubusercontent.com/112517511/187546271-18cf89a9-3d22-47f4-82a6-0679fe534489.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Versie 105.0.5195.54 (Officiële build) (64-bits)

**Comment by ndsmyter** [comment]
Die is nog niet geïmplementeerd inderdaad. Maar goed dat je het zegt, want ik was die eigenlijk al uit het oog verloren.

**Comment by ndsmyter** [comment]
Is nu reeds te testen op test.nelos.be
