### ISSUE TITLE
[Feature] Zoeken op tags

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#90]
Op de overzichtspagina van de activiteiten zou het mogelijk moeten zijn om te zoeken op je persoonlijke tags

**Comment by DIVEScoordinator** [comment]
Toegevoegd aan sprint 2024-02 onder JIRA ticket NELOS-668

**Comment by DIVEScoordinator** [comment]
Dit ticket werd al bij de mei sprint meegenomen en je kan nu op tags zoeken.
