### ISSUE TITLE
knop activiteit opslaan half verborgen op samsung A5

### ISSUE THREAD

**Issue by danielvandijck** [Nelos-VZW/dives-2#91]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Op mijn gsm samsung galaxy A5 blijft de knop activiteit opslaan half verborgen achter de blauwe balk met logboek en kandidaten knop, de knop activiteit opslaan  kan wel bediend worden maar dit is niet optimaal

**Beschrijf de oplossing die je zou willen**
de blauwe balk verwijderen want de knoppen logboek en kandidaten  staan al in de dropdown menu links

**Extra context**
![Screenshot_20220930-185934_Chrome 918](https://user-images.githubusercontent.com/113804099/193324350-8f9dffbe-c3ce-485a-83ba-6655b31b175e.jpg)

**Comment by ndsmyter** [comment]
Ziet er een redelijk gelijkaardig probleem uit als #35 , maar gaat juist over ander toestel. Maar ik zou vermoeden dat als #35 opgelost is, deze ook wel opgelost zal zijn.

Ik laat deze nog even open staan zodanig dat we opnieuw kunnen testen als #35 opgelost is.

**Comment by danielvandijck** [comment]
top ik wacht af

**Comment by user4294** [comment]
Dit probleem stelt zich bij mij wanneer ik Dives 2.0 op Android in de browser zelf gebruik (Brave met bottom toolbar, vermoedelijk identiteit in Chrome). Het onderste gedeelte van het scherm verdwijnt dan op elk scherm onder de bottom toolbar, waardoor verschillende functionaliteiten niet kunnen worden gebruikt. 

Probleem stelt zich niet in de fullscreenversie (met Dives toegevoegd aan homescreen).

**Comment by ndsmyter** [comment]
@user4294 Goed om weten. Op de screenshot van @danielvandijck lijkt het me ook wel redelijk fullscreen te zijn.
Lijkt me nuttig dat het in alle instanties werkt, dus hopelijk is dit binnenkort opgelost.

**Comment by user4294** [comment]
Hierbij nog enkele screenshots ter aanvulling. In Brave (Chromium) met bottom toolbar verdwijnt 'Opslaan' volledig achter de blauwe knop 'Logboek'. Met top toolbar is de knop half zichtbaar. In de fullscreenversie is de knop volledig zichtbaar. 

![Screenshot_20221105-200049_Brave](https://user-images.githubusercontent.com/56023403/200162864-5616f9cb-e8a4-4c78-901d-2d745d583052.jpg)

![Screenshot_20221105-200226_Brave](https://user-images.githubusercontent.com/56023403/200162871-1573811e-66a0-4718-9a3c-9d26c2945286.jpg)

![Screenshot_20221105-200314_Brave](https://user-images.githubusercontent.com/56023403/200162872-ccfef814-ec33-4e1f-98a1-711adf3347f6.jpg)

**Comment by user4294** [comment]
Aanvullend: de knop 'opslaan' bleef grijs toen ik de duik eerst ingaf. Ik kon er niet op drukken en dus ook niet achterhalen waarom de knop niet beschikbaar werd. Heb het niet kunnen achterhalen en de duik opnieuw ingegeven. Mogelijk ook een aandachtspuntje?

**Comment by user4294** [comment]
Net even getest op een Samsung Galaxy Tab S6. Ook hier blijven er nog schermdelen onzichtbaar in de browser (met bottom toolbar). Fullscreen stellen deze problemen zich niet.

![Screenshot_20221204_160844_Brave](https://user-images.githubusercontent.com/56023403/205502967-54ad6c7c-8b6c-407c-84db-e72f1b18d36c.jpg)

![Screenshot_20221204_161100_Brave](https://user-images.githubusercontent.com/56023403/205502989-4ac81ca8-6482-48d6-a125-07d3b6e0d587.jpg)

**Comment by user4294** [comment]
Het probleem lijkt ook nog iets groter wanneer je de knop 'Duiklocatie zoeken' hebt gebruikt - de knop 'Opslaan' zakt dan nog verder weg.

**Comment by ndsmyter** [comment]
Zou nu in orde moeten zijn.
