### ISSUE TITLE
dubbele knop voeg proeven toe? eentje verwijderen?

### ISSUE THREAD

**Issue by danielvandijck** [Nelos-VZW/dives-2#92]
**Is uw nieuwe functionaliteit gelinkt aan een probleem? Gelieve te beschrijven.**
Er staan 2 knoppen onderaan de activiteit "voeg proeven toe"  misschien eentje overbodig?

**Beschrijf de oplossing die je zou willen**
Er staat bij duik/theorie/zwembad activiteit zowel links als rechts onderaan voeg proeven toe, 1 van de 2 verwijderen.

**Ex
![image](https://user-images.githubusercontent.com/113804099/193328600-789b1738-245d-4da8-8492-9fce61c70c1e.png)
tra context**

**Comment by ndsmyter** [comment]
Die ene knop "Voeg een proef toe" is daar met opzet gezet voor de gebruiksvriendelijkheid. Deze is enkel als er nog geen proeven zijn, en dus als het tekstje daar staat daar geen proeven zijn.
De knop aan de rechterkant blijft altijd bestaan.

Het is dus met opzet dat we daar 2 knoppen hebben staan, dus dat is op zich geen bug :-)
