### ISSUE TITLE
[BUG] Zoekfunctie "vanaf" is een "tot"

### ISSUE THREAD

**Issue by user4294** [Nelos-VZW/dives-2#93]
**Beschrijf de bug**
In de zoekfunctie staat "Vanaf maand of jaar" weergegeven, maar de filter lijkt de duiken "tot maand of jaar" weer te geven. 

**Stappen om te reproduceren**
1. Ga naar 'Logboek'
2. Klik op een maand of een jaartal
3. De duiken tot het geselecteerde tijdstip worden weergeven.

**Verwachte resultaat**
Dat de duiken vanaf het geselecteerde tijdstip worden weergegeven. M.i. kan de filter blijven as is (in lijn met Dives 1.0) en kan best de bijhorende tekst worden aangepast.

**Screenshots**
Indien mogelijk, kan je hier screenshots geven van wat er gebeurde.
![ss](https://user-images.githubusercontent.com/56023403/193789685-7947279c-8224-4b44-8cea-b7effe5f56f6.png)

**Extra informatie**
Voeg alle extra informatie die je nog bedenkt hier gerust toe

**Comment by DIVEScoordinator** [comment]
aangepast in DEV nog niet in productie - komt met de volgende release
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/8892335b-f939-405d-a966-b93c6da0d1ba)
