### ISSUE TITLE
[BUG] Bewerkingsgeschiedenis geeft altijd wijziging aan datum en tijd weer

### ISSUE THREAD

**Issue by user4294** [Nelos-VZW/dives-2#94]
**Beschrijf de bug**
Telkens je een duik bewerkt en opslaat (en ook als je geen wijzigingen aanbrengt), komt er een nieuw item in de bewerkingsgeschiedenis dat stelt dat "De datum en tijd werd aangepast van... naar ..."

**Stappen om te reproduceren**
1. Ga naar een duik en druk op Bewerken. 
2. Druk op "Aanpassen" (evt. "Opslaan"?)
3. Scroll naar beneden en open item Bewerkingsgeschiedenis.
4. Entry is toegevoegd.

**Verwachte resultaat**
Onbestaande wijziging zou niet mogen worden gelogd.

**Screenshots**
![bw](https://user-images.githubusercontent.com/56023403/193793510-4da402ad-d80a-4b3e-8809-445f0dd48990.png)

**Extra informatie**
Extra bug: om dit te testen, verwijderde ik mijn buddy en voegde hem opnieuw toe. In het logboek verschijnen twee duikers die ik niet heb aangeduid, en ook geen lid zijn van de clubs waarbij ik ben aangesloten. Dit lijkt reproduceerbaar.

**Comment by user4294** [comment]
Aanvullend: Bewerkingsgeschiedenis is leeg by default. Mogelijk wenselijk dat er telkens een eerste entry met de aanmaakdatum wordt opgenomen?

**Comment by ndsmyter** [comment]
Bug doorgegeven aan Endare.
https://endare.atlassian.net/browse/NELOS-290 (link enkel toegankelijk voor mij, maar is om overzicht te kunnen houden)
