### ISSUE TITLE
[Feature] Pagina per locatie met statistieken

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#98]
Toevoegen van een pagina per locatie om enkele statistieken te visualiseren. Statistieken over het aantal duiken, de gemiddelde temperatuur over de laatste dagen, zichtbaarheid over de laatste dagen en dergelijke.

Functionaliteit die we in DIVES 1.0 ook al hadden, maar in DIVES 2.0 nog niet als prioriteit werd gezien. Bv. https://leden.nelos.be/duikplaats/PL-OS-6-64

**Comment by ndsmyter** [comment]
Voorgesteld door @user4294

**Comment by DIVEScoordinator** [comment]
Toegevoegd aan spirnt 2024-03 die specifiek duikplaatsen gaat behandelen (november periode) als JIRA NELOS-

**Comment by DIVEScoordinator** [comment]
dubbel item

**Comment by ndsmyter** [comment]
Duplicate of #370
