### ISSUE TITLE
[BUG] Extra brevetten worden niet getoond op de profielpagina

### ISSUE THREAD

**Issue by ndsmyter** [Nelos-VZW/dives-2#99]
**Beschrijf de bug**
Als je als instructeur naar de brevetkaart van een kandidaat gaat kijken, zie je wel de extra brevetten van een persoon. Maar als persoon zelf, kan je deze tab blijkbaar niet zien op je eigen profiel. Niet echt logisch.

**Stappen om te reproduceren**
1. Ga naar 'Profiel' via knop rechtsboven
2. Zie geen tab 'Brevetten' staan
<img width="541" alt="image" src="https://user-images.githubusercontent.com/648669/193823968-b8420a0b-d5a7-4e38-9615-90f4ab9eb683.png">
4. Ga als instructeur naar 'Kandidaten'
5. Zoek je eigen brevetkaart op (als je die hebt, anders van andere persoon)
6. Open je eigen brevetkaart (als je die hebt, anders van andere persoon)
7. Zie wel een tab 'Brevetten' staan
<img width="500" alt="image" src="https://user-images.githubusercontent.com/648669/193824283-4e12912e-17a6-4937-8a29-2ab784589026.png">

**Verwachte resultaat**
Je zou ook op je eigen profiel de tab "Brevetten" moeten zien staan

**Comment by ndsmyter** [comment]
Gemeld door @user4294

**Comment by ndsmyter** [comment]
Lijkt bij mij opgelost

**Comment by user4294** [comment]
Ik kan nu ook mijn eigen extra brevetten zien.
